### ISSUE TITLE
YouLookv6: Shame On You

### ISSUE THREAD

**Issue by m00nLi** [meituan/YOLOv6#100]
The so call "YOLOv6":
![image](https://user-images.githubusercontent.com/102453574/176082657-be51b773-0ad2-4607-b05e-45b613553bbf.png)

https://github.com/ultralytics/yolov5:
![image](https://user-images.githubusercontent.com/102453574/176082804-34dfc2d9-5d5f-4f6d-abe9-9a83d07870cc.png)

**Comment by gachiemchiep** [comment]
@m00nLi 
What made you so mad?
From your image, I can see some improvements in inference speed, model size, flops.


![image](https://user-images.githubusercontent.com/2300329/176108789-3a15aa1d-9014-4b4a-92fa-4b2effa1a8dd.png)

![image](https://user-images.githubusercontent.com/2300329/176108851-3cf49309-290d-4472-84c8-f8a75885062a.png)

**Comment by m00nLi** [comment]
Are you sure? 
田忌赛马吗？

**Comment by gachiemchiep** [comment]
@m00nLi 
Yes I am. 
I clean up their report numbers a little bit. 
I only take the inference speed of Speed of (V100, fp32, batch=32). 
The input size is set into 640

Then the number look like this

![image](https://user-images.githubusercontent.com/2300329/176117478-0ee55b60-9692-496b-af86-12fb9c6aab48.png)

![image](https://user-images.githubusercontent.com/2300329/176117534-c71fe4a8-0359-4d41-a428-7a1c672bb6f7.png)

I put the number in Excel so you can comment if you want 
https://docs.google.com/spreadsheets/d/1AA2d6p7emfuh96Trsle33IPdt0YsYY7QtnXtWsArt6o/edit?usp=sharing

I think authors are still doing their experiments, so bashing them right now is not a good option. 
I am not Chinese so If you can, please write in English.

**Comment by deepthman** [comment]
lose face

**Comment by m00nLi** [comment]
Let me show you:
"YOLOv6-n": 11.1 GLOPs, YOLOv5n: 4.5 GFLOPs
"YOLOv6-tiny": 36.7 GLOPs, YOLOv5s: 16.5 GFLOPs
"YOLOv6-s": 44.2GLOPs, YOLOv5m: 49 GFLOPs
Is that clear enough?

**Comment by ruabliuqiu** [comment]
> 

GFLOPs

> Let me show you: "YOLOv6-n": 11.1 GLOPs, YOLOv5n: 4.5 GFLOPs "YOLOv6-tiny": 36.7 GLOPs, YOLOv5s: 16.5 GFLOPs "YOLOv6-s": 44.2GLOPs, YOLOv5m: 49 GFLOPs Is that clear enough?

就你眼尖

**Comment by m00nLi** [comment]
> > 
> 
> GFLOPs
> 
> > Let me show you: "YOLOv6-n": 11.1 GLOPs, YOLOv5n: 4.5 GFLOPs "YOLOv6-tiny": 36.7 GLOPs, YOLOv5s: 16.5 GFLOPs "YOLOv6-s": 44.2GLOPs, YOLOv5m: 49 GFLOPs Is that clear enough?
> 
> 就你眼尖

I regret your inability
