### ISSUE TITLE
真有傻子上当？霉团这是搞了个半成品坑你给他补全呢

### ISSUE THREAD

**Issue by e0r** [meituan/YOLOv6#1000]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [x] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

真有傻子上当？霉团这是搞了个半成品坑你给他补全呢
信啥都不能信中国鬼子

**Comment by DrChungAlbert** [comment]
本來就是學術性值的討論 何必這樣酸? 再說實驗數據說明一切 這網路架構的確比較快 準度也相當不錯 只是文件有點小缺失沒專人整理 至於是否能做成品應用那可不是研究者的工作 是工程師該完成的 不是嗎 ?

**Comment by flashmoment** [comment]
我知道你很急但是你先别急
