### ISSUE TITLE
How to decide solo mode or not in non_max_suppression_seg?

### ISSUE THREAD

**Issue by DrChungAlbert** [meituan/YOLOv6#1001]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

If there are only 3 class segment objects, although the objects may be very close, their masks do not actually overlap, but the masks of the candidate objects may overlap.
how to choice the solo or not solo mode for non_max_suppression_seg in this case?

**Comment by Chilicyy** [comment]
Hi @DrChungAlbert , it depends on whether the model you want to infer is solo structure or not. If it's solo structure, you can run inference by adding the parameter `--issolo`, and then non_max_suppression_seg_solo would be applied.

**Comment by DrChungAlbert** [comment]
There are two structures inside nms seg ,okay.
