### ISSUE TITLE
 weight size not match the proto's after handle_proto_coord in handle_proto_solo function

### ISSUE THREAD

**Issue by DrChungAlbert** [meituan/YOLOv6#1004]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

I have try to test the solo function in yolov6-seg by:
python tools/infer.py --weights weights/yolov6n_seg.pt  --yaml data/coco.yaml --issolo 

Traceback (most recent call last):
  File "/data1/YOLOv6-seg/tools/infer.py", line 122, in <module>
    main(args)
  File "/data1/YOLOv6-seg/tools/infer.py", line 117, in main
    run(**vars(args))
  File "/root/miniconda3/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data1/YOLOv6-seg/tools/infer.py", line 110, in run
    inferer.infer(conf_thres, iou_thres, classes, agnostic_nms, max_det, save_dir, save_txt, not not_save_img, hide_labels, hide_conf, view_img, issolo=issolo)
  File "/data1/YOLOv6-seg/yolov6/core/inferer.py", line 99, in infer
    segments = [self.handle_proto_solo([protos[li].reshape(1, *(protos[li].shape[-3:]))], segconf[li], img.shape[-2:], weight_sums=weight_nums, bias_sums=bias_nums, dyconv=dyconv_channels) for li in range(len(loutputs))][0]
  File "/data1/YOLOv6-seg/yolov6/core/inferer.py", line 99, in <listcomp>
    segments = [self.handle_proto_solo([protos[li].reshape(1, *(protos[li].shape[-3:]))], segconf[li], img.shape[-2:], weight_sums=weight_nums, bias_sums=bias_nums, dyconv=dyconv_channels) for li in range(len(loutputs))][0]
File "/data1/YOLOv6-seg/yolov6/core/inferer.py", line 426, in handle_proto_solo
    x = F.conv2d(
RuntimeError: Given groups=1, weight of size [1, 66, 1, 1], expected input[1, 34, 160, 160] to have 66 channels, but got 34 channels instead

Mismatch in Convolution Operation:

In the handle_proto_solo function, you attempt to perform a convolution operation with the derived weights and biases.
The error indicates that the convolution expects an input with 66 channels (Given groups=1, weight of size [1, 66, 1, 1], expected input[1, 34, 160, 160] to have 66 channels), but the actual input tensor (proto) only has 34 channels after processing with handle_proto_coord.

Thanks.

**Comment by Chilicyy** [comment]
Hi @DrChungAlbert , is the weight model ` weights/yolov6n_seg.pt`  achieved by our release download link or trained by yourself ? We only release yolov6n segmentation model with YOLACT head, which can't be inferred with parameter `--issolo`.

**Comment by DrChungAlbert** [comment]
Hi @Chilicyy ,
I get  weights/yolov6n_seg.pt achieved by your release download link.
Is there a way to train the yolov6-seg by using the solo architecture?
