### ISSUE TITLE
RuntimeError: shape 

### ISSUE THREAD

**Issue by elmsamcht2189** [meituan/YOLOv6#1006]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

    ipred_seg = (tiseg_cf@iseg_proto[i].reshape(self.tt, -1)).reshape(-1, pshape, pshape) # (?2, h, w)                                                         
RuntimeError: shape '[-1, 112, 112]' is invalid for input of size 358400

yolov6-seg
```
python -m torch.distributed.launch \
--nproc_per_node 4 \
tools/train.py \
--batch 64 \
--specific-shape \
--height 256 \
--width 448 \
--epochs 400 \
--workers 8 \
--eval-interval 20 \
--conf configs/huachuangban_yolov6n_seg_finetune.py \
--data data/huachuangban.yaml \
--device 4,5,6,7 \
--output-dir ./runs/train \
--name huachuangban_h256w448
```

**Comment by Chilicyy** [comment]
HI @elmsamcht2189 , `specific-shape` training is not supported for segmentation. Feel welcome to add this feature and PR !
