### ISSUE TITLE
How to export ONNX model trained with Specific shape?

### ISSUE THREAD

**Issue by karls-accnt** [meituan/YOLOv6#1009]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [ ] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

I trained yolov6 nano model with specific shape option.(I used coco dataset, input shape is width : 640, height : 360)

After trainning, I got error while exporting pt model to onnx. 

**onnx deploy script is here.**

> python ./deploy/ONNX/export_onnx.py --weights 640x360.pt --img 360 640 --batch 1 --simplify

**And error is here.**

Exception has occurred: RuntimeError

> Sizes of tensors must match except in dimension 1. Expected size 24 but got size 23 for tensor number 1 in the list.
>   File "./YOLOv6/yolov6/layers/common.py", line 766, in forward
>     return self.cv3(torch.cat((x0, x1, x2), dim=1))
>   File "./YOLOv6/yolov6/models/reppan.py", line 220, in forward
>     f_concat_layer0 = self.Bifusion0([fpn_out0, x1, x2])
>   File "./YOLOv6/yolov6/models/yolo.py", line 36, in forward
>     x = self.neck(x)
>   File "./YOLOv6/deploy/ONNX/export_onnx.py", line 99, in <module>
>     y = model(img)  # dry run
> RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 24 but got size 23 for tensor number 1 in the list.

How can i solve it?

**Comment by mtjhl** [comment]
The input size pass to the model must be the multiples of 32. 
You should use
```
python ./deploy/ONNX/export_onnx.py --weights 640x360.pt --img 384 640 --batch 1 --simplify
```
or with size 352, 640

**Comment by karls-accnt** [comment]
@mtjhl 
As you see, In my question, I used same script that wrote you. 

But i got Runtime Error.(as the below)
Sizes of tensors must match except in dimension 1. Expected size 24 but got size 23 for tensor number 1 in the list.
File "./YOLOv6/yolov6/layers/common.py", line 766, in forward
return self.cv3(torch.cat((x0, x1, x2), dim=1))
File "./YOLOv6/yolov6/models/reppan.py", line 220, in forward
f_concat_layer0 = self.Bifusion0([fpn_out0, x1, x2])
File "./YOLOv6/yolov6/models/yolo.py", line 36, in forward
x = self.neck(x)
File "./YOLOv6/deploy/ONNX/export_onnx.py", line 99, in
y = model(img) # dry run
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 24 but got size 23 for tensor number 1 in the list.
