### ISSUE TITLE
AssertionError: Results do not correspond to current coco set

### ISSUE THREAD

**Issue by moxigk** [meituan/YOLOv6#101]
之前的错误是：
TypeError: '<' not supported between instances of 'str' and 'int'
           
我根据你的方法改了，
image_id = int(path.stem) if path.stem.isnumeric() else path.stem
   image_id=path.stem
出现了这个问题
AssertionError: Results do not correspond to current coco set

是不是数据集的名字必须是数字吗？不能包含英文吗或者其他字符吗？

**Comment by jia0511** [comment]
+1

**Comment by yydc-0** [comment]
+1

**Comment by WhXl** [comment]
+1

**Comment by mtjhl** [comment]
Please pull the latest code, if training on custom dataset, set this flag to False.
https://github.com/meituan/YOLOv6/blob/fb9485fdb3c5e290c51b8c7dc8b05e2bc78a8da3/data/coco.yaml#L9
