### ISSUE TITLE
YOLOv6-Segmentation 分割模型导出onnx异常

### ISSUE THREAD

**Issue by laishenghui** [meituan/YOLOv6#1013]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

我用的是这里的代码和权重文件https://github.com/meituan/YOLOv6/releases/tag/0.4.1
使用export_onnx.py导出yolov6n_seg.pt时出现异常
异常日志如下：
D:\Anaconda3\envs\yolov6\python.exe E:\YOLOv6\YOLOv6-0.4.1\deploy\ONNX\export_onnx.py --weights weights\yolov6n_seg.pt --img-size 640 --batch-size 1 --end2end --ort --topk-all 100 --device 0 
Namespace(batch_size=1, conf_thres=0.5, device='0', dynamic_batch=False, end2end=True, half=False, img_size=[640, 640], inplace=False, iou_thres=0.65, ort=True, simplify=False, topk_all=100, trt_version=8, weights='weights\\yolov6n_seg.pt', with_preprocess=False)
Loading checkpoint from weights\yolov6n_seg.pt

Fusing model...
===================
End2End(
  (model): Model(
    (backbone): EfficientRep(
      (stem): RepVGGBlock(
        (nonlinearity): ReLU(inplace=True)
        (se): Identity()
        (rbr_reparam): Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      )
      (ERBlock_2): Sequential(
        (0): RepVGGBlock(
          (nonlinearity): ReLU(inplace=True)
          (se): Identity()
          (rbr_reparam): Conv2d(16, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        )
        (1): RepBlock(
          (conv1): RepVGGBlock(
            (nonlinearity): ReLU(inplace=True)
            (se): Identity()
            (rbr_reparam): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          )
          (block): Sequential(
            (0): RepVGGBlock(
              (nonlinearity): ReLU(inplace=True)
              (se): Identity()
              (rbr_reparam): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            )
          )
        )
      )
      (ERBlock_3): Sequential(
        (0): RepVGGBlock(
          (nonlinearity): ReLU(inplace=True)
          (se): Identity()
          (rbr_reparam): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        )
        (1): RepBlock(
          (conv1): RepVGGBlock(
            (nonlinearity): ReLU(inplace=True)
            (se): Identity()
            (rbr_reparam): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          )
          (block): Sequential(
            (0): RepVGGBlock(
              (nonlinearity): ReLU(inplace=True)
              (se): Identity()
              (rbr_reparam): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            )
            (1): RepVGGBlock(
              (nonlinearity): ReLU(inplace=True)
              (se): Identity()
              (rbr_reparam): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            )
            (2): RepVGGBlock(
              (nonlinearity): ReLU(inplace=True)
              (se): Identity()
              (rbr_reparam): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            )
          )
        )
      )
      (ERBlock_4): Sequential(
        (0): RepVGGBlock(
          (nonlinearity): ReLU(inplace=True)
          (se): Identity()
          (rbr_reparam): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        )
        (1): RepBlock(
          (conv1): RepVGGBlock(
            (nonlinearity): ReLU(inplace=True)
            (se): Identity()
            (rbr_reparam): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          )
          (block): Sequential(
            (0): RepVGGBlock(
              (nonlinearity): ReLU(inplace=True)
              (se): Identity()
              (rbr_reparam): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            )
            (1): RepVGGBlock(
              (nonlinearity): ReLU(inplace=True)
              (se): Identity()
              (rbr_reparam): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            )
            (2): RepVGGBlock(
              (nonlinearity): ReLU(inplace=True)
              (se): Identity()
              (rbr_reparam): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            )
            (3): RepVGGBlock(
              (nonlinearity): ReLU(inplace=True)
              (se): Identity()
              (rbr_reparam): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            )
            (4): RepVGGBlock(
              (nonlinearity): ReLU(inplace=True)
              (se): Identity()
              (rbr_reparam): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            )
          )
        )
      )
      (ERBlock_5): Sequential(
        (0): RepVGGBlock(
          (nonlinearity): ReLU(inplace=True)
          (se): Identity()
          (rbr_reparam): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        )
        (1): RepBlock(
          (conv1): RepVGGBlock(
            (nonlinearity): ReLU(inplace=True)
            (se): Identity()
            (rbr_reparam): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          )
          (block): Sequential(
            (0): RepVGGBlock(
              (nonlinearity): ReLU(inplace=True)
              (se): Identity()
              (rbr_reparam): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            )
          )
        )
        (2): SimCSPSPPF(
          (cspsppf): CSPSPPFModule(
            (cv1): ConvBNReLU(
              (block): ConvModule(
                (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1))
                (act): ReLU(inplace=True)
              )
            )
            (cv2): ConvBNReLU(
              (block): ConvModule(
                (conv): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1))
                (act): ReLU(inplace=True)
              )
            )
            (cv3): ConvBNReLU(
              (block): ConvModule(
                (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                (act): ReLU(inplace=True)
              )
            )
            (cv4): ConvBNReLU(
              (block): ConvModule(
                (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1))
                (act): ReLU(inplace=True)
              )
            )
            (m): MaxPool2d(kernel_size=5, stride=1, padding=2, dilation=1, ceil_mode=False)
            (cv5): ConvBNReLU(
              (block): ConvModule(
                (conv): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1))
                (act): ReLU(inplace=True)
              )
            )
            (cv6): ConvBNReLU(
              (block): ConvModule(
                (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                (act): ReLU(inplace=True)
              )
            )
            (cv7): ConvBNReLU(
              (block): ConvModule(
                (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
                (act): ReLU(inplace=True)
              )
            )
          )
        )
      )
    )
    (neck): RepBiFPANNeck(
      (reduce_layer0): ConvBNReLU(
        (block): ConvModule(
          (conv): Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1))
          (act): ReLU(inplace=True)
        )
      )
      (Bifusion0): BiFusion(
        (cv1): ConvBNReLU(
          (block): ConvModule(
            (conv): Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1))
            (act): ReLU(inplace=True)
          )
        )
        (cv2): ConvBNReLU(
          (block): ConvModule(
            (conv): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
            (act): ReLU(inplace=True)
          )
        )
        (cv3): ConvBNReLU(
          (block): ConvModule(
            (conv): Conv2d(192, 64, kernel_size=(1, 1), stride=(1, 1))
            (act): ReLU(inplace=True)
          )
        )
        (upsample): Transpose(
          (upsample_transpose): ConvTranspose2d(64, 64, kernel_size=(2, 2), stride=(2, 2))
        )
        (downsample): ConvBNReLU(
          (block): ConvModule(
            (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
            (act): ReLU(inplace=True)
          )
        )
      )
      (Rep_p4): RepBlock(
        (conv1): RepVGGBlock(
          (nonlinearity): ReLU(inplace=True)
          (se): Identity()
          (rbr_reparam): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
        (block): Sequential(
          (0): RepVGGBlock(
            (nonlinearity): ReLU(inplace=True)
            (se): Identity()
            (rbr_reparam): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          )
          (1): RepVGGBlock(
            (nonlinearity): ReLU(inplace=True)
            (se): Identity()
            (rbr_reparam): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          )
          (2): RepVGGBlock(
            (nonlinearity): ReLU(inplace=True)
            (se): Identity()
            (rbr_reparam): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          )
        )
      )
      (reduce_layer1): ConvBNReLU(
        (block): ConvModule(
          (conv): Conv2d(64, 32, kernel_size=(1, 1), stride=(1, 1))
          (act): ReLU(inplace=True)
        )
      )
      (Bifusion1): BiFusion(
        (cv1): ConvBNReLU(
          (block): ConvModule(
            (conv): Conv2d(64, 32, kernel_size=(1, 1), stride=(1, 1))
            (act): ReLU(inplace=True)
          )
        )
        (cv2): ConvBNReLU(
          (block): ConvModule(
            (conv): Conv2d(32, 32, kernel_size=(1, 1), stride=(1, 1))
            (act): ReLU(inplace=True)
          )
        )
        (cv3): ConvBNReLU(
          (block): ConvModule(
            (conv): Conv2d(96, 32, kernel_size=(1, 1), stride=(1, 1))
            (act): ReLU(inplace=True)
          )
        )
        (upsample): Transpose(
          (upsample_transpose): ConvTranspose2d(32, 32, kernel_size=(2, 2), stride=(2, 2))
        )
        (downsample): ConvBNReLU(
          (block): ConvModule(
            (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
            (act): ReLU(inplace=True)
          )
        )
      )
      (Rep_p3): RepBlock(
        (conv1): RepVGGBlock(
          (nonlinearity): ReLU(inplace=True)
          (se): Identity()
          (rbr_reparam): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
        (block): Sequential(
          (0): RepVGGBlock(
            (nonlinearity): ReLU(inplace=True)
            (se): Identity()
            (rbr_reparam): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          )
          (1): RepVGGBlock(
            (nonlinearity): ReLU(inplace=True)
            (se): Identity()
            (rbr_reparam): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          )
          (2): RepVGGBlock(
            (nonlinearity): ReLU(inplace=True)
            (se): Identity()
            (rbr_reparam): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          )
        )
      )
      (downsample2): ConvBNReLU(
        (block): ConvModule(
          (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
          (act): ReLU(inplace=True)
        )
      )
      (Rep_n3): RepBlock(
        (conv1): RepVGGBlock(
          (nonlinearity): ReLU(inplace=True)
          (se): Identity()
          (rbr_reparam): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
        (block): Sequential(
          (0): RepVGGBlock(
            (nonlinearity): ReLU(inplace=True)
            (se): Identity()
            (rbr_reparam): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          )
          (1): RepVGGBlock(
            (nonlinearity): ReLU(inplace=True)
            (se): Identity()
            (rbr_reparam): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          )
          (2): RepVGGBlock(
            (nonlinearity): ReLU(inplace=True)
            (se): Identity()
            (rbr_reparam): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          )
        )
      )
      (downsample1): ConvBNReLU(
        (block): ConvModule(
          (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
          (act): ReLU(inplace=True)
        )
      )
      (Rep_n4): RepBlock(
        (conv1): RepVGGBlock(
          (nonlinearity): ReLU(inplace=True)
          (se): Identity()
          (rbr_reparam): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
        (block): Sequential(
          (0): RepVGGBlock(
            (nonlinearity): ReLU(inplace=True)
            (se): Identity()
            (rbr_reparam): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          )
          (1): RepVGGBlock(
            (nonlinearity): ReLU(inplace=True)
            (se): Identity()
            (rbr_reparam): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          )
          (2): RepVGGBlock(
            (nonlinearity): ReLU(inplace=True)
            (se): Identity()
            (rbr_reparam): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          )
        )
      )
    )
    (detect): Detect(
      (proj_conv): Conv2d(17, 1, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (stems): ModuleList(
        (0): ConvBNSiLU(
          (block): ConvModule(
            (conv): Conv2d(32, 32, kernel_size=(1, 1), stride=(1, 1))
            (act): SiLU()
          )
        )
        (1): ConvBNSiLU(
          (block): ConvModule(
            (conv): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1))
            (act): SiLU()
          )
        )
        (2): ConvBNSiLU(
          (block): ConvModule(
            (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1))
            (act): SiLU()
          )
        )
      )
      (cls_convs): ModuleList(
        (0): ConvBNSiLU(
          (block): ConvModule(
            (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            (act): SiLU()
          )
        )
        (1): ConvBNSiLU(
          (block): ConvModule(
            (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            (act): SiLU()
          )
        )
        (2): ConvBNSiLU(
          (block): ConvModule(
            (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            (act): SiLU()
          )
        )
      )
      (reg_convs): ModuleList(
        (0): ConvBNSiLU(
          (block): ConvModule(
            (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            (act): SiLU()
          )
        )
        (1): ConvBNSiLU(
          (block): ConvModule(
            (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            (act): SiLU()
          )
        )
        (2): ConvBNSiLU(
          (block): ConvModule(
            (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            (act): SiLU()
          )
        )
      )
      (seg_convs): ModuleList(
        (0): ConvBNSiLU(
          (block): ConvModule(
            (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            (act): SiLU()
          )
        )
        (1): ConvBNSiLU(
          (block): ConvModule(
            (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            (act): SiLU()
          )
        )
        (2): ConvBNSiLU(
          (block): ConvModule(
            (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            (act): SiLU()
          )
        )
      )
      (cls_preds): ModuleList(
        (0): Conv2d(32, 80, kernel_size=(1, 1), stride=(1, 1))
        (1): Conv2d(64, 80, kernel_size=(1, 1), stride=(1, 1))
        (2): Conv2d(128, 80, kernel_size=(1, 1), stride=(1, 1))
      )
      (reg_preds): ModuleList(
        (0): Conv2d(32, 4, kernel_size=(1, 1), stride=(1, 1))
        (1): Conv2d(64, 4, kernel_size=(1, 1), stride=(1, 1))
        (2): Conv2d(128, 4, kernel_size=(1, 1), stride=(1, 1))
      )
      (seg_preds): ModuleList(
        (0): Conv2d(32, 32, kernel_size=(1, 1), stride=(1, 1))
        (1): Conv2d(64, 32, kernel_size=(1, 1), stride=(1, 1))
        (2): Conv2d(128, 32, kernel_size=(1, 1), stride=(1, 1))
      )
      (cls_preds_ab): ModuleList()
      (reg_preds_ab): ModuleList()
      (seg_preds_ab): ModuleList()
      (seg_proto): ModuleList(
        (0): Proto(
          (cv1): Conv(
            (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
          (upsample): Upsample(scale_factor=2.0, mode=nearest)
          (cv2): Conv(
            (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
          (cv3): Conv(
            (conv): Conv2d(64, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
        )
      )
    )
  )
  (end2end): ONNX_ORT()
)
===================
Traceback (most recent call last):
  File "E:\YOLOv6\YOLOv6-0.4.1\deploy\ONNX\export_onnx.py", line 99, in <module>
    y = model(img)  # dry run
  File "D:\Anaconda3\envs\yolov6\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\YOLOv6\YOLOv6-0.4.1\yolov6\models\end2end.py", line 281, in forward
    x = self.end2end(x)
  File "D:\Anaconda3\envs\yolov6\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\YOLOv6\YOLOv6-0.4.1\yolov6\models\end2end.py", line 153, in forward
    batch, anchors, _ = x.shape
AttributeError: 'tuple' object has no attribute 'shape'

Process finished with exit code 1

**Comment by laishenghui** [comment]
@Chilicyy 感谢您的及时回复，去除end2end参数后，确实可以导出。我还想请问一下，如果导出模型不是end2end模型，那用onnx模型推理的时候需要做什么额外处理吗？

**Comment by bilibili12433014** [comment]
但是我使用的是yolov6n，也出现了这个问题
