### ISSUE TITLE
Could  yolov6-seg do validation by pycocotools now?

### ISSUE THREAD

**Issue by DrChungAlbert** [meituan/YOLOv6#1017]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

At present, the code for these performance evaluations by  pycocotools seems to be commented out from
https://github.com/meituan/YOLOv6/blob/yolov6-seg/tools/eval.py#L163
and here
https://github.com/meituan/YOLOv6/blob/yolov6-seg/yolov6/core/evaler.py#L160
And, only work to do evaluation when do_pr_metric is on by ap_per_class_box_and_mask()
https://github.com/meituan/YOLOv6/blob/yolov6-seg/yolov6/core/evaler.py#L220C1-L239C1

Could the yolov6-seg support the pycocotools for validation by --task val now ?

**Comment by Chilicyy** [comment]
Hi @DrChungAlbert , YOLOv6-seg applies the indicator calculation method same as yolov8 for fair comparision. Using pycocotools   for segmentation evaluation is not supported , and we'll try to improve this function asap. Sorry for the inconvenience.
