### ISSUE TITLE
Error of tools/eval.py, --task val

### ISSUE THREAD

**Issue by jrsebastian** [meituan/YOLOv6#1018]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [ ] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

我已经根据指导组织了 COCO 数据集的目录，但是在 val 时，仍然会出现map = -1 的情况，我打印了 label_paths 的数据，是正常的，但是为什么到了 self.check_labels 中，nf_per_file 就是 0 了呢？

![image](https://github.com/meituan/YOLOv6/assets/34502782/92960e0a-e4a7-4717-9838-dd2f9b7958a4)

我的命令是python tools/eval.py --data data/coco.yaml --batch 32 --weights weights/yolov6s.pt --task val --device cpu

**Comment by DrChungAlbert** [comment]
val path need to be correct in yaml

**Comment by jrsebastian** [comment]
> val path need to be correct in yaml

my val path is correct. Maybe the label format is wrong?But i download these from COCO

**Comment by Chilicyy** [comment]
Hi @jrsebastian , you could download the YOLO format coco label files from [here](https://github.com/meituan/YOLOv6/releases/download/0.1.0/coco2017labels.zip), and make sure your dataset structure is correct. Please refer to README.md.

**Comment by jrsebastian** [comment]
Hi @Chilicyy ,Thankyou for your label files. It worked, and I will close this issue, Thank you very much
