### ISSUE TITLE
Subsequent runs don't create new runs/train/expX dir 

### ISSUE THREAD

**Issue by knoppmyth** [meituan/YOLOv6#102]
Hello,

First off, kudos on "YOLOv6"! Using the same training data I created a model that so far appears to out perform a model I made with YOLOv5! It finds objects with greater accuracy and at the same or slight faster speed!

Using YOLOv5, if I attempt to build a subsequent models, a new directory is created for each. Doing this with YOLOv6, I don't see a new directory getting created under 'runs/train/'. The older directory gets over ridden. Is this by design? Should a new expX directory get created?

Keeping the older and creating a new would be great as one could easier compare their created models and note the args.yaml to help keep of changes.

**Comment by mtjhl** [comment]
> Hello,
> 
> First off, kudos on "YOLOv6"! Using the same training data I created a model that so far appears to out perform a model I made with YOLOv5! It finds objects with greater accuracy and at the same or slight faster speed!
> 
> Using YOLOv5, if I attempt to build a subsequent models, a new directory is created for each. Doing this with YOLOv6, I don't see a new directory getting created under 'runs/train/'. The older directory gets over ridden. Is this by design? Should a new expX directory get created?
> 
> Keeping the older and creating a new would be great as one could easier compare their created models and note the args.yaml to help keep of changes.

Sorry for the  inconvenience, currently you can add `--name` to assign the name, for example 
  `python tools/train.py --name exp_name ` .
We will add the function you mentioned as soon as possible.

**Comment by knoppmyth** [comment]
Thanks for the response. It isn't an inconvenience. I'm looking forward to this change and future improvements. Thanks for releasing this!

**Comment by mtjhl** [comment]
> Thanks for the response. It isn't an inconvenience. I'm looking forward to this change and future improvements. Thanks for releasing this!

HI, we add this function now. Thank you for your advise.

**Comment by knoppmyth** [comment]
This appears to be resolved in the latest pull (7/28/22). Thanks again.
