### ISSUE TITLE
How to properly inference YOLOv6-L6 onnx?

### ISSUE THREAD

**Issue by HeChengHui** [meituan/YOLOv6#1021]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [ ] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

I am trying to inference [YOLOv6-L6](https://github.com/meituan/YOLOv6/releases/download/0.4.0/yolov6l6.pt) on onnxruntime

> torch                     2.1.0+cu118              pypi_0    pypi
> torchvision               0.16.0+cu118             pypi_0    pypi
> onnx                      1.15.0                   pypi_0    pypi
> onnx-simplifier           0.4.35                   pypi_0    pypi
> onnxruntime-gpu           1.17.0                   pypi_0    pypi
> onnxscript                0.1.0.dev20240207          pypi_0    pypi

1. when i tried to run `python deploy/ONNX/OpenCV/yolo_video.py --model "yolov6l6.onnx"`, the speed is super slow.
2. tried follow the tutorial [here](https://github.com/meituan/YOLOv6/blob/87dd3d3963b6b373ccdc626b9bae5a2afec5639e/deploy/ONNX/YOLOv6-Dynamic-Batch-onnxruntime.ipynb) but when i export using 
```
python deploy/ONNX/export_onnx.py \
    --weights weights/yolov6.pt \
    --end2end --simplify \
    --topk-all 100 \
    --iou-thres 0.65 \
    --conf-thres 0.35 \
    --img-size 640 640 \
    --dynamic-batch \
    --ort \
```
i get the error: `onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from YOLO/YOLOv6/yolov6l6.onnx failed:Type Error: Type parameter (T) of Optype (Where) bound to different types (tensor(int64) and tensor(float) in node (/end2end/Where_1).`

It works when i remove --end2end but the output becomes `outname=['outputs']` instead of `['num_dets', 'det_boxes', 'det_scores', 'det_classes']`

**Comment by laishenghui** [comment]
https://github.com/meituan/YOLOv6/issues/1013#issue-2111373801
我之前也遇到这个问题，你可以看看这个

**Comment by HeChengHui** [comment]
@laishenghui 
我确实尝试过不用 --end2end，但output名称与 jupyter notebook 中所述的不同。这是有意的行为吗？

**Comment by laishenghui** [comment]
名称不同没关系的，只需要获取到信息，然后计算出区域就可以

**Comment by bilibili12433014** [comment]
@HeChengHui 我找到了问题并在我的设备上成功运行了，希望能够帮助到你：https://github.com/meituan/YOLOv6/pull/1028#issue-2181304935
