### ISSUE TITLE
Some questions about inference using various engines

### ISSUE THREAD

**Issue by jrsebastian** [meituan/YOLOv6#1023]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

I want to use other engine(*.onnx) to running inference with YOLOv6s model, but ```tools/eval.py``` seems not support.
I use ```deploy/ONNX/eval_trt.py``` but it not worked, yolov6n.onnx is exported from ```/deploy/ONNX/export_onnx.py```
The error is:
![image](https://github.com/meituan/YOLOv6/assets/34502782/01d16633-49f4-4a59-8013-63e38edaf75e)

Is there any Class like this [AutoBackend](https://github.com/ultralytics/ultralytics/blob/61088b43d763a91c614134f295cf762f5beaba76/ultralytics/nn/autobackend.py#L53)?
How to infer *.onnx models? Thank you

**Comment by laishenghui** [comment]
![image](https://github.com/meituan/YOLOv6/assets/81606481/2d6d24b7-a43c-45a8-ac20-d4631380e6ff)
you should use this file

**Comment by jrsebastian** [comment]
> ![image](https://private-user-images.githubusercontent.com/81606481/306240650-2d6d24b7-a43c-45a8-ac20-d4631380e6ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODM1MTQsIm5iZiI6MTcwODQ4MzIxNCwicGF0aCI6Ii84MTYwNjQ4MS8zMDYyNDA2NTAtMmQ2ZDI0YjctYTQzYy00NWE4LWFjMjAtZDQ2MzEzODBlNmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAyNDAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NDY3N2RjY2M4ZDczMjJiZTdiZGMxZjNiNjcyZWVjYzQxZmYyOTNiMjBlYjdjMGFhNDNiMzk4ZWM0OWU5MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8yLLDKN-zUhkC9q42jePmITC13uu4pGOvmnSRClvch0) you should use this file

@laishenghui Thank you very much. But this file seems only output Inference time and show the img? Exactly I want to eval the onnx model, and get mAPval 0.5:0.95 on COCO dataset, Is there any file can do this?
Thanks

**Comment by laishenghui** [comment]
i don‘t know this, maybe you should write it  by youself.
