### ISSUE TITLE
Yolov6_Face models incompatible

### ISSUE THREAD

**Issue by joooshuaa** [meituan/YOLOv6#1025]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [ ] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

Since the release of yolov6 face lite models, the original face models are not compatible anymore.
See commit df7c92f64252812ef2434b2893417622d327428c.
Here the new Conv Layer Structure (I guess like in 4.x) in layers/common.py is merged into the yolov6-face release and therefore becomes incompatible with the 3.x models.
E.g. when trying to load yolov6l_face.pt:
![image](https://github.com/meituan/YOLOv6/assets/50237865/2b7e75e0-2b26-474b-b73d-8a7a0768bd09)
Especially since in the readme, for inference, it says to download one of the models from the [release](https://github.com/meituan/YOLOv6/releases/tag/0.3.1). Following that link, only the large models are displayed, all of which are incompatible with the latest yolov6-face code.
What is the proposed solution if one wants to use the original/non-lite face models? Should one checkout to commit 4147856855a664b6e1b25c5721b127d143017cdd where old models are still compatible? Or possibly the larger models with the new layer structure can be fine-tuned for 300 epochs, as originally, and uploaded again?
Thank you very much.

**Comment by Chilicyy** [comment]
Hi @joooshuaa , the converted yolov6-face models corresponding to the latest code can be downloaded [here](https://github.com/meituan/YOLOv6/releases/tag/0.4.0) under Assets.

**Comment by joooshuaa** [comment]
I see, thank you. Appreciate your work!

**Comment by joooshuaa** [comment]
I see, thank you. Appreciate your work!
