### ISSUE TITLE
mAP为0

### ISSUE THREAD

**Issue by hutao568** [meituan/YOLOv6#103]
我在[新版本](https://github.com/meituan/YOLOv6/commit/1d1335c62a939f2e5d639bdf2afec65c18beb59f)后训练我自己的数据集结果mAP仍然为0，当我把数据集调小训练200epoch后发现模型不会收敛。

**Comment by mtjhl** [comment]
> 我在[新版本](https://github.com/meituan/YOLOv6/commit/1d1335c62a939f2e5d639bdf2afec65c18beb59f)后训练我自己的数据集结果mAP仍然为0，当我把数据集调小训练200epoch后发现模型不会收敛。

We are reproducing this problem, we will try to fix this bug today.

**Comment by hutao568** [comment]
@mtjhl 最新代码mAP正常了，初始代码放的太着急了
