### ISSUE TITLE
yolov6n_seg.pt是P6模型吗？为什么训练的时候设置--fuse_ab的时候训练会出现异常

### ISSUE THREAD

**Issue by laishenghui** [meituan/YOLOv6#1037]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

版本0.4.1
疑问如题，异常信息如下图
![image](https://github.com/meituan/YOLOv6/assets/81606481/6e3b8e6a-63f6-493f-8969-7a48e12c42be)

**Comment by Chilicyy** [comment]
您好 @laishenghui ，分割模型是P5模型，暂不支持fuse_ab的训练。

**Comment by laishenghui** [comment]
感谢大佬回复
