### ISSUE TITLE
训练时出现ModuleNotFoundError: No module named 'tools.eval'

### ISSUE THREAD

**Issue by HUANG7M** [meituan/YOLOv6#104]
我是通过pip install -r requirements.txt安装的所有包，python3.8
训练时出现ModuleNotFoundError: No module named 'tools.eval'请问是什么原因呢？

**Comment by mtjhl** [comment]
> 我是通过pip install -r requirements.txt安装的所有包，python3.8
> 训练时出现ModuleNotFoundError: No module named 'tools.eval'请问是什么原因呢？

I guess you have install YOLOX in this ends, you can run `pip uninstall yolox` , or create a new envs.

**Comment by yyxxcxd** [comment]
I have a same question

**Comment by HUANG7M** [comment]
我已解决，具体为：
在YOLOv6/tools/中创建新的 __init__.py 

内容：

```python
import sys
import os
ROOT = os.getcwd()
if str(ROOT) not in sys.path:
sys.path.insert(0, str(ROOT))
```

然后更改tools/train.py中的sys.path.insert(0, str(ROOT))改为：sys.path.append(str(ROOT))

**Comment by HUANG7M** [comment]
Thank you for your careful answer

**Comment by wanyne-yyds** [comment]
查看sys.path里的tools路径，然后用 sys.path.remove("/home/ckn/Code/YOLOX-0.3.0") 删掉无用路径即可。无需其它操作。

**Comment by keepgoing365** [comment]
> 



> 查看sys.path里的tools路径，然后用 sys.path.remove("/home/ckn/Code/YOLOX-0.3.0") 删掉无用路径即可。无需其它操作。

亲测有效，一开始我还以为是源码有问题，结果是sys.path里的路径中有其他项目也有tools/文件，编译器找错了。我在train.py文件中加的sys.path.remove('XXX')代码
