### ISSUE TITLE
如何在不改变分割模型尺寸的情况下，调整推理结果中mask的尺寸？

### ISSUE THREAD

**Issue by laishenghui** [meituan/YOLOv6#1043]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

0.4.1版本的yolov6提供了分割模型，当训练分割模型时设置--img_size为640*640时，训练完成后的模型输出mask的尺寸为160*160，如果我想要将模型输出的mask尺寸调整为640*640，我应该如何修改以实现这个目的？
![image](https://github.com/meituan/YOLOv6/assets/81606481/e327eeee-c727-4a22-b15f-64b08967a1dc)

**Comment by YahooKID** [comment]
This is currently not feasible. It is the direct output of the convolution, and increasing it would affect the model size and inference speed. You can try using resize directly on the output side.

Cheers.

**Comment by laishenghui** [comment]
嗯嗯，修改网络之后推理会出问题
