### ISSUE TITLE
Why mAP is so low? use yolov6 to train my data 

### ISSUE THREAD

**Issue by betterbq** [meituan/YOLOv6#105]
![image](https://user-images.githubusercontent.com/99774744/176116589-4657ffe0-ccc7-4026-aa91-79d0b05bfd6c.png)

**Comment by mtjhl** [comment]
How many epochs have you trained? How many images in your train dataset?

**Comment by betterbq** [comment]
> 
300epochs and 3000images

**Comment by youwenjing** [comment]
我也是一样的结果 应该是val出了问题？

**Comment by mtjhl** [comment]
Please pull the latest code. Train on custom dataset, set the flag is_coco to False.
https://github.com/meituan/YOLOv6/blob/fb9485fdb3c5e290c51b8c7dc8b05e2bc78a8da3/data/coco.yaml#L9
