### ISSUE TITLE
Google Colab Tutorial

### ISSUE THREAD

**Issue by hammadyounas2008** [meituan/YOLOv6#106]
Hello , I hope you are doing well. 
have you any google colab tutorial, please add google colab tutorial , it will be very beneficial for all of new python developer

**Comment by mtjhl** [comment]
Thank you for your advice, this repo is in rapid developing, when we reach a milestone, we will consider to write a collar tutorial.

**Comment by Zephyr69** [comment]
@hammadyounas2008  You can get ur hands on yolov5 while waiting. That one adopts essentially the same dataset format and has been tried, tested, and developed for a long time.

**Comment by hammadyounas2008** [comment]
@Zephyr69 I have hands on experience with yolov5, but there is some different in this repo that's why i asked for google colab tutorial because it is very beneficial for new yolo users

**Comment by hammadyounas2008** [comment]
@mtjhl  Thanks waiting for it.

**Comment by mahdilamb** [comment]
Hi @hammadyounas2008, Please see my fork with the following code:
https://github.com/mahdilamb/YOLOv6/blob/main/inference.ipynb

Allows you to run inference using google colab forms
