### ISSUE TITLE
Train your own dataset problem

### ISSUE THREAD

**Issue by GuanLinHu** [meituan/YOLOv6#107]
Hello I would like to ask if I want to train my model error according to your tutorial, if there is a solution, thank you.
![image](https://user-images.githubusercontent.com/61997271/176127434-cedea4eb-ad00-4712-b758-3de9da434a98.png)
![image](https://user-images.githubusercontent.com/61997271/176126418-32da4379-7353-4b9d-a466-7f7c6a72c841.png)
![image](https://user-images.githubusercontent.com/61997271/176126804-6ddcdd2b-bca6-4cd6-90df-273f1b4c8402.png)
![image](https://user-images.githubusercontent.com/61997271/176126996-08d2453d-f2cd-462b-82f3-1475d66c4824.png)

**Comment by Zephyr69** [comment]
Try to use absolute path in the yaml.

**Comment by aknsel** [comment]
![Screen Shot 2022-06-28 at 11 27 46](https://user-images.githubusercontent.com/108330135/176132993-6e2c0de1-b3a1-4be0-b760-15a21a34d7f4.png)
![Screen Shot 2022-06-28 at 11 26 19](https://user-images.githubusercontent.com/108330135/176131837-4721e5e7-8390-4f93-a804-03e68f0e9dd9.png)
I've similar problem. Labels are txt format in labels folder train/val located separately. But I got an error as above

**Comment by Zephyr69** [comment]
> ![Screen Shot 2022-06-28 at 11 27 46](https://user-images.githubusercontent.com/108330135/176132993-6e2c0de1-b3a1-4be0-b760-15a21a34d7f4.png) ![Screen Shot 2022-06-28 at 11 26 19](https://user-images.githubusercontent.com/108330135/176131837-4721e5e7-8390-4f93-a804-03e68f0e9dd9.png) I've similar problem. Labels are txt format in labels folder train/val located separately. But I got an error as above

This is a different issue. 
You might have the annotations in the wrong format, which causes the checking function to return None for img_path and breaks the dataset class at img_info.pop(img_path). 
https://github.com/meituan/YOLOv6/blob/1d1335c62a939f2e5d639bdf2afec65c18beb59f/yolov6/data/datasets.py#L477

**Comment by GuanLinHu** [comment]
I tried to use the absolute path but also got an error.
![image](https://user-images.githubusercontent.com/61997271/176137782-a867f331-3e1e-4a51-988a-4e385a2457c8.png)

**Comment by guptadikshant** [comment]
I also faced the same issue but suddenly after 2-3 runs it started executing . Can you please try to make folder structure like
Images
======
  --train(contains only images)
  --val(contains only validation images)
  --test(contains only test images)

labels
=====
 --train(contains only train labels in text format)
 --val(contains only validation labels in text format)
 --test(contains only test labels in text format)

And then update your **data.yaml** file with the absolute paths of these folders

**Comment by aknsel** [comment]
> # I also faced the same issue but suddenly after 2-3 runs it started executing . Can you please try to make folder structure like
> Images
> --train(contains only images) --val(contains only validation images) --test(contains only test images)
> 
> # labels
> --train(contains only train labels in text format) --val(contains only validation labels in text format) --test(contains only test labels in text format)
> 
> And then update your **data.yaml** file with the absolute paths of these folders

I tried but it doesn't work..:(... Folder structure is as you mentioned... I just give image folder path in data.yaml file..Do you give label folder path in data.yaml? Could you share your yaml file also?

**Comment by ozzmanmuhammad** [comment]
I am facing the same issue, while the same labels .txt files work fine for the yolov5.

**Comment by guptadikshant** [comment]
Hi @GuanLinHu I used below folder structure

![image](https://user-images.githubusercontent.com/51189309/176381537-d19a28e1-c1e3-4a6b-a2f8-10de5864bf68.png)

**Comment by guptadikshant** [comment]
Hi @aknsel please find below my data.yaml file

![image](https://user-images.githubusercontent.com/51189309/176381844-281cbc8a-8014-47f7-8387-a7fc9aab40df.png)

**Comment by eduardocarnunes** [comment]
I was also having this error yesterday.
I had to use the COCO format (as in the image).
It worked like this for me.

1º: I used roboflow to export in COCO format
2º Structure of my custom dataset
3º Each folder has 


![ddddddd](https://user-images.githubusercontent.com/23443227/176393387-4fa74205-e72f-4721-a995-00ecfdb72595.png)

**Comment by GuanLinHu** [comment]
@guptadikshant Thank you, I can run, the problem of folder placement, great to run.
![a](https://user-images.githubusercontent.com/61997271/176393818-d603ffc6-ce97-418c-a2a2-d4e91314dabf.PNG)

**Comment by guptadikshant** [comment]
@GuanLinHu can you please confirm are you able to do the inferencing. I mean after running the inferencing command are you able to see the the result image in the saved directory?

**Comment by GuanLinHu** [comment]
@guptadikshant Hello, I have a model after training, but after training with yolov5, there will be training data (.csv or training result graph), but I don't have it after running. Also, the calss set by my .yaml are 1, 2, 3.. But I am still looking for other classes
![1](https://user-images.githubusercontent.com/61997271/176410202-42506439-0757-49ed-9f40-b4eb29a7d9fb.PNG)
![2](https://user-images.githubuserconten
![3](https://user-images.githubusercontent.com/61997271/176410224-7913ad4c-6a39-4630-9360-93b1854eca1d.PNG)
t.com/61997271/176410212-601026e1-7dc7-412d-99ee-65cd69676a85.PNG)
.

**Comment by thangarajdeivasikamani** [comment]
> @guptadikshant Hello, I have a model after training, but after training with yolov5, there will be training data (.csv or training result graph), but I don't have it after running. Also, the calss set by my .yaml are 1, 2, 3.. But I am still looking for other classes. ![1](https://user-images.githubusercontent.com/61997271/176410731-631cf21f-1d7d-49bf-8d19-50ed22b4acd0.PNG) ![2](https://user-images.githubusercontent.com/61997271/176412685-049286da-5207-471b-8464-caca875e6d32.PNG) ![3](https://user-images.githubusercontent.com/61997271/176410756-07725fd9-2b9d-44e6-a80c-ca2613d46990.PNG)

@GuanLinHu 

Have you got the solution for wrong labeling? I am also facing same issue for my custom Training
