### ISSUE TITLE
Training Custom Data

### ISSUE THREAD

**Issue by AhmedEmadEldinHussin** [meituan/YOLOv6#111]
I am training on custom dataset 
the yaml file is written in this way 
![Screenshot from 2022-06-28 14-49-54](https://user-images.githubusercontent.com/18230011/176161465-c631aae4-016c-40da-a19d-74d1d62dc5d3.png)

and Im getting this error
AssertionError: /home/ahmed/yolov6/images/labels/ is an invalid directory path!

**Comment by AhmedEmadEldinHussin** [comment]
Thanks 
the problem has been solved by removing the slash from the directory path

**Comment by guptadikshant** [comment]
Hi @AhmedEmadEldinHussin I am also facing same issue. Can you please share your data.yaml file.

**Comment by AhmedEmadEldinHussin** [comment]
![Screenshot from 2022-06-28 15-24-48](https://user-images.githubusercontent.com/18230011/176167361-6f10f6b5-8cbb-46e3-9870-0f00aaa7904d.png)

**Comment by guptadikshant** [comment]
Can you please let me know which slash you removed? My yaml file looks like below

train: /content/drive/MyDrive/Deep_Learning_Notebooks/YOLOv6/data/images/train
val: /content/drive/MyDrive/Deep_Learning_Notebooks/YOLOv6/data/images/val

nc: 7
names: ['fish', 'jellyfish', 'penguin', 'puffin', 'shark', 'starfish', 'stingray']

I am training in Google Colab

**Comment by AhmedEmadEldinHussin** [comment]
> Can you please let me know which slash you removed? My yaml file looks like below
> 
> train: /content/drive/MyDrive/Deep_Learning_Notebooks/YOLOv6/data/images/train val: /content/drive/MyDrive/Deep_Learning_Notebooks/YOLOv6/data/images/val
> 
> nc: 7 names: ['fish', 'jellyfish', 'penguin', 'puffin', 'shark', 'starfish', 'stingray']
> 
> I am training in Google Colab
the path files was looking like 
train: /home/ahmed/yolov6/images/train/
so i have just removed last slash to be 
train: /home/ahmed/yolov6/images/train

**Comment by AhmedEmadEldinHussin** [comment]
if you could share with methe problem the error I may help
