### ISSUE TITLE
mAP 0 like YOLOX have same issue

### ISSUE THREAD

**Issue by zh-song** [meituan/YOLOv6#113]

**Comment by mtjhl** [comment]
Hi, I am a little confuse, did you mean when you training on your dataset, the mAP of YOLOv6 and YOLOX are both 0 ?

**Comment by zh-song** [comment]
For both YOLOv6 and YOLOX, mAP of some epoches are 0 or very tiny value.
![image](https://user-images.githubusercontent.com/67272893/176325908-6c756395-0492-44d6-8f07-270ee836e63d.png)

**Comment by youwenjing** [comment]
一样的问题 并且迭代了100epoch之后map也很差

**Comment by mtjhl** [comment]
@youwenjing @zh-song 试着拉取一下最新的代码，如果是您自己的数据，把这个标志设置为 False
https://github.com/meituan/YOLOv6/blob/fb9485fdb3c5e290c51b8c7dc8b05e2bc78a8da3/data/coco.yaml#L9
