### ISSUE TITLE
yolov6n anchors 

### ISSUE THREAD

**Issue by danweil24** [meituan/YOLOv6#115]
Is yolov6n have 1 -anchor for each resolution? if no then why do you use 5d tensors with the shape of  1,1,w,h,85?  
This format is problematic for quantization in snpe (tool for Qualcomm device). 
Thanks, Dan

**Comment by mtjhl** [comment]
YOLOv6 is anchor free detector. If needed, you can squeeze the tensor `1,1,w,h,85` to `1, w, h, 85`.
