### ISSUE TITLE
TensorRT inference with  C++ for YOLOv6

### ISSUE THREAD

**Issue by linghu8812** [meituan/YOLOv6#122]
Hello every one, here is a repo for YOLOv6 inference with C++: [https://github.com/linghu8812/tensorrt_inference/tree/master/project/YOLOv6](https://github.com/linghu8812/tensorrt_inference/tree/master/project/YOLOv6), the inference results are consistent with PyTorch results.
![image](https://user-images.githubusercontent.com/36389436/176329876-0376b353-e87e-42d4-9c67-03fd6f5d528d.png)
For more information, please refer this blog: [https://blog.csdn.net/linghu8812/article/details/125513929](https://blog.csdn.net/linghu8812/article/details/125513929)

**Comment by Linaom1214** [comment]
here is my repo also support C++
https://github.com/Linaom1214/tensorrt-python
