### ISSUE TITLE
After 1 epoch of training , some errors occured in evaluate and save mode

### ISSUE THREAD

**Issue by aijekiL** [meituan/YOLOv6#124]
![F)_C%}DAG053)EJKBCK7`%M](https://user-images.githubusercontent.com/46265227/176346354-05b75d78-6629-4e5b-be2d-1cfb79931d56.png)
![{6O7~GR8B(VO` PZ_ K7@RG](https://user-images.githubusercontent.com/46265227/176346375-87887d62-cc66-43ca-b661-2980a0cad368.png)

**Comment by Chilicyy** [comment]
Thanks for your attention.
It seems that the imagefile name of your dataset has some invalid character, maybe you can check and rename the filenames.

**Comment by JovanBosic** [comment]
> Thanks for your attention. It seems that the image file names of your dataset have some invalid characters, maybe you can check and rename the file names.

This doesnt solve the problem.

**Comment by abdulghani91** [comment]
@Chilicyy I have the same problem, after one epoch, but only with YOLOv6m and YOLOv6L, the tiny and small work fine, I able to finish 100 epochs with the tiny. I am using win 11 with python3.10 CUDA 1.1.13 GPU RTX 3080 notebook.

The last thing that I did reduce --eval-interval from 20 to 2 and its work with YOLOv6m. Now I am using the command below to train:

python tools/train.py --epochs 600 --batch-size 16 --eval-interval 2 --conf configs/yolov6m_finetune.py 
--data ./path to/data.yaml --output-dir ./path/  --name 600_Epochs_YOLOM --write_trainbatch_tb --device 0
