### ISSUE TITLE
About the format of the data set

### ISSUE THREAD

**Issue by M15-3080** [meituan/YOLOv6#125]
YOLOv6 training itself that the data set format must be JSON?  Can't you use TXT format?

**Comment by ruabliuqiu** [comment]
也可以是yolo格式的，参考：https://blog.csdn.net/DeepLearning_/article/details/125511165?spm=1001.2014.3001.5502

**Comment by M15-3080** [comment]
> Re
谢谢您的回复，但是在yaml文件中anno_path需要一个json格式的文件

**Comment by ruabliuqiu** [comment]
> > Re
> > 谢谢您的回复，但是在yaml文件中anno_path需要一个json格式的文件

不需要的，直接保留train和val的图片路径，训练时，像代码给的coco.yaml中的test:、anno_path:可以直接注释掉。你可以试试

**Comment by ruabliuqiu** [comment]
> > Re
> > 谢谢您的回复，但是在yaml文件中anno_path需要一个json格式的文件

可以看下“Train Custom Data”中的介绍，step4并没有提anno_path:，test:是可以选择使用的

**Comment by Chilicyy** [comment]
Thanks for your attention!
You don't have to set the anno_path when training on your custom data,  because the annotation file for evaluation is automatically generated.  You just need to prepare well the images and label files (*.txt) in YOLO format.
