### ISSUE TITLE
Trian loss still 0, but i used the new code

### ISSUE THREAD

**Issue by PANPEIWEN** [meituan/YOLOv6#126]
This is my dataset Format

- coco
- -images
- - -train2017
- - - -img1.jpg
- - - -img2.jpg
- ----..................
- - -val2017
- - - -img1.jpg
- - - -img2.jpg
- ----..................
- -labels
- - -train2017
- - - -train2017.json
- - -val2017
- - - -val2017.json

**Comment by Chilicyy** [comment]
hi, you should convert your label file into YOLO format, referring to https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md.
