### ISSUE TITLE
ModuleNotFoundError: No module named 'tools.eval'

### ISSUE THREAD

**Issue by joel5638** [meituan/YOLOv6#127]
Unable to train with custom data.
Have 10 images on a singe gpu traininng.

im using this command.
python3 tools/train.py --batch 2 --conf configs/yolov6s_finetune.py --data data/dataset.yaml --device 0

Im getting
**ModuleNotFoundError: No module named 'tools.eval'**

**Comment by Chilicyy** [comment]
hi, you can try adding the root directory of the project into the PYTHONPATH, like
export PYTHONPATH=$PYTHONPATH:/xxx/YOLOv6

**Comment by guoguolord** [comment]
我的问题是module 'tools.eval' has no attribute 'run'

**Comment by lucienwang1009** [comment]
Add `__init__.py` to the `tools` dir:
```
touch tools/__init__.py
```
