### ISSUE TITLE
keeps returning "AssertionError: No information in record files, please add option --check_images."

### ISSUE THREAD

**Issue by baggins34** [meituan/YOLOv6#129]
Images and labels are in YOLO format. The code always returns "AssertionError: No information in record files, please add option --check_images." error. If "--check_images" is added like "python tools/train.py --batch 256 --conf configs/yolov6s_finetune.py --data data/coco.yaml --device 0 --check_images", it still returns the same error
![Uploading Screenshot from 2022-06-29 11-26-32.png…]()

**Comment by BandyKenny** [comment]
try change *.png -> *.jpg

**Comment by baggins34** [comment]
Nope! Still the same error "AssertionError: No information in record files, please add option --check_images."
I've also tried .jpeg extension. It also says "ignoring corrupt image: 'NoneType' object has no attribute 'seek'"

**Comment by Chilicyy** [comment]
Thanks for your attention!  We updated some relative scripts for images checking. Please git pull the latest code and try again.
