### ISSUE TITLE
AssertionError: Image Not Found /home/joelk/Projects/YOLOv6/data/images/val/frame10.jpg, workdir: /home/joelk/Projects/YOLOv6

### ISSUE THREAD

**Issue by joel5638** [meituan/YOLOv6#130]
Though i do not have the fram10.jpg image in my Val folder. Why does it still look for that image?

My dataset.yaml looks like this.

**train: ./data/images/train # train images
val: ./data/images/val # val images
#test: path/to/data/images/test # test images (optional)

# Classes
nc: 1  # number of classes
names: ['blister']  # class names**

I have tried changing the folder paths too. it just doesnt work

**Comment by Kushal73** [comment]
If you want to train your custom images, please create a new sub folder "custom_dataset" inside the data folder. Inside the custom_dataset folder create two folders namely, images and labels. These two folders should contain train and val folders in each of them. I had no issue when I did this. I am also attaching the link to the folder structure view provided by the git owner. Also change the dataset.yaml appropriately. 
https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md
