### ISSUE TITLE
Publish results to paperswithcode.com

### ISSUE THREAD

**Issue by LifeIsStrange** [meituan/YOLOv6#133]
https://paperswithcode.com/sota/real-time-object-detection-on-coco
https://paperswithcode.com/sota/object-detection-on-coco
So that the world can discover your paper.
@meituan-gengyifei
@Chilicyy

**Comment by Chilicyy** [comment]
Thanks for your attention! This project is ongoing and updated rapidly. We will consider your suggestion.

**Comment by LifeIsStrange** [comment]
@Chilicyy I am not seeing it in the leaderboards, link?
