### ISSUE TITLE
YoloV6训练的各种问题

### ISSUE THREAD

**Issue by QIANXUNZDL123** [meituan/YOLOv6#134]
环境: pytorch1.10.1 + cuda10.2 
问题1：
数据集加载问题：
官方文档数据集格式：
![image](https://user-images.githubusercontent.com/46549527/176420932-7662bfdc-6f7d-4eb8-9051-78a98afe66c2.png)
训练出错：
![image](https://user-images.githubusercontent.com/46549527/176421026-b3624c50-2481-4da7-a8dc-b99eab5d3d08.png)
问题根源：
![image](https://user-images.githubusercontent.com/46549527/176421113-fdee58d4-56cf-47b3-9b4c-9f521131ec33.png)
这地方应该是多写了osp.dirname(img_dir)，
![image](https://user-images.githubusercontent.com/46549527/176421229-2abfaabb-026a-4a7e-8273-902a909d40f3.png)
打印之后的路径
![image](https://user-images.githubusercontent.com/46549527/176421328-4a0513f3-7bff-4111-8cf3-dd305365c0c2.png)

![image](https://user-images.githubusercontent.com/46549527/176421435-8e447963-375e-487f-9308-817cc3618f4e.png)
这样就可以正常的加载数据集了

问题2：
![image](https://user-images.githubusercontent.com/46549527/176421510-9faadeaf-6914-48a9-88db-d1e36b384d36.png)
这个问题，，解决下吧，，，刚git clone 的 时间2022/06/29/16点左右

我刚换了这个地方，用之前的替代了
![image](https://user-images.githubusercontent.com/46549527/176422006-ca9e7d38-f43c-493e-bad3-3e285452f8fe.png)

问题3：Map = 0
第一轮：
![image](https://user-images.githubusercontent.com/46549527/176422253-dcb93607-bb40-471f-9677-174caded5e8b.png)
第二轮：
![image](https://user-images.githubusercontent.com/46549527/176422349-65b96217-653a-4db9-9a72-c4f8412486e8.png)

大致遇到的就是这些问题。。。后面断掉训练了，因为连续2轮都是0也没必要训练了

**Comment by Wangwang99999** [comment]
I also found the problem that all the mAP is zero! I found that it is because my data is not square shape, and the author confused the 'img_w' and 'img_h' in function 'generate_coco_format_labels' of dataset.py (line 368).
