### ISSUE TITLE
Where is the yolov6 paper?

### ISSUE THREAD

**Issue by Keiku** [meituan/YOLOv6#14]
Has a paper been released comparing it with other YOLOvX series detectors?

By the way, there is no paper for YOLOv5 and YOLOv7, so everyone is confused.

* https://github.com/ultralytics/yolov5/issues/1333
* https://github.com/jinfagang/yolov7/issues/6

**Comment by ttjjmm** [comment]
Waiting for author's paper or technical report !!!!

**Comment by Keiku** [comment]
I'm glad it wasn't a non-academic work like YOLOv5 or YOLOv7. Thank you for your reply.

**Comment by Chilicyy** [comment]
@Keiku @ttjjmm Thanks for your attention! We will publish the technical report of YOLOv6 soon.

**Comment by cmhungsteve** [comment]
Please check the real YOLOv7 paper (including the original YOLO authors):
YOLOv7: Trainable bag-of-freebies sets new state-of-the-art for real-time object detectors
https://arxiv.org/abs/2207.02696

**Comment by Keiku** [comment]
@cmhungsteve Thank you for telling me. I have updated the comments.

**Comment by Keiku** [comment]
@cmhungsteve There are two implementations of YOLOv7. The correct implementation is for WongKinYiu, right?

* https://github.com/WongKinYiu/yolov7
* https://github.com/jinfagang/yolov7

**Comment by Keiku** [comment]
@cmhungsteve Thanks for your comment. That's right. I believe in the work of Alexey, which also has paper released. I would use WongKinYiu's YOLOv7.

**Comment by cmhungsteve** [comment]
@Keiku 
It seems that your comments were deleted and blocked...
https://github.com/jinfagang/yolov7/issues/6

**Comment by Keiku** [comment]
@cmhungsteve I wasn't the direct cause, but the comments of others made it off-topic. The author says that there is no paper because it is a framework name. However, I think it's okay to ask if there is paper.
