### ISSUE TITLE
【YOLOv6 VS PP-YOLOE s】官方实测性能对比/Official Performance Comparison

### ISSUE THREAD

**Issue by YixinKristy** [meituan/YOLOv6#140]
#### English Version
<p>It is glad to see that YOLOv6 has improved the algorithm effectiveness of the YOLO family. It is also a pleasure to compare the algorithm results with <a href="https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyoloe">PP-YOLOE</a> developed by PaddlePaddle.</p>
<p>Here we want to make several clarifications about the indicators of accuracy and speed.</p>
<h2 id="pp-yoloe-speed-test-data-corrections-on-t4-tensorrt" class="atx"><a href="https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyoloe">PP-YOLOE</a> Speed test data corrections on T4 TensorRT</h2>
<p><a href="https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyoloe">PP-YOLOE</a> provided speed test method in its official website. Under T4 TensorRT 7.2:</p>
<ul>
<li><p>batch size=1, Speed is 357FPS</p>
</li>
<li><p>batch size=32, Speed is 472FPS</p>
</li>
</ul>
<p>There is a large discrepancy between the public data of YOLOv6 and that of PP-YOLOE. The actual data is as follows:</p>

Model-actual measurement | batch size | ONNX-TRT Speed | Params(M) | FLOPS(G)
-- | -- | -- | -- | --
YOLOv6-s | 1 | 383 FPS | 17.2 | 44.2
YOLOv6-s | 32 | 542 FPS | - | -
PP-YOLOE s | 1 | 357FPS | 7.9 | 17.4
PP-YOLOE s | 32 | 472FPS | - | -

On the basis of the test data, compared to YOLOv6 s, PP-YOLOE s is 6.8% slower, has 54% less parameters and 61% less computation.

## Differences in NMS parameters result in inaccurate time tests

During the accuracy test, we found that YOLOv6 and [PP-YOLOE]([PaddleDetection/configs/ppyoloe at release/2.4 · PaddlePaddle/PaddleDetection · GitHub](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyoloe)) used different NMS parameters, while the time for post-processing was missed during the performance comparison. After we adjusted the NMS parameters, the accuracy of PP-YOLOE was tied with YOLOv6 s in general. The test data are as follows:

| Model      | epoch | AP 0.5:0.95 | AP 0.5 | AP 0.75 | AP small | AP medium | AP large | AR small | AR medium | AR large |
|:----------:|:-----:|:-----------:|:------:|:-------:|:--------:|:---------:|:--------:|:--------:|:---------:|:--------:|
| PP-YOLOE s | 300   | 43.0        | 59.6   | 47.2    | 26.0     | 47.4      | 58.7     | 45.1     | 70.6      | 81.4     |
| YOLOv6 s   | 400   | 43.1        | 62.0   | 46.2    | 23.9     | 47.4      | 58.8     | 40.2     | 65.5      | 76.4     |

<p><strong>Meanwhile, the accuracy of <a href="https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyoloe">PP-YOLOE</a> m/l/x also sees a 0.4 mAP increase on COCO val2017 and a 0.2 mAP increase on COCO test2017. More information in <a href="https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/README_cn.md">PP-YOLOE Github official website</a>. At the same time, we believe that if trained 400 epoch, PP-YOLOE can have a better performance.</strong></p>
<p>You are welcomed to share your thoughts at <a href="https://github.com/PaddlePaddle/PaddleDetection/issues">ISSUE</a>. Later, PaddlePaddle <a href="https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyoloe">PP-YOLOE</a> R&amp;D team will pay more attention to the end to end performance of detection algorithm, and continue to improve the accessibility and applicability of algorithms based on industrial practices. Follow our updates if you are interested😊</p>
<p>From PaddlePaddle <a href="https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyoloe">PP-YOLOE</a> R&amp;D team</p>

#### Chinese Version
<p>作为飞桨PaddleDetection的产研团队，我们很高兴看到YOLOv6的推出再度提升了YOLO家族的算法效果，也很荣幸能够看到飞桨团队开发的PP-YOLOE算法效果被加入到对比当中。</p>
其中对于PP-YOLOE的精度速度指标这里做出几点澄清：
<h2 id="pp-yoloe在t4-tensorrt上的速度测试数据更正" class="atx"><a href="https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyoloe">PP-YOLOE</a>在T4 TensorRT上的速度测试数据更正</h2>
<p><a href="https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyoloe">PP-YOLOE</a>在官方文档中提供了<a href="https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/README_cn.md#%E9%80%9F%E5%BA%A6%E6%B5%8B%E8%AF%95">速度测试方法</a>，在T4 TensorRT 7.2 环境下：</p>
<ul>
<li><p>batch size=1 的速度为357FPS</p>
</li>
<li><p>batch size=32 的速度为472FPS</p>
</li>
</ul>
<p>相比YOLOv6公开数据差距较大，实测数据对比如下：</p>

Model | batch size | ONNX-TRT Speed | Params(M) | FLOPS(G)
-- | -- | -- | -- | --
YOLOv6-s 实测 | 1 | 383 FPS | 17.2 | 44.2
YOLOv6-s 实测 | 32 | 542 FPS | - | -
PP-YOLOE s 实测 | 1 | 357FPS | 7.9 | 17.4
PP-YOLOE s 实测 | 32 | 472FPS | - | -

基于我们的实测数据，PP-YOLOE s相比YOLOv6 s，速度慢6.8%，参数量少54%，计算量少61%

## NMS参数差异导致精度测试不等价

在精度测试过程中，我们发现YOLOv6和[PP-YOLOE](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyoloe)使用了不同的NMS参数，同时后处理耗时没有加入到性能对比中，因此我们将NMS参数调整后，精度和YOLOv6 s基本打平，测试数据如下：

| 模型         | epoch | AP 0.5:0.95 | AP 0.5 | AP 0.75 | AP small | AP medium | AP large | AR small | AR medium | AR large |
|:----------:|:-----:|:-----------:|:------:|:-------:|:--------:|:---------:|:--------:|:--------:|:---------:|:--------:|
| PP-YOLOE s | 300   | 43.0        | 59.6   | 47.2    | 26.0     | 47.4      | 58.7     | 45.1     | 70.6      | 81.4     |
| YOLOv6 s   | 400   | 43.1        | 62.0   | 46.2    | 23.9     | 47.4      | 58.8     | 40.2     | 65.5      | 76.4     |

<p><strong>与此同时<a href="https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyoloe">PP-YOLOE</a> m/l/x在COCO val2017数据集精度也都有0.4点的提升，在COCO test2017数据集精度也有0.2点的提升，更多精度信息可以参考<a href="https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/README_cn.md">PP-YOLOE官方文档</a>。 同时我们认为PP-YOLOE训练400epoch后可以进一步提升模型精度。</strong></p>
<p>以上测试也欢迎在issue去沟通交流，后续飞桨<a href="https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyoloe">PP-YOLOE</a>研发团队会进一步关注检测算法端到端性能，并基于产业实践持续优化算法易用性与泛化性，以更好的服务于检测算法的产业落地，敬请关注。</p>
<p>以上，</p>
<p>飞桨<a href="https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyoloe">PP-YOLOE</a>研发团队</p>

**Comment by Doragd** [comment]
give a thumb up!

**Comment by YixinKristy** [comment]
> 为什么PPYOLO-E s 参数量少、计算量少速度反而慢？

目前主要差异点是激活函数不同，mt-yolov6使用的relu，ppyoloe使用的swish，trt对这两种激活的优化程度不同导致速度差异，但是不影响参数量~

**Comment by khwengXU** [comment]
Hi, we test the speed of PPYOLOE-s under our environment with [速度测试方法](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/README_cn.md#%E9%80%9F%E5%BA%A6%E6%B5%8B%E8%AF%95), and get similar speed, compared with previous results.

In details, our environment is T4 TensorRT 7.2 Cuda 10.2 Cudnn 8.0.2.

**Comment by serser** [comment]
@YixinKristy 这个[速度测试方法](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/README_cn.md#%E9%80%9F%E5%BA%A6%E6%B5%8B%E8%AF%95) 说，
```
# 使用上边的脚本, 在T4 和 TensorRT 7.2的环境下，PPYOLOE-s模型速度如下
# batch_size=1, 2.80ms, 357fps
```
请教下这个2.80ms是以下哪个时间（使用 T4， TensorRT 7.2.1.6 测试），
```
----------------------------------------------------------------
Input filename:   ./ppyoloe_crn_s_300e_coco.onnx
ONNX IR version:  0.0.8
Opset version:    12
Producer name:    PaddlePaddle
Producer version:
Domain:
Model version:    0
Doc string:
----------------------------------------------------------------
[07/03/2022-15:58:11] [W] [TRT] onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[07/03/2022-15:58:12] [W] [TRT] TensorRT was linked against cuDNN 8.0.4 but loaded cuDNN 8.0.2
[07/03/2022-15:58:51] [I] [TRT] Some tactics do not have sufficient workspace memory to run. Increasing workspace size mayincrease performance, please check verbose output.
[07/03/2022-16:04:45] [I] [TRT] Detected 4 inputs and 2 output network tensors.
[07/03/2022-16:04:45] [W] [TRT] TensorRT was linked against cuDNN 8.0.4 but loaded cuDNN 8.0.2
[07/03/2022-16:04:46] [I] Engine built in 395.381 sec.
[07/03/2022-16:04:46] [W] [TRT] TensorRT was linked against cuDNN 8.0.4 but loaded cuDNN 8.0.2
[07/03/2022-16:04:46] [I] Starting inference
[07/03/2022-16:04:49] [I] Warmup completed 0 queries over 200 ms
[07/03/2022-16:04:49] [I] Timing trace has 0 queries over 3.00735 s
[07/03/2022-16:04:49] [I] Trace averages of 1000 runs:
[07/03/2022-16:04:49] [I] Host Latency
[07/03/2022-16:04:49] [I] min: 3.76541 ms (end to end 5.67526 ms)
[07/03/2022-16:04:49] [I] max: 4.18774 ms (end to end 6.69061 ms)
[07/03/2022-16:04:49] [I] mean: 3.85272 ms (end to end 5.98521 ms)
[07/03/2022-16:04:49] [I] median: 3.83997 ms (end to end 5.98267 ms)
[07/03/2022-16:04:49] [I] percentile: 4.09534 ms at 99% (end to end 6.47632 ms at 99%)
[07/03/2022-16:04:49] [I] throughput: 0 qps
[07/03/2022-16:04:49] [I] walltime: 3.00735 s
[07/03/2022-16:04:49] [I] Enqueue Time
[07/03/2022-16:04:49] [I] min: 1.01562 ms
[07/03/2022-16:04:49] [I] max: 1.65796 ms
[07/03/2022-16:04:49] [I] median: 1.07062 ms
[07/03/2022-16:04:49] [I] GPU Compute
[07/03/2022-16:04:49] [I] min: 2.9451 ms
[07/03/2022-16:04:49] [I] max: 3.37305 ms
[07/03/2022-16:04:49] [I] mean: 3.03262 ms
[07/03/2022-16:04:49] [I] median: 3.02142 ms
[07/03/2022-16:04:49] [I] percentile: 3.26495 ms at 99%
[07/03/2022-16:04:49] [I] total compute time: 3.00229 s
&&&& PASSED TensorRT.trtexec # trtexec --onnx=./ppyoloe_crn_s_300e_coco.onnx --saveEngine=./ppyoloe_s_bs1.engine --workspace=1024 --avgRuns=1000 --shapes=image:1x3x640x640,scale_factor:1x2 --fp16
```
