### ISSUE TITLE
Can you please the model structure for yolov6? like I want to know the key difference between yolov5 and yolov6 

### ISSUE THREAD

**Issue by noreenanwar** [meituan/YOLOv6#145]

**Comment by meituan-gengyifei** [comment]
Thanks for your suggestion! We will add structure comparison diagrams as soon as possible to help better understand yolov6.

**Comment by mtjhl** [comment]
Currently, you can use Netron to visualize the onnx model and find the difference.

**Comment by noreenanwar** [comment]
ok but I am facing issues while training it on my customize dataset(cityscape)I already train it in yolov5 now I am trying with v6

**Comment by noreenanwar** [comment]
YOLOv6/yolov6/data/datasets.py", line 336, in get_imgs_labels
    for img_path, info in img_info.items()
ValueError: not enough values to unpack (expected 2, got 0)


This is the error.IDK what is the matter as I followed every instruction mentioned.
