### ISSUE TITLE
Label files with '.' in the name aren't valid

### ISSUE THREAD

**Issue by MiiaBestLamia** [meituan/YOLOv6#150]
I name my images/labels after a certain format, which involves dates and locations, for example:
0250_London_2004.01.12_12.48.04_testvid.txt
The following code in datasets.py incorrectly renames image files into label files (splitting by a '.', which ruins the name of the label).
```
label_paths = sorted(
            osp.join(label_dir, osp.basename(p).split(".")[0] + ".txt")
            for p in img_paths
)
```
Changing the code to something like this fixes the issue:
```
label_paths = sorted(
            osp.join(label_dir, osp.basename(p)[:-4] + ".txt")
            for p in img_paths
)
```

**Comment by mahdilamb** [comment]
An alternative would be:
```
label_paths = sorted(
            osp.join(label_dir, osp.splitext(osp.basename(p))[0] + ".txt")
            for p in img_paths
)
```

**Comment by Zephyr69** [comment]
Try
from pathlib import Path 
osp.basename(p).split(".")[0] -> Path(osp.basename(p)).stem
