### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by deepthman** [meituan/YOLOv6#156]
训练的时候训练到一半就中断，然后重新训练，去看模型的时候发现文件夹乱了。
![image](https://user-images.githubusercontent.com/50742242/176579491-91815ede-b938-4c7c-af73-8651d5c22c12.png)

**Comment by Zephyr69** [comment]
Same, mentioned here:
https://github.com/meituan/YOLOv6/pull/137

**Comment by M15-3080** [comment]
我也遇到了相同的问题，并且生成的文件夹都是很乱的

**Comment by meituan-gengyifei** [comment]
Thanks for your attention! This project is ongoing and updated rapidly. For the problem of inhumane naming of weight folders after training, we are optimizing as soon as possible. The user experience here will be optimized in future updates.

**Comment by mtjhl** [comment]
> 训练的时候训练到一半就中断，然后重新训练，去看模型的时候发现文件夹乱了。
> ![image](https://user-images.githubusercontent.com/50742242/176579491-91815ede-b938-4c7c-af73-8651d5c22c12.png)
This problem have fix. Sorry for the inconvenience。

**Comment by mtjhl** [comment]
This bug has been fixed, really sorry for the inconvenience.
