### ISSUE TITLE
训练错误ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by baiwan0** [meituan/YOLOv6#163]
Using 1 GPU for training... 
Traceback (most recent call last):
  File "tools/train.py", line 92, in <module>
    main(args)
  File "tools/train.py", line 81, in main
    trainer = Trainer(args, cfg, device)
  File "/home/liu/baiwan/YOLOv6-main/yolov6/core/engine.py", line 40, in __init__
    self.train_loader, self.val_loader = self.get_data_loader(args, cfg, self.data_dict)
  File "/home/liu/baiwan/YOLOv6-main/yolov6/core/engine.py", line 222, in get_data_loader
    train_loader = create_dataloader(train_path, args.img_size, args.batch_size // args.world_size, grid_size,
  File "/home/liu/baiwan/YOLOv6-main/yolov6/data/data_load.py", line 41, in create_dataloader
    dataset = TrainValDataset(
  File "/home/liu/baiwan/YOLOv6-main/yolov6/data/datasets.py", line 63, in __init__
    self.img_paths, self.labels = self.get_imgs_labels(self.img_dir)
  File "/home/liu/baiwan/YOLOv6-main/yolov6/data/datasets.py", line 327, in get_imgs_labels
    img_paths, labels = list(
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by M15-3080** [comment]
我之前遇到了相同的问题，目前已经解决，是数据集的原因

**Comment by baiwan0** [comment]
> 我之前遇到了相同的问题，目前已经解决，是数据集的原因

是数据集哪里不好呀

**Comment by M15-3080** [comment]
> > 我之前遇到了相同的问题，目前已经解决，是数据集的原因
> 
> 是数据集哪里不好呀

是你数据集的格式不对，请参考：https://blog.csdn.net/qq_58355216/article/details/125525243?spm=1001.2014.3001.5502

**Comment by baiwan0** [comment]
> > > 我之前遇到了相同的问题，目前已经解决，是数据集的原因
> > 
> > 
> > 是数据集哪里不好呀
> 
> 是你数据集的格式不对，请参考：https://blog.csdn.net/qq_58355216/article/details/125525243?spm=1001.2014.3001.5

> > > 我之前遇到了相同的问题，目前已经解决，是数据集的原因
> > 
> > 
> > 是数据集哪里不好呀
> 
> 是你数据集的格式不对，请参考：https://blog.csdn.net/qq_58355216/article/details/125525243?spm=1001.2014.3001.5502

我试了试还是不行，还是这样，是数据集txt格式不对吗

**Comment by M15-3080** [comment]
> > > > 我之前遇到了相同的问题，目前已经解决，是数据集的原因
> > > 
> > > 
> > > 是数据集哪里不好呀
> > 
> > 
> > 是你数据集的格式不对，请参考：https://blog.csdn.net/qq_58355216/article/details/125525243?spm=1001.2014.3001.5
> 
> > > > 我之前遇到了相同的问题，目前已经解决，是数据集的原因
> > > 
> > > 
> > > 是数据集哪里不好呀
> > 
> > 
> > 是你数据集的格式不对，请参考：https://blog.csdn.net/qq_58355216/article/details/125525243?spm=1001.2014.3001.5502
> 
> 我试了试还是不行，还是这样，是数据集txt格式不对吗
这篇博文是我写的，你可以私聊我

**Comment by noreenanwar** [comment]
I followed your instruction but still facing same error.

**Comment by M15-3080** [comment]
> 我遵循了您的指示，但仍然面临相同的错误。
Is it the latest version of Git?  Is the path of the dataset in the YAML file correct?  Try using absolute paths;  Change lines 253-255 in the datasets.py file to lines 257-259 below.  Hope I can help you
![`MF39OC}6F{8}`SZUBL6UIM](https://user-images.githubusercontent.com/91411583/176803702-770fd94c-3029-499b-9967-d7b51dbce75b.png)

**Comment by noreenanwar** [comment]
I did this n performed all steps

**Comment by noreenanwar** [comment]
![Capture d’écran du 2022-06-30 21-42-32](https://user-images.githubusercontent.com/52344371/176806329-d9b8bbbc-1266-48fb-9353-665ee0ce4228.png)


See this

**Comment by noreenanwar** [comment]
<img width="1121" alt="Screen Shot 2022-06-30 at 9 50 50 PM" src="https://user-images.githubusercontent.com/52344371/176806808-200ffa9a-ab83-4cf8-9944-8689dfb84bf9.png">

**Comment by M15-3080** [comment]
> 我这样做了n执行所有步骤







> <img alt="屏幕截图 2022-06-30 在 9 50 50 PM" width="1121" src="https://user-images.githubusercontent.com/52344371/176806808-200ffa9a-ab83-4cf8-9944-8689dfb84bf9.png">
> 
> 看到这个我遇到了同样的错误

Are you using single category data?

**Comment by noreenanwar** [comment]
I am using cityscape dataset that have 38 classes .

**Comment by noreenanwar** [comment]
my git version is git version 2.36.1

**Comment by M15-3080** [comment]
> 我正在使用具有38个类的城市景观数据集。但是我将其自定义为1个类别，即人。

I encountered the same error with a single category dataset before, so switch to multiple categories to train

![1)3~YOLH7HT @63C4 FV)QX](https://user-images.githubusercontent.com/91411583/176809327-faa3d82d-6bd0-4fc7-a422-0920b1df2645.png)

**Comment by noreenanwar** [comment]
but I am getting the same when I changed it into more classes.

# YOLOv5  by Ultralytics, GPL-3.0 license
# COCO 2017 dataset http://cocodataset.org by Microsoft
# Example usage: python train.py --data coco.yaml
# parent
# ??? yolov5
# ??? datasets
# ??? coco ? downloads here


# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
#path: ../cityscape  # dataset root dir
train: data/images/train  # train images (relative to 'path') 118287 images
val: data/images/val  # val images (relative to 'path') 5000 images
test: data/images/test  # 20288 of 40670 images, submit to https://competitions.codalab.org/competitions/20794

# Classes
nc: 38 # number of classes
names: ['rectification border','sky','road','building','static','pole','train','ground','traffic light','traffic sign','sidewalk','terrain','bus','vegetation','car','fence','person','motorcycle','cargroup','parking','dynamic','persongroup','license plate','bicycle','rider','wall','bicyclegroup','truck','trailer','bridge','polegroup','ridergroup','guard rail','caravan','tunnel','truckgroup','rail track','motorcyclegroup']  # class names

**Comment by M15-3080** [comment]
> but I am getting the same when I changed it into more classes.
> 
> # YOLOv5 by Ultralytics, GPL-3.0 license
> # COCO 2017 dataset http://cocodataset.org by Microsoft
> # Example usage: python train.py --data coco.yaml
> # parent
> # ??? yolov5
> # ??? datasets
> # ??? coco ? downloads here
> # Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
> #path: ../cityscape # dataset root dir train: data/images/train # train images (relative to 'path') 118287 images val: data/images/val # val images (relative to 'path') 5000 images test: data/images/test # 20288 of 40670 images, submit to https://competitions.codalab.org/competitions/20794
> 
> # Classes
> nc: 38 # number of classes names: ['rectification border','sky','road','building','static','pole','train','ground','traffic light','traffic sign','sidewalk','terrain','bus','vegetation','car','fence','person','motorcycle','cargroup','parking','dynamic','persongroup','license plate','bicycle','rider','wall','bicyclegroup','truck','trailer','bridge','polegroup','ridergroup','guard rail','caravan','tunnel','truckgroup','rail track','motorcyclegroup'] # class names

YOLOv6 reads data sets in a different format than YOLOv5, probably because the path of the data sets in your YAML file is not correct. V6 does not need to use images, just put the train and val files in the same directory as the labels files.  Put the dataset in the home directory, myData is my dataset 
![image](https://user-images.githubusercontent.com/91411583/176811971-c16613d4-d65d-4264-bda5-b0fe31d256fc.png)

**Comment by M15-3080** [comment]
> 但是当我把它改成更多的类时，我也得到了同样的东西。
> 
> # YoLOv5 by Ultralytics， GPL-3.0 license
> # 微软 http://cocodataset.org COCO 2017数据集
> # 示例用法：python train.py --data coco.yaml
> # 父母
> # ???约洛夫5
> # ???数据
> # ???可可？在此处下载
> # Train/val/testset as 1） dir： path/to/imgs， 2） file： path/to/imgs.txt， or 3） list： [path/to/imgs1， path/to/imgs2， ..]
> #path： ../cityscape # dataset root dir train： data/images/train # train images （相对于 'path'） 118287 images val： data/images/val # val images （相对于 'path'） 5000 张图片测试： data/images/test # 20288 of 40670 张图片，提交给 https://competitions.codalab.org/competitions/20794
> 
> # 类
> nc： 38#类名数：[“整改边界”，“天空”，“道路”，“建筑”，“静态”，“杆”，“火车”，“地面”，“交通灯”，“交通标志”，“人行道”，“地形”，“公共汽车”，“植被”，“汽车”，“围栏”，“人”，“摩托车”，“汽车”，“停车场”，“动态”，“人组”，“车牌”，“自行车”，“骑手”，“墙”，“自行车组”，“卡车”，“拖车”，“桥”，“杆组”，“骑手组”，“警卫栏”，“大篷车”，“隧道”，“卡车组”，“铁路轨道”，“摩托车组”] #类名

Is the program running normally?

**Comment by noreenanwar** [comment]
yes I am following that in my image folder I ave train ,vastest n labels folder

**Comment by noreenanwar** [comment]
File "/home/travail/noanw/YOLOv6/yolov6/data/datasets.py", line 309, in get_imgs_labels
    f"WARNING: No labels found in {osp.dirname(self.img_paths[0])}. "
AttributeError: 'TrainValDataset' object has no attribute 'img_paths'

Got this new error now

**Comment by M15-3080** [comment]
> ```
> f"WARNING: No labels found in {osp.dirname(self.img_paths[0])}. "
> ```
> 
> 属性错误：“TrainValDataset”对象没有属性“img_paths”
> 
> 现在遇到此新错误

Please check whether your data storage format is correct. I have downloaded Git again and can train as usual according to the above operations

**Comment by noreenanwar** [comment]
I followed the format

**Comment by noreenanwar** [comment]
<img width="848" alt="Screen Shot 2022-07-01 at 8 02 20 AM" src="https://user-images.githubusercontent.com/52344371/176890863-d438fa10-b8f0-45f2-83c4-74fbea00739f.png">
<img width="942" alt="Screen Shot 2022-07-01 at 8 02 46 AM" src="https://user-images.githubusercontent.com/52344371/176890893-36677c15-7bd5-456d-80a6-ccb7d45eabef.png">


You can see that.I also tried to run infer.py and it gives me this error.
FileNotFoundError: [Errno 2] No such file or directory: 'yolov6s.pt'

I have this file in my weights folder

**Comment by shensheng272** [comment]
> <img alt="Screen Shot 2022-07-01 at 8 02 20 AM" width="848" src="https://user-images.githubusercontent.com/52344371/176890863-d438fa10-b8f0-45f2-83c4-74fbea00739f.png">
> 
> <img alt="Screen Shot 2022-07-01 at 8 02 46 AM" width="942" src="https://user-images.githubusercontent.com/52344371/176890893-36677c15-7bd5-456d-80a6-ccb7d45eabef.png">
> 
> You can see that.I also tried to run infer.py and it gives me this error. FileNotFoundError: [Errno 2] No such file or directory: 'yolov6s.pt'
> 
> I have this file in my weights folder

you need set relative or full path for pt, like weights/yolov6s.pt

**Comment by shensheng272** [comment]
This issue is outdated. Wellcome to open new issue if need.
