### ISSUE TITLE
训练报错如下，这是什么原因

### ISSUE THREAD

**Issue by SunYiLing123** [meituan/YOLOv6#167]
(yolov6) [root@localhost YOLOv6-0.1.0]# python tools/train.py --conf-file configs/yolov6s_finetune.py --data-path data/Tube.yaml --device 0
training args are: Namespace(batch_size=32, check_images=False, check_labels=False, conf_file='configs/yolov6s_finetune.py', data_path='data/Tube.yaml', device='0', dist_url='tcp://127.0.0.1:8888', epochs=400, gpu_count=0, img_size=640, local_rank=-1, name='exp', noval=False, output_dir='./runs/train', rank=-1, workers=8, world_size=1)

Using 1 GPU for training...
Train: Checking formats of images with 8 process(es):
74 image(s) corrupted: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 74/74 [00:00<00:00, 1794.60it/s]
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0026.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0027.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0028.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0029.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0030.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0031.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0032.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0033.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0035.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0036.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0037.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0038.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0039.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0040.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0041.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0042.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0043.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0044.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0045.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0046.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0047.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0048.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0049.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0050.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0051.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0052.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0053.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0054.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0055.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0056.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0057.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0058.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0059.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0060.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0061.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0062.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0063.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0064.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0065.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0066.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0067.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0068.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0069.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0070.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0071.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0072.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0073.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0074.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0075.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0076.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0077.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0078.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0079.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0080.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0081.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0082.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0083.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0084.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0085.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0086.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0087.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0088.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0089.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0090.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0091.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0092.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0093.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0094.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0095.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0096.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0097.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0098.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0099.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
WARNING: /root/hanyong/YOLOv6-0.1.0/data/images/train_tube/image-0100.png: ignoring corrupt image: 'NoneType' object has no attribute 'seek'
label_dir:  /root/hanyong/YOLOv6-0.1.0/data/labels/train_tube
img_info:  {}
Traceback (most recent call last):
  File "tools/train.py", line 87, in <module>
    main(args)
  File "tools/train.py", line 76, in main
    trainer = Trainer(args, cfg, device)
  File "/root/hanyong/YOLOv6-0.1.0/yolov6/core/engine.py", line 40, in __init__
    self.train_loader, self.val_loader = self.get_data_loader(args, cfg, self.data_dict)
  File "/root/hanyong/YOLOv6-0.1.0/yolov6/core/engine.py", line 206, in get_data_loader
    train_loader = create_dataloader(train_path, args.img_size, args.batch_size // args.world_size, grid_size,
  File "/root/hanyong/YOLOv6-0.1.0/yolov6/data/data_load.py", line 23, in create_dataloader
    dataset = TrainValDataset(path, img_size, batch_size,
  File "/root/hanyong/YOLOv6-0.1.0/yolov6/data/datasets.py", line 39, in __init__
    self.img_paths, self.labels = self.get_imgs_labels(self.img_dir)
  File "/root/hanyong/YOLOv6-0.1.0/yolov6/data/datasets.py", line 190, in get_imgs_labels
    assert img_info, 'No information in record files, please add option --check_images.'
AssertionError: No information in record files, please add option --check_images.

**Comment by Zephyr69** [comment]
Comment this line:
https://github.com/meituan/YOLOv6/blob/a1aa6796d292738bb71643cba3261198629b48ec/yolov6/data/datasets.py#L424

**Comment by meituan-gengyifei** [comment]
@SunYiLing123 Thanks for your attention. You can try to add --check_images = true by referring to the current error message.If you still have questions, please provide the following information:Changed config files;Changed source code files;Your script or command line for training or evaluation;The complete log file that records the problem you mentioned;Few examples of your labels;Few examples of paths of images and labels of your dataset.
