### ISSUE TITLE
COCO Eval Error: 'numpy.float64' object cannot be interpreted as an integer 

### ISSUE THREAD

**Issue by HeZhang33** [meituan/YOLOv6#174]
Dear Meituan team,

Firstly, thank you for your contribution to the YOLO families.

However, when I trained YOLOv6 on custom data coco128 for training and validation (the super-tiny dataset provided by ultralytic/yolov5, only 128 images from the raw COCO dataset, using same images for training and validation, just for testing purpose of course), I got the error in evaluation part as below, please help!
---------------------------------------------------------------------------------------------------------------------

Training start...

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
      0/19     4.462     2.758     9.207     1.935: 100%|██████████| 7/7 [00:15<

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
      1/19     3.476      2.11      6.14     2.563: 100%|██████████| 7/7 [00:11<

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
      2/19     3.151     2.078     5.929     2.821: 100%|██████████| 7/7 [00:11<

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
      3/19     2.958     2.054     6.098     2.922: 100%|██████████| 7/7 [00:11<

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
      4/19     2.937     2.116     5.918     2.884: 100%|██████████| 7/7 [00:11<

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
      5/19       2.9     2.101     5.773     2.911: 100%|██████████| 7/7 [00:11<

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
      6/19     2.918     2.095     5.776     2.849: 100%|██████████| 7/7 [00:11<

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
      7/19     2.888     2.067     5.872     2.844: 100%|██████████| 7/7 [00:11<

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
      8/19     2.871     2.075     5.789     2.836: 100%|██████████| 7/7 [00:11<

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
      9/19     2.917      2.12     5.705     2.766: 100%|██████████| 7/7 [00:11<

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     10/19     2.883      2.08     5.795     2.775: 100%|██████████| 7/7 [00:11<

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     11/19     2.869     2.012     5.658     2.765: 100%|██████████| 7/7 [00:11<

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     12/19     2.849     2.042     5.654     2.754: 100%|██████████| 7/7 [00:11<

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     13/19     2.844     2.084     5.659     2.741: 100%|██████████| 7/7 [00:11<

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     14/19      2.93     2.113     5.587     2.681: 100%|██████████| 7/7 [00:11<

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     15/19     2.817     2.048     5.634     2.751: 100%|██████████| 7/7 [00:11<

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     16/19     2.864     2.051     5.584     2.705: 100%|██████████| 7/7 [00:11<

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     17/19     2.821     2.115     5.542     2.719: 100%|██████████| 7/7 [00:11<

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     18/19     2.856     2.149     5.629     2.719: 100%|██████████| 7/7 [00:11<

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     19/19     2.778     2.103     5.615     2.711: 100%|██████████| 7/7 [00:11<
Inferencing model in val datasets.: 100%|█████████| 4/4 [00:04<00:00,  1.06s/it]

Evaluating speed.

Evaluating mAP by pycocotools.
Saving runs/train/exp_test2/predictions.json...
loading annotations into memory...
Done (t=0.06s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.28s)
creating index...
index created!
ERROR in evaluate and save model.
ERROR in training loop or eval/save model.

Training completed in 0.082 hours.
Traceback (most recent call last):
  File "tools/train.py", line 92, in <module>
    main(args)
  File "tools/train.py", line 82, in main
    trainer.train()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/multi-gpu-4-tesla-m60/code/Users/zhanghe/cv-safety-detection/YOLOv6/yolov6/core/engine.py", line 70, in train
    self.train_in_loop()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/multi-gpu-4-tesla-m60/code/Users/zhanghe/cv-safety-detection/YOLOv6/yolov6/core/engine.py", line 89, in train_in_loop
    self.eval_and_save()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/multi-gpu-4-tesla-m60/code/Users/zhanghe/cv-safety-detection/YOLOv6/yolov6/core/engine.py", line 115, in eval_and_save
    self.eval_model()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/multi-gpu-4-tesla-m60/code/Users/zhanghe/cv-safety-detection/YOLOv6/yolov6/core/engine.py", line 134, in eval_model
    results = eval.run(self.data_dict,
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/multi-gpu-4-tesla-m60/code/Users/zhanghe/cv-safety-detection/YOLOv6/tools/eval.py", line 83, in run
    eval_result = val.eval_model(pred_result, model, dataloader, task)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/multi-gpu-4-tesla-m60/code/Users/zhanghe/cv-safety-detection/YOLOv6/yolov6/core/evaler.py", line 128, in eval_model
    cocoEval = COCOeval(anno, pred, 'bbox')
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/pycocotools/cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/pycocotools/cocoeval.py", line 527, in __init__
    self.setDetParams()
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/pycocotools/cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 5, in linspace
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/numpy/core/function_base.py", line 113, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by HeZhang33** [comment]
Thank you @meituan-gengyifei for your quick response. 
And to replicate the issue: 

1. The coco128 dataset that I used can be downloaded from: https://ultralytics.com/assets/coco128.zip
2. The "coco128.yaml" that I used is shown as below:
----------------------------------------------------
# train & val & test sets
train: ../datasets/coco128/images/train2017  # train images (relative to 'path') 128 images
val: ../datasets/coco128/images/train2017  # val images (relative to 'path') 128 images
test:  # test images (optional)

# whether it is coco dataset, only coco dataset should be set to True.
is_coco: False

# classe information
nc: 80  # number of classes
names: ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light',
        'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
        'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
        'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard',
        'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
        'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
        'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
        'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear',
        'hair drier', 'toothbrush']  # class names
----------------------------------------------------

Hope this helps you confirm / solve the issue. Thank you!

**Comment by MTChengMeng** [comment]
> Thank you @meituan-gengyifei for your quick response. And to replicate the issue:
> 
> 1. The coco128 dataset that I used can be downloaded from: https://ultralytics.com/assets/coco128.zip
> 2. The "coco128.yaml" that I used is shown as below:
> 
> ## train & val & test sets
> train: ../datasets/coco128/images/train2017 # train images (relative to 'path') 128 images val: ../datasets/coco128/images/train2017 # val images (relative to 'path') 128 images test: # test images (optional)
> 
> ## whether it is coco dataset, only coco dataset should be set to True.
> is_coco: False
> 
> ## classe information
> ## nc: 80 ## number of classes
> names: ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light',
> 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
> 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
> 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard',
> 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
> 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
> 'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
> 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear',
> 'hair drier', 'toothbrush'] # class names
> Hope this helps you confirm / solve the issue. Thank you!

Hi, we have tried reproducing your problem according to the provided config, but everything is ok.  We suggest you check your environment, and confirm that the version of required packages  are right especially numpy. Besides, you can add --check-images and --check-labels options in your command line and try again.

**Comment by HeZhang33** [comment]
> > Thank you @meituan-gengyifei for your quick response. And to replicate the issue:
> > 
> > 1. The coco128 dataset that I used can be downloaded from: https://ultralytics.com/assets/coco128.zip
> > 2. The "coco128.yaml" that I used is shown as below:
> > 
> > ## train & val & test sets
> > train: ../datasets/coco128/images/train2017 # train images (relative to 'path') 128 images val: ../datasets/coco128/images/train2017 # val images (relative to 'path') 128 images test: # test images (optional)
> > ## whether it is coco dataset, only coco dataset should be set to True.
> > is_coco: False
> > ## classe information
> > ## nc: 80 ## number of classes
> > names: ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light',
> > 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
> > 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
> > 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard',
> > 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
> > 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
> > 'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
> > 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear',
> > 'hair drier', 'toothbrush'] # class names
> > Hope this helps you confirm / solve the issue. Thank you!
> 
> Hi, we have tried reproducing your problem according to the provided config, but everything is ok. We suggest you check your environment, and confirm that the version of required packages are right especially numpy. Besides, you can add --check-images and --check-labels options in your command line and try again.

Thank you @MTChengMeng ! Could you post your training output (using my coco128.yaml, with 20 epochs, image size 480, using yolov6s.pt), so that I can cross-check with mine? In your run, did you notice the low / zero mAP issue as well? I was using python 3.8 and pip installed the requirements.txt provided by your site. I will try --check-labels/images. Thanks!

**Comment by HeZhang33** [comment]
Hello, after I git pulled your latest codes, the errors are gone. However, the mAPs are too low or almost zero, compared with the results from yolov5. I will close this issue, and open another new issue for the low / zero mAP issue. Thank you.

**Comment by wenjunx** [comment]
怎么解决的，按照这样改还是错误，我的是单类别

**Comment by kokiez** [comment]
I solved it by converting that `num `to `int type`.

**Open function_base.py, location might look like this:** ` /anaconda/envs/azureml_py38/lib/python3.8/site-packages/numpy/core/function_base.py`

**before**  _num = operator.index(num)_ **Add the following**:
`    num = int(num)`
as shown in picture:
![image](https://user-images.githubusercontent.com/105941365/202875383-8df28c48-1889-45f0-a6e2-f6ab4f57ad3a.png)
