### ISSUE TITLE
how to specify --img-size during inferencing

### ISSUE THREAD

**Issue by fjremnav** [meituan/YOLOv6#178]
I tried --img-size 1920 1080, or --img-size 1920,1080 to infer.py and both don't work.
How to specify --img-size with w and h in infer.py?

Thanks,

**Comment by fjremnav** [comment]
My image is 960x540 and I like to use this size without rescaling during inferencing if possible.
If this is not possible, I like to preserve aspect ratio of 960x540 if rescaling is needed during inferencing.

Thanks,

**Comment by Mobu59** [comment]
@fjremnav Maybe you can add "args.img_size = [1920, 1080]" in infer.py, that is adding it after line 107

**Comment by shensheng272** [comment]
> My image is 960x540 and I like to use this size without rescaling during inferencing if possible. If this is not possible, I like to preserve aspect ratio of 960x540 if rescaling is needed during inferencing.
> 
> Thanks,
Your should set image size as the longer one(960 in your case),  function `letterbox` will auto scale image with the same height/width ratio.
