### ISSUE TITLE
How can I contribute to the flask deployment of yolov6？

### ISSUE THREAD

**Issue by WangRongsheng** [meituan/YOLOv6#184]
Hello,I used flask to deploy the reasoning of yolov6. How can I submit it to you？

**Comment by MTChengMeng** [comment]
> Hello,I used flask to deploy the reasoning of yolov6. How can I submit it to you？

Hi, thanks for your participation. You can fork this project and create a pull request to submit your code. We will check the code soon and merge it if it is helpful.
