### ISSUE TITLE
CUDA要求是什么版本

### ISSUE THREAD

**Issue by wangqi8245** [meituan/YOLOv6#186]
我的cuda是8.0版本的能跑起来吗？

**Comment by MTChengMeng** [comment]
> 我的cuda是8.0版本的能跑起来吗？

感谢关注！我们建议的CUDA版本是11.0或11.2

**Comment by deepthman** [comment]
cuda8.0还是用cpu吧，用gpu的话torch只能装1.0版本，差太多了。
