### ISSUE TITLE
Enconter No rendezvous handler for env:// Erro using multi GPU (ubuntu)

### ISSUE THREAD

**Issue by mendoza-G** [meituan/YOLOv6#188]
It seems to be a dist_url erro, when I replaced it with '--dist_url tcp://local:1001', the erro was gone, but the terminal stuck at "Initioning Group"as #168 
I don't konw how to deal with it.
But it worked when using the no-recommended `python tools/train.py --batch 16 --conf configs/yolov6s_finetune.py --data data/xxx.yaml --device 0,1,2,3 --workers x --epochs x` mentioned in yolov5

**Comment by mtjhl** [comment]
in `--dist_url tcp://local:1001`, `local` may should  be `localhost`.
