### ISSUE TITLE
错误：AttributeError: module 'torch' has no attribute 'concat'

### ISSUE THREAD

**Issue by LemonWang0110** [meituan/YOLOv6#195]
这里[return torch.concat([X, resBoxes, resClasses, resScores], 1)](https://github.com/meituan/YOLOv6/blob/main/yolov6/models/end2end.py#:~:text=return%20torch.concat(%5BX%2C%20resBoxes%2C%20resClasses%2C%20resScores%5D%2C%201)) 应该是`return torch.cat([X, resBoxes, resClasses, resScores], 1)` 吧

**Comment by triple-Mu** [comment]
您是什么版本的pytorch呀？我记不清是不是concat拉，您可以pr一下
