### ISSUE TITLE
bmpfile error?

### ISSUE THREAD

**Issue by zzd1994** [meituan/YOLOv6#199]
hi, my dataset contains bmp images,  and the error occurs, how to solve it?
![微信图片_20220702002229](https://user-images.githubusercontent.com/48470140/176934679-acddf6a9-e702-473d-b656-653aa37ed0fa.jpg)

Thanks

**Comment by mtjhl** [comment]
H, is your bmp file corrupt? Or you can  change bmp file to jpg or png format and try to train  again.
