### ISSUE TITLE
Add MobileOne backbone to YOLOv6

### ISSUE THREAD

**Issue by zhiqwang** [meituan/YOLOv6#20]
### Description

Hi the awesome YOLOv6 team , [MobileOne](https://arxiv.org/abs/2206.04040) introduced by Apple is interesting, the mobile-vision team implement it at https://github.com/facebookresearch/mobile-vision/pull/91 , is there any plan to support it there? 

### Use case

![image](https://user-images.githubusercontent.com/4210061/174939870-29d4acf1-edb0-43c3-823a-dea863392c48.png)

### Additional

![image](https://user-images.githubusercontent.com/4210061/174940048-f301df15-8006-40f1-9b64-410d74bc2674.png)

**Comment by zhiqwang** [comment]
> Thanks for your attention! We have plans to publish models for Mobile. This model maybe one of the choices.

COOL!

And just FYI, the mobile-vision team have already implement this `MobileOneBlock` at belows, maybe it could be used as reference.

https://github.com/facebookresearch/mobile-vision/blob/4d5207c/mobile_cv/arch/fbnet_v2/mobileone_block.py#L15

**Comment by khwengXU** [comment]
> COOL! @khwengXU Thanks for opening source this **AWESOME** project!
> 
> And just FYI, the mobile-vision team have already implement this `MobileOneBlock` at belows, maybe it could be used as reference.
> 
> https://github.com/facebookresearch/mobile-vision/blob/4d5207c/mobile_cv/arch/fbnet_v2/mobileone_block.py#L15

Thanks for your suggestion! We will consider it. :D
