### ISSUE TITLE
RuntimeError: all elements of input should be between 0 and 1

### ISSUE THREAD

**Issue by joel5638** [meituan/YOLOv6#200]
Im trying with 450 images in train and 130 in val. I have the training started but encountered this error.

RuntimeError: all elements of input should be between 0 and 1

Im attaching a screenshot of the error too
![Screenshot from 2022-07-01 22-11-36](https://user-images.githubusercontent.com/38422983/176936037-d30a5af9-452a-4603-90d0-3f86cc10206c.png)

**Comment by mtjhl** [comment]
Hi, did you set the CUDA environment correctly.  If your computer does not have GPU, you can try to add `--device=cpu` when you run the training  code.
