### ISSUE TITLE
YOLOV6 在一些非常明显的前景大目标时无法检测，相比之下YOLOV5要很多好，希望能得到优化

### ISSUE THREAD

**Issue by tms2003** [meituan/YOLOv6#201]
https://www.youtube.com/watch?v=yd1DhOf8mW4的1:18秒
可以看出（同样的示例还有很多），YOLOV5要比YOLOV6好不少。YOLOV6对小目标检测不错。但对大目标有很大的问题。我认为这是应当不难得以改善的

**Comment by mtjhl** [comment]
Thank you for your attention, we will try to improve the mAP of large object.

**Comment by mtjhl** [comment]
I read your code, you user YOLOv5s6 trained with 1280 resolution to compare with YOLOv6s trained with 640 resolution, this is incomparable.

**Comment by tms2003** [comment]
you should watch this:https://www.youtube.com/watch?v=5GXWvoDzpDU ,at 1 secomd clip ! you can found the truck be lost also!

**Comment by lipond** [comment]
@tms2003 兄弟，语法错误太多了，要么直接用中文吧，或者用机翻搞下都行啊

**Comment by mtjhl** [comment]
@tms2003 We are not sure this model is YOLOv5 or YOLOv5n6, YOLOv6n's mAP is higher than v5n, however it is lower than v5n6.  YOLOv5 and v6 are trained on COCO with 80 classes,  we selected the best model evaluted on 80 classes.  If a model  has higher mAP, however, it has lower mAP in large objects, it must have higher mAP in middle or small objects.
Also, different model has different confidence threshold, maybe one model's best confidence is 0.5 (evaluate with best F1 score), another model is 0.45. 

> you should watch this:https://www.youtube.com/watch?v=5GXWvoDzpDU ,at 1 secomd clip ! you can found the truck be lost also!

**Comment by khwengXU** [comment]
There are many factors can influence the detection effects for large/small objects. Could you give more details about the comparations?  e.g. detailed model info/image resolution, etc.
