### ISSUE TITLE
一个重要的补充！

### ISSUE THREAD

**Issue by 2050airobert** [meituan/YOLOv6#203]
Hi，
     周末拜托了您的大作，只是提出个小问题，作为技术报告的补充吧。
     1 我想问下EfficientRep Backbone + Rep-PAN Neck  这两个trick 分别增强map多少个点呢？  
     2 比如不使用Rep-PAN时候 map比之前增加了多少，如果只用Rep-PAN Neck不用EfficientRep Backbone map增加了多少？
     
BR

**Comment by mtjhl** [comment]
Hi, thank you for your attention，we'll consider to write a tech report later to show the ablation experiments result.

**Comment by 2050airobert** [comment]
还是没有发出报告来的啊，问题并没有解决呢！

**Comment by khwengXU** [comment]
We have plans to publish technical report and show the ablations study.
