### ISSUE TITLE
TypeError: increment_name() missing 1 required positional argument: 'master_process' ?

### ISSUE THREAD

**Issue by allansdefreitas** [meituan/YOLOv6#206]
When, after train the model, I run the evaluation script, like:

`python tools/eval.py --data dataset.yaml  --weights run/train/exp7/weights/best_ckpt.pt --device 0`

I get as result in an **error**, as follows:

Namespace(batch_size=32, conf_thres=0.001, data='dataset.yaml', device='0', half=False, img_size=640, iou_thres=0.65, name='exp', save_dir='runs/val/', task='val', weights='run/train/exp7/weights/best_ckpt.pt')
Traceback (most recent call last):
  File "tools/eval.py", line 93, in <module>
    main(args)
  File "tools/eval.py", line 88, in main
    run(**vars(args))
  File "/usr/local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "tools/eval.py", line 65, in run
    save_dir = str(increment_name(osp.join(save_dir, name)))
TypeError: increment_name() missing 1 required positional argument: 'master_process'

Do you have any idea to how to solve this error?

**Comment by mtjhl** [comment]
Sorry for the inconvenience, we will fix this today. 
You can edit the 65 line of `tools/eval.py`  to `save_dir = str(increment_name(osp.join(save_dir, name)), True)` to run the validation.

**Comment by mtjhl** [comment]
We have fix this bug now. Your can pull the latest code to run.

**Comment by allansdefreitas** [comment]
> We have fix this bug now. Your can pull the latest code to run.

Thanks a lot, @mtjhl.

**Comment by allansdefreitas** [comment]
Tha

> We have fix this bug now. Your can pull the latest code to run.

Thanks a lot, @mtjhl .

**Comment by Milan2698** [comment]
Namespace(batch_size=32, conf_thres=0.001, data='my_data.yaml', device='0', half=False, img_size=416, iou_thres=0.65, name='exp', save_dir='runs/val/', task='val', weights='runs/train/exp4/weights/best_ckpt.pt')
Traceback (most recent call last):
  File "eval1.py", line 93, in <module>
    main(args)
  File "eval1.py", line 88, in main
    run(**vars(args))
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "eval1.py", line 65, in run
    save_dir = str(increment_name(osp.join(save_dir, name)), True)
TypeError: increment_name() missing 1 required positional argument: 'master_process'


**still, I am facing the same error !!!**
