### ISSUE TITLE
UserWarning: User provided device_type of 'cuda', but CUDA is not available

### ISSUE THREAD

**Issue by saiteja-kuchipudi** [meituan/YOLOv6#210]
My system has CUDA v10.2, still I get the error "UserWarning: User provided device_type of 'cuda', but CUDA is not available" while training. Images are getting trained on CPU instead of GPU. Can someone help.

![Capture2](https://user-images.githubusercontent.com/69788462/177029392-27058129-3746-408d-b6f2-00f37fa1c999.JPG)
![Capture](https://user-images.githubusercontent.com/69788462/177029401-8927bb92-e7be-407e-92ab-92570b9c19cc.JPG)

**Comment by mtjhl** [comment]
You can open a python terminal, type in 
```
import torch
torch.cuda.is_available()
```
to check if CUDA is available.

**Comment by saiteja-kuchipudi** [comment]
Thanks @mtjhl
