### ISSUE TITLE
Resume Training issue: AttributeError: 'Trainer' object has no attribute 'epoch'

### ISSUE THREAD

**Issue by fadishaar84** [meituan/YOLOv6#212]
Hello, 
Trying to resume training on a custom dataset and got this error: 
    strip_optimizer(save_ckpt_dir, self.epoch)  # strip optimizers for saved pt model
AttributeError: 'Trainer' object has no attribute 'epoch'

**Comment by yydc-0** [comment]
I had the same problem.

**Comment by mtjhl** [comment]
Sorry for the inconvenience, we have push a PR to fix this bug, wait for a while for our colleague to merge it.
