### ISSUE TITLE
I cannot implement yolov6 in colab

### ISSUE THREAD

**Issue by Shrabana97** [meituan/YOLOv6#224]
I don't why but I am doing same thing but in colab it's showing weird error. have anyone implemented on colab? is it working for them? please tell me guys.

**Comment by Kurmangozhin** [comment]
example: 
https://colab.research.google.com/drive/1h3mOntYI11uATQTlkPNGdO4WbQZ_5FVA?usp=sharing

**Comment by SammriddhGupta** [comment]
It's working normally on colab as well, but you need to separately upload the .pt weights files before you can run infer.py
