### ISSUE TITLE
关于使用到的SIOU的一些疑问

### ISSUE THREAD

**Issue by bubbliiiing** [meituan/YOLOv6#225]
SIOU论文中提到，收敛过程将首先最小化𝛼， 否则最小化β。
但α接近于45度时，gamma=-1。
当α接近于0度时，gamma=-2。
当rho_x和rho_y等同时，distance_cost的在α接近于45度时小于α接近于0度时。这是不是意味着45度才是收敛方向呢？
这似乎与原论文的意义不同？

**Comment by 11wswhl** [comment]
哈哈  遇到导师了啊

**Comment by bubbliiiing** [comment]
> 哈哈 遇到导师了啊

😂，学习SIOU遇到了一些难以理解的困难，非常烦躁

**Comment by 11wswhl** [comment]
upup  看看我在yolox_tf2的提问呗😂

**Comment by HouSanDuo123** [comment]
When rho_x and rho_y are equal, it don't converge in 45 degrees，alpha direction convergence is selected by default.

**Comment by RikWzzz** [comment]
偶遇导师 求一份tensorflow版本Siou的代码

**Comment by HouSanDuo123** [comment]
You can make changes base on './yolov6/utils/figure_iou.py' line 75.

**Comment by HouSanDuo123** [comment]
> 偶遇导师 求一份tensorflow版本Siou的代码

You can make changes base on './yolov6/utils/figure_iou.py' line 75.
