### ISSUE TITLE
yolov5都有个简体中文说明，国产的yolov6居然全英文

### ISSUE THREAD

**Issue by monkeycc** [meituan/YOLOv6#228]
yolov5都有个简体中文说明，国产的yolov6居然全英文文档

加上中文 并不会显得很低级  拉低yolov6国际化的档次

**Comment by nowaylv** [comment]
谁允许你叫yoloV6的？

**Comment by buxihuo** [comment]
> yolov5都有个简体中文说明，国产的yolov6居然全英文文档

yolov5中国用户老多了。

**Comment by nowaylv** [comment]
> yolov5都有个简体中文说明，国产的yolov6居然全英文文档
> 
> 加上中文 并不会显得很低级 拉低yolov6国际化的档次

全称MT-YOLOV6简称YOLOV6这种行为要是被别人知道是咱们中国人干的，那该有多丢脸啊！

**Comment by monkeycc** [comment]
美团的yolov6命名就是蹭热度的
只要能像yolov5那样 坚持下去才可以


`https://github.com/jinfagang/yolov7`
国内的  yolov7都敢叫了
detectron2改改，就敢改名为yolov7了
起码美团的yolo还有点yolo样子，yolov7就是一言难尽了

**Comment by Crestina2001** [comment]
学会使用翻译软件...

**Comment by mtjhl** [comment]
关于中文的文档，后面我们会补齐的。
