### ISSUE TITLE
Resume training fails with 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by JonathanSamelson** [meituan/YOLOv6#231]
Hi,

I tried to resume my training (on a custom dataset) that stops after 136 epochs (out of 399 epochs) and got the following error:

```
Traceback (most recent call last):
  File "/linux/samelson/YOLOv6-main/tools/train.py", line 112, in <module>
    main(args)
  File "/linux/samelson/YOLOv6-main/tools/train.py", line 101, in main
    trainer = Trainer(args, cfg, device)
  File "/linux/samelson/YOLOv6-main/yolov6/core/engine.py", line 56, in __init__
    self.optimizer.load_state_dict(self.ckpt['optimizer'])
  File "/home/samelson/miniconda3/envs/yolov6/lib/python3.9/site-packages/torch/optim/optimizer.py", line 138, in load_state_dict
    saved_groups = state_dict['param_groups']
TypeError: 'NoneType' object is not subscriptable

```

Here is the command line I used: 
`python tools/train.py --batch 32 --conf configs/yolov6n_finetune.py --data data/mio-tcd.yaml --device 1 --img-size=480 --resume runs/train/exp4/weights/last_ckpt.pt`

Do you have any clue on how to resume my training?

Thank you in advance.

**Comment by JonathanSamelson** [comment]
Unfortunately no... In the meantime I relaunched a new training.

**Comment by Mahathi-l** [comment]
> Hi,
> 
> I tried to resume my training (on a custom dataset) that stops after 136 epochs (out of 399 epochs) and got the following error:
> 
> ```
> Traceback (most recent call last):
>   File "/linux/samelson/YOLOv6-main/tools/train.py", line 112, in <module>
>     main(args)
>   File "/linux/samelson/YOLOv6-main/tools/train.py", line 101, in main
>     trainer = Trainer(args, cfg, device)
>   File "/linux/samelson/YOLOv6-main/yolov6/core/engine.py", line 56, in __init__
>     self.optimizer.load_state_dict(self.ckpt['optimizer'])
>   File "/home/samelson/miniconda3/envs/yolov6/lib/python3.9/site-packages/torch/optim/optimizer.py", line 138, in load_state_dict
>     saved_groups = state_dict['param_groups']
> TypeError: 'NoneType' object is not subscriptable
> ```
> 
> Here is the command line I used: `python tools/train.py --batch 32 --conf configs/yolov6n_finetune.py --data data/mio-tcd.yaml --device 1 --img-size=480 --resume runs/train/exp4/weights/last_ckpt.pt`
> 
> Do you have any clue on how to resume my training?
> 
> Thank you in advance.

Were you able to solve the issue?

**Comment by erfanchy93** [comment]
I am having the same issue. How to solve this ? 

I am trying to train from last checkpoint  (last.pt) and train another 100 epochs.

**Comment by diplomatist** [comment]
same problem!  The speed of training is very slow and It takes a lot of time to retrain。

**Comment by mtjhl** [comment]
Please git pull the latest code. Sorry for the inconvenience.
When the training process is done, we will trim the checkpoint, delete the optimizer parameters. So currently, we can only resume from the checkpoint saved in the process of the training.
Did you resume from the final checkpoint?  @diplomatist @erfanchy93

**Comment by np-n** [comment]
@zidanexu  and @mtjhl I got the same issue and I have tried all the solutions that have available here and other similar issues, So how you fixed it?

**Comment by np-n** [comment]
> @zidanexu and @mtjhl I got the same issue and I have tried all the solutions that have available here and other similar issues, So how you fixed it?

Sorry, just fixed it replacing pretrained='weights/yolov6s.pt' by pretrained='./runs/train/exp/weights/last_ckpt.pt'`, Thanks!
