### ISSUE TITLE
Did the author of YOLOv3/YOLOv4 agree with you to use this name ?  And why did you delete the description about naming？

### ISSUE THREAD

**Issue by floveqq** [meituan/YOLOv6#232]
https://github.com/meituan/YOLOv6/commit/2b32b1e7ebee72a8f6e13159149d76785f5b9655
https://github.com/meituan/YOLOv6/commit/7f83d6b51fa9f65bc722046e4f0c9bcae406725e

If you got permission, why not publish it to everyone?

**Comment by m00nLi** [comment]
一个搞外卖的，不去持续优化大数据杀熟，反而跨行业东拼西凑的搞起目标检测，还厚颜无耻地碰瓷占用了别人的版本号给国人蒙羞，建议王老板将他们就地解聘
YouLookv6:
![YouLookv6](https://user-images.githubusercontent.com/102453574/177512913-cc42d247-75ce-4646-a1b1-7cc8acf2c46d.png)

**Comment by m00nLi** [comment]
closed，说怎么命名的删除了，说联系人家的删了，跟yolov5的参数对比也删除了，直接装死，太无耻了，哈哈
![15CC2A27](https://user-images.githubusercontent.com/102453574/185559205-7440278b-d587-4a51-9847-6d68257498d5.png)
