### ISSUE TITLE
{infer.py} No testing images getting saved in output directory runs/inference/exp

### ISSUE THREAD

**Issue by saiteja-kuchipudi** [meituan/YOLOv6#233]
I tried training on my custom dataset and testing an image with the best weights. It displays results saved to runs/inference/exp. And I find no predictions in that folder

**Comment by ShisuiUzumaki** [comment]
I think you should try setting these two args in infer.py

```
parser.add_argument('--save-txt', action='store_true', help='save results to *.txt.')
parser.add_argument('--save-img', action='store_false', help='save visuallized inference results.')
```

**Comment by saiteja-kuchipudi** [comment]
Thanks @ShisuiUzumaki. Later, it was working. I realized that problem was with saving those images where no instances have been found. When, I trained my model further, I was getting outputs saved.
