### ISSUE TITLE
【YOLOv6 VS PP-YOLOE s（400 epoch） Update】官方性能实测更新 / Update of the Official Performance Comparison 

### ISSUE THREAD

**Issue by YixinKristy** [meituan/YOLOv6#235]
# Update of the Test Result after Training 400 Epoch of PP-YOLOE s

Here is the latest comparison result:

Model | epoch | AP 0.5:0.95 | AP 0.5 | AP 0.75 | AP small | AP medium | AP large | AR small | AR medium | AR large
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
PP-YOLOE s | 300 | 43.0 | 59.6 | 47.2 | 26.0 | 47.4 | 58.7 | 45.1 | 70.6 | 81.4
PP-YOLOE s |  400 | 43.4 | 60.0 | 47.5 | 25.7 | 47.8 | 59.2 | 43.9 | 70.8 | 81.9
YOLOv6 s | 400 | 43.1 | 62.0 | 46.2 | 23.9 | 47.4 | 58.8 | 40.2 | 65.5 | 76.4

Feel free to raise any question or suggestion about the result~
PP-YOLOE always respect the original work of YOLO series and we'll keep working on providing more high-quality models.

For more reference: https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyoloe

The original issue with complete test result: https://github.com/meituan/YOLOv6/issues/140

# 性能对比测试数据更新（PP-YOLOE s训练400 epoch后）

<p data-first-child="" data-pid="2YYmsOjk" style="scroll-behavior: auto !important; margin: 0px 0px 1.4em; color: rgb(18, 18, 18); font-family: -apple-system, &quot;system-ui&quot;, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Microsoft YaHei&quot;, &quot;Source Han Sans SC&quot;, &quot;Noto Sans CJK SC&quot;, &quot;WenQuanYi Micro Hei&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">2022.7.5日更新：</p><p data-pid="fzhsjstc" style="scroll-behavior: auto !important; margin: 1.4em 0px; color: rgb(18, 18, 18); font-family: -apple-system, &quot;system-ui&quot;, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Microsoft YaHei&quot;, &quot;Source Han Sans SC&quot;, &quot;Noto Sans CJK SC&quot;, &quot;WenQuanYi Micro Hei&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">由于收到大家的反馈，我们训练针对PP-YOLOE s版本训练了400<span> </span><span style="scroll-behavior: auto !important;"><a data-za-not-track-link="true" href="https://www.zhihu.com/search?q=epoch&amp;search_source=Entity&amp;hybrid_search_source=Entity&amp;hybrid_search_extra=%7B%22sourceType%22%3A%22answer%22%2C%22sourceId%22%3A2551076952%7D" target="_blank" class="css-pgtd2j" style="scroll-behavior: auto !important; color: rgb(23, 81, 153); text-decoration: none; cursor: pointer;">epoch<svg width="10px" height="10px" viewBox="0 0 15 15" class="css-1dvsrp"><path d="M10.89 9.477l3.06 3.059a1 1 0 0 1-1.414 1.414l-3.06-3.06a6 6 0 1 1 1.414-1.414zM6 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8z" fill="currentColor"></path></svg></a></span>，以下是对比效果：<br style="scroll-behavior: auto !important;"></p>

模型 | epoch | AP 0.5:0.95 | AP 0.5 | AP 0.75 | AP small | AP medium | AP large | AR small | AR medium | AR large
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
PP-YOLOE s | 300 | 43.0 | 59.6 | 47.2 | 26.0 | 47.4 | 58.7 | 45.1 | 70.6 | 81.4
PP-YOLOE s | 400 | 43.4 | 60.0 | 47.5 | 25.7 | 47.8 | 59.2 | 43.9 | 70.8 | 81.9
YOLOv6 s | 400 | 43.1 | 62.0 | 46.2 | 23.9 | 47.4 | 58.8 | 40.2 | 65.5 | 76.4

<p data-pid="gqVJeHqj" style="scroll-behavior: auto !important; margin: 1.4em 0px; color: rgb(18, 18, 18); font-family: -apple-system, &quot;system-ui&quot;, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Microsoft YaHei&quot;, &quot;Source Han Sans SC&quot;, &quot;Noto Sans CJK SC&quot;, &quot;WenQuanYi Micro Hei&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">大家有任何问题欢迎在评论区中讨论提出~</p><p data-pid="uRYj5c0o" style="scroll-behavior: auto !important; margin: 1.4em 0px; color: rgb(18, 18, 18); font-family: -apple-system, &quot;system-ui&quot;, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Microsoft YaHei&quot;, &quot;Source Han Sans SC&quot;, &quot;Noto Sans CJK SC&quot;, &quot;WenQuanYi Micro Hei&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b style="scroll-behavior: auto !important; font-weight: 600; font-synthesis: style;">PP-YOLOE始终保持着向YOLO系列的致敬，希望大家能多多尝试，提出宝贵的建议！

如需获取完整的对比测试，请参考原始issue：https://github.com/meituan/YOLOv6/issues/140

**Comment by hutao568** [comment]
美团：这是来砸场子的吗Σ(⊙▽⊙"a

**Comment by qmcreeper** [comment]
> 美团：这是来砸场子的吗Σ(⊙▽⊙"a

再来个yolov7的比就更有意思了 : P
