### ISSUE TITLE
The mAP is lower than YoloX with my traffic-light dataset. Any suggestions?

### ISSUE THREAD

**Issue by sean-wade** [meituan/YOLOv6#239]
I'm using the DTLD traffic light dataset. The objects is normaly small. 

When I use YOLOX-s, the mAP@0.5 achieve at 0.569. Yet the yolov6-s only achieve at 0.537.(0.475 if no loading pretrained pt.)

**Comment by Zephyr69** [comment]
You may want take a closer look beyond mAP, like FNs, FPs, and per-category performances to see which model is performing better really; this also helps you localize potential problems. 

mAP alone is misleading and doesn't tell much about model performance at all (unless you are sure all categories should be weighted equally even in an unbalanced dataset).
