### ISSUE TITLE
请问训练使用的GPU型号是什么呢？多大显存呢?

### ISSUE THREAD

**Issue by Joker-co** [meituan/YOLOv6#240]
训练时单张卡使用32 batch size感觉很大，请问训练使用的GPU型号是什么呢？是a100或者v100吗，多大显存呢？

**Comment by mtjhl** [comment]
Hi, if your GPU memory is small, you'd better reduce the batch size number. We train the model on A100(80/40G) or  V100( 32G).

**Comment by Joker-co** [comment]
thanks!
