### ISSUE TITLE
Qs for RepVGGBlock

### ISSUE THREAD

**Issue by d5423197** [meituan/YOLOv6#241]
Hello there,

Thanks for the conritbution. I am new to this repVgg block. As I know, this kind of architecture will be modified to self.rbr_reparam when predicting. But in your code, it is still using the training architecture when predicting if I understand correctly. 

Any help will be appreciated!

https://github.com/meituan/YOLOv6/blob/b6cef8753c4bee2dc0ca120c5a2f6dcb5d2b4fe9/yolov6/layers/common.py#L185-L195

**Comment by mtjhl** [comment]
In eval mode, it will switch to brr_reparm.
https://github.com/meituan/YOLOv6/blob/c85065cf4b58c7f929013fbc73c8dc362e8bed86/yolov6/core/evaler.py#L54

**Comment by d5423197** [comment]
Thanks for your reply. What about inferencing? (infer.py)

**Comment by khwengXU** [comment]
During inference(infer.py), RepVggBlock will switch to deploy status, too.

**Comment by khwengXU** [comment]
Sorry, during inference(infer.py), the switch of repvggblock is not used by default. But you can use this switch function in infer.py to improve inference speed.

**Comment by d5423197** [comment]
Will do, thanks.
