### ISSUE TITLE
The owners of this repo should seriously consider renaming it. You got the hype you wanted by misusing the YOLO name, now please change it to something more meaningful and appropriate.

### ISSUE THREAD

**Issue by floveqq** [meituan/YOLOv6#246]

**Comment by Doragd** [comment]
I also feel confused that the owners removed the link to renaming docs in the `README.md` yesterday without any explanation. I don't know if the authors of YOLO have authorized them. 

By the way, I found that doubts about the performance were also expressed in a Q&A community called ZhiHu.
You can access via the following link:
https://www.zhihu.com/question/539205443/answer/2557990982

![image](https://user-images.githubusercontent.com/26213546/177391667-d4be5c00-7086-4ded-a6cf-425bbb410dd3.png)
