### ISSUE TITLE
How to infer yolov6 model for single image

### ISSUE THREAD

**Issue by mallapraveen** [meituan/YOLOv6#254]
i need a python script which take single image and do the prediction on it and return the results.
can someone help on this

**Comment by Rjshrivastav** [comment]
try using infer.py and pass your image path in source argument.
for eg.
```python tools/infer.py --weights <saved_model_path> --source <img path>```

**Comment by mallapraveen** [comment]
@Rjshrivastav  that is one way of doing it, I need script which take a  single image and return the bounding boxes and class labels.

**Comment by MTChengMeng** [comment]
> @Rjshrivastav that is one way of doing it, I need script which take a single image and return the bounding boxes and class labels.

Hi, you can add --save-txt option to save predicted scores and labels of yolo format.

**Comment by mallapraveen** [comment]
@MTChengMeng do we have a predict function which takes image as input and gives the output as bboxes and labels. I have currently trained the model and want function to integrate with my codebase.
A function would help instead of invoking like this 'python tools/infer.py --weights <saved_model_path> --source <img path>'

**Comment by Rjshrivastav** [comment]
you can use```yolov6/core/inferer.py``` that contains all the necessary functions.

**Comment by mallapraveen** [comment]
@SongHfei Thanks
