### ISSUE TITLE
yolo v6 --save-txt tag will be wrong in labelImg

### ISSUE THREAD

**Issue by GuanLinHu** [meituan/YOLOv6#257]
When I open the label generated by the test in the labelImg program, an error occurs.
![image](https://user-images.githubusercontent.com/61997271/177549131-e136a45e-ec7c-44cf-bf7c-7013ff982144.png)
Official correct .txt format
![image](https://user-images.githubusercontent.com/61997271/177655689-e1b81ade-924f-4ddf-89b1-cdf6d9e885a3.png)
--save-txt out of the format
![image](https://user-images.githubusercontent.com/61997271/177655869-6f676e6d-b94d-4147-8df8-8a1c4071a360.png)

**Comment by altarizer** [comment]
yolo's tensor results can parse by this format 
[class id center_x center_y bbox_width bbox_height confidence]

**Comment by GuanLinHu** [comment]
@altarizer Thank you, I removed the confidence and it can be displayed normally
[confidence]
