### ISSUE TITLE
adding layers

### ISSUE THREAD

**Issue by Mahathi-l** [meituan/YOLOv6#258]
How to add more layers to the YOLOv6 architecture? I have a bad quality image dataset & I want to add a few layers to handle image quality. Any suggestions on where and how to add layers to the network? @meituan-gengyifei

**Comment by mtjhl** [comment]
Hi, you can increase the `depth_multiple` and `width_multiple` here to increase the model's depth and width.
https://github.com/meituan/YOLOv6/blob/471c72ff34178e48a80eab6737a4519282ed38f5/configs/yolov6s.py#L5
