### ISSUE TITLE
about the yolov6 train log

### ISSUE THREAD

**Issue by FL77N** [meituan/YOLOv6#261]
Hello, thanks for your great work! I want to implement yolov6 in my own project, could you provide yolov6 train log for my implementing, thank you!

**Comment by khwengXU** [comment]
Thanks for your attentions!
What's the purpose of yolov6 train log?

**Comment by FL77N** [comment]
> Thanks for your attentions! What's the purpose of yolov6 train log? For reproducing result or for your project?

Exactly, train log can help to guild my reproducing and find out some errors in my implementation , could you help me? Thanks~
