### ISSUE TITLE
int8 量化问题

### ISSUE THREAD

**Issue by HawkL327** [meituan/YOLOv6#265]
使用tensorrt进行int8量化，精度会掉10%，有什么很好的解决办法吗？

**Comment by HawkL327** [comment]
https://arxiv.org/pdf/2205.15242.pdf

**Comment by xingyueye** [comment]
RepOpt版本实现及相应的TRT量化问题已经基本解决，这几天就会PR，可以期待一下😚

**Comment by yghstill** [comment]
@HawkL327 可以参考PaddleSlim自动化压缩方案：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/example/auto_compression/pytorch_yolov6
精度损失1个点左右，相比trt-fp16加速58%。

**Comment by HawkL327** [comment]
> @HawkL327 可以参考PaddleSlim自动化压缩方案：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/example/auto_compression/pytorch_yolov6 精度损失1个点左右，相比trt-fp16加速58%。

谢谢 我试试
