### ISSUE TITLE
Would be great to add Per-Class "Precision, Recall, mAPs" to the Evaluation Metrics | 请考虑对每一类加上验证指标，如Precision，Recall，mAPs

### ISSUE THREAD

**Issue by HeZhang33** [meituan/YOLOv6#266]
Dear YOLOv6 team,

I am really enjoying your work. One advice / wish is that: it would be super if you could add extra metrics such as Precision, Recall, and mAPs, to EACH of the classes so that we could have an easy comparison with YOLOv5 and others. 

For example, for a binary detection task with 2 classes Cat and Dog:

![屏幕截图 2022-07-07 180913](https://user-images.githubusercontent.com/97652535/177749334-506d9b54-2ef9-4a7c-a3b1-9d2f2204c994.png)

Many thanks in advance! 

He

**Comment by mtjhl** [comment]
Hi， thank you for your advice. We will take it into consideration.

**Comment by HeZhang33** [comment]
By the way, just saw a similar request in #277.

Again, hope to have precison and recall per class soon. 

Thank you!

**Comment by dejavvuu** [comment]
@HeZhang33 ， you can adapt /pycocotools/cocoeval.py to get the detail information

**Comment by norah-art** [comment]
Good day, 

Is there any update in this request for having the Precision, Recall, and F1score command to evaluate custom dataset?
having them is so important to compare the results with yolov5

thank you

**Comment by rakibjabed** [comment]
@norah-art 
have you found your Precision, Recall and F1 score?

**Comment by norah-art** [comment]
> @norah-art have you found your Precision, Recall and F1 score?

Unfortunately, I have not find them

**Comment by shensheng272** [comment]
Latest code will print conf on best mF1 and print P R under iou50. Also default plot curves like yolov5. Also you can log infos you want near https://github.com/meituan/YOLOv6/blob/main/yolov6/core/evaler.py#L188

**Comment by norah-art** [comment]
Hi @shensheng272 
how to print the conf or at least show the result for it, I wrote the command as below but I get error
!python /content/YOLOv6/yolov6/core/evaler.py --data data/dataset.yaml --img-size 416 --weights runs/train/exp/weights/best_ckpt.pt --device 0

Traceback (most recent call last):
  File "/content/YOLOv6/yolov6/core/evaler.py", line 14, in <module>
    from yolov6.data.data_load import create_dataloader
ModuleNotFoundError: No module named 'yolov6'

**Comment by norah-art** [comment]
Hi @shensheng272
how to print the conf or at least show the result for it, I wrote the command as below but I get error
!python /content/YOLOv6/yolov6/core/evaler.py --data data/dataset.yaml --img-size 416 --weights runs/train/exp/weights/best_ckpt.pt --device 0

Traceback (most recent call last):
File "/content/YOLOv6/yolov6/core/evaler.py", line 14, in
from yolov6.data.data_load import create_dataloader
ModuleNotFoundError: No module named 'yolov6'

**Comment by nelsonvarte** [comment]
I got the Precision, Recall and F1 by changing  "default=True" in -

https://github.com/meituan/YOLOv6/blob/main/tools/eval.py#44 

parser.add_argument('--do_pr_metric', default=True, type=boolean_string, help='whether to calculate precision, recall and F1, n, set False to close')

**Comment by YASHkh2609** [comment]
Thank you @nelsonvarte your solution did work but this got me only the overall Precision, Recall and F1 but i also need the class-wise values so can you help me with it.
