### ISSUE TITLE
Can I use yolov6 best weights on yolov5?

### ISSUE THREAD

**Issue by ewankim1023** [meituan/YOLOv6#274]
I can confirm that Yolov6 is stronger than yolov5. Higher confidence score. Not sure about training/inference speed. But maybe.

The problem is dataset structure is different - yolov6 : (images,labels) --> (train/test/valid), yolov5 : (train/test/valid) --> (images,labels) and some of aspects (yaml --> py). I already have deployed yolov5, so I just wonder if I can use yolov6 weights for yolov5

**Comment by Zephyr69** [comment]
Unless either of them changed it in the most recent update, their dataset structure should be exactly the same ((images,labels) --> (train/test/valid)) or at least compatible as I've been training both on the same dataset for a while now. It's just how they are loaded is configured differently.

To use yolov6 under yolov5, you need to either implement v6 under v5's framework or make them compatible. Their modules and blocks are different, and v6 is anchor-free.

**Comment by khwengXU** [comment]
Thanks for your attentions!
The model of yolov6 and yolov5 is different. Yolov6 best weights can not used directly on yolov5.
