### ISSUE TITLE
SyntaxError: invalid syntax`

### ISSUE THREAD

**Issue by totoadel** [meituan/YOLOv6#275]
i got this error when do training on colab 

`%cd /content/YOLOv6
!python tools/train.py  --data-path /content/data.yaml --device 0`

`/content/YOLOv6
Traceback (most recent call last):
  File "tools/train.py", line 17, in <module>
    from yolov6.core.engine import Trainer
  File "/content/YOLOv6/yolov6/core/engine.py", line 16, in <module>
    import tools.eval as eval
  File "/content/YOLOv6/tools/eval.py", line 13, in <module>
    from yolov6.core.evaler import Evaler
  File "/content/YOLOv6/yolov6/core/evaler.py", line 14, in <module>
    from yolov6.data.data_load import create_dataloader
  File "/content/YOLOv6/yolov6/data/data_load.py", line 11, in <module>
    from yolov6.utils.torch_utils import torch_distributed_zero_first
  File "/content/YOLOv6/yolov6/utils/torch_utils.py", line 105
    flops, params = profile(deepcopy(model), inputs=(img,), verbose=False)
        ^
SyntaxError: invalid syntax`

**Comment by HelloSZS** [comment]
我down了master的版本的之后运行，也遇到这个问题

(yolov6) D:\WK_roller\GD_TC\YOLOv6-main>python tools/infer.py --weights weights/yolov6n.pt --source data/images
Traceback (most recent call last):
  File "tools/infer.py", line 15, in <module>
    from yolov6.core.inferer import Inferer
  File "D:\WK_roller\GD_TC\YOLOv6-main\yolov6\core\inferer.py", line 16, in <module>
    from yolov6.utils.torch_utils import get_model_info
  File "D:\WK_roller\GD_TC\YOLOv6-main\yolov6\utils\torch_utils.py", line 105
    flops, params = profile(deepcopy(model), inputs=(img,), verbose=False)
    ^
SyntaxError: invalid syntax


应该是“YOLOv6-main/yolov6/utils/torch_utils.py”里的line102的"try:... except: ..."没写全

`def get_model_info(model, img_size=640):
    """Get model Params and GFlops.
    Code base on https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/utils/model_utils.py
    """
    from thop import profile
    stride = 32
    try:
        img = torch.zeros((1, 3, stride, stride), device=next(model.parameters()).device)
        
    flops, params = profile(deepcopy(model), inputs=(img,), verbose=False)
    ......
`

将其修改成
`def get_model_info(model, img_size=640):
    """Get model Params and GFlops.
    Code base on https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/utils/model_utils.py
    """
    from thop import profile
    stride = 32
    try:
        img = torch.zeros((1, 3, stride, stride), device=next(model.parameters()).device)
    except Exception as e:
        print(e)
        
    flops, params = profile(deepcopy(model), inputs=(img,), verbose=False)
    ...
`

就可以运行

**Comment by mtjhl** [comment]
Sorry for the inconvenience, we remove the try except here. Please git pull the latest codes.
