### ISSUE TITLE
Support for Oriented Bounding Boxes (OBB)

### ISSUE THREAD

**Issue by zardadi** [meituan/YOLOv6#276]
has anyone tested Yolov6 against [DOTA](https://captain-whu.github.io/DOTA/dataset.html) dataset? 
I know people have used Yolov5 for OBB like this [link](https://github.com/hukaixuan19970627/yolov5_obb/blob/master/docs/GetStart.md).

**Comment by Avant-Gardiste** [comment]
Hi @zardadi, I'm acctually working on it. It still in progress and i'll keep you in touch once it's completed !
