### ISSUE TITLE
Model training and evaluation problems

### ISSUE THREAD

**Issue by GuanLinHu** [meituan/YOLOv6#277]
This is the model after we train the model, but I want to get the P(precision), R(recall), F1score of the model how to get these values.
![image](https://user-images.githubusercontent.com/61997271/177886689-9a769fd5-22ac-482a-af9b-5b47dacfa8eb.png)

**Comment by mtjhl** [comment]
Hi, if you want to get precision and recall at one specific confidence, you can filter out the detect boxes whose confidence are lower than your  specific confidence. 
Second, put the detect results and annotation to pycocotools,  you can get the details contain precision and recall at cocoEval here.
https://github.com/meituan/YOLOv6/blob/c85065cf4b58c7f929013fbc73c8dc362e8bed86/yolov6/core/evaler.py#L135
cocoEval contains rich information. You can explore it.

**Comment by GuanLinHu** [comment]
@mtjhl  Sorry, my problem is to other detection frameworks (ex: yolov5, yolor, yolox), when the training is completed, precision and recall can be found in .txt or .csv, but I only have .json in yolov6 and do not see the above precision and recall recall, can you please assist me? Thank you.

**Comment by mtjhl** [comment]
Ok, we will discuss about whether to add this function.

**Comment by GuanLinHu** [comment]
@mtjhl So I can't know about precision and recall?There are other ways...

**Comment by HeZhang33** [comment]
I have just asked the similar feature request. Hope to have precision and recall output as well. #266

**Comment by Passion0930** [comment]
> Ok, we will discuss about whether to add this function.

yes, we want to know precision and recall of all kinds of categories. please add this function soon!

**Comment by Chilicyy** [comment]
Thanks for your suggestion! We'll mark it down and try to add this feature.

**Comment by norah-art** [comment]
Hi, Is there any update on that?
It will be amazing for having (precision), (recall), F1 score

**Comment by shensheng272** [comment]
Latest code will print conf on best mF1 and print P R under iou50. Also default plot curves like yolov5. Also you can log infos you want near https://github.com/meituan/YOLOv6/blob/main/yolov6/core/evaler.py#L188
