### ISSUE TITLE
Issue with Try statement line 105 in yolov6/utils/torch_utils.py

### ISSUE THREAD

**Issue by sangramdogra** [meituan/YOLOv6#279]
There is no except clause which is causing syntax error in training for try statement in line 105

**Comment by bdubbs09** [comment]
This is being corrected in a current pull request that is under review. If you want to fix it in a copy, just add:
`except:
raise Exception("must be nn.module")`

**Comment by nateraw** [comment]
Fix was just merged. This is resolved
