### ISSUE TITLE
Adding U-Net backbone before EfficientRep 

### ISSUE THREAD

**Issue by Mahathi-l** [meituan/YOLOv6#289]
I am trying to add an extra network in front of Efficientrep which is based on UNet( to handle denoising in image dataset) . I would really appreciate it if you can give me some insights on how to get started with that. Because, the way the backbone, neck and head are organized is similar across yolov6n,yolov6s & yolov6-tiny is same. So, to add an extra network before the backbone, is there a way to do that?

**Comment by Chilicyy** [comment]
Thx for your attention! If you want to add an extra network before the backbone, you need to create a pyfile for your own network structure , and then put it under the directory of [$YOLOv6/yolov6/models]. After that, you can add the extra network in the [build_network function](https://github.com/meituan/YOLOv6/blob/HEAD/yolov6/models/yolo.py#L63) #L62. I hope it would help you.
