### ISSUE TITLE
coco preparation

### ISSUE THREAD

**Issue by XiaoJiNu** [meituan/YOLOv6#29]
How to prepare coco data ? What is the tree structure of the coco folder?

**Comment by Chilicyy** [comment]
Thanks for your attention !
You can convert coco data into YOLO format, as the [tutorial](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) showed.

The structure of coco folder is like as below:
```
# image directory
./coco/images/train2017/*.jpg
./coco/images/val2017/*.jpg

# label directory
./coco/labels/train2017/*.txt
./coco/labels/val2017/*.txt
```

**Comment by XiaoJiNu** [comment]
@Chilicyy Thank you.
