### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by Satyajit1993** [meituan/YOLOv6#292]
While executing train.py it shows

Traceback (most recent call last):
  File "tools/train.py", line 23, in <module>
    from yolov6.core.engine import Trainer
ModuleNotFoundError: No module named 'yolov6.core'

**Comment by Chilicyy** [comment]
Thanks for your attention! You can try to add the directory of YOLOv6 to $PYTHONPATH.

**Comment by Satyajit1993** [comment]
I tried but unable to resolve the issue. Kindly tell me the process of adding the directory into pythonpath. It will be great

**Comment by Mandroide** [comment]
> I tried but unable to resolve the issue. Kindly tell me the process of adding the directory into pythonpath. It will be great

If you have a Linux environment, open your terminal (CTRL + ALT + T) and replace what is inside "<" and ">" with the absolute path of the repository:
```shell
echo PYTHONPATH=\"<ABSOLUTE/PATH/TO>/YOLOv6/yolov6\" >> ~/.bashrc
source ~/.bashrc
```

**Comment by Satyajit1993** [comment]
Thanks for your reply but my system is windows 10 with nvdia 940mx , cuda
11.5+cudnn 8.3

**Comment by Mandroide** [comment]
> Thanks for your reply but my system is windows 10 with nvdia 940mx , cuda 11.5+cudnn 8.3

With Powershell opened as administrator
```powershell
$PYTHONPATH = [Environment]::GetEnvironmentVariable("PYTHONPATH")
$yolov6_path = "<ABSOLUTE/PATH/TO>/YOLOv6/yolov6"
[Environment]::SetEnvironmentVariable("PYTHONPATH", "$PYTHONPATH;$yolov6_path")
```

**Comment by Satyajit1993** [comment]
Still have the same issue after @Mandroide's solution.  I am using a virtual environment in anaconda prompt because of that this error is coming or something else.

**Comment by Mandroide** [comment]
> Still have the same issue after @Mandroide's solution. I am using a virtual environment in anaconda prompt because of that this error is coming or something else.

Write into the command prompt with your absolute path to the directory.
```cmd
setx PYTHONPATH %PYTHONPATH%;<ABSOLUTE\PATH\TO>\YOLOv6\yolov6
```

**Comment by Satyajit1993** [comment]
Followed all the steps still have the same error

**Comment by sohaiblaraba** [comment]
Try this solution [here](https://github.com/meituan/YOLOv6/issues/64#issuecomment-1166731492)

**Comment by sriramk146** [comment]
@Satyajit1993 you can run Train.py on <ABSOLUTE PATH/YOLOv6/> from the command prompt to sort out this issue.

**Comment by selfpline** [comment]
windows 10  pycharm  anconda 虚拟环境 如何from yolov6.core.engine import Trainer
ModuleNotFoundError: No module named 'yolov6.core'  解决这个问题
