### ISSUE TITLE
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.

### ISSUE THREAD

**Issue by cvirxsc** [meituan/YOLOv6#293]
The program always stops at the same iteration and then reports an error. What should I do?
![311284476004653961](https://user-images.githubusercontent.com/102666935/178098815-08428a7a-d9c7-4615-a4fc-ca38b26134a5.jpg)

**Comment by meituan-gengyifei** [comment]
Thanks for your attention! We are trying to reproduce your error. Before that, you also can try this solution:
https://blog.csdn.net/weixin_35848967/article/details/120200055?spm=1001.2101.3001.6650.1&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-1-120200055-blog-123645660.pc_relevant_multi_platform_whitelistv1_exp2&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-1-120200055-blog-123645660.pc_relevant_multi_platform_whitelistv1_exp2&utm_relevant_index=2

Might be able to pinpoint your problem more clearly
