### ISSUE TITLE
A training Error after the 20 epoch.

### ISSUE THREAD

**Issue by naan03** [meituan/YOLOv6#294]
Hi, meituan team, I trained the model by my own dataset on Google Colab. I got an error after the 20th epoch. any advice about this err?   

  Epoch  iou_loss   l1_loss  obj_loss  cls_loss
    20/399     2.245     1.259     2.337    0.6923: 100% 9/9 [00:25<00:00,  2.86s/it]
Inferencing model in val datasets.: 100% 2/2 [00:02<00:00,  1.44s/it]

Evaluating speed.

Evaluating mAP by pycocotools.
Saving runs/train/exp2/predictions.json...
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.41s)
creating index...
index created!
ERROR in evaluate and save model.
ERROR in training loop or eval/save model.

Training completed in 0.160 hours.
Traceback (most recent call last):
  File "tools/train.py", line 112, in <module>
    main(args)
  File "tools/train.py", line 102, in main
    trainer.train()
  File "/content/gdrive/MyDrive/YOLOv6/yolov6/core/engine.py", line 75, in train
    self.train_in_loop()
  File "/content/gdrive/MyDrive/YOLOv6/yolov6/core/engine.py", line 94, in train_in_loop
    self.eval_and_save()
  File "/content/gdrive/MyDrive/YOLOv6/yolov6/core/engine.py", line 120, in eval_and_save
    self.eval_model()
  File "/content/gdrive/MyDrive/YOLOv6/yolov6/core/engine.py", line 145, in eval_model
    task='train')
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/gdrive/MyDrive/YOLOv6/tools/eval.py", line 83, in run
    eval_result = val.eval_model(pred_result, model, dataloader, task)
  File "/content/gdrive/MyDrive/YOLOv6/yolov6/core/evaler.py", line 128, in eval_model
    cocoEval = COCOeval(anno, pred, 'bbox')
  File "/usr/local/lib/python3.7/dist-packages/pycocotools/cocoeval.py", line 80, in __init__
    self.params.imgIds = sorted(cocoGt.getImgIds())
TypeError: '<' not supported between instances of 'str' and 'int'

**Comment by shensheng272** [comment]
https://github.com/meituan/YOLOv6/issues/98   the same problem,  might try pull the lastest code

**Comment by mtjhl** [comment]
Hi, are the mAP of the previous 20 epoch normal? @naan03

**Comment by naan03** [comment]
> Hi, are the mAP of the previous 20 epoch normal? @naan03

How to check the mAP? the JSON file is hard to understand. This is the output log of the first 20 epochs. Evaluating speed.

Evaluating mAP by pycocotools.
Epoch: 0 | mAP@0.5: 0.0 | mAP@0.50:0.95: 0.0

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     1/399     3.071     1.437     7.206     1.789: 100% 9/9 [00:20<00:00,  2.29s/it]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     2/399     3.082     1.434     7.039     1.476: 100% 9/9 [00:24<00:00,  2.71s/it]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     3/399     3.055     1.458     6.818     1.161: 100% 9/9 [00:26<00:00,  2.93s/it]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     4/399     2.983     1.436      6.37    0.9526: 100% 9/9 [00:24<00:00,  2.71s/it]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     5/399     2.925     1.425     6.059    0.8638: 100% 9/9 [00:26<00:00,  2.94s/it]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     6/399     2.781      1.38     5.323     0.778: 100% 9/9 [00:24<00:00,  2.70s/it]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     7/399     2.573     1.313     4.739    0.7302: 100% 9/9 [00:25<00:00,  2.87s/it]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     8/399     2.402     1.228     4.184    0.7205: 100% 9/9 [00:24<00:00,  2.69s/it]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     9/399     2.283     1.143     3.511    0.7055: 100% 9/9 [00:25<00:00,  2.87s/it]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
    10/399     2.208     1.102     3.259    0.6971: 100% 9/9 [00:26<00:00,  2.95s/it]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
    11/399     2.465     1.291      3.42    0.7089: 100% 9/9 [00:25<00:00,  2.84s/it]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
    12/399     2.313     1.136      3.12    0.7012: 100% 9/9 [00:24<00:00,  2.73s/it]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
    13/399     2.186      1.07     2.765    0.6918: 100% 9/9 [00:26<00:00,  2.90s/it]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
    14/399     2.272     1.112      2.63    0.6963: 100% 9/9 [00:24<00:00,  2.71s/it]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
    15/399     2.247     1.168     2.762    0.6912: 100% 9/9 [00:26<00:00,  2.96s/it]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
    16/399     2.145     1.025     2.658    0.6919: 100% 9/9 [00:23<00:00,  2.66s/it]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
    17/399     2.635     1.472     3.413    0.7335: 100% 9/9 [00:26<00:00,  2.90s/it]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
    18/399     2.382     1.303     2.879    0.6996: 100% 9/9 [00:24<00:00,  2.70s/it]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
    19/399     2.454     1.335     2.673    0.7046: 100% 9/9 [00:26<00:00,  2.93s/it]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
    20/399     2.245     1.259     2.337    0.6923: 100% 9/9 [00:25<00:00,  2.86s/it]
Inferencing model in val datasets.: 100% 2/2 [00:02<00:00,  1.44s/it]

Evaluating speed.

Evaluating mAP by pycocotools.
Saving runs/train/exp2/predictions.json...
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.41s)
creating index...
index created!
ERROR in evaluate and save model.
ERROR in training loop or eval/save model.

**Comment by leedewdew** [comment]
tensorboard is all u need

**Comment by Caius-Lu** [comment]
在自己的数据集，我也遇到了上述问题，以下是我的解决方法。
第一： 文件名不能有中文，有的话改代码，json dump  要改掉。
第二： 文件名不能含有192.168.，“.”这种字符，代码里会根据这个来split，导致annsImgIds和 self.getImgIds()对应不上， 文件名最好是纯粹的数字或者纯粹的字符串， 混用的话要改代码。
第三： 如果还有问题， debug一下，定位到行。

**Comment by naan03** [comment]
> 

非常感谢，我自查一下。

**Comment by the-cat-crying** [comment]
pred = anno.loadRes(pred_json)
            cocoEval = COCOeval(anno, pred, 'bbox')

这个地方会报错，不知道作者能不能弄一个验证的或者MAP的数据格式

**Comment by Caius-Lu** [comment]
> 我的没有，为什么还是会出这样的错误，训练没问题，使用trian,val验证的时候总会报错

这个就是上面我说的问题啊，它是把验证集保存成json，然后预测也保存成json，再调用cooceval来做，如果验证集图片名有特殊字符，或者字符串和数字混用， 找不到对应的set就会报错，具体的还是要看你自己的数据和它的代码。

**Comment by the-cat-crying** [comment]
我看代码，验证集和预测也都保存好了.json，但是就会有错误，图片命名我都是数字+.jpg格式。测试集没有预测出目标，标签为0，验证集有，这种对应在一起会不会报这样的错

**Comment by sarmientoj24** [comment]
same error

**Comment by Caius-Lu** [comment]
> 

你直接断点到Cocoeval 那行代码呀，看具体是啥问题。

**Comment by the-cat-crying** [comment]
这个我也知道，目前就是公司断网，只能用内网，我环境都是用的docker，vscode连过去看，就是调不了代码，难受。

**Comment by Caius-Lu** [comment]
> 这个我也知道，目前就是公司断网，只能用内网，我环境都是用的docker，vscode连过去看，就是调不了代码，难受。

我们不会一个司吧， 可调呀。。 我用的也是docker，也是内网， 上不了外网的那种

**Comment by the-cat-crying** [comment]
不会吧，你是怎么调的，ssh过去么，我的ssh连不上去，不知道为什么，插件那些都装了。

**Comment by shensheng272** [comment]
https://github.com/meituan/YOLOv6/pull/309 fix this, plz try again

**Comment by shensheng272** [comment]
> ```
>         pred = anno.loadRes(pred_json)
>         cocoEval = COCOeval(anno, pred, 'bbox')
> ```
> 
> 这个地方会报错，不知道作者能不能弄一个验证的或者MAP的数据格式

拉取新代码，删掉原本生成的 *_instance.json 试试

**Comment by the-cat-crying** [comment]
@[shensheng272](https://github.com/shensheng272) 好的，谢谢。
