### ISSUE TITLE
Model resume training

### ISSUE THREAD

**Issue by Ahashluxy** [meituan/YOLOv6#298]
Hello friends, it's great to see your work is so popular I would like to ask how yolov6 can continue training after a training break

**Comment by MTChengMeng** [comment]
Hi, you can add --resume option in your command line to resume your training. ([Reference](https://github.com/meituan/YOLOv6#resume)).

**Comment by Ahashluxy** [comment]
Thank you very much for your help Your suggestion is very effective but I get the following error I would be grateful if you could answer！


assert os.path.isfile(args.resume), 'ERROR: --resume checkpoint does not exists'
AssertionError: ERROR: --resume checkpoint does not exists

**Comment by Ahashluxy** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "meituan/YOLOv6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月11日(星期一) 晚上7:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [meituan/YOLOv6] Model resume training (Issue #298)





 
Hi, you can add --resume option in your command line to resume your training (Reference).
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.
Thank you very much for your help Your suggestion is very effective but I get the following error I would be grateful if you could answer！ assert os.path.isfile(args.resume), 'ERROR: --resume checkpoint does not exists'
AssertionError: ERROR: --resume checkpoint does not exists

**Comment by shensheng272** [comment]
--resume  should set to the pt path.    like       --resume  run/exp/last_ckpt.pt     

By the way --resume is not compatible with --name, because --resume will read args.ymal in train folder.

**Comment by DrChungAlbert** [comment]
Can resume training with adding more total epoch than before ?
