### ISSUE TITLE
Help!Help!Help!Help!Help!Help!Help!Help!Help!Help!Help!Help!Help!

### ISSUE THREAD

**Issue by yuanzhougege** [meituan/YOLOv6#300]
Traceback (most recent call last):
  File "tools/train.py", line 112, in <module>
    main(args)
  File "tools/train.py", line 101, in main
    trainer = Trainer(args, cfg, device)
  File "/docker_code/yolov6/YOLOv6-main/yolov6/core/engine.py", line 43, in __init__
    self.train_loader, self.val_loader = self.get_data_loader(args, cfg, self.data_dict)
  File "/docker_code/yolov6/YOLOv6-main/yolov6/core/engine.py", line 219, in get_data_loader
    train_loader = create_dataloader(train_path, args.img_size, args.batch_size // args.world_size, grid_size,
  File "/docker_code/yolov6/YOLOv6-main/yolov6/data/data_load.py", line 41, in create_dataloader
    dataset = TrainValDataset(
  File "/docker_code/yolov6/YOLOv6-main/yolov6/data/datasets.py", line 63, in __init__
    self.img_paths, self.labels = self.get_imgs_labels(self.img_dir)
  File "/docker_code/yolov6/YOLOv6-main/yolov6/data/datasets.py", line 327, in get_imgs_labels
    img_paths, labels = list(
ValueError: not enough values to unpack (expected 2, got 0)

请问这种情况怎么办

**Comment by Caius-Lu** [comment]
self.get_imgs_labels(self.img_dir) ，查数据， debug到这个函数里面啊

**Comment by Caius-Lu** [comment]
> Traceback (most recent call last): File "tools/train.py", line 112, in main(args) File "tools/train.py", line 101, in main trainer = Trainer(args, cfg, device) File "/docker_code/yolov6/YOLOv6-main/yolov6/core/engine.py", line 43, in **init** self.train_loader, self.val_loader = self.get_data_loader(args, cfg, self.data_dict) File "/docker_code/yolov6/YOLOv6-main/yolov6/core/engine.py", line 219, in get_data_loader train_loader = create_dataloader(train_path, args.img_size, args.batch_size // args.world_size, grid_size, File "/docker_code/yolov6/YOLOv6-main/yolov6/data/data_load.py", line 41, in create_dataloader dataset = TrainValDataset( File "/docker_code/yolov6/YOLOv6-main/yolov6/data/datasets.py", line 63, in **init** self.img_paths, self.labels = self.get_imgs_labels(self.img_dir) File "/docker_code/yolov6/YOLOv6-main/yolov6/data/datasets.py", line 327, in get_imgs_labels img_paths, labels = list( ValueError: not enough values to unpack (expected 2, got 0)
> 
> 请问这种情况怎么办
查数据， debug到 self.get_imgs_labels这个函数里面

**Comment by mtjhl** [comment]
Hi, which dataset are you used when this error occurs?

**Comment by ShisuiUzumaki** [comment]
I think the issue might be in your directory structure or your paths. Please refer to custom dataset tutorial provided in the README.md file
