### ISSUE TITLE
How to perform inference for instance segmentation using the pre-trained model?

### ISSUE THREAD

**Issue by Srikanthv466** [meituan/YOLOv6#301]
Hi, 
Great work!
I've two questions, 
1. How to perform inference for instance segmentation using pre-trained model and get the masks?
2. I would like to train instance segmentation model, can you help me with the data format (how the segmentation points are represented in the annotation file).
For now I only see class, x, y, w, h in the annotation file, how are segmentation points represented?
Any link to sample annotation file would be helpful.
Any help would be much appreciated!

**Comment by shensheng272** [comment]
For now, yolov6 is focus on object detection. You might try solov2 for your application.

**Comment by khwengXU** [comment]
Thanks for your attentions!
Currently, YOLOv6 only supports Object Detection tasks.
