### ISSUE TITLE
[解決]請問訓練完後測試出來的類別不是當初設定的類別，該如何設置？

### ISSUE THREAD

**Issue by huchi00057** [meituan/YOLOv6#310]
我已更改 coco.yaml 內的 names 以及 nc。但訓練好的模型在圖片上的標記仍然是 person, car, bicycle, 就是 coco.yaml 類別的前三個。
是不是在訓練前有檔案沒有設置好呢?
求解QQ

**Comment by huchi00057** [comment]
PS.訓練的時候也有修改參數
python tools/train.py --batch 8 --conf configs/yolov6s.py --data data/colon.yaml --device 0

**Comment by khwengXU** [comment]
Thanks for your attentions！
Can you give the details of new coco.yaml?

**Comment by Rjshrivastav** [comment]
@huchi00057 
```python tools/infer.py --weights <saved model path> --source <img path>  --yaml data/colon.yaml```

**Comment by huchi00057** [comment]
Oooooops!
I think I found the CRUCIAL.
Bcz i have not modify the parameter of "--yaml", the default document is coco.yaml.
And it leaded to the results always show the classes of coco.yaml.
Thank u soooooo much!! @Rjshrivastav ❤️❤️❤️❤️

**Comment by huchi00057** [comment]
@khwengXU 
Thanks for ur attention and reply.
I think i solved it!!
Thanks a lot.💓
