### ISSUE TITLE
RuntimeError: all elements of input should be between 0 and 1

### ISSUE THREAD

**Issue by joel5638** [meituan/YOLOv6#312]
Im trying using 70 images in my train and 20 in val. The training runs fine for few epochs and throws an error. I
![Screenshot from 2022-07-12 17-35-45](https://user-images.githubusercontent.com/38422983/178486270-5c1203a6-6dde-4fd7-8548-b42d96768913.png)
m training using CPU. and my command while training for device is cpu.
If it is a CPU Ram load issue. I was successfully able to train before and this is happening from a week. Im not sure why
Im attaching the screenshot of the error. please help. Thank you.

**Comment by d5423197** [comment]
you did not set cuda properly. the training is running on cpu. This might be the reason
