### ISSUE TITLE
About Repopt.

### ISSUE THREAD

**Issue by BowieHsu** [meituan/YOLOv6#316]
If I understand correctly, the finetune of repopt needs to start from the model yolov6s_scale.pt every time, there is no way to continue finetune on the basis of an already trained repopt model.

**Comment by xingyueye** [comment]
Of course you can, if optimizer is saved in the trained repopt model. 'yolov6s_scale.pt' actually provide the scales to init optimizer.

**Comment by xingyueye** [comment]
I get what you mean, Does the conflict occurs when you set like that `'pretrained='./assets/yolov6s_opt.pt',`
It seems that transfer the scale parameter by 'pretrained' is not a good choice, I would change it.

**Comment by BowieHsu** [comment]
yes, in fact, we will frequently finetune the model based on the newly received data, this part can be written more elegantly.

**Comment by mtjhl** [comment]
> yes, in fact, we will frequently finetune the model based on the newly received data, this part can be written more elegantly.

We have update the code, please pull the latest code.

**Comment by BowieHsu** [comment]
> > yes, in fact, we will frequently finetune the model based on the newly received data, this part can be written more elegantly.
> 
> We have update the code, please pull the latest code.

cool.
