### ISSUE TITLE
训练中断，使用官方的说明 继续训练出现了错误 

### ISSUE THREAD

**Issue by wangbaoyi** [meituan/YOLOv6#318]
麻烦官方能将继续训练的文档说清楚一点，最好能运行train.py 修改
    parser.add_argument('--resume', nargs='?', const=True, default=False, help='resume the most recent training')
里面的参数就能成功训练
在线等解决方式

**Comment by Stoooner** [comment]
好巧，我也遇到这个问题，到issue中查resume的问题查到说是解决了这个bug了，结果拉取下来的代码还是有这个问题，只能一train到底，根本不敢中间停止，感觉官方的代码bug有点多诶

**Comment by wangbaoyi** [comment]
兄弟 交个朋友 我QQ1621564706  它这个问题  我刚刚重新拉取了最新的代码  解决了。哈哈

**Comment by wangbaoyi** [comment]
> 好巧，我也遇到了问题中查恢复的查到说是解决了这个bug了，导致这个问题出现的问题来的代码还是有，只能一训到底，根本中间停止，感觉官方的代码bug有点多诶
重新拉取代码就解决了

**Comment by mtjhl** [comment]
> 麻烦官方能将继续训练的文档说清楚一点，最好能运行train.py 修改
> parser.add_argument('--resume', nargs='?', const=True, default=False, help='resume the most recent training')
> 里面的参数就能成功训练
> 在线等解决方式

您好，麻烦贴一下 resume 的报错信息可以吗？

**Comment by wangbaoyi** [comment]
啊这。，。这个问题我已经拉取你们最新分支的代码得到了解决。。。
