### ISSUE TITLE
Why is the IOU_LOSS as nan?

### ISSUE THREAD

**Issue by joel5638** [meituan/YOLOv6#319]
Im training with 69 images and 10 images for testing. Im trainng on my local pc.

im using python3 tools/train.py --batch 1 --conf configs/yolov6s.py --data data/dataset.yaml --device 0

Im getting iou_loss as nan as shown in the picture im sharing.
![Screenshot from 2022-07-13 13-17-41](https://user-images.githubusercontent.com/38422983/178680174-9f0ede2f-2453-45b7-88cd-1ce10a929698.png)

**Comment by joel5638** [comment]
@qinhao14 where do i add that? right in the function?

**Comment by qinhao14** [comment]
@joel5638 YOLOv6/yolov6/utils/figure_iou.py  class IOUloss: 
![image](https://user-images.githubusercontent.com/108449966/178697395-9f272248-8ae7-47d4-8b5b-a3363a22e7ad.png)

**Comment by mtjhl** [comment]
Yes, in you screenshot, it shows `Final number of valid images: 69 / labels:69`.
