### ISSUE TITLE
how to use it with tensorrt?

### ISSUE THREAD

**Issue by xinsuinizhuan** [meituan/YOLOv6#32]
tensorrt two ways：
1、as the https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5
     pt->wts->tensorrt
     i try the pt convert to wts use the gen_wts.py，but false, with error: AttributeError: 'Model' object has no attribute 'model'
     could provide the way to convert?
2、as the shouxieai:
     pt->onnx->trt
     i am trying....

**Comment by triple-Mu** [comment]
I think it will be ok.
Pt -> Onnx -> trt is the most easy way for building engine

**Comment by xinsuinizhuan** [comment]
> I think it will be ok. Pt -> Onnx -> trt is the most easy way for building engine

I try it, pt->onnx->trt conver is ok. But when use tensorrt load the trt model, it break.

**Comment by triple-Mu** [comment]
> > I think it will be ok. Pt -> Onnx -> trt is the most easy way for building engine
> 
> I try it, pt->onnx->trt conver is ok. But when use tensorrt load the trt model, it break.

Don't warry!
It seems like the onnx have some error node or somethings else.
You can clone my code from https://github.com/triple-Mu/YOLOv6/tree/patch-1 and use cmd
``` shell
python3 deploy/ONNX/export_onnx.py  --weights yolov5s.pt --simplify --device cpu
```
After onnxsim the onnx you export will be safety for tensorrt parser

**Comment by xinsuinizhuan** [comment]
> > > I think it will be ok. Pt -> Onnx -> trt is the most easy way for building engine
> > 
> > 
> > I try it, pt->onnx->trt conver is ok. But when use tensorrt load the trt model, it break.
> 
> Don't warry! It seems like the onnx have some error node or somethings else. You can clone my code from https://github.com/triple-Mu/YOLOv6/tree/patch-1 and use cmd
> 
> ```shell
> python3 deploy/ONNX/export_onnx.py  --weights yolov5s.pt --simplify --device cpu
> ```
> 
> After onnxsim the onnx you export will be safety for tensorrt parser

I try it， but also break.

**Comment by Linaom1214** [comment]
> 
this is my repo mybe help you 
https://github.com/Linaom1214/tensorrt-python
