### ISSUE TITLE
Is there a way to change model_fitness similar to YOLOv5 so you can increase recall or precision?

### ISSUE THREAD

**Issue by sarmientoj24** [meituan/YOLOv6#323]

**Comment by mtjhl** [comment]
Did you mean how to increase the model's depth and width? If it is, you can change the `depth_multiple` and  `width_multiple` here:
https://github.com/meituan/YOLOv6/blob/ccf8b43e0ec575c2ee7b6e035e5ccb0f1512c4c8/configs/yolov6_tiny.py#L5

**Comment by Chilicyy** [comment]
@sarmientoj24 Thanks for your attention! Currently we don't support this feature.  We will consider your suggestion and add it in subsequent releases.
