### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)   help

### ISSUE THREAD

**Issue by yuanzhougege** [meituan/YOLOv6#327]
![image](https://user-images.githubusercontent.com/92565074/178937023-59fd36e5-9c98-46b7-a2db-5b098c4d2dc8.png)

请问这是什么情况我的数据集都是好的呀
![image](https://user-images.githubusercontent.com/92565074/178937361-0e57d45c-28b5-4b6c-9880-048e88eb0ba5.png)

![image](https://user-images.githubusercontent.com/92565074/178937384-d6d3ea25-8edc-44fa-876f-a3995a6700b5.png)

![image](https://user-images.githubusercontent.com/92565074/178937440-d7ff4c89-08f3-486a-a8fe-0ab548106677.png)

标签也是好的呀 之前报错以为是图片太大缘故，后来切割图片后还是报错是为什么

**Comment by shensheng272** [comment]
你好，日志看起来使用的命令是  "python tools/train.py" 吗？  应在训练命中中指定对应的数据集参数
例如
python tools/train.py --batch 256 --conf configs/yolov6s_finetune.py --data data/data.yaml --device 0
可以参考
https://github.com/meituan/YOLOv6/blob/main/docs/tutorial_voc.ipynb
以及
https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md

**Comment by yuanzhougege** [comment]
> 你好，日志看起来使用的命令是 "python tools/train.py" 吗？ 应在训练命中中指定对应的数据集参数 例如 python tools/train.py --batch 256 --conf configs/yolov6s_finetune.py --data data/data.yaml --device 0 可以参考 https://github.com/meituan/YOLOv6/blob/main/docs/tutorial_voc.ipynb 以及 https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md


这些参数我已经在代码里设置好了 还是报错呀 怎么回事/(ㄒoㄒ)/~~

**Comment by shensheng272** [comment]
> 

日志看起来应该是路径下没有找到图片，是否是图片的后缀比较特别，之前有修复过tif图片后缀的问题。
不好意思这里回复不一定及时。可以加微信  MTtech04 回复 YOLOv6 进微信群
