### ISSUE TITLE
在PC上测试的比较准，但是发现量化之后位置就会存在较大的偏差，会不会是因为backbone参数重组的原因？

### ISSUE THREAD

**Issue by LYHTZHANGJIANG** [meituan/YOLOv6#329]

**Comment by mtjhl** [comment]
我们刚提交了最新的 [量化代码](https://github.com/meituan/YOLOv6/tree/main/tools/partial_quantization), 可以基本解决 RepVGG结构量化化带来的问题。请拉取最新的代码。

**Comment by LYHTZHANGJIANG** [comment]
![image](https://user-images.githubusercontent.com/49071179/179193763-ff254407-55fd-42a9-af6b-3f122b7a2347.png)
这里的model的参数有float32、float16、int型，然后image不管是什么类型的都推理不过的呀？

**Comment by LYHTZHANGJIANG** [comment]
![image](https://user-images.githubusercontent.com/49071179/179197955-b4c8f2c7-7941-4cc6-89e0-265ba9db50dd.png)
这里的model 的参数的精度是混合的，但是images是float,这样推理会报错

**Comment by serser** [comment]
运行环境（gpu/cpu，torch， tensorrt etc.）和脚本辛苦给一下，另外报错信息也贴一下？
