### ISSUE TITLE
Since it is an industrial application, if it is deployed on C++! with training?

### ISSUE THREAD

**Issue by z13228604287** [meituan/YOLOv6#33]
Industrial applications or C++ C# are more mainstream

**Comment by Chilicyy** [comment]
Thanks for your attention! Do you mean deploy model on C++?

**Comment by czla** [comment]
Hi, you can refer to [TensorRT](https://github.com/Linaom1214/TensorRT-For-YOLO-Series) or [OpenCV](https://github.com/meituan/YOLOv6/tree/main/deploy/ONNX/OpenCV) to deploy YOLOv6 on C++.
