### ISSUE TITLE
removal of residual connections in inference mode

### ISSUE THREAD

**Issue by dshirron** [meituan/YOLOv6#332]
I think there is a bug in residual connections in inference.
In inferer.py, line 56:
self.model_switch(self.model, self.img_size)

model_switch is supposed to remove residual convolutions and fold them into main branch.

but since self.model is passed, looping on the modules () only finds a single module called "DetectBackend" and non of the "RepVGGBlock" is found for folding.

So line 56 should be fixed to:
self.model_switch(self.model.model, self.img_size)

**Comment by shensheng272** [comment]
Thanks for the report. fix in https://github.com/meituan/YOLOv6/pull/372
