### ISSUE TITLE
Any model for edge device?

### ISSUE THREAD

**Issue by johnnysclai** [meituan/YOLOv6#334]
I found that even I use the yolov6-nano model on my edge device (rockpi 3) it can only have 2FPS. Any suggestion how should I further reduce the model size to save the computation?

**Comment by czla** [comment]
You can try [partial_quantization](https://github.com/meituan/YOLOv6/tree/main/tools/partial_quantization)

**Comment by johnnysclai** [comment]
Thank you for your advice.
