### ISSUE TITLE
There appears to be an error in specifying the path to the dataset

### ISSUE THREAD

**Issue by NJIMAMTO** [meituan/YOLOv6#335]
Hi.

I followed the [Tutorials](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) and attempted to train on a custom dataset.
However, due to a bug in the get_imgs_labels method of TrainValDataset, I could not train successfully.

I verified that it works by rewriting the` check and load anns `part as follows.

before
```
label_dir = osp.join(
            osp.dirname(osp.dirname(img_dir)), "labels", osp.basename(img_dir)
        )
```
after
`label_dir = img_dir.replace('images','labels')`

If anyone comes up with a better algorithm, please let me know.

**Comment by yjtan118** [comment]
You can refer to my setup:
1) The custom dataset folder with images and labels folder is located inside the main yolov6 folder.
![image](https://user-images.githubusercontent.com/36371419/179438474-8da296f2-bebb-469f-83a4-6fee4801a4c1.png)

2) Then the custom dataset.yaml file is located in the main yolov6/data folder. In the custom dataset.yaml file, ensure that it's referring to the right train and val images folder location
![image](https://user-images.githubusercontent.com/36371419/179438441-b2b9f4fd-931d-43d6-a6a4-13121899bc4a.png)

3) when you run the train.py, i run it from the main yolov6 folder.

**Comment by NJIMAMTO** [comment]
Oops.
I think I may have figured out why it is not working as expected.
I had added / to the end of the path specification in the yaml file.
I removed this and verified that it works with the existing code.
