### ISSUE TITLE
Potential source of bug

### ISSUE THREAD

**Issue by Arunavameister** [meituan/YOLOv6#336]
Hello, firstly, thank you for your wonderful work.

I would like to point out a potential source of bug.
In datasets.py, check_image(im_file) method, 
the line im_exif = im._getexif() is inside the try block and it generates 'shape' error for me(I am using png images for training).
I think depending on the version of Pillow(it is not specified in the requirements.txt), the _getexif() method may or may not work and can throw errors and it should be handled properly.
To run the training, I comment out the following part to make it work.

> im_exif = im._getexif()
> if im_exif and ORIENTATION in im_exif:
>      rotation = im_exif[ORIENTATION]
>      if rotation in (6, 8):
>          shape = (shape[1], shape[0])

Hopefully, you find this information useful.

**Comment by shensheng272** [comment]
Thanks for the report.
Could you provide the pillow version which is not working.
And is all png img will failed?
We need those infos to reproduce the bug.
Thanks

**Comment by Zephyr69** [comment]
Is it actually _getexif() causing the error (check if commenting im.verify() works)? If it's the latter that is actually responsible, this issue has existed since the dawn of this repo.

**Comment by Arunavameister** [comment]
Hello, sorry for the late response. It was indeed not working for any of the .png images.
@shensheng272  The Pillow version I am using is '8.2.0'.
@Zephyr69 You are right! removing the im.verify() indeed solved the problem. I didnt know that the _getexif() method has to be run right after opening the image. 
Can you explain what's going on? I will close the issue.

**Comment by Zephyr69** [comment]
> Hello, sorry for the late response. It was indeed not working for any of the .png images. @shensheng272 The Pillow version I am using is '8.2.0'. @Zephyr69 You are right! removing the im.verify() indeed solved the problem. I didnt know that the _getexif() method has to be run right after opening the image. Can you explain what's going on? I will close the issue.

Nah idk what's going on either; it doesn't work for my pngs too. Since ommenting im.verify doesn't seem to break anything, I'm fine with that currently.
