### ISSUE TITLE
😱How to print the TP,FP,FN,TN in the terminal?😱

### ISSUE THREAD

**Issue by huchi00057** [meituan/YOLOv6#337]

**Comment by Zephyr69** [comment]
They didn't implement their own metrics calculation methods like yolov5 but used pycocotools. You may check pycocotools repo to see what modifications are needed.

**Comment by mtjhl** [comment]
Hi, to the best of my knowledge, there are no definitions of FN and TN in object detection.

**Comment by shensheng272** [comment]
Lastest version support print metric on certain det conf and draw confusion matrix. Most metric use precision and recall, not tp fo tn fn.
