### ISSUE TITLE
__init__() got an unexpected keyword argument 'data_dict'

### ISSUE THREAD

**Issue by aizim** [meituan/YOLOv6#339]
Hello,I have follow the [](https://github.com/meituan/YOLOv6/issues/298 issue) for my  train.But could not resume my train.
i getting below error:
Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main(args)
  File "tools/train.py", line 103, in main
    trainer = Trainer(args, cfg, device)
  File "C:\Users\ASUS\Desktop\yolov6\YOLOv6-main\yolov6\core\engine.py", line 44, in __init__
    self.train_loader, self.val_loader = self.get_data_loader(args, cfg, self.data_dict)
  File "C:\Users\ASUS\Desktop\yolov6\YOLOv6-main\yolov6\core\engine.py", line 225, in get_data_loader
    train_loader = create_dataloader(train_path, args.img_size, args.batch_size // args.world_size, grid_size,
  File "C:\Users\ASUS\Desktop\yolov6\YOLOv6-main\yolov6\data\data_load.py", line 41, in create_dataloader
    dataset = TrainValDataset(
TypeError: __init__() got an unexpected keyword argument 'data_dict'

data_load.py, line 41, in create_dataloader:
![1](https://user-images.githubusercontent.com/79129282/179447243-ea43781b-1bb2-47f9-a946-6c6497bd47a8.png)

engine.py, line 225, in get_data_loader
![2](https://user-images.githubusercontent.com/79129282/179447518-7e395a13-5954-4e81-bb5a-8bc2a756ba98.png)

engine.py, line 44, in __init__
![3](https://user-images.githubusercontent.com/79129282/179447596-1b54ebcb-8d0f-4e31-9a0b-46c5092f82f3.png)

**Comment by aizim** [comment]
thanks all.

**Comment by mtjhl** [comment]
Hi, it looks like `TypeError: init() got an unexpected keyword argument 'data_dict'` is not related to resume.
You can have a look at https://github.com/meituan/YOLOv6/blob/979151f0e0c9c765e223c8ddc3ee85c0f16154ed/yolov6/data/datasets.py#L54
 in your local computer, if your local code do not have `data_dict`, then try pull the latest code.

**Comment by aizim** [comment]
> Hi, it looks like `TypeError: init() got an unexpected keyword argument 'data_dict'` is not related to resume. You can have a look at
> 
> https://github.com/meituan/YOLOv6/blob/979151f0e0c9c765e223c8ddc3ee85c0f16154ed/yolov6/data/datasets.py#L54
> 
> 
> in your local computer, if your local code do not have `data_dict`, then try pull the latest code.
Thanks. when pull the latest code have done all error.
