### ISSUE TITLE
Error during resuming training when i tried resuming from last saved checkpoints.

### ISSUE THREAD

**Issue by yuvraajj** [meituan/YOLOv6#341]
Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main(args)
  File "tools/train.py", line 103, in main
    trainer = Trainer(args, cfg, device)
  File "/content/drive/MyDrive/Projects/YOLOv6/yolov6/core/engine.py", line 63, in __init__
    self.optimizer.load_state_dict(self.ckpt['optimizer'])
  File "/usr/local/lib/python3.7/dist-packages/torch/optim/optimizer.py", line 138, in load_state_dict
    saved_groups = state_dict['param_groups']
TypeError: 'NoneType' object is not subscriptable

**Comment by mtjhl** [comment]
Hi, what's your resume command ?

**Comment by yuvraajj** [comment]
!python tools/train.py --resume runs/train/exp1/weights/best_ckpt.pt

**Comment by yuvraajj** [comment]
Did you figure out anything on this, if i am doing it wrongly, please let me know?

**Comment by mtjhl** [comment]
could you try to run this code:
```
import torch
ckpt = torch.load('/train/exp1/weights/best_ckpt.pt')
print(kept['optimizer'])
```
to check whether it is None, maybe it is because the best_ckpt.pt has been trimed, or you try to use last_ckpt.pt

**Comment by yuvraajj** [comment]
i tried using last_ckpt.pt as well but did not work?

**Comment by yuvraajj** [comment]
whether it means that, it's not possible to resume training?

**Comment by mtjhl** [comment]
> could you try to run this code:
> 
> ```
> import torch
> ckpt = torch.load('/train/exp1/weights/best_ckpt.pt')
> print(kept['optimizer'])
> ```
> 
> to check whether it is None, maybe it is because the best_ckpt.pt has been trimed, or you try to use last_ckpt.pt

Did you try those commands?

**Comment by CuongTranXuan** [comment]
Hi @mtjhl, I have exactly the same problem, when I run those command, I got this: 
`>>> print(ckpt['optimizer'])
None`

**Comment by yuvraajj** [comment]
> 

yeah, that returns None

**Comment by mohamed19871988** [comment]
I have got the same error for the load of optimizer and the ema 
is it possible to resume training or we should train with initial weights?

**Comment by diplomatist** [comment]
same problem！Has anyone solved it?

**Comment by lucienwang1009** [comment]
See #368 
The optimizer's state was stripped after the training loop. An alternative is to use `pretrained` arg in the config file to fine-tune the last weights.

**Comment by yuvrajhembade** [comment]
> Hi, I met the same problem when I'd like to resume from a model that has been trained. I solved this problem by using the `pretrained` option in the config file to further fine-tune the model. See #368

What exactly did you do? Do you replace None for Pretrained with paths of new checkpoints OR something else?

**Comment by lucienwang1009** [comment]
> > Hi, I met the same problem when I'd like to resume from a model that has been trained. I solved this problem by using the `pretrained` option in the config file to further fine-tune the model. See #368
> 
> What exactly did you do? Do you replace None for Pretrained with paths of new checkpoints OR something else?

Yes! Just a workaround but works fine for my dataset.

**Comment by yuvrajhembade** [comment]
> > > Hi, I met the same problem when I'd like to resume from a model that has been trained. I solved this problem by using the `pretrained` option in the config file to further fine-tune the model. See #368
> > 
> > 
> > What exactly did you do? Do you replace None for Pretrained with paths of new checkpoints OR something else?
> 
> Yes! Just a workaround but works fine for my dataset.

How does this a concern with the dataset? It about optimizer
>>> print(ckpt['optimizer']) 
None

**Comment by lucienwang1009** [comment]
> > > > Hi, I met the same problem when I'd like to resume from a model that has been trained. I solved this problem by using the `pretrained` option in the config file to further fine-tune the model. See #368
> > > 
> > > 
> > > What exactly did you do? Do you replace None for Pretrained with paths of new checkpoints OR something else?
> > 
> > 
> > Yes! Just a workaround but works fine for my dataset.
> 
> How does this has a concern with the dataset? It's about optimizer
> 
> > > > print(ckpt['optimizer'])
> > > > None

Yes, you're right. It concerns the optimizer. When using this workaround, the optimizer will be re-initialized. It might screw up the SGD process.  But on my dataset, it works well.

**Comment by yuvrajhembade** [comment]
So you mean to this issue is Dataset Specific?

**Comment by lucienwang1009** [comment]
No, I think it is a missing feature that allows someone to resume the training already finished. What I talked about was just a workaround that might cause some unintentional problems. You can try it on your task and see if the training process goes well (the loss declines and metrics improves).
