### ISSUE TITLE
Multiple GPU command doesn't work on colab?

### ISSUE THREAD

**Issue by yuvraajj** [meituan/YOLOv6#342]
This is command i used
!python -m torch.distributed.launch --nproc_per_node 4 tools/train.py --batch 4 --conf configs/yolov6s_finetune.py --data data/dataset.yaml --device 0,1,2,3
Getting error
Initializing process group... 
Added key: store_based_barrier_key:1 to store for rank: 0
Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main(args)
  File "tools/train.py", line 96, in main
    torch.cuda.set_device(args.local_rank)
  File "/usr/local/lib/python3.7/dist-packages/torch/cuda/__init__.py", line 314, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal

**Comment by mtjhl** [comment]
I am not familiar with colab, I search it google, may those information help you?
https://stackoverflow.com/questions/65142518/more-than-one-gpu-in-google-colab

**Comment by yuvraajj** [comment]
yeah colab doesn't support multi 
GPU training.
