### ISSUE TITLE
no attribute 'python_exit_status';'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by stringk245** [meituan/YOLOv6#343]
# error
- 发现只要加了 --resume 迭代训练，迭代训练就会中断报错，无法迭代训练
- 不加--resume 迭代训练，迭代训练正常，训练模型能保存成功，但是最后日志会报python_exit_status，可加 --workers 0 解决
```text
no attribute 'python_exit_status'
```
## env
```text
python=3.7.9
torch==1.10.0+cu102
torchaudio==0.10.0+rocm4.1
torchvision==0.11.0+cu102
```
## cmd
```bash
python tools/train.py --batch-size 32 --img-size 640 --epochs 10 --device 0,1  --output-dir runs/train \
--data-path coco128.yaml  --conf-file configs/yolov6s.py --workers 0 --resume yolov6s.pt
```

# error
- 发现只要加了 --resume 迭代训练，迭代训练就会中断报错，无法训练
```text
'NoneType' object is not subscriptable
```
## env
```text
python=3.8.13
torch==1.8.0+cu111
torchaudio==0.8.0
torchvision==0.9.0+cu111

```

**Comment by yuvraajj** [comment]
Hey Man but how to resolve the error?

**Comment by yuvraajj** [comment]
Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main(args)
  File "tools/train.py", line 103, in main
    trainer = Trainer(args, cfg, device)
  File "/content/drive/MyDrive/Projects/YOLOv6/yolov6/core/engine.py", line 63, in __init__
    self.optimizer.load_state_dict(self.ckpt['optimizer'])
  File "/usr/local/lib/python3.7/dist-packages/torch/optim/optimizer.py", line 159, in load_state_dict
    saved_groups = state_dict['param_groups']
TypeError: 'NoneType' object is not subscriptable

**Comment by mtjhl** [comment]
Are you resuming from the checkpoint we provided on this repo's home page?  The model we provided does not have the optimizer weights. If you want fine-tuning , you can add the model path here.
https://github.com/meituan/YOLOv6/blob/979151f0e0c9c765e223c8ddc3ee85c0f16154ed/configs/yolov6s_finetune.py#L4

**Comment by stringk245** [comment]
> pretrained
![1658195764775](https://user-images.githubusercontent.com/11296126/179647384-3bd22cf3-af0b-48b2-bd8c-cbbfa0d2c94e.jpg)

**Comment by stringk245** [comment]
![image](https://user-images.githubusercontent.com/11296126/179651477-b1251df8-fd78-4504-9b33-7d036eebb4ad.png)
```bash
python tools/train.py --batch-size 32 --img-size 640 --epochs 5 --device 0,1  --output-dir runs/train \
--data-path coco128.yaml  --conf-file configs/yolov6s_finetune.py

```
1. 如果 torch >=1.10.0 ,需要加上 --workers 0   参数，否则最后保存模型时日志会报python_exit_status,不影响训练和保存模型
2. 迭代训练不要使用 --resume 参数指定模型，应该修改configs/yolov6s_finetune.py文件中的pretrained=yolov6s.pt

**Comment by yuvraajj** [comment]
Have made changes in yolov6s_finetune.py but still there is the same error.

**Comment by Chilicyy** [comment]
@yuvraajj Hi, we have fixed the bug when resuming training. You could train the model again.
