### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by gfdegsfgsfgsf** [meituan/YOLOv6#344]

**Comment by mtjhl** [comment]
您是用 CPU 训练吗，试一下加上 `--device cpu`命令

**Comment by gfdegsfgsfgsf** [comment]
GPU训练

**Comment by gfdegsfgsfgsf** [comment]
我这里做了一个小测试，
![image](https://user-images.githubusercontent.com/109531452/179636560-d67d2c4d-6eb4-40fc-a2f5-abfad5b064fb.png)
cuda是能正常使用的，但是我在yolov6/utils/envs.py文件夹的第32行，打印torch.cuda.is_available()，发现结果是false。
![image](https://user-images.githubusercontent.com/109531452/179636748-37c65de5-2f8d-4629-9e95-defb7394ceb8.png)
![image](https://user-images.githubusercontent.com/109531452/179636765-beaa7127-d3a7-4c67-bf81-8531ab7045a6.png)

**Comment by gfdegsfgsfgsf** [comment]
我这边的实验环境是
torch：1.10.1
GPU：name='NVIDIA GeForce RTX 3060 Ti', major=8, minor=6, total_memory=8191MB, multi_processor_count=38)
cuda：11.3

**Comment by gfdegsfgsfgsf** [comment]
所以，我这边暂时得出一个结论，实验环境为：
torch：1.10.1，
GPU：RTX 3060 Ti 8G，
cuda：11.3。
能跑通YOLOv5 6.0框架，但是在YOLOv6框架下，使用GPU时无法运行，会报错（CPU没问题）。报错原因是torch.cuda.is_available()的结果为False且不能打印出GPU的信息。
![image](https://user-images.githubusercontent.com/109531452/179637991-dfac89e3-a23b-4de7-9ecc-4fd35498a967.png)

**Comment by gfdegsfgsfgsf** [comment]
感觉是YOLOv6框架本身的问题，与实验环境无关。

**Comment by shensheng272** [comment]
可以发下   pip list， which python的结果吗？

**Comment by gfdegsfgsfgsf** [comment]
![image](https://user-images.githubusercontent.com/109531452/179683999-ae5a6c6c-4174-4b4a-a18b-9502b72ccc24.png)
![image](https://user-images.githubusercontent.com/109531452/179684053-ab191af3-b82b-422a-8adb-cd521ac24952.png)
![image](https://user-images.githubusercontent.com/109531452/179684219-b1a2994b-1f2c-4f38-a63a-742db9749116.png)

**Comment by gfdegsfgsfgsf** [comment]
用的win10系统，安装路径E:\anaconda\envs\pytorch，python 3.9.9

**Comment by Zephyr69** [comment]
看你这个piplist，没装gpu版本的torch。你注意过跑yolov5时有调用cuda吗？

**Comment by gfdegsfgsfgsf** [comment]
![image](https://user-images.githubusercontent.com/109531452/179694301-4537da93-c958-42b3-8799-195304b1c805.png)
是这样吗？YOLOv5 console输出了YOLOv5  2021-10-12 torch 1.10.1 CUDA:0 (NVIDIA GeForce RTX 3060 Ti, 8191.5MB)。
![image](https://user-images.githubusercontent.com/109531452/179694468-0d4c2475-b381-42a3-b7f3-be49712a1f09.png)

**Comment by gfdegsfgsfgsf** [comment]
![image](https://user-images.githubusercontent.com/109531452/179695237-c9b6ef2d-e137-40b6-9b88-417d035e3b0f.png)

**Comment by gfdegsfgsfgsf** [comment]
![image](https://user-images.githubusercontent.com/109531452/179696601-2c9fd18f-0e93-40b8-a33e-4ae8d539b547.png)
