### ISSUE TITLE
Encountered some issue when converting to ONNX

### ISSUE THREAD

**Issue by charlieguo0610** [meituan/YOLOv6#348]
Hi,
I'd like to report an issue with converting from torch to onnx. The below listed shows the prompted error message when saving the onnx file.
<img width="927" alt="image" src="https://user-images.githubusercontent.com/48096429/179766354-2c6d9055-fb02-46c8-bccf-b2a51777399d.png">
Even if the onnx model is successfully saved, when I tried to run python tools/eval.py --data data/coco.yaml --batch 32 --weights yolov6s.onnx --task val --device cpu, the program crashed and it shows an error message as follows.
<img width="920" alt="image" src="https://user-images.githubusercontent.com/48096429/179766720-0a6fc923-613e-4c2c-8572-9f2dd2a18d1a.png">
Please help me with solving this problem. Thank you in advance!

**Comment by Hyrtsi** [comment]
Your upper image shows a warning, not an error. A warning is just a warning.

Could you try running `eval.py` with pytorch model instead of onnx model? It's not meant to be ran with an onnx model.

**Comment by charlieguo0610** [comment]
Hi, the PyTorch model can be successfully executed. However, the onnx model does not work. Is there any way to run with onnx model?

**Comment by Hyrtsi** [comment]
Could you please elaborate what you have tried
- Your system specs
- The exact commands you used for installation
- The exact commands you used for running the code

and could you please elaborate what does it mean that "the onnx model does not work"? Thank you.

**Comment by shensheng272** [comment]
For now, `python tools/eval.py` only support pt weights.
To run onnx as infer, you might export onnx with `--end2end `, then try onnxruntime or other supported [onnx](https://github.com/onnx/onnx) backend.
If you convert onnx to trt, the trt engine eval script is [eval_trt.py](https://github.com/meituan/YOLOv6/blob/main/deploy/ONNX/eval_trt.py)
