### ISSUE TITLE
How to reproduce the results

### ISSUE THREAD

**Issue by yurkovak** [meituan/YOLOv6#349]
Hi! Thank you for your work. I'm trying to reproduce your results and I get the following mismatch:

Model | Resolution  | mAP<sup>val<br/>0.5:0.95 | mAP<sup>val<br/>0.5:0.95 reproduction
-- | -- | -- | --
YOLOv6-n | 640 | 35.0 | **34.7**
YOLOv6-tiny | 640 | 41.3 | 41.4
YOLOv6-s | 640 | 43.1 | **42.6**

As you can see, Nano and Small models don't reproduce. I used 
```shell
python -m torch.distributed.launch --nproc_per_node 4 tools/train.py --batch 256 --conf configs/yolov6n.py --data data/coco.yaml --device 0,1,2,3
```
for Nano (4, GPUs) and 
```shell
python -m torch.distributed.launch --nproc_per_node 8 tools/train.py --batch 256 --conf configs/yolov6s.py --data data/coco.yaml --device 0,1,2,3,4,5,6,7
```
for Small (8 GPUs).

In both cases, this is the batch size and configs you mention in the README. Is there something else I should do to get your result?
Thanks in advance!

**Comment by shensheng272** [comment]
Hi, thanks for reproduce exp.
You might try --batch 128 for n and s. 0.2~0.3% gap is normal because of random seed.

**Comment by hhaAndroid** [comment]
I train with the same result. mAP is 42.6

**Comment by shensheng272** [comment]
New models and scripts for reproducing train/val result are available now. More info in [readme](https://github.com/meituan/YOLOv6/blob/main/README.md). 
By the way, we publish result on different test scheme comparing to yolov5/yolov7. Still you could compare eval result in training whose test scheme is same to yolov5/yolov7. AP result of two test scheme actually quite close to each other .
