### ISSUE TITLE
 [NVIDIA] [CUDA] [SOLVED] Warning: NVIDIA GeForce RTX Laptop GPU with CUDA capability sm_86 is not compatible

### ISSUE THREAD

**Issue by Hyrtsi** [meituan/YOLOv6#350]
Greetings,

If you get this error

```
.venv/lib/python3.7/site-packages/torch/cuda/__init__.py:146: UserWarning: 
NVIDIA GeForce RTX 3080 Laptop GPU with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3080 Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
```

you need to do the following after installing the dependencies:

```
pip install torch==1.12.0+cu116 torchvision==0.13.0+cu116 -f https://download.pytorch.org/whl/torch_stable.html
```

## Explanation

If you try to run pytorch modules using a Nvidia GPU and CUDA, you need to install `pytorch` packages with appropriate CUDA version.

Meaning: if you have CUDA 11.6, you need to install `torch==x.y.z+cu116`. You can see the support matrix [here](https://download.pytorch.org/whl/torch_stable.html) (kind of).

Check which CUDA version you have:

```
nvidia-smi

| NVIDIA-SMI 515.48.07    Driver Version: 515.48.07    CUDA Version: 11.7     |
```

Then, ctrl+f [here](https://download.pytorch.org/whl/torch_stable.html) your CUDA version. You will see that for example CUDA 11.7 isn't there. But CUDA 11.6 versions of the wheel packages works fine if you're using CUDA 11.7.

Then, check the appropriate `torch`,`torchvision` and `torchaudio` versions supported for your CUDA version and download accordingly like in my command above. I hope this helps you if you run into the same problem.

## Extra info

I have Nvidia RTX 3080, Ubuntu 20.04, Python 3.7 virtual environment (venv) and CUDA 11.7.

**Comment by shensheng272** [comment]
Thanks for the issue.
