### ISSUE TITLE
AttributeError: 'Trainer' object has no attribute 'vis_imgs_list'

### ISSUE THREAD

**Issue by thegamercoder19** [meituan/YOLOv6#355]
I found new issue: after yolov6/core/engine.py was updated, now after one training step it shows an error which is in attached screenshot.
![Screenshot 2022-07-21 180740](https://user-images.githubusercontent.com/60265838/180234157-83a11566-266b-4c0d-af9c-e0802cb201cd.png)

**Comment by mtjhl** [comment]
Sorry for the inconvenience, we fixed this bug, please pull the latest code.
