### ISSUE TITLE
中国人集合

### ISSUE THREAD

**Issue by baifeng-gcu** [meituan/YOLOv6#36]

**Comment by Hunter-Bo** [comment]
可以发中文了？

**Comment by sunbinbin1991** [comment]
为啥这个可以叫yolov6 而不是v5plus？

**Comment by baifeng-gcu** [comment]
> 为啥这个可以叫yolov6 而不是v5plus？
可能因为他引用了transform

**Comment by baifeng-gcu** [comment]
> 为啥这个可以叫yolov6 而不是v5plus？

我们开发了专门针对工业应用的算法，并在YOLO系列工作的基础上做了一些改进。 因此，我们将项目命名为 YOLOv6 以向 YOLO 系列的作品致敬。

 实际上，该项目的全称是MT-YOLOv6，为了简洁，我们称之为YOLOv6。

 对于该项目，我们将继续完善和维护，为工业应用贡献更多价值。

原文  We developd the algorithm dedicated to industrial applications, and made some improvements based on the work of the YOLO series. Therefore, we named the project YOLOv6 to pay tribute to the work of YOLO series.
Actually, the full name of the project is MT-YOLOv6, and we call it YOLOv6 for brevity.
As for the project, we'll continue to improve and maintain it, contributing more values for industrial applications.

**Comment by LvShuaiChao** [comment]
> > 为啥这个可以叫yolov6 而不是v5plus？
> 
> 我们开发了专门针对工业应用的算法，并在YOLO系列工作的基础上做了一些改进。 因此，我们将项目命名为 YOLOv6 以向 YOLO 系列的作品致敬。
> 
> 实际上，该项目的全称是MT-YOLOv6，为了简洁，我们称之为YOLOv6。
> 
> 对于该项目，我们将继续完善和维护，为工业应用贡献更多价值。
> 
> 原文 We developd the algorithm dedicated to industrial applications, and made some improvements based on the work of the YOLO series. Therefore, we named the project YOLOv6 to pay tribute to the work of YOLO series. Actually, the full name of the project is MT-YOLOv6, and we call it YOLOv6 for brevity. As for the project, we'll continue to improve and maintain it, contributing more values for industrial applications.

请问这段文字来自于何处？YOLOv6发论文了吗？

**Comment by wqh17101** [comment]
> 我们开发了专门针对工业应用的算法，并在YOLO系列工作的基础上做了一些改进。 因此，我们将项目命名为 YOLOv6 以向 YOLO 系列的作品致敬。
> 
> 实际上，该项目的全称是MT-YOLOv6，为了简洁，我们称之为YOLOv6。
> 
> 对于该项目，我们将继续完善和维护，为工业应用贡献更多价值。

愿景是好的，但是这个项目的license是商业不友好的GPL，这意味着合规的产品在使用这个款软件时必须采用进程隔离或者开源使用到这款软件的产品自己代码，后续推广难度很高

**Comment by monkeycc** [comment]
YOLOv6 命名肯定有质疑的
不管官方给出什么所谓的理由和原因

然后国内唯一深度学习框架是使用 [GPL-3.0 license]
自己的项目不能商业化   必须开源
不然美团律师就能找你罚钱

**Comment by zhiqwang** [comment]
GNU General Public License v3.0
![image](https://user-images.githubusercontent.com/4210061/176076433-642924a8-2300-464b-8d65-fcfc6bce2140.png)

**Comment by m00nLi** [comment]
比旷视的“YOLOX”更无耻哈

**Comment by Shimada666** [comment]
为了简洁你们该用 molo，就像 mafka

**Comment by buxihuo** [comment]
@baifeng-gcu 感觉GitHub中文越来越多了，我要把我的项目名字改为CN-YOLO🌟
