### ISSUE TITLE
LICENSE 

### ISSUE THREAD

**Issue by maxkeller321** [meituan/YOLOv6#362]
Hi Guys, 

first, I do want to say thank you for such a great work. 

We would like to test the model in our product, but the GNU GPL-3.0 license would be a problem for us. Because if we make use of the model, our product code would then also need to be licensed under GNU GPL-3.0. Of course, we can not afford this. 

I did just wonder, about the license, because the project is marketed as "Object detection for industrial applications,". Would it be possible to Switch the license from GNU GPL-3.0 to MIT or APACHE 2.0? 

Best regards, 
Max

**Comment by knoppmyth** [comment]
Hi Max,

I'm wondering why you think the model would make your product fall under the GPL. Generally, the GPL refers to the code itself and not the result of the code. 

If you took the code from YOLOv6, forked it, modified it, you'd have to make those changes available. Not the resulting model.

Just having a model in a product doesn't make the product itself fall under the GPL. If your product includes code that was originally GPL, then you'd have to make the code available.

Please note, I'm not a lawyer.

Any information you have to share would certainly be appreciated. I'm sure you're not the only one working on productizing something and want to ensure you keep the competitive edge.

Regards,
km

**Comment by Y-T-G** [comment]
Are the pretrained weights distributed under GPLv3 license too?

Can I fine-tune the pretrained model and have the fine-tune model not be GPLv3?

Different people give different answers. YOLOv5 or YOLOv8 considers any model trained to be under AGPL. YOLO-NAS considers the pretrained model to be AGPL, while trained from scratch is not.

What's YOLOv6's stance?
