### ISSUE TITLE
state_dict['param_groups'] TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by recycie** [meituan/YOLOv6#368]
Resume model got Error => TypeError: 'NoneType' object is not subscriptable

Resume training from the checkpoint file :./runs/train/exp2/weights/last_ckpt.pt
Using 1 GPU for training... 
training args are: Namespace(batch_size=32, check_images=False, check_labels=False, conf_file='configs/yolov6s.py', data_path='datasetsv6/data.yaml', device='0', dist_url='env://', epochs=400, eval_final_only=False, eval_interval=20, gpu_count=0, heavy_eval_range=50, img_size=640, local_rank=-1, name='exp', output_dir='./runs/train', rank=-1, resume='./runs/train/exp2/weights/last_ckpt.pt', save_dir='runs/train/exp2', workers=8, world_size=1)

Train: Final numbers of valid images: 2884/ labels: 2884. 
1.1s for dataset initialization.
Convert to COCO format
100% 720/720 [00:00<00:00, 122377.07it/s]
Convert to COCO format finished. Resutls saved in datasetsv6/annotations/instances_valid.json
Val: Final numbers of valid images: 720/ labels: 720. 
1.8s for dataset initialization.
Model: Model(
  (backbone): EfficientRep(
    (stem): RepVGGBlock(
      (nonlinearity): ReLU(inplace=True)
      (se): Identity()
      (rbr_dense): Sequential(
        (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      ) ................
      (2): Conv(
        (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
    )
  )
)
Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main(args)
  File "tools/train.py", line 103, in main
    trainer = Trainer(args, cfg, device)
  File "/content/drive/MyDrive/YOLOv6/yolov6/core/engine.py", line 66, in __init__
    self.optimizer.load_state_dict(self.ckpt['optimizer'])
  File "/usr/local/lib/python3.7/dist-packages/torch/optim/optimizer.py", line 159, in load_state_dict
    saved_groups = state_dict['param_groups']
TypeError: 'NoneType' object is not subscriptable

**Comment by mtjhl** [comment]
Are you resuming from a checkpoint which was already trained to the end? Currently, we will tail the checkpoint at the end of the training.  However, the checkpoints saved at the process of training have the optimizer parameters, which resume needs.
So, if you already trained the model normally, you'd better use pretrain mode.
You can configure it here: https://github.com/meituan/YOLOv6/blob/b33352c03c04bbd0e0f546809c5cf8f0424c9341/configs/yolov6s.py#L4

**Comment by yuvrajhembade** [comment]
> Are you resuming from a checkpoint which was already trained to the end? Currently, we will tail the checkpoint at the end of the training. However, the checkpoints saved at the process of training have the optimizer parameters, which resume needs. So, if you already trained the model normally, you'd better use pretrain mode. You can configure it here:
> 
> https://github.com/meituan/YOLOv6/blob/b33352c03c04bbd0e0f546809c5cf8f0424c9341/configs/yolov6s.py#L4

But What exactly you did?

**Comment by yuvrajhembade** [comment]
> > Are you resuming from a checkpoint which was already trained to the end? Currently, we will tail the checkpoint at the end of the training. However, the checkpoints saved at the process of training have the optimizer parameters, which resume needs. So, if you already trained the model normally, you'd better use pretrain mode. You can configure it here:
> > https://github.com/meituan/YOLOv6/blob/b33352c03c04bbd0e0f546809c5cf8f0424c9341/configs/yolov6s.py#L4
> 
> But What exactly you did?

Did you replace None with path of best checkpoints in run?

**Comment by mtjhl** [comment]
When the training process is done, we will trim the checkpoint, delete the optimizer and ema, so you can not resume from the final checkpoint, we can only resume from the checkpoint saved during the training process.
