### ISSUE TITLE
We need to have Confusion matrix, Precision, Recall and F1 score

### ISSUE THREAD

**Issue by norah-art** [meituan/YOLOv6#370]
Hi, 
Is there any way to calculate and show P(precision), R(recall), and F1 score, also confusion matrix as in YOLOv5 and YOLOv4.
Having them helps to evaluate and compare the current model with previous models, especially in custom data.

![image](https://user-images.githubusercontent.com/110122657/181396200-365aebd5-8b28-4426-bcaf-4e142bbd6d6d.png)
![22](https://user-images.githubusercontent.com/110122657/181396351-93742a6a-6ecd-482f-a257-cb25b47ad3b5.jpg)

Thank you,

**Comment by mtjhl** [comment]
Ok, we will consider to add those functions as soon as possible.

**Comment by norah-art** [comment]
Is there any update on that? 
If not, when can we have those functions?

**Comment by shensheng272** [comment]
Latest code will print conf on best mF1 and print P R under iou50, when eval model. Also default plot curves like yolov5. 
Also you can log infos you want near https://github.com/meituan/YOLOv6/blob/main/yolov6/core/evaler.py#L188

**Comment by norah-art** [comment]
Hi @shensheng272 
how to print the conf or at least show the result for it, I wrote the command as below but I get error
!python /content/YOLOv6/yolov6/core/evaler.py --data data/dataset.yaml --img-size 416 --weights runs/train/exp/weights/best_ckpt.pt --device 0

Traceback (most recent call last):
  File "/content/YOLOv6/yolov6/core/evaler.py", line 14, in <module>
    from yolov6.data.data_load import create_dataloader
ModuleNotFoundError: No module named 'yolov6'
