### ISSUE TITLE
所有图像都被诊断为损坏 如何操作？ tif不支持吗

### ISSUE THREAD

**Issue by hichenjuntao** [meituan/YOLOv6#379]
4000 image(s) corrupted: 100%|██████████| 40
WARNING: ../custom_dataset/images/train\1.tif: ignoring corrupt image: _getexif
WARNING: ../custom_dataset/images/train\10.tif: ignoring corrupt image: _getexif
00/4000 

....

    f"WARNING: No labels found in {osp.dirname(self.img_paths[0])}. "
AttributeError: 'TrainValDataset' object has no attribute 'img_paths'

**Comment by hichenjuntao** [comment]
使用了 新发布的yolov7可以训练 大约是yolov5的问题

**Comment by mtjhl** [comment]
不好意思，我们会及时修复这个问题。

**Comment by MTChengMeng** [comment]
> 使用了 新发布的yolov7可以训练 大约是yolov6读取图片的逻辑问题 暂时不知道哪里有错

感谢提问！这个问题已经修复了，可以拉最新版本的代码再试一下。
