### ISSUE TITLE
https://github.com/FeiGeChuanShu/ncnn-android-yolov6

### ISSUE THREAD

**Issue by nihui** [meituan/YOLOv6#38]
The yolov6 object detection
android camera realtime application by feigechuanshu

https://github.com/FeiGeChuanShu/ncnn-android-yolov6

可以把链接放在readme里~

**Comment by Baiyuetribe** [comment]
发现NCNN版与yolox一样，只需搬运yolox的代码，然后在这行代码下面加上归一化就可以正常运行
```c++
    ncnn::copy_make_border(in, in_pad, 0, hpad, 0, wpad, ncnn::BORDER_CONSTANT, 114.f);
```
```c++

    const float norm_vals[3] = {1 / 255.f, 1 / 255.f, 1 / 255.f};
    in_pad.substract_mean_normalize(0, norm_vals);
```

**Comment by tututu11** [comment]
> 

使用了ncnn，cpu占用非常高，是什么导致的呢

**Comment by tututu11** [comment]
> 发现NCNN版与yolox一样，只需搬运yolox的代码，然后在这行代码下面加上归一化就可以正常运行
> 
> ```c++
>     ncnn::copy_make_border(in, in_pad, 0, hpad, 0, wpad, ncnn::BORDER_CONSTANT, 114.f);
> ```
> 
> ```c++
>     const float norm_vals[3] = {1 / 255.f, 1 / 255.f, 1 / 255.f};
>     in_pad.substract_mean_normalize(0, norm_vals);
> ```

使用了ncnn，cpu占用非常高，是什么导致的呢

**Comment by Baiyuetribe** [comment]
还是该函数导致的，尤其是PC上，`ncnn::copy_make_border`调用了全部线程，导致CPU满负载。可以改成如下
```c++
    ncnn::Option opt;
    opt.num_threads = 1;
    ncnn::copy_make_border(in, in_pad, 0, hpad, 0, wpad, ncnn::BORDER_CONSTANT, 114.f, opt);
```
完整C++版可以参考这个[ncnn-models](https://github.com/Baiyuetribe/ncnn-models/tree/main/object_dection/yolov6)
