### ISSUE TITLE
ValueError: Using a target size (torch.Size([12, 332, 14])) that is different to the input size (torch.Size([12, 332, 9])) is deprecated

### ISSUE THREAD

**Issue by ISySRGg** [meituan/YOLOv6#382]
![Capture](https://user-images.githubusercontent.com/88493930/182091877-fd8835d8-7e3c-462e-840d-c42747cdf29b.PNG)

**Comment by mtjhl** [comment]
Did you make any change to the codes?

**Comment by ISySRGg** [comment]
> Did you make any change to the codes?

no, I just changed the custom dataset

**Comment by mtjhl** [comment]
How many classes of your dataset?
