### ISSUE TITLE
large size model

### ISSUE THREAD

**Issue by looput** [meituan/YOLOv6#385]
could the author provide  the config of  large size model?

**Comment by khwengXU** [comment]
Thanks for your attentions! We have plans to release large size models.

**Comment by looput** [comment]
@khwengXU Can you provide the configuration first? I want to train the model on my own datasets

**Comment by mtjhl** [comment]
You can increase the `depth_multiple` and `width_multiple` here.
https://github.com/meituan/YOLOv6/blob/5f00d8bf374d9f2cd01cc8ab9a4204ce37d66186/configs/yolov6s.py#L5

**Comment by looput** [comment]
Thanks for your reply, I know this works, but i want to know the best conbination of depth and width.

**Comment by mtjhl** [comment]
We are  iterative develop the model. We will release the official codes as soon as possible.

**Comment by khwengXU** [comment]
> We are planning to release large size models.
