### ISSUE TITLE
GPU Tesla T4 is available but can't use multi GPU training

### ISSUE THREAD

**Issue by yuvrajhembade** [meituan/YOLOv6#388]
FutureWarning,
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Using 4 GPU for training... 
training args are: Namespace(batch_size=5, check_images=False, check_labels=False, conf_file='configs/yolov6s_finetune.py', data_path='data/dataset.yaml', device='0,1,2,3', dist_url='env://', epochs=400, eval_final_only=False, eval_interval=20, gpu_count=0, heavy_eval_range=50, img_size=640, local_rank=0, name='exp', output_dir='./runs/train', rank=0, resume=False, save_dir='runs/train/exp9', workers=8, world_size=4, write_trainbatch_tb=False)

Initializing process group... 
Added key: store_based_barrier_key:1 to store for rank: 0
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "tools/train.py", line 115, in <module>
  File "tools/train.py", line 115, in <module>
  File "tools/train.py", line 115, in <module>
    main(args)        
main(args)main(args)  File "tools/train.py", line 97, in main

  File "tools/train.py", line 97, in main
  File "tools/train.py", line 97, in main
        torch.cuda.set_device(args.local_rank)torch.cuda.set_device(args.local_rank)

  File "/usr/local/lib/python3.7/dist-packages/torch/cuda/__init__.py", line 314, in set_device
  File "/usr/local/lib/python3.7/dist-packages/torch/cuda/__init__.py", line 314, in set_device
    torch.cuda.set_device(args.local_rank)
  File "/usr/local/lib/python3.7/dist-packages/torch/cuda/__init__.py", line 314, in set_device
        torch._C._cuda_setDevice(device)torch._C._cuda_setDevice(device)

RuntimeErrorRuntimeError: : CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 416 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 417) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 755, in run
    )(*cmd_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-08-02_05:10:56
  host      : bc8933e1947b
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 418)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2022-08-02_05:10:56
  host      : bc8933e1947b
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 419)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-08-02_05:10:56
  host      : bc8933e1947b
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 417)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by mtjhl** [comment]
Hi, what's your training command?

**Comment by yuvrajhembade** [comment]
!python -m torch.distributed.launch --nproc_per_node 4 tools/train.py --batch 5 --conf configs/yolov6s_finetune.py --data data/dataset.yaml --device 0,1,2,3

**Comment by mtjhl** [comment]
Are you sure you really used this command? Change `--batch 5` to `--batch-size 32` and `--conf ` to `--conf-file`, please paste the command you really use.

**Comment by yuvrajhembade** [comment]
Hey man, why should I lie? I have 45 images to train so I made batches of 5 to run 9 iterations in each epoch, why this should have a concern multi GPU training?

![image](https://user-images.githubusercontent.com/109716107/182317657-ff938f78-4890-4841-b39d-bc0d6d571cb1.png)

**Comment by Zephyr69** [comment]
Make batchsize a multiple of gpu count and see if it works.

**Comment by mtjhl** [comment]
Can it run normally in single gpu?

**Comment by yuvrajhembade** [comment]
yes it runs for a single GPU.
