### ISSUE TITLE
how to get mAP

### ISSUE THREAD

**Issue by ISySRGg** [meituan/YOLOv6#391]
how to view mAP results. all classes and every class

**Comment by mtjhl** [comment]
Actually, pycocotools contains AP for each class. You can refer to [this](https://stackoverflow.com/questions/56247323/coco-api-evaluation-for-subset-of-classes), we will consider to add the function to print AP for each class later.

**Comment by ISySRGg** [comment]
thank you. can we see the graph in yolov6 F1-Curve, P-Curve, PR-Curve, R-Curve ?

> Actually, pycocotools contains AP for each class. You can refer to [this](https://stackoverflow.com/questions/56247323/coco-api-evaluation-for-subset-of-classes), we will consider to add the function to print AP for each class later.
