### ISSUE TITLE
Annotations Matter???????

### ISSUE THREAD

**Issue by yuvrajhembade** [meituan/YOLOv6#393]
I mean to say that if the annotation has a sequence in the classes file with 0, 1, 2, as class numbers & then in annotation file of respective images will have a class number followed by normalized coordinates of bounding boxes.
Does it matters for accuracy if we randomly annotate any class amongst three in any sequence?  
i.e in this way,
0 class ------bbox
1 class ------bbox
0 class ------bbox
0 class ------bbox
2 class ------bbox
2 class ------bbox
1 class ------bbox
0 class ------bbox
2 class ------bbox
2 class ------bbox
1 class ------bbox

OR we should keep classs annotations in desired sequence? like,
0 class ------bbox
0 class ------bbox
0 class ------bbox
0 class ------bbox
1 class ------bbox
1 class ------bbox
1 class ------bbox
2 class ------bbox
2 class ------bbox
2 class ------bbox
2 class ------bbox

**Comment by czla** [comment]
Hi, changing row order within an label file doesn't affect the accuracy.

See also:
> One image corresponds to one label file, and the label format example is presented as below.
> 
> ```json
> # class_id center_x center_y bbox_width bbox_height
> 0 0.300926 0.617063 0.601852 0.765873
> 1 0.575 0.319531 0.4 0.551562
> ```
> 
> 
> - Each row represents one object.
> - Class id starts from `0`.
> - Boundingbox coordinates must be in normalized `xywh` format (from 0 - 1). If your boxes are in pixels, divide `center_x` and `bbox_width` by image width, and `center_y` and `bbox_height` by image height.

**Comment by yuvrajhembade** [comment]
OK, Thank You.
