### ISSUE TITLE
no eachClass Precision, Recall

### ISSUE THREAD

**Issue by chenlei76** [meituan/YOLOv6#394]

**Comment by chenlei76** [comment]
Dear YOLOv6 team,

I am using your work. I just used eval.py and found that there is no Precision, Recall to each class? Can you support them? 

Thanks.

**Comment by mtjhl** [comment]
Hi, we will consider to add the function as soon as possible.

**Comment by Chilicyy** [comment]
hi @chenlei76 , we have supported this feature currently. Please git pull the latest code and set the params - verbose=True during evaluation. More details can be found in https://github.com/meituan/YOLOv6/pull/442/commits/96a61ee33d989bf0f545433e78e92f05f5bd4d9d.
