### ISSUE TITLE
pip install pycocotools>=2.0 error on windows

### ISSUE THREAD

**Issue by oki-aryawan** [meituan/YOLOv6#395]
I tried to install pycocotools with my pip 
```
pip install pycocotools>=2.0
```
the the output:
```
Failed to build pycocotools
ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects
```
can anyone help me with this one? thank's

**Comment by HaojieYuu** [comment]
pycocotools does not support windows, try:
`pip install pycocotools-windows`

**Comment by oki-aryawan** [comment]
Okay thanks, it's work. Thank you
