### ISSUE TITLE
Disable labeled photo on the screen by cv2 

### ISSUE THREAD

**Issue by ahmetburakgozel** [meituan/YOLOv6#398]
When I run "python tools/infer.py --weights yolov6s.pt --source C:\Users\ahmtb\Downloads\train_set" all the photos in the file are tagged. And it opens and closes sequentially on the screen. Then the command ends. I don't know how I made a change and this happened? Can you help me?

**Comment by mtjhl** [comment]
Sorry, I didn't  get your question.  What's your demand?
