### ISSUE TITLE
更简洁的端到端TRT加速支持

### ISSUE THREAD

**Issue by Linaom1214** [meituan/YOLOv6#403]
https://github.com/Linaom1214/tensorrt-python

无须修改代码，一键添加nms plugin

**Comment by khwengXU** [comment]
Thanks for your suggestion！ We will consider it.

**Comment by Linaom1214** [comment]
> Thanks for your suggestion！ We will consider it.

users can refer this https://github.com/WongKinYiu/yolov7/issues/474
