### ISSUE TITLE
Even though specify the correct class name and mapping data.yaml ,Model detecting and labeling random class

### ISSUE THREAD

**Issue by thangarajdeivasikamani** [meituan/YOLOv6#409]
Hi,
I have used the below dataset for object detection:
 https://www.kaggle.com/datasets/ashfakyeafi/road-vehicle-images-dataset

I have created dataset folder as below:
![image](https://user-images.githubusercontent.com/46878296/185024527-f142f4a2-fb1a-4eb1-8bd0-48230c2e8f62.png)

Data_1.yaml prepared as below:

![image](https://user-images.githubusercontent.com/46878296/185024436-f15dab09-0703-4bc3-b2d8-35c37b5fcad5.png)

Class:
 ['ambulance', 'army vehicle', 'auto rickshaw', 'bicycle', 'bus', 'car', 'garbagevan', 'human hauler', 'minibus', 'minivan', 'motorbike', 'pickup', 'policecar',
 'rickshaw', 'scooter', 'suv', 'taxi', 'three wheelers -CNG-', 'truck', 'van', 'wheelbarrow']

Training command I have used :
# training with single GPU support
!python tools/train.py --batch 32 --conf configs/yolov6s.py --epochs 200 --data  /content/drive/MyDrive/YOLO_6_Custom/dataset/trafic_data/data_1.yaml --device 0

Around 75 Epocs completed:

![image](https://user-images.githubusercontent.com/46878296/185025313-f567f402-305e-41fc-b10a-6c2e9b9b3004.png)

After that I have done the inference as below:

!python tools/infer.py --weights /content/drive/MyDrive/YOLO_6_Custom/YOLOv6/runs/train/exp/weights/best_ckpt.pt --source /content/drive/MyDrive/YOLO_6_Custom/dataset/trafic_data/images/test --device 0 

But I am getting wrong prediction labels:

![image](https://user-images.githubusercontent.com/46878296/185025571-f7585cc3-52a6-419b-83f9-e58ce58fd67b.png)

**Comment by mtjhl** [comment]
Please check if the index of the labels is the same with your labels.
```
['ambulance', 'army vehicle', 'auto rickshaw', 'bicycle', 'bus', 'car', 'garbagevan', 'human hauler', 'minibus', 'minivan', 'motorbike', 'pickup', 'policecar',
'rickshaw', 'scooter', 'suv', 'taxi', 'three wheelers -CNG-', 'truck', 'van', 'wheelbarrow']
```
For example ,  `army vehicle` label's index is 1, is it 1 in the txt format labels?

**Comment by thangarajdeivasikamani** [comment]
> Please check if the index of the labels is the same with your labels.
> 
> ```
> ['ambulance', 'army vehicle', 'auto rickshaw', 'bicycle', 'bus', 'car', 'garbagevan', 'human hauler', 'minibus', 'minivan', 'motorbike', 'pickup', 'policecar',
> 'rickshaw', 'scooter', 'suv', 'taxi', 'three wheelers -CNG-', 'truck', 'van', 'wheelbarrow']
> ```
> 
> For example , `army vehicle` label's index is 1, is it 1 in the txt format labels?



> Please check if the index of the labels is the same with your labels.
> 
> ```
> ['ambulance', 'army vehicle', 'auto rickshaw', 'bicycle', 'bus', 'car', 'garbagevan', 'human hauler', 'minibus', 'minivan', 'motorbike', 'pickup', 'policecar',
> 'rickshaw', 'scooter', 'suv', 'taxi', 'three wheelers -CNG-', 'truck', 'van', 'wheelbarrow']
> ```
> 
> For example , `army vehicle` label's index is 1, is it 1 in the txt format labels?

Hi, The same data set and labeling working in YOLO V5.And also refer the attached detection screenshot. I am not sure whether the model get the labels examples Horse, Fire hydrant,etc

**Comment by mtjhl** [comment]
If YOLOv6 and v5 all have same problem, the class index maybe is wrong. You'd better visualize the index on image, to see if the index is wrong.

**Comment by danielchua2602** [comment]
try including --yaml /content/drive/MyDrive/YOLO_6_Custom/dataset/trafic_data/data_1.yaml when running your inference

**Comment by thangarajdeivasikamani** [comment]
@danielchua2602
Thanks now working
