### ISSUE TITLE
mAP一直是0

### ISSUE THREAD

**Issue by LvShuaiChao** [meituan/YOLOv6#41]
![image](https://user-images.githubusercontent.com/35528109/175730119-6c8fa42e-ae1c-473e-b7c3-d8cf481f0bda.png)

`Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     1/399         0         0 0.0009047         0: 100%|██████████| 369/369 [01:09<00:00,  5.35it/s]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     2/399         0         0  0.000713         0: 100%|██████████| 369/369 [01:04<00:00,  5.69it/s]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     3/399         0         0 0.0005463         0: 100%|██████████| 369/369 [00:58<00:00,  6.35it/s]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     4/399         0         0 0.0004098         0: 100%|██████████| 369/369 [00:57<00:00,  6.43it/s]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     5/399         0         0 0.0003198         0: 100%|██████████| 369/369 [01:02<00:00,  5.92it/s]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     6/399         0         0 0.0002474         0: 100%|██████████| 369/369 [01:02<00:00,  5.92it/s]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     7/399         0         0 0.0002138         0: 100%|██████████| 369/369 [01:01<00:00,  6.02it/s]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     8/399         0         0  0.000196         0: 100%|██████████| 369/369 [01:01<00:00,  6.02it/s]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
     9/399         0         0 0.0001817         0: 100%|██████████| 369/369 [01:04<00:00,  5.72it/s]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
    10/399         0         0 0.0001668         0: 100%|██████████| 369/369 [01:00<00:00,  6.13it/s]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
    11/399         0         0 0.0001494         0: 100%|██████████| 369/369 [01:00<00:00,  6.12it/s]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
    12/399         0         0 0.0001287         0: 100%|██████████| 369/369 [01:00<00:00,  6.07it/s]

     Epoch  iou_loss   l1_loss  obj_loss  cls_loss
    13/399         0         0 0.0001141         0:  65%|██████▌   | 240/369 [00:40<00:20,  6.31it/s]
`

**Comment by LiJiahang617** [comment]
i met this issue too, have you solved it?

**Comment by LvShuaiChao** [comment]
Modifying the path of the coco dataset may solve this problem

**Comment by kwuliang** [comment]
I met the same  issue,

**Comment by kwuliang** [comment]
I think the bug is the new generation of the  /path/to/your/data/annotations/instances_vall.json. Because I draw the bbox on the image, it's wrong
