### ISSUE TITLE
利用yolov6-nano训练两个onnx模型（一个检测吸烟，一个检测玩手机），如何将两个onnx模型合并成一个onnx？

### ISSUE THREAD

**Issue by lixiangMindSpore** [meituan/YOLOv6#410]
利用yolov6-nano训练两个onnx模型（一个检测吸烟，一个检测玩手机），如何将两个onnx模型合并成一个onnx？该onnx模型既能检测吸烟，又能检测玩手机

**Comment by mtjhl** [comment]
据我所知，这种应该是不行的。但是我做过跟您这种类似的需求。方案有两种：
1）直接训练一个 2 类别的检测器，一个类别是是否在抽烟，一个类别是是否玩手机；
2）如果抽烟，玩手机的数据是独立的，可以做一个共享 backbone，两个检测头的检测器，一个检测头检测是否抽烟，一个检测头检测是否在玩手机；

**Comment by lixiangMindSpore** [comment]
> 据我所知，这种应该是不行的。但是我做过跟您这种类似的需求。方案有两种： 1）直接训练一个 2 类别的检测器，一个类别是是否在抽烟，一个类别是是否玩手机； 2）如果抽烟，玩手机的数据是独立的，可以做一个共享 backbone，两个检测头的检测器，一个检测头检测是否抽烟，一个检测头检测是否在玩手机；

谢谢您的解答，之前是基于我的抽烟检测数据集和玩手机数据集各训练一个模型，抽烟检测数据集中包含玩手机的，玩手机的数据集中也包含抽烟的，当前在不改变数据集标注的前提下，想把两个模型合成一个？您有什么方法？

**Comment by mtjhl** [comment]
> > 据我所知，这种应该是不行的。但是我做过跟您这种类似的需求。方案有两种： 1）直接训练一个 2 类别的检测器，一个类别是是否在抽烟，一个类别是是否玩手机； 2）如果抽烟，玩手机的数据是独立的，可以做一个共享 backbone，两个检测头的检测器，一个检测头检测是否抽烟，一个检测头检测是否在玩手机；
> 
> 谢谢您的解答，之前是基于我的抽烟检测数据集和玩手机数据集各训练一个模型，抽烟检测数据集中包含玩手机的，玩手机的数据集中也包含抽烟的，当前在不改变数据集标注的前提下，想把两个模型合成一个？您有什么方法？

这种也是可以做的，两批数据合并，在前传抽烟图片的时候，不计算玩手机对应检测的损失（因为你这张图片没有标注是否玩手机，所以不能计算损失）， 在前传玩手机图片的时候，不计算抽烟对应检测的损失。这样也可以训练。
