### ISSUE TITLE
Validation is not in the size of indicated img-size

### ISSUE THREAD

**Issue by sarmientoj24** [meituan/YOLOv6#424]
I have a backbone that is sensitive to the input resolution and can only take image of fixed input resolution of NxN such as 512x512. Training seems fine as it seems to pass through. However, the validation doesnt seem to fix the input size into the desired 512x512 from my debugging.

Any idea why?

**Comment by sarmientoj24** [comment]
seems like it has something to do with the `rect=True` here https://github.com/meituan/YOLOv6/blob/435cf0f9a89f6d3f63a48174164731cb1e646c50/yolov6/core/engine.py#L339-L342

**Comment by mtjhl** [comment]
Did you set the parameters of `--img-size`  to 512 here?
https://github.com/meituan/YOLOv6/blob/435cf0f9a89f6d3f63a48174164731cb1e646c50/tools/eval.py#L23

**Comment by sarmientoj24** [comment]
Yeah i added that. it doesnt work and still has a different resolution when validating because rect is True

**Comment by sarmientoj24** [comment]
my dataset is not NxN

**Comment by shensheng272** [comment]
> seems like it has something to do with the `rect=True` here
> 
> https://github.com/meituan/YOLOv6/blob/435cf0f9a89f6d3f63a48174164731cb1e646c50/yolov6/core/engine.py#L339-L342

Yes, to force no pad when eval in training, you might manual change `rect` to `False` **here**.  
Also you need check the `rect` params  in `Evaler.init_data` when you only want to eval.

The latest 0.2.0 add `not_infer_on_rect` when only eval. Might further include the test params in training config

**Comment by shensheng272** [comment]
[PR](https://github.com/meituan/YOLOv6/pull/442) add feature to support configurable eval params in training process. You can refer to  https://github.com/meituan/YOLOv6/blob/main/configs/experiment/yolov6n_with_eval_params.py.
For your case. you could set param as follow:
```
eval_params = dict(
    img_size=512,  #None mean will be the same as train image size
    conf_thres=0.03,
    iou_thres=0.65,
    task='train',

    #pading and scale coord 
    test_load_size=512, #None mean will be the same as test image size  # you could try smaller one for better metric result
    letterbox_return_int=False,  
    force_no_pad=True,
    not_infer_on_rect=True,
    scale_exact=False,

    #metric
    verbose=False,
    do_coco_metric=True,
    do_pr_metric=False,
    plot_curve=False,
    plot_confusion_matrix=False
)
```
