### ISSUE TITLE
What does num_layers mean and how to deal with a feature extractor that has 4 feature pyramid outputs?

### ISSUE THREAD

**Issue by sarmientoj24** [meituan/YOLOv6#427]
I saw this one and I am not sure if this stands for the decoupled head of cls, reg, and obj or does this stand for the three feature pyramids that the Detect Layers get from RePPAN?

https://github.com/meituan/YOLOv6/blob/435cf0f9a89f6d3f63a48174164731cb1e646c50/yolov6/models/effidehead.py#L17

In line with that, say I fused YOLOv6 with a network that outputs 4 feature pyramids instead of three. Any insights on how to deal with that?

**Comment by mtjhl** [comment]
YOLOv6 output three feature pyramids.  `num_layers`  is the number of detection layers, it is the same with feature pyramids layers.

**Comment by sarmientoj24** [comment]
@mtjhl i am trying to use a backbone in replacement of YOLOv6's backbone that contains 4 pyramid layers instead of three. Any advise on how to modify the PANNeck to use 4 pyramid layers?

**Comment by Chilicyy** [comment]
@sarmientoj24 You can try to add some operations like RepBlocks+1*1conv+upsample to build P2 outputs . Modify the code in ./yolov6/models/reppan.py.
