### ISSUE TITLE
什么时候推出ncnn

### ISSUE THREAD

**Issue by tututu11** [meituan/YOLOv6#43]
什么时候推出ncnn呢

**Comment by triple-Mu** [comment]
> 什么时候推出ncnn呢

已经有其他仓库做了。

**Comment by Baiyuetribe** [comment]
已有多个现成案例。其实很简单，就是yolox基础上加个归一化
安卓版: https://github.com/FeiGeChuanShu/ncnn-android-yolov6
纯C++版：https://github.com/Baiyuetribe/ncnn-models/tree/main/object_dection/yolov6
Windows-GUI版：https://github.com/Baiyuetribe/paper2gui/blob/main/Object%20Detection/yolov6_gui.md

**Comment by shensheng272** [comment]
please refer to our third party resource part on [readme](https://github.com/meituan/YOLOv6/blob/main/README.md)

**Comment by fanatic-studio** [comment]
为什么没有IOS版？
