### ISSUE TITLE
Need help in utilizing 4 feature pyramids to create 3 feature maps

### ISSUE THREAD

**Issue by sarmientoj24** [meituan/YOLOv6#430]
I saw this diagram as the architecture of YOLOv6's neck. It seems to use 3 feature pyramids from the backbone. However, I have 4 feature pyramids from the backbone I am using to test with YOLOv6. I would like to ask help in the implementation of this.

Basically, it will take 4 feature maps -- C2, C3, C4, and C5 but only has to output P3, P4, and P5.
![image](https://user-images.githubusercontent.com/8830319/188645561-c44c7afd-c37e-43bc-bbc3-70867f5712d9.png)

**Comment by shensheng272** [comment]
Current neck has 3 in 3 out. 
IF you want to 4 in 3 out, you might just ignore C2 and input C3 C4 C5, so neck is still 3 in 3 out.
IF you want to 4 in 4 out, you need to adjust neck and head.
