### ISSUE TITLE
Adding Support for other Dataset formats

### ISSUE THREAD

**Issue by ShisuiUzumaki** [meituan/YOLOv6#434]
Can we create a pull request to add support for other object detection dataset formats

**Comment by Chilicyy** [comment]
Of course you can, but for the sake of simplicity and readability of the code and consistent format, we recommend adding some of the more commonly used detection dataset formats. Thanks!

**Comment by ShisuiUzumaki** [comment]
I was thinking of adding an API that automatically converts common dataset formats to current format. What do you think @Chilicyy

**Comment by Chilicyy** [comment]
It sounds great. Welcome to contribute!

**Comment by ShisuiUzumaki** [comment]
Ok I will give it a try
