### ISSUE TITLE
The weights used in quantization

### ISSUE THREAD

**Issue by ysuwl** [meituan/YOLOv6#439]
Hello, excuse me, where can I find the weights and quant weights used in the onnx model, and how do I get the weights used in the quantization process? It would be nice to have a relevant explanation.

**Comment by Chilicyy** [comment]
hi @ysuwl , you can download the weights relevant to quantization process from the [2.0 release](https://github.com/meituan/YOLOv6/releases/tag/0.2.0). Tutorials of quantization can be found in [here](https://github.com/meituan/YOLOv6/blob/main/tools/qat/README.md).

**Comment by ysuwl** [comment]
I have problems with quantification:
      Traceback (most recent call last):
        File "tools/qat/qat_export.py", line 84, in <module>
          concat_quant_amax_fuse(ops)
        File ".../YOLOv6-quantization/tools/partial_quantization/utils.py", line 62, in 
        concat_quant_amax_fuse
          op_amax = op._input_quantizer._amax.detach().item()
        File "/usr/local/Python-3.8.6/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in __getattr__
          raise AttributeError("'{}' object has no attribute '{}'".format(
      AttributeError: 'TensorQuantizer' object has no attribute '_amax'
I printed out the information of op._input_quantizer and found that it didn't have _amax:
      (_input_quantizer): TensorQuantizer(8bit fake per-tensor amax=dynamic calibrator=HistogramCalibrator scale=1.0 quant)
What causes this? I suspect that my quantification process went wrong, and I want to ask how do I set up the calib_pt of the yolov6n_opt_qat.py and the teacher_model_path of the QAT process in the subsequent quantization process?

**Comment by shensheng272** [comment]
@xingyueye

**Comment by lippman1125** [comment]
@ysuwl please use commands from  tutorials [https://github.com/meituan/YOLOv6/blob/main/tools/qat/README.md](url) to perform quantization

**Comment by oforomar** [comment]
Hello,
I am trying to perform QAT after training scales and fp32 model on custom dataset for the yolov6 nano variant,
But I am confused about the .pt file here:-
![image](https://user-images.githubusercontent.com/30784448/195443084-87a61cb0-4f5d-4c54-8ea1-6dc8775f639b.png)
would appreciate your help
