### ISSUE TITLE
最新0.2.0又报这个bug  AttributeError: 'Trainer' object has no attribute 'epoch'

### ISSUE THREAD

**Issue by cq10086123** [meituan/YOLOv6#440]
最新0.2.0又报这个bug  AttributeError: 'Trainer' object has no attribute 'epoch'

**Comment by shensheng272** [comment]
你好，请问如何能复现这个问题？
是直接使用cooc训练，并且使用我们提供的复现命令吗？

**Comment by cq10086123** [comment]
coco使用的我自己数据集  然后运行train就报这个错， 之后我又换回0.1.0就可以训练了

**Comment by shensheng272** [comment]
可以试下备份下程序和数据，然后在备份的数据中删除缓存（数据集里面的.cache 文件）试试。

**Comment by Chilicyy** [comment]
hi @cq10086123 , 请问您这边拉了最新的代码以及从 这里：https://github.com/meituan/YOLOv6/releases/tag/0.2.0 下载最新的权重吗？

**Comment by JMChenl** [comment]
您好 请问解决了嘛 我也遇见了这问题

**Comment by weiqian0928** [comment]
我在resume训练时遇到这个问题，我的解决方法如下，不确定对你是否有帮助。

再训练时报属性错误：Trainer对象没有epoch属性：
这是由于yolov6/core/engine.py的train()函数中self.start_epoch取得的是上次训练结束时的epoch数值，若此次传入的epochs数值小于之前训练的epoch数，则导致未执行该遍历操作：for self.epoch in range(self.start_epoch, self.max_epoch)，因而报上述错误。

**Comment by wenjunx** [comment]
起码能训练再开源吧？一堆bug，训练不起来，训练还提示各种包没有，楼主提出的这个问题也没解决，今天拉的最新的代码
