### ISSUE TITLE
AttributeError when trying top run notebook

### ISSUE THREAD

**Issue by wuuthraad-x** [meituan/YOLOv6#443]
I am just trying to run the example notebook( [turtorial.ipynb](https://github.com/meituan/YOLOv6/blob/main/turtorial.ipynb) ) on google colab but it keeps giving me an error which says : " AttributeError: 'Detect' object has no attribute 'grid_cell_size'  " I did not change any part of the code, I am just running it as is.

**Comment by Chilicyy** [comment]
Hi, did you use the 2.0 released weights with the latest code?




------------------ Original ------------------
From: wuuthraad ***@***.***&gt;
Date: Sat,Sep 10,2022 2:22 PM
To: meituan/YOLOv6 ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [meituan/YOLOv6] AttributeError when trying top run notebook (Issue#443)





 
I am just trying to run the example notebook( turtorial.ipynb ) on google colab but it keeps giving me an error which says : " AttributeError: 'Detect' object has no attribute 'grid_cell_size'  " I did not change any part of the code, I am just running it as is.

**Comment by wuuthraad-x** [comment]
Yes I have and the error message changed now it's "
[/usr/local/lib/python3.7/dist-packages/google/colab/patches/__init__.py](https://localhost:8080/#) in cv2_imshow(a)
     16       image.
     17   """
---> 18   a = a.clip(1, 255).astype('uint8')
     19   # cv2 stores colors as BGR; convert to RGB
     20   if a.ndim == 3:

AttributeError: 'NoneType' object has no attribute 'clip'" 

I honestly do not know what I am doing wrong... I never even edited the code(I am using the latest code)

**Comment by wuuthraad-x** [comment]
Just had to mount my drive
