### ISSUE TITLE
Where would be the det proposals in the head architecture?

### ISSUE THREAD

**Issue by sarmientoj24** [meituan/YOLOv6#444]
I was trying to determine where in this architecture and where in the code are those proposal boxes are. I am trying to apply an attention mechanism in the class proposal features. 
Could you help me?

![image](https://user-images.githubusercontent.com/8830319/189479653-b4dcdf74-a7b4-4c25-9013-6551d26af806.png)

**Comment by shensheng272** [comment]
https://github.com/meituan/YOLOv6/blob/main/yolov6/models/effidehead.py  maybe add some block here
