### ISSUE TITLE
Diagram for updated architecture and writeup

### ISSUE THREAD

**Issue by sarmientoj24** [meituan/YOLOv6#445]
I am reading this thing [link](https://min.news/en/news/cddfdf9fe2d2b91815470aa47655b3a9.html) and it seems to follow what is on the code until the latest code changes where there are no obj_convs anymore.

Is there an updated writeup for this?

**Comment by sarmientoj24** [comment]
why is there no object loss? and is better to have DFL to be true as default or no?

**Comment by shensheng272** [comment]
No obj conv make model faster and better, you might find details in tech report .(loss function part)

**Comment by sarmientoj24** [comment]
where to get tech report

**Comment by shensheng272** [comment]
> where to get tech report

Tech Report link has updated in top of reademe.  https://github.com/meituan/YOLOv6#readme
