### ISSUE TITLE
Where is best spot to add albumentations augmentation?

### ISSUE THREAD

**Issue by sarmientoj24** [meituan/YOLOv6#446]
I already instantiated albumentations. Where is the best place in the code it should be added?

**Comment by shensheng272** [comment]
It should be .yolov6/dataset.py

**Comment by sarmientoj24** [comment]
Yes. But where in that spot should I put something like `images, labels = self.albumentations(...)`

**Comment by shensheng272** [comment]
https://github.com/meituan/YOLOv6/blob/main/yolov6/data/datasets.py#L141  either  before/after/replace` img, labels = random_affine(...)`
