### ISSUE TITLE
AttributeError: 'Detect' object has no attribute 'grid_cell_size'

### ISSUE THREAD

**Issue by mabedd** [meituan/YOLOv6#447]
Hello

I have trained on a custom dataset and both training and evaluation worked like a charm. However, when running the inference on an image using the `best_chkpt` for detection using this command: 
`! python tools/infer.py --weights weights/best_ckpt.pt --source custom_data/inference_1.jpg --device 0`

it loads the chkpt then starts Fusing Model and suddenly gives this weird error:
`AttributeError: 'Detect' object has no attribute 'grid_cell_size`

I have tried using even the base models just to check if the problem is with the model but it appears it is not.
One thing that I face while installing requirements.txt is the following message but I am not sure if it is relevance or not:
`Collecting thop
  Downloading thop-0.1.1.post2209072238-py3-none-any.whl (15 kB)
ERROR: Could not find a version that satisfies the requirement pytorch_quantization>=2.1.1 (from versions: 0.0.1.dev4, 0.0.1.dev5)
ERROR: No matching distribution found for pytorch_quantization>=2.1.1`

This error did not appear first time training, but when I restarted the notebook it started appearing. Please note that I am using Google Colab and cloning the repo then installing requirements.txt, and I am following the exact documentation stated in Docs.

**Comment by shensheng272** [comment]
Look like model load failed.  You might check the path to the weights.
If problem still there, is it possible to upload the model?

**Comment by mabedd** [comment]
I don't think so because I am not getting a `No such file or directory`, In fact I tried to modify the path to a wrong one and it generated `No such file or directory`. 

I am saving the weights under the root `YOLO` directory under a directory I created called `weights`, so it is under `YOLO/weights/best_ckpt.pt`. Btw, the evaluation command worked successfully using the same directory.

I have uploaded all assets to my GIthub [repo](https://github.com/mabedd/Hardhat-Safety-Vest-Detection-YOLOv6)

**Comment by Chilicyy** [comment]
hi @mabedd , it seems that you trained a model with the v1.0 code, but try to do evaluation with the v2.0 code. Please git pull the latest code and try to train a new model for your custom dataset.

**Comment by mabedd** [comment]
Thanks dear @Chilicyy you are just right. Seems that I trained my model just before the update and when I wanted to do inference on the next day the update released. Everything now works like a charm !!

Appreciate your help :)

**Comment by minhducnart12** [comment]
> Thanks dear @Chilicyy you are just right. Seems that I trained my model just before the update and when I wanted to do inference on the next day the update released. Everything now works like a charm !!
> 
> Appreciate your help :)

Hi.I want to draw F1 curve ,PR_curve... please show me how to draw

**Comment by mabedd** [comment]
Hi @minhducnart12

Just run this command
`python tools/eval.py --data {path/to/data.yaml}  --weights runs/train/exp1/weights/best_ckpt.pt --device 0`

> > Thanks dear @Chilicyy you are just right. Seems that I trained my model just before the update and when I wanted to do inference on the next day the update released. Everything now works like a charm !!
> > Appreciate your help :)
> 
> Hi.I want to draw F1 curve ,PR_curve... please show me how to draw

**Comment by minhducnart12** [comment]
> Hi @minhducnart12
> 
> Just run this command `python tools/eval.py --data {path/to/data.yaml} --weights runs/train/exp1/weights/best_ckpt.pt --device 0`
> 
> > > Thanks dear @Chilicyy you are just right. Seems that I trained my model just before the update and when I wanted to do inference on the next day the update released. Everything now works like a charm !!
> > > Appreciate your help :)
> > 
> > 
> > Hi.I want to draw F1 curve ,PR_curve... please show me how to draw

oh.thank you. I trained my model when the author has not updated that function.
