### ISSUE TITLE
How can i run onnx and engine model?

### ISSUE THREAD

**Issue by kadirnar** [meituan/YOLOv6#453]
Hello,

I want to make large models onnx and tensorRT transforms and run them on video. I couldn't see the demo code. Could you help?

**Comment by shensheng272** [comment]
Export ONNX : [https://github.com/meituan/YOLOv6/tree/main/deploy/ONNX](https://github.com/meituan/YOLOv6/tree/main/deploy/ONNX)
ONNX to trt use `trtexec` : https://github.com/meituan/YOLOv6/blob/main/deploy/ONNX/export_onnx.py#L117
Test trt with python script: [https://github.com/meituan/YOLOv6/blob/main/deploy/ONNX/eval_trt.py](https://github.com/meituan/YOLOv6/blob/main/deploy/ONNX/eval_trt.py)

**Comment by kadirnar** [comment]
Hi @shensheng272 ,

I am looking for the demo python file. I want to run .engine and .onnx models on video. Can you share the sample code line? There is no source parameter in [eval_trt.py](https://github.com/meituan/YOLOv6/blob/main/deploy/ONNX/eval_trt.py) file. I can't play the video either.

**Comment by shensheng272** [comment]
Video infer only support pt using `tools/infer.py`. We might add trt infer demo later.

**Comment by kadirnar** [comment]
Thank you for the feedback.

**Comment by xingyueye** [comment]
@kadirnar hi, TRT inference for single image is supported, you can test is like 
`python deploy/TensorRT/eval_yolo_trt.py -v -m model.trt --imgs-dir /workdir/datasets/coco/images/val2017 --annotations /workdir/datasets/coco/annotations/instances_val2017.json --conf-thres 0.25 --iou-thres`
Inference for video would be released asap. And we also appreciate it if you could submit a PR for this scripts

**Comment by kadirnar** [comment]
> @kadirnar hi, TRT inference for single image is supported, you can test is like `python deploy/TensorRT/eval_yolo_trt.py -v -m model.trt --imgs-dir /workdir/datasets/coco/images/val2017 --annotations /workdir/datasets/coco/annotations/instances_val2017.json --conf-thres 0.25 --iou-thres 0.45` Inference for video would be released asap. And we also appreciate it if you could submit a PR for this scripts

@akashAD98 can you do this?

**Comment by akashAD98** [comment]
@kadirnar im doing it , thanks

**Comment by akashAD98** [comment]
> @kadirnar hi, TRT inference for single image is supported, you can test is like `python deploy/TensorRT/eval_yolo_trt.py -v -m model.trt --imgs-dir /workdir/datasets/coco/images/val2017 --annotations /workdir/datasets/coco/annotations/instances_val2017.json --conf-thres 0.25 --iou-thres 0.45` Inference for video would be released asap. And we also appreciate it if you could submit a PR for this scripts

 I have added video inference support which supports end2end  or without end2end conversion https://github.com/meituan/YOLOv6/pull/469/commits ,please have look & it would be great if you accept this pr
