### ISSUE TITLE
tutorial_repopt训练疑问

### ISSUE THREAD

**Issue by ChungTak** [meituan/YOLOv6#456]
1.教程里面说先 hyper_search再repopt训练，如果我要训练yolov6s自定义的数据集400 epochs。
   是需要先hyper_search训练400 epochs得出scale模型，再训练400 epochs,一共要训练800 epochs ? 还是说scale直接用你们coo预训练的scale模型，我只需要训练repopt模型400 epochs就可以呢？

2.repopt进行finetune迁移学习，配置文件 pretrained 是用yolov6s_v2_reopt.pt 还是yolov6s.pt 呢？

**Comment by xingyueye** [comment]
1. 我们尚未做过400epochs的repopt实验。建议可以先用我们release的scale训练一波看看结果，如果不符合预期的话再尝试完整走一遍400epochs的两个阶段；
2. 在finetune时，pretrained选择为yolov6s_v2_reopt.pt
