### ISSUE TITLE
end-to-end onnx 推理问题

### ISSUE THREAD

**Issue by whuhit** [meituan/YOLOv6#458]
作者您好，我使用提供的yolov6s.pt模型推理结果是正常的，但是转成end-to-end的onnx模型之后，再次推理的时候，二者结果不一样，且onnx模型最多只能检测8个目标。请问有遇到过这种情况吗

**Comment by shensheng272** [comment]
@triple-Mu

**Comment by shensheng272** [comment]
> 作者您好，我使用提供的yolov6s.pt模型推理结果是正常的，但是转成end-to-end的onnx模型之后，再次推理的时候，二者结果不一样，且onnx模型最多只能检测8个目标。请问有遇到过这种情况吗

是使用0.2.0之后的新版本吗？ 导出end2end的地方可以设置最大导出框数目，默认应该是100

**Comment by whuhit** [comment]
不好意思，我刚找到原因了，因为yolov6s.pt推理时预处理是尽可能保持原图的长宽比，另外使用114填充，onnx推理时那边我预处理设置的不一样导致的二者差异。

**Comment by whuhit** [comment]
另外一个问题，pt模型在export end-to-end onnx的时候，可以考虑导出动态长宽的onnx模型吗。

**Comment by shensheng272** [comment]
动态长宽实际应用少，容易影响速度。暂时还不在更新计划中
