### ISSUE TITLE
Exception happened when i pythoned infer.py

### ISSUE THREAD

**Issue by LiJiahang617** [meituan/YOLOv6#46]
After typing in terminal: python tools/infer.py --weights yolov6s.pt --source [/home/lijiahang/Desktop/yolov6/data/images/image1.jpg],issue happened.
i gave the right location where i stored my testing images, is it because i misunderstand the README file? shouldn't i gave the image directory location in  []?

**Comment by LiJiahang617** [comment]
the issue said:Exception: Invalid path: [/home/lijiahang/Desktop/yolov6/data/images/image1.jpg]

**Comment by Chilicyy** [comment]
Thanks for your attention! 
Yes, you don't need to give '[]' outside your image directory. I'll fix the README file.

**Comment by LiJiahang617** [comment]
thanks, by the way, when i trained the model,i saw this cfg in coco.yaml :anno_path: /home/Desktop/detectron2-main/datasets/coco/annotations/instances_val2017.json,but this is val dataset's annotation,is this right? isn't train datasets correspond with train2017.json and val datasets with val2017.yaml? how should i organize my anno_path? should i write train2017.yaml and val2017.yaml at the same time when i want to train model?

**Comment by Chilicyy** [comment]
As to coco preparation, you can refer to [issues#29](https://github.com/meituan/YOLOv6/issues/29).

**Comment by LiJiahang617** [comment]
thanks, but i have one more question, why the annotation in the tree you gave is *.txt instead of *.json, my coco dataset's annotations are all * .json
