### ISSUE TITLE
Inference with ONNX

### ISSUE THREAD

**Issue by trungpt2608** [meituan/YOLOv6#460]
Is there any sample code for infer with onnx. On YOLOv6 version 1, when i convert pt to onnx, i can infer with repo of ibaiGorordo, but on YOLOv6, version 2, when convert to onnx format, i don't know how to infer.

This is the result when i infer yolov6 v2 onnx with the inference code of v1
![detected_objects](https://user-images.githubusercontent.com/96898546/190059177-502db5af-f864-4391-9aa2-ec52b85a6d14.jpg)

**Comment by triple-Mu** [comment]
It seems to be caused by incorrect result parsing.
Such as bbox format xywh to xyxy or normalized bbox to non-normalized.
