### ISSUE TITLE
关于贵单位论文上面的表格数据

### ISSUE THREAD

**Issue by FYM1209** [meituan/YOLOv6#464]
贵单位的杰作yolov6 ，里面table1的yolov7-tiny的精度和速度数据 是直接使用官方提供的模型权重验证的 还是自己从头又跑了一遍然后又验证的？
如果是自己从头跑了一遍 我想寻求一些贵单位在训练时候的超参数 比如学习率 动量等等，因为我跑不出你们的结果，总是差几个点 
非常感谢！！

**Comment by zidanexu** [comment]
您好，我们采用官方提供的权重进行验证

**Comment by FYM1209** [comment]
嗯嗯 我的问题 数据没错
