### ISSUE TITLE
does it matter what i keep in val images for yelo training?

### ISSUE THREAD

**Issue by yuvrajhembade** [meituan/YOLOv6#465]
If I have a dataset in three different color backgrounds & I am keeping images in Val folder of data with only one color background, then will it matter in getting the best checkpoints?

**Comment by Chilicyy** [comment]
hi @yuvrajhembade , in this case, it can be shown that the current best checkpoint works better only on the val dataset. As for the data with the other two color backgrounds, it may need some tests.

**Comment by yuvrajhembade** [comment]
Thank You, it simply means i need to add in val set, to get better ckpt's. Thanks for fast resolve.
