### ISSUE TITLE
pytorch-quantization

### ISSUE THREAD

**Issue by Huangdebo** [meituan/YOLOv6#468]
你好：
        感谢你的开源项目。请问 pytorch-quantization 只支持 linux吗？在 windows 中安装 pytorch-quantization 是一值遇到错误。
![image](https://user-images.githubusercontent.com/54938217/190370968-130f01bb-21f6-460e-8614-922041a5d818.png)

**Comment by lippman1125** [comment]
@Huangdebo  Please use commands as follow to try again.
pip install --extra-index-url=https://pypi.ngc.nvidia.com/ --trusted-host pypi.ngc.nvidia.com nvidia-pyindex
pip install --extra-index-url=https://pypi.ngc.nvidia.com/ --trusted-host pypi.ngc.nvidia.com pytorch_quantization

**Comment by Huangdebo** [comment]
> @Huangdebo Please use commands as follow to try again. pip install --extra-index-url=https://pypi.ngc.nvidia.com/ --trusted-host pypi.ngc.nvidia.com nvidia-pyindex pip install --extra-index-url=https://pypi.ngc.nvidia.com/ --trusted-host pypi.ngc.nvidia.com pytorch_quantization

Thanks for your reply. I have tried those two commands, but it still get the same error.

**Comment by lippman1125** [comment]
@Huangdebo Pip did not find this package caused this error, you can try to install it from source.   
`git clone git@github.com:NVIDIA/TensorRT.git`
`cd TensorRT/tools/pytorch-quantization/`  
 `python3 setup.py develop`

**Comment by Zephyr69** [comment]
I believe this package is installed as part of tensorrt and should not be installed using pip. On windows it's not on my pip list but the code runs fine.

**Comment by Huangdebo** [comment]
> @Huangdebo Pip did not find this package caused this error, you can try to install it from source. `git clone git@github.com:NVIDIA/TensorRT.git` `cd TensorRT/tools/pytorch-quantization/` `python3 setup.py develop`

thank you very much， it works ！

**Comment by Huangdebo** [comment]
> I believe this package is installed as part of cuda or tensorrt and should not be installed using pip. On windows it's not on my pip list but the code runs fine.

how ca I install this package as part of cuda?
