### ISSUE TITLE
AssertionError: Results do not correspond to current coco set

### ISSUE THREAD

**Issue by LvShuaiChao** [meituan/YOLOv6#47]
I use the following code for training
python tools/train.py --batch 4 --conf configs/yolov6s.py --data ./data/coco.yaml --device 0 --workers 0
But this mistake happened during the val
AssertionError: Results do not correspond to current coco set
![image](https://user-images.githubusercontent.com/35528109/175759992-068c80c6-b25d-4ea0-ba6d-eb7705e8711c.png)

**Comment by LiJiahang617** [comment]
i also met issues when training:
/home/lijiahang/Pictures/Screenshot from 2022-06-25 13-47-53.png
i can't understand the reason,why its a invalid directory path?

**Comment by meituan-gengyifei** [comment]
The first problem might be due to the annotation's cache file. You can delete previously generated cache files and regenerate them when using a new training set. We will also optimize this part of the settings as soon as possible, and it is expected to be completed next week. At that time, you can check whether the problem still exists.
The second question suggests that you try using absolute paths in coco.yaml to see if the same problem still exists.
Thank you for your attention

**Comment by Dreamcatcher-wind** [comment]
> i also met issues when training: ![Screenshot from 2022-06-25 13-47-53](https://user-images.githubusercontent.com/103312600/175760357-1808bbbf-3db0-426e-8a1a-5f6090487439.png)
> 
> i can't understand the reason,why its a invalid directory path?

I think you can try to modify the root : from "../coco/images/train2017" to "./coco/images/train2017"

**Comment by Dreamcatcher-wind** [comment]
This file".\runs\train\exp\predictions.json" may have problem, such as "image_id": 1333", my dataset don't have an image named 1333. How to solve it?

**Comment by UygarUsta99** [comment]
> I use the following code for training python tools/train.py --batch 4 --conf configs/yolov6s.py --data ./data/coco.yaml --device 0 --workers 0 But this mistake happened during the val AssertionError: Results do not correspond to current coco set ![image](https://user-images.githubusercontent.com/35528109/175759992-068c80c6-b25d-4ea0-ba6d-eb7705e8711c.png)

I am having the same issue at the moment.I have deleted the generated annotations folder and .train.json and tried again but I got the same error.Also after deleting the annotations folder and json files, even though all the paths are correct, at first I receive invalid directory path issue, then I run the command again without changing anything it trains for one epoch and I get the same  'Results do not correspond to current coco set'  error. It feels like a weird loop I cant debug.Thank you for your help.

**Comment by mingwz** [comment]
#76
