### ISSUE TITLE
交流群

### ISSUE THREAD

**Issue by sdreamforchen** [meituan/YOLOv6#472]
您好，看你们准备长期建设YOLOV6.能否建一个WX交流群呢

**Comment by sdreamforchen** [comment]
另外，YOLOV6精度是在没有预训练权重的情况下得到的吗

**Comment by zidanexu** [comment]
您好，感谢您的关注，我们的初衷是长期建设YOLOv6，在创新和工业落地方面能做的更好：
1、![image](https://user-images.githubusercontent.com/54395639/190545462-645a6c47-df4e-43eb-b4fa-3c654c8c8dc6.png)
2、我们所有模型都没有预训练
