### ISSUE TITLE
mosaic augmentation is slow?

### ISSUE THREAD

**Issue by johnnysclai** [meituan/YOLOv6#473]
I found that the training speed between with and without mosaic augmentation is huge. Any way to improve the speed of mosaic augmentation?

**Comment by eorroot** [comment]
+ 1

**Comment by eorroot** [comment]
+  1

**Comment by mtjhl** [comment]
Mosaic augmentation is usefull to improve the model's performance. Did you compare the time cost of one epoch between with and without mosaic? Mosaic is done in Dataset module, it use multithread to process it. If it is very slow, we will consider to optimize it.

**Comment by johnnysclai** [comment]
In my experiment with A6000 * 1 GPU, it will increase ~30-40% of training time when using mosaic augmentation.

**Comment by shensheng272** [comment]
Mosaic augmentation is useful to detect small object, you can change the probability in train config to boost training. Default   probability for mosaic augmentation is 1.0
