### ISSUE TITLE
Yolov6n export onnx have different 

### ISSUE THREAD

**Issue by YunlongHu** [meituan/YOLOv6#476]
The model i train on my dataset , and use "./deploy/ONNX/export_onnx.py" to export
![1663349424813](https://user-images.githubusercontent.com/24264769/190698546-15135795-5537-44e9-b27a-b627c23edcf1.png)

But the onnx model downloaded from your website is different with mine.

![1663349582341](https://user-images.githubusercontent.com/24264769/190698879-6fdf7ced-3c9e-4c49-a8cc-7d22e3638d1c.png)

How to solve this problem. The first onnx is difficult to depoly.

**Comment by Chilicyy** [comment]
hi @YunlongHu , did you add the param --simplify when exporting onnx? You can refer to https://github.com/meituan/YOLOv6/tree/main/deploy/ONNX .
