### ISSUE TITLE
Validation image is not the same as train image, does not resize to NxN with pad

### ISSUE THREAD

**Issue by sarmientoj24** [meituan/YOLOv6#477]
I added this on the config

```
eval_params = dict(
    img_size=None,  
    task='val', 
    test_load_size=None, 
    letterbox_return_int=False,  
    force_no_pad=True,
    not_infer_on_rect=True,
    scale_exact=False,
)
```

My images are rectangular in nature about 1960x1460 sometimes with small discrepancies. My training changes the image into my desired 640x640 where the aspect ratio is preserved and it is padded.

Meanwhile, it doesnt seem to resize the image when evaluating.
I checked it and it this is the output
```
torch.Size([128, 3, 512, 672])
```

**Comment by shensheng272** [comment]
`eval_params` in train config is to config the eval params in training.(to choose best ckpt and monitor traning process)  
So the `task` here should be `train` .
If you want to change eval param when using `eval.py`, need to set args.
We might change the way to avoid confusion
