### ISSUE TITLE
AttributeError: __enter__

### ISSUE THREAD

**Issue by Gwencong** [meituan/YOLOv6#479]
When export TensorRT model with **int8** precision using `tools/quantization/tensorrt/post_training/onnx_to_tensorrt.py`, i got this error:
```
...
[09/18/2022-17:07:34] [TRT] [V] Deleting timing cache: 3156 entries, served 15122 hits since creation.
[09/18/2022-17:07:34] [TRT] [E] 1: Unexpected exception 
Traceback (most recent call last):
  File "tools/quantization/tensorrt/post_training/onnx_to_tensorrt.py", line 222, in <module>
    main()
  File "tools/quantization/tensorrt/post_training/onnx_to_tensorrt.py", line 216, in main
    with builder.build_engine(network, config) as engine, open(args.output, "wb") as f:
AttributeError: __enter__
```
my export command is:
```
python tools/quantization/tensorrt/post_training/onnx_to_tensorrt.py \
    --onnx weights/yolov6l.onnx \
    --output weights/yolov6l-int8.engine \
    --max-batch-size 1 \
    -v \
    --explicit-batch \
    --fp16 \
    --int8 \
    --calibration-cache caches/yolov6l.cache \
    --calibration-batch-size 128 \
    --calibration-data coco/images/train2017
```
the onnx model is export with the command [here](https://github.com/meituan/YOLOv6/tree/main/deploy/ONNX#export-script).

If i export TensorRT model with **fp16** precision, everything is ok, so i think this problem may be related to the int8 part of the code in  `tools/quantization/tensorrt/post_training/onnx_to_tensorrt.py`.

**Comment by xingyueye** [comment]
@Gwencong hi, You can use `deploy/TensorRT/onnx_to_trt.py` to export onnx model. 
Original `tools/quantization/tensorrt/post_training/onnx_to_tensorrt.py` would be deprecated.

**Comment by Gwencong** [comment]
thanks for your reply, I have tried `deploy/TensorRT/onnx_to_trt.py`, it works.
