### ISSUE TITLE
qat无法训练

### ISSUE THREAD

**Issue by dejavvuu** [meituan/YOLOv6#480]
AttributeError: 'RepPANNeck' object has no attribute 'upsample_feat0_quant'

看了下代码
`    def upsample_enable_quant(self):
        print("Insert fakequant after upsample")
        # Insert fakequant after upsample op to build TensorRT engine
        from pytorch_quantization import nn as quant_nn
        from pytorch_quantization.tensor_quant import QuantDescriptor
        conv2d_input_default_desc = QuantDescriptor(num_bits=8, calib_method='histogram')
        self.upsample_feat0_quant = quant_nn.TensorQuantizer(conv2d_input_default_desc)
        self.upsample_feat1_quant = quant_nn.TensorQuantizer(conv2d_input_default_desc)
        global _QUANT
        _QUANT = True`

问题应该在这里，怎么改比较好

**Comment by dejavvuu** [comment]
`        if _QUANT and hasattr(self, 'upsample_feat0_quant'):
            upsample_feat0 = self.upsample_feat0_quant(upsample_feat0)
        f_concat_layer0 = torch.cat([upsample_feat0, x1], 1)
        f_out0 = self.Rep_p4(f_concat_layer0)

        fpn_out1 = self.reduce_layer1(f_out0)
        upsample_feat1 = self.upsample1(fpn_out1)
        if _QUANT and hasattr(self, 'upsample_feat1_quant'):
            upsample_feat1 = self.upsample_feat1_quant(upsample_feat1)`

需要添加成员判断

**Comment by lippman1125** [comment]
@dejavvuu Well done，we will fix it.
