### ISSUE TITLE
install issu

### ISSUE THREAD

**Issue by zcgecho** [meituan/YOLOv6#484]
when execute pip install -r requirements.txt,errors occur as follow.
my env is python38 on win12

C:\code\YOLOv6>pip -V
pip 22.2.2 from c:\users\zrui\appdata\local\programs\python\python38\lib\site-packages\pip (python 3.8)

C:\code\YOLOv6>python -V
Python 3.8.2

Collecting thop
  Using cached thop-0.1.1.post2209072238-py3-none-any.whl (15 kB)
ERROR: Could not find a version that satisfies the requirement pytorch_quantization>=2.1.1 (from versions: 0.0.1.dev4, 0.0.1.dev5)
ERROR: No matching distribution found for pytorch_quantization>=2.1.1

**Comment by Chilicyy** [comment]
hi @zcgecho, you can try to install this package by the commands below:
pip install --extra-index-url=https://pypi.ngc.nvidia.com --trusted-host pypi.ngc.nvidia.com nvidia-pyindex
pip install --extra-index-url=https://pypi.ngc.nvidia.com --trusted-host pypi.ngc.nvidia.com pytorch_quantization
