### ISSUE TITLE
训练模型时，GPU显存在逐渐增加

### ISSUE THREAD

**Issue by ZHJ-fighting** [meituan/YOLOv6#486]
我在进行yolov6n模型训练voc数据集时，在每个epoch进行到83%时，gpu显存会增加，最后导致CUDA out of memory。尝试多种方法，问题解决不了，求助各位大佬

**Comment by JiaPai12138** [comment]
减少batch size试试呢

**Comment by ZHJ-fighting** [comment]
刚试过了，我将batch size从32减到了16，但是也只是拉长了GPU显存增加的间隔，且每次模型进行验证时显存都会增加，验证完不回掉，目前我的解决办法是在每个step结束时删除loss并使用torch.cuda.empty_cache()清空未占用显存。但是，这样操作会使显存占用变为动态的，好像也能将显存控制在一个范围内。但是感觉没有从根本上解决问题，这样操作应该也会拖慢训练进程。

**Comment by mtjhl** [comment]
您的训练启动命令是什么？ @ZHJ-fighting

**Comment by Zephyr69** [comment]
还要继续减batchsize，我也是这样。显存不是会不断增加，只是在整个训练过程中十分不稳定，不像v5一条直线。我训练的时候每块gpu显存用不到一半左右才大概率不会训练到一半oom。

**Comment by ZHJ-fighting** [comment]
![1](https://user-images.githubusercontent.com/101438113/191464200-35d0b934-313e-452e-838e-517c0d2c7bf3.png)
这是我的启动命令 @mtjhl

**Comment by ZHJ-fighting** [comment]
对的，显存不稳定，会在训练途中某一刻增加，除了减小batch-size来腾出显存增加空间外还有办法解决该问题吗，我尝试去debug每一步寻找显存增加原因，但每次增加的地方都不同，有点无从下手的感觉。 @Zephyr69

**Comment by xiyunqiao** [comment]
我的也是，训练到中间某个epoch，突然就OOM

**Comment by jazzseow** [comment]
i think the OOM is caused by the assigners modules, maybe it'll help if we run those in cpu, but it might slow down the process.

**Comment by leedewdew** [comment]
#503 #508
