### ISSUE TITLE
加载之前的模型精调训练，指标完全退化

### ISSUE THREAD

**Issue by bob77109** [meituan/YOLOv6#491]
同样的网络结构，已经训练获得一个模型，加载该模型继续训练时loss很大，且第一轮的eval指标接近0
请问下可能是什么原因？
![1](https://user-images.githubusercontent.com/113669836/191475893-084f3890-f3a5-4c65-a79c-68b5aa1308e0.JPG)
![2](https://user-images.githubusercontent.com/113669836/191475902-e68eb755-87e9-4380-a0cb-5c881a3c7cbb.JPG)

**Comment by Chilicyy** [comment]
您好，这边用的配置文件是yolov6n_finetune.py吗？另外，两次训练的数据集类别差异大吗

**Comment by bob77109** [comment]
两次训练唯一的区别是pretrained，数据和config一致，lr调整到非常低的值了。
resume报错无法加载optimizer等训练状态信息

**Comment by Chilicyy** [comment]
resume报错的问题在最新版的代码中已经修复了，建议拉最新的代码重新训练，谢谢！
