### ISSUE TITLE
Training Error: Evaluation script looking for instances_train.json instead of instances_valid.json

### ISSUE THREAD

**Issue by sovit-123** [meituan/YOLOv6#498]
I pulled the latest update today and was faced with this error when reaching the first evaluation loop after the first epoch.

`FileNotFoundError: [Errno 2] No such file or directory: '../final_dataset_underwater/yolov6/annotations/instances_train.json'`

Instead of `instances_valid.json`, now it is looking for `instances_train.json`. If I am not wrong, this issue is related to [this commit](https://github.com/meituan/YOLOv6/commit/79819a4ca4e0feb05a6ded3f6a3e614302827f02) made yesterday.

I also verified by running the same command on the same dataset and data YAML file that was running fine 2 days ago.

**Comment by Chilicyy** [comment]
Hi, thanks for pointing out this problem. We fix the bug in [this commit](https://github.com/meituan/YOLOv6/commit/28a0b9ba6ec5067012131266bdd345596a99f17f).
