### ISSUE TITLE
Where can I download yolov6 pretrained model?

### ISSUE THREAD

**Issue by triple-Mu** [meituan/YOLOv6#5]
I want to test yolov6 model,where can I download yolov6 pretrained model?

**Comment by Chilicyy** [comment]
Thanks for your attention! We'll release the pretrained model soon (probably next week).

**Comment by triple-Mu** [comment]
> Thanks for your attention! We'll release the pretrained model soon (probably next week).

Looking forward to yolov6's performance on coco datasets in my laptop.

**Comment by xinsuinizhuan** [comment]
when release the pretrained model ?

**Comment by kadirnar** [comment]
https://github.com/meituan/YOLOv6/releases/
