### ISSUE TITLE
How can i get TP,FP,FN, and mAP of all classes?

### ISSUE THREAD

**Issue by huchi00057** [meituan/YOLOv6#500]

**Comment by mtjhl** [comment]
Currently we can only print mAP and AP of each class, we will add the TP, FP, FN functions later.

**Comment by shensheng272** [comment]
Lastest code support such feature. Using config file to config `eval_params` to custom your eval setting.
To print each class precision/recall/map, set `--versbose`.
Most metric use precision and recall, not tp fo tn fn.
