### ISSUE TITLE
How can i continue train my model with broken weight file?

### ISSUE THREAD

**Issue by huchi00057** [meituan/YOLOv6#501]

**Comment by mtjhl** [comment]
What do you mean broken weight file? If the training process is interrupt, the lastest weight file is intact, you can resume the training process, please refer to the hopepage [here](https://github.com/meituan/YOLOv6 ) about resume training.
If the weight file is broken, we can only train the model again.

**Comment by huchi00057** [comment]
But what's the checkpoint path actual like?

**Comment by Chilicyy** [comment]
hi @huchi00057 If you didn't rename your experiment, then you can find the last checkpoint under the path `runs/train/exp/weights/last_ckpt.pt`.

**Comment by huchi00057** [comment]
> 你好@huchi00057如果你沒有重命名你的實驗，那麼你可以在 path 下找到最後一個檢查點`runs/train/exp/weights/last_ckpt.pt`。

Thank you!!
