### ISSUE TITLE
计算参数量的时候cfg无法使用

### ISSUE THREAD

**Issue by wxh1402714457** [meituan/YOLOv6#504]
![image](https://user-images.githubusercontent.com/97824555/192242085-db2e612f-0b01-4785-8918-cd1709e33bad.png)
m = build_model(cfg,num_classes=num_classes, device='0').to(device)

**Comment by Chilicyy** [comment]
你好，请问你是在哪里使用这个函数？你可以指定一个conf_file，并调用`cfg = Config.fromfile(args.conf_file)` 得到cfg。

**Comment by wxh1402714457** [comment]
谢谢，成功解决，python小白还是有很多代码不会的，还要继续学习
