### ISSUE TITLE
Outputs results not getting saved. AttributeError: 'NoneType' object has no attribute 'python_exit_status'

### ISSUE THREAD

**Issue by alumini** [meituan/YOLOv6#506]
Hi Team, 
 I am running yolov6 on custom dataset, but getting the below error after the training:
![image](https://user-images.githubusercontent.com/8180920/192432862-a2f0179b-3038-40b0-901e-a3774503275d.png)
Can someone help please?

**Comment by Chilicyy** [comment]
Hi @alumini, the error may due to resource saturation. You can set the parameter `--workers`  to 0 to solve this problem.

**Comment by alumini** [comment]
It's working now, thank you
