### ISSUE TITLE
map

### ISSUE THREAD

**Issue by CatchDr** [meituan/YOLOv6#515]
评估数据的结果没有map0.5么？怎么对应其他框架的精准率和召回率

**Comment by Chilicyy** [comment]
你好，跑eval任务时会输出mAP@0.5和mAP@0.50:0.95等指标，如果需要对标其他框架，可以翻阅我们的tech report上的表格数据。如果需要输入准确率和召回率，我们也提供了功能支持，详见readme中Evaluation部分的参数说明。

**Comment by CatchDr** [comment]
python tools/eval.py --data data/grape.yaml  --batch 1 --weights runs/train/exp/weights/best_ckpt.pt --task val
![image](https://user-images.githubusercontent.com/49591435/192741043-9d89c065-4a7b-4ef3-b395-ef0a2ef7cf29.png)
没有看到map

**Comment by CatchDr** [comment]
抱歉看到了，稍等正在测试

**Comment by CatchDr** [comment]
![image](https://user-images.githubusercontent.com/49591435/192744912-f94908c3-8dc2-4245-bad1-dd161665e262.png)
![image](https://user-images.githubusercontent.com/49591435/192745005-82b1ce34-7aa1-435d-b977-774cae671f07.png)
修改了默认值，但是结果并没有生效

**Comment by Chilicyy** [comment]
刚刚验证了下，修改默认值正常应该会生效的，麻烦确认下是否保存了以及修改的文件是tools/eval.py。

**Comment by CatchDr** [comment]
![image](https://user-images.githubusercontent.com/49591435/192925583-6bceb53e-9041-4a25-8514-1f901b92f9f8.png)
![image](https://user-images.githubusercontent.com/49591435/192925643-9bbd2aa1-b73b-4024-b193-e5597342c666.png)
我确定以及肯定无法开启，是否存在其他缓存文件呢？因为如图所示，batch的确被修改为2了

**Comment by shensheng272** [comment]
> ![image](https://user-images.githubusercontent.com/49591435/192925583-6bceb53e-9041-4a25-8514-1f901b92f9f8.png) ![image](https://user-images.githubusercontent.com/49591435/192925643-9bbd2aa1-b73b-4024-b193-e5597342c666.png) 我确定以及肯定无法开启，是否存在其他缓存文件呢？因为如图所示，batch的确被修改为2了

你好，使用最新的我这边没法复现相应的问题，这块读取配置文件的逻辑主要使用argparse，可以调试看看。
我猜想可能的原因是代码和运行路径不匹配，比如代码在本地修改后没有同步到服务端等等。在运行python命令前能否试试` cat tools/eval.py`  (linux) 查看文件是否有修改。
eval参数支持使用config_file进行配置，但是看打印出的命令行参数并没有使用。

**Comment by CatchDr** [comment]
问题解决了，可以关闭了，的确是没修改成功，非常感谢
