### ISSUE TITLE
训练结果可视化之后颇显奇怪

### ISSUE THREAD

**Issue by JiaPai12138** [meituan/YOLOv6#517]
我想确认下是不是我学习率设置不当造成的？
```
    lr0=0.02, #0.01 # 0.02  # 官方
    lrf=0.01,

    lr0=0.01, #0.01 # 0.02  # 我的
    lrf=0.1,
```
### yolov6 1.0版本时的训练结果
![image](https://user-images.githubusercontent.com/72233260/192879352-fa3e190d-6f89-4cca-ae70-6384d0da7497.png)
![image](https://user-images.githubusercontent.com/72233260/192879379-dcbbb0d6-9ab5-45a0-81c1-b7bc094315da.png)

### yolov6 2.0版本时的训练结果
![image](https://user-images.githubusercontent.com/72233260/192879422-7f82d18e-58c1-4372-8479-84c1141b4ca0.png)
![image](https://user-images.githubusercontent.com/72233260/192879490-e1e7fbc7-fced-4bf6-acc8-df75ca956a1d.png)

实际上2.0时我只训练了320 epoch, 第300轮次开始关闭mixup和马赛克增强
然后呢2.0版本训练时前300轮次每轮训练时间 **3:40** 以上
关闭数据增强后每轮时间 **1:15** ...

我会再按照官方的学习率再训练一次看看结果
ps:
![image](https://user-images.githubusercontent.com/72233260/192886694-06769264-ee2d-49b1-b61f-78a995233b30.png)

**Comment by Chilicyy** [comment]
@JiaPai12138 建议先用这边提供的配置文件的超参训练看下呢。另外如果是自己的数据集finetune，推荐使用v6n_finetune.py配置文件。

**Comment by JiaPai12138** [comment]
> @JiaPai12138 建议先用这边提供的配置文件的超参训练看下呢。另外如果是自己的数据集finetune，推荐使用v6n_finetune.py配置文件。

请问batchsize如果是官方四倍的话 学习率该如何设置在yolov6合适呢

**Comment by Chilicyy** [comment]
最新的代码中增加了 学习率关联batchsize调整的逻辑，可以尝试拉取最新的代码，用官方提供的配置文件试试。

**Comment by JiaPai12138** [comment]
> @JiaPai12138 建议先用这边提供的配置文件的超参训练看下呢。另外如果是自己的数据集finetune，推荐使用v6n_finetune.py配置文件。

官方配置
![image](https://user-images.githubusercontent.com/72233260/193106793-2a29f6ec-ac5f-4149-9fc2-c302f2517d63.png)

**Comment by JiaPai12138** [comment]
> 最新的代码中增加了 学习率关联batchsize调整的逻辑，可以尝试拉取最新的代码，用官方提供的配置文件试试。

好的好的

**Comment by JiaPai12138** [comment]
```
0.01
0.01
```
正常了
