### ISSUE TITLE
'ConfigDict' object has no attribute 'distill_weight'

### ISSUE THREAD

**Issue by hanjian-code** [meituan/YOLOv6#519]
请问这是什么问题？？尝试了很多次都是这个问题。
ERROR in training loop or eval/save model.

Training completed in 0.000 hours.
Traceback (most recent call last):
  File "/home/jysp/hanjian/yolov6_020/code/YOLOv6-0.2.0/yolov6/core/engine.py", line 97, in train
    self.train_before_loop()
  File "/home/jysp/hanjian/yolov6_020/code/YOLOv6-0.2.0/yolov6/core/engine.py", line 226, in train_before_loop
    distill_weight = self.cfg.model.head.distill_weight,
  File "/home/jysp/hanjian/yolov6_020/code/YOLOv6-0.2.0/yolov6/utils/config.py", line 30, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'distill_weight'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 126, in <module>
    main(args)
  File "tools/train.py", line 116, in main
    trainer.train()
  File "/home/jysp/hanjian/yolov6_020/code/YOLOv6-0.2.0/yolov6/core/engine.py", line 105, in train
    self.train_after_loop()
  File "/home/jysp/hanjian/yolov6_020/code/YOLOv6-0.2.0/yolov6/core/engine.py", line 261, in train_after_loop
    strip_optimizer(save_ckpt_dir, self.epoch)  # strip optimizers for saved pt model
AttributeError: 'Trainer' object has no attribute 'epoch'

**Comment by nice-kai** [comment]
I have same problem

**Comment by hanjian-code** [comment]
解决了    是源码的问题，源码的配置文件中没有head.distill_weight这个属性，把YOLOv6-0.2.0\yolov6\core\engine.py 中227行中的那个属性注释掉就行了

**Comment by shensheng272** [comment]
> 解决了 是源码的问题，源码的配置文件中没有head.distill_weight这个属性，把YOLOv6-0.2.0\yolov6\core\engine.py 中227行中的那个属性注释掉就行了

你好，方便说下使用的目的吗？
看了下代码中使用蒸馏主要在大模型上，因此大模型的config中有相关的配置，小模型n/t/s是没有的，请问是需要在小模型进行蒸馏吗？

**Comment by Chilicyy** [comment]
@hanjian-code @nice-kai 建议拉下最新的代码呢

**Comment by hanjian-code** [comment]
纯粹是进行学习的目的，目前并没有其他目的@shensheng272

**Comment by nice-kai** [comment]
@Chilicyy master分支吗 ？

**Comment by Chilicyy** [comment]
@nice-kai 对的

**Comment by nice-kai** [comment]
3Q

**Comment by shensheng272** [comment]
> 纯粹是进行学习的目的，目前并没有其他目的@shensheng272

0.2.0下有相关的bug会导致直接训练有问题，在之后的commit中修复了，我们尽快release一个新tag。建议使用最新的代码哈

**Comment by hanjian-code** [comment]
@shensheng272   欧了欧了

**Comment by nice-kai** [comment]
感谢上面的大神。但是我还是遇到了新的问题。

RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

这个是CUDA，没有安装成功吗？使用最新的代码试了好几次，都是一样的结果。

**Comment by hanjian-code** [comment]
@nice-kai 是不是torch于CUDA的匹配问题呢？？让我看看你的CUDA版本和torch版本

**Comment by nice-kai** [comment]
pytorch是用官网的推荐的conda命令安装的啊。测试GPU的代码也是可用的。
`
# packages in environment at /home/limk/anaconda3/envs/yolov6-2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
absl-py                   0.15.0             pyhd3eb1b0_0    defaults
addict                    2.4.0                    pypi_0    pypi
aiohttp                   3.8.1            py38h7f8727e_1    defaults
aiosignal                 1.2.0              pyhd3eb1b0_0    defaults
async-timeout             4.0.1              pyhd3eb1b0_0    defaults
attrs                     21.4.0             pyhd3eb1b0_0    defaults
blas                      1.0                    openblas    defaults
blinker                   1.4              py38h06a4308_0    defaults
brotlipy                  0.7.0           py38h27cfd23_1003    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
c-ares                    1.18.1               h7f8727e_0    defaults
ca-certificates           2022.07.19           h06a4308_0    defaults
cachetools                4.2.2              pyhd3eb1b0_0    defaults
cairo                     1.16.0               h19f5f5c_2    defaults
certifi                   2022.9.14        py38h06a4308_0    defaults
cffi                      1.15.1           py38h74dc2b5_0    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.0.4            py38h06a4308_0    defaults
commonmark                0.9.1                    pypi_0    pypi
contourpy                 1.0.5                    pypi_0    pypi
cpuonly                   1.0                           0    pytorch
cryptography              37.0.1           py38h9ce1e76_0    defaults
cudatoolkit               11.3.1               h2bc3f7f_2    defaults
cycler                    0.11.0                   pypi_0    pypi
dataclasses               0.8                pyh6d0b6a4_7    defaults
dbus                      1.13.18              hb2f20db_0    defaults
eigen                     3.3.7                hd09550d_1    defaults
expat                     2.4.9                h6a678d5_0    defaults
ffmpeg                    4.2.2                h20bf706_0    defaults
fftw                      3.3.9                h27cfd23_1    defaults
fontconfig                2.13.1               h6c09931_0    defaults
fonttools                 4.37.3                   pypi_0    pypi
freetype                  2.11.0               h70c0345_0    defaults
frozenlist                1.2.0            py38h7f8727e_0    defaults
giflib                    5.2.1                h7b6447c_0    defaults
glib                      2.69.1               h4ff587b_1    defaults
gmp                       6.2.1                h295c915_3    defaults
gnutls                    3.6.15               he1e5248_0    defaults
google-auth               2.6.0              pyhd3eb1b0_0    defaults
google-auth-oauthlib      0.4.4              pyhd3eb1b0_0    defaults
graphite2                 1.3.14               h295c915_1    defaults
grpcio                    1.42.0           py38hce63b2e_0    defaults
gst-plugins-base          1.14.0               h8213a91_2    defaults
gstreamer                 1.14.0               h28cd5cc_2    defaults
harfbuzz                  4.3.0                hd55b92a_0    defaults
hdf5                      1.10.6               h3ffc7dd_1    defaults
icu                       58.2                 he6710b0_3    defaults
idna                      3.3                pyhd3eb1b0_0    defaults
importlib-metadata        4.11.3           py38h06a4308_0    defaults
intel-openmp              2022.1.0          h9e868ea_3769    defaults
jpeg                      9e                   h7f8727e_0    defaults
kiwisolver                1.4.4                    pypi_0    pypi
krb5                      1.19.2               hac12032_0    defaults
lame                      3.100                h7b6447c_0    defaults
lcms2                     2.12                 h3be6417_0    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
lerc                      3.0                  h295c915_0    defaults
libclang                  10.0.1          default_hb85057a_2    defaults
libdeflate                1.8                  h7f8727e_5    defaults
libedit                   3.1.20210910         h7f8727e_0    defaults
libevent                  2.1.12               h8f2d780_0    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgfortran-ng            11.2.0               h00389a5_1    defaults
libgfortran5              11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libidn2                   2.3.2                h7f8727e_0    defaults
libllvm10                 10.0.1               hbcb73fb_5    defaults
libopenblas               0.3.20               h043d6bf_1    defaults
libopus                   1.3.1                h7b6447c_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libpq                     12.9                 h16c4e8d_3    defaults
libprotobuf               3.20.1               h4ff587b_0    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libtasn1                  4.16.0               h27cfd23_0    defaults
libtiff                   4.4.0                hecacb30_0    defaults
libunistring              0.9.10               h27cfd23_0    defaults
libuuid                   1.0.3                h7f8727e_2    defaults
libvpx                    1.7.0                h439df22_0    defaults
libwebp                   1.2.2                h55f646e_0    defaults
libwebp-base              1.2.2                h7f8727e_0    defaults
libxcb                    1.15                 h7f8727e_0    defaults
libxkbcommon              1.0.1                hfa300c1_0    defaults
libxml2                   2.9.14               h74e7548_0    defaults
libxslt                   1.1.35               h4e12654_0    defaults
lz4-c                     1.9.3                h295c915_1    defaults
markdown                  3.3.4            py38h06a4308_0    defaults
matplotlib                3.6.0                    pypi_0    pypi
mkl                       2022.1.0           hc2b9512_224    defaults
multidict                 5.2.0            py38h5eee18b_3    defaults
ncurses                   6.3                  h5eee18b_3    defaults
nettle                    3.7.3                hbbd107a_1    defaults
ninja                     1.10.2               h06a4308_5    defaults
ninja-base                1.10.2               hd09550d_5    defaults
nspr                      4.33                 h295c915_0    defaults
nss                       3.74                 h0370c37_0    defaults
numpy                     1.21.5           py38hf838250_3    defaults
numpy-base                1.21.5           py38h1e6e340_3    defaults
nvidia-pyindex            1.0.9                    pypi_0    pypi
oauthlib                  3.2.0              pyhd3eb1b0_1    defaults
onnx                      1.12.0           py38h6736146_0    defaults
onnx-simplifier           0.4.8                    pypi_0    pypi
opencv                    4.6.0            py38hd653453_0    defaults
opencv-python             4.6.0.66                 pypi_0    pypi
openh264                  2.1.1                h4ff587b_0    defaults
openjpeg                  2.4.0                h3ad879b_0    defaults
openssl                   1.1.1q               h7f8727e_0    defaults
packaging                 21.3                     pypi_0    pypi
pcre                      8.45                 h295c915_0    defaults
pillow                    9.2.0            py38hace64e9_1    defaults
pip                       22.1.2           py38h06a4308_0    defaults
pixman                    0.40.0               h7f8727e_1    defaults
prettytable               3.4.1                    pypi_0    pypi
protobuf                  3.20.1           py38h295c915_0    defaults
py-opencv                 4.6.0                h06a4308_0    defaults
pyasn1                    0.4.8              pyhd3eb1b0_0    defaults
pyasn1-modules            0.2.8                      py_0    defaults
pycocotools               2.0.5                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0    defaults
pygments                  2.13.0                   pypi_0    pypi
pyjwt                     2.4.0            py38h06a4308_0    defaults
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pyparsing                 3.0.9                    pypi_0    pypi
pysocks                   1.7.1            py38h06a4308_0    defaults
python                    3.8.13               h12debd9_0    defaults
python-dateutil           2.8.2                    pypi_0    pypi
pytorch-quantization      2.1.2                    pypi_0    pypi
pyyaml                    6.0              py38h7f8727e_1    defaults
qt-main                   5.15.2               h327a75a_7    defaults
qt-webengine              5.15.9               hd2b0992_4    defaults
qtwebkit                  5.212                h4eab89a_4    defaults
readline                  8.1.2                h7f8727e_1    defaults
requests                  2.28.1           py38h06a4308_0    defaults
requests-oauthlib         1.3.0                      py_0    defaults
rich                      12.5.1                   pypi_0    pypi
rsa                       4.7.2              pyhd3eb1b0_1    defaults
scipy                     1.7.3            py38hf838250_2    defaults
setuptools                63.4.1           py38h06a4308_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
sphinx-glpi-theme         0.3                      pypi_0    pypi
sqlite                    3.39.2               h5082296_0    defaults
tensorboard               2.9.0            py38h06a4308_0    defaults
tensorboard-data-server   0.6.0            py38hca6d32c_0    defaults
tensorboard-plugin-wit    1.8.1            py38h06a4308_0    defaults
thop                      0.1.1-2209072238          pypi_0    pypi
tk                        8.6.12               h1ccaba5_0    defaults
torch                     1.12.1                   pypi_0    pypi
torchaudio                0.4.0                      py38    pytorch
torchvision               0.13.1                   pypi_0    pypi
tqdm                      4.64.0           py38h06a4308_0    defaults
typing-extensions         4.3.0            py38h06a4308_0    defaults
typing_extensions         4.3.0            py38h06a4308_0    defaults
urllib3                   1.26.11          py38h06a4308_0    defaults
wcwidth                   0.2.5                    pypi_0    pypi
werkzeug                  2.0.3              pyhd3eb1b0_0    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
x264                      1!157.20191217       h7b6447c_0    defaults
xz                        5.2.6                h5eee18b_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
yarl                      1.8.1            py38h5eee18b_0    defaults
zipp                      3.8.0            py38h06a4308_0    defaults
zlib                      1.2.12               h5eee18b_3    defaults
zstd                      1.5.2                ha4553b6_0    defaults

`

**Comment by nice-kai** [comment]
Thu Sep 29 14:52:50 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
|  0%   46C    P8    38W / 340W |    733MiB / 10240MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1217      G   /usr/lib/xorg/Xorg                 53MiB |
|    0   N/A  N/A      1906      G   /usr/lib/xorg/Xorg                373MiB |
|    0   N/A  N/A      2046      G   /usr/bin/gnome-shell               51MiB |
|    0   N/A  N/A      3240      G   ...216728023906785561,131072      141MiB |
|    0   N/A  N/A    392680      G   ...RendererForSitePerProcess       96MiB |
+-----------------------------------------------------------------------------+

**Comment by hanjian-code** [comment]
@nice-kai 你这cuda版本太高了吧。而且官方给的requirements.txt文件中torch的版本需要>=1.8.0 而你当前的torch版本为torch 1.12.1。建议降低cuda版本提高torch版本重新试一下。

**Comment by nice-kai** [comment]
@hanjian-code 感谢。你就是用官方给的requirements.txt文件，直接使用pip3安装的吗？为啥我安装的时候有一些源安装不上的呢。例如：pytorch_quantization这个包，我昨天安装的时候，PIP说只有0.X的版本。

我是反复试验好几次，最后才把这些包给安装上。
利用conda创建的环境，然后，先安装的OpenCV和py-Opencv（应该对应的是opencv-python，conda里面没有这个名字），再安装Pytorch，从官网找的conda命令【conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch】，最后，再看requirements.txt里面没有安装的，能用conda安装的用conda，不行的就用pip安装，再不行就改版本了。pytorch_quantization这个版本肯定跟官网不一致了。

环境配置太曲折了，楼主你是怎么安装的环境，能跟我分享一下不？我对Python这些是新手。
万分感谢。

**Comment by Chilicyy** [comment]
@nice-kai 看起来是torch版本和cuda版本没对应，试试 pip install torch==1.8.0+cu111 重新安装，可参考https://pytorch.org/get-started/previous-versions/里面的命令。

**Comment by hanjian-code** [comment]
@hanjian-code 个人不喜欢用conda   我是自己在docker上拉了个虚拟镜像，然后使用pip逐包导入的，pytorch_quantization这个包pip确实没法导入，但是貌似没有这个包也能运行，可能后续需要用到这个包吧。

**Comment by nice-kai** [comment]
@Chilicyy 感谢。
我感觉torch和cuda的版本应该是能对上的，因为是从官网选择安装的，我这个安装都是的最新版本，确实比官网推荐的要高一些。如下图：

----------------------------------------------------------------------------------------------

![2022-09-29 15-23-51 的屏幕截图](https://user-images.githubusercontent.com/18050781/192967874-ffaecac2-633d-4017-8c80-b92fe43b5c4e.png)

-----------------------------------------------------------------------------------------------------------------------

图中给的pytorch和cuda就是对应上的，我安装的pytorch=1.12和cuda=11.3。
所以感觉能对应上。我感觉还是大概率是版本太高了吧。

您的环境是怎么安装的，可以分享一下吗？

**Comment by nice-kai** [comment]
@hanjian-code 使用docker确实是个好的办法，那docker里面的系统，你一般都用什么？Ubuntu？ 20.04 还是22.04？
就算是用docker，那么直接安装环境的时候，就没有在创建虚拟环境吗？那样Python的安装不会跟系统的Python版本冲突吗？

conda这个我的理解是它能够解决Python各种库的依赖问题，pip是解决不掉的。所以，我的环境安装每次都很曲折。

Python的整生态给我的感觉就是有好多的库，但是我还没有找一个更好的安装软件，像Java里那样使用maven和Spring全家桶那样很容易的解决掉库的依赖与冲突问题，而且maven里面所有的库基本都能找到。不知道Python里面有没有类似这样的，比conda和pip更全的软件？

**Comment by Chilicyy** [comment]
@nice-kai 我是通过pip安装的，可以看看上一条评论。

**Comment by hanjian-code** [comment]
@nice-kai 可以使用docker拉一个指定的基础python镜像啊，这样python就没有冲突了啊，然后创建容器逐包导入呗。想要像java的maven那样方便我目前还没遇到过。或者自己搞一个基础通用的dockerfile文件啊，很方便的。

**Comment by nice-kai** [comment]
@Chilicyy 感谢
那你们平时在遇到新模型或者自己创新新的模型的时候，肯定要创新的环境。这个时候，是像[hanjian-code](https://github.com/hanjian-code)那样使用docker，还是使用虚拟环境呢？

**Comment by nice-kai** [comment]
@hanjian-code 你看看我说的对不对哈。我对dockerfile不太了解用得少。
1. 自己创建一个dockerfile，作为base或者模板，在这里面规定好Python的版本；
2. 每次要创建新的环境，利用这个dockerfile，构建起新的docker容器；
3. 进入新构建的docker容器，然后在利用按照requirements.txt要求，利用pip进行安装；

我理解的对吗？

**Comment by hanjian-code** [comment]
@nice-kai 对的就是这样。因为你不可能在一台机器上同时符合多种算法的环境。因此我都会留一个基础的镜像，然后每次要做新的算法就在基础镜像上导入自己需要的包，然后把这个容器给提交为镜像保存下来，这样下次再用到这个算法就不必要重新安装环境了。

**Comment by nice-kai** [comment]
@hanjian-code 明白了。感谢。感谢。
