### ISSUE TITLE
指定device=0，但是所有gpu都占用了

### ISSUE THREAD

**Issue by jiheng1982** [meituan/YOLOv6#525]
before training：
![ndkgoEsRI0](https://user-images.githubusercontent.com/24932386/193002937-2c2e1059-f502-492d-9fd4-86264a3bb5f3.jpg)
run command
![EtePS55kjC](https://user-images.githubusercontent.com/24932386/193003454-c7912284-b6f1-4aa0-962c-b8b1bc7ccab1.jpg)

after command：
![cSpBSSOBjz](https://user-images.githubusercontent.com/24932386/193003293-ce791706-6131-44c5-a6f3-2286e11d53c0.jpg)

**Comment by Chilicyy** [comment]
是不是有历史遗留进程没有清理呀。

**Comment by jiheng1982** [comment]
> 

清理了，应该不是进程的问题，之前能跑几个epoch，然后崩了几次，就开在这里了

**Comment by Chilicyy** [comment]
我这边执行你的启动命令之后 不会出现这种情况呢，暂时无法复现你的问题。这边是运行最新的代码吗？如果执行其他项目代码是否一样的情况呢?

**Comment by jiheng1982** [comment]
是的，最新的代码，其他项目的代码不会，我也搞不会了

**Comment by Chilicyy** [comment]
这边可以试试在启动命令开头添加`CUDA_VISIBLE_DEVICES=0`
