### ISSUE TITLE
关于 tal 的背景类

### ISSUE THREAD

**Issue by FL77N** [meituan/YOLOv6#529]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [ ] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）  

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

你好，v6 里面的背景类不是 80 吗，这里设置为 0 不会出错吗？

**Comment by leedewdew** [comment]
Basically, it won't. But the question is why did you should change the background label?

**Comment by FL77N** [comment]
> Basically, it won't. But the question is why did you should change the background label?

因为我看到v6 code里面atss背景类设置的 num_classes，这里却设置为 0，而且这段代码是参考的paddle的，我看了 paddle 的代码这里也是设置的 num_classes，所以感到不解

**Comment by leedewdew** [comment]
so where is the bg label set to 0? show me your code pls

**Comment by leedewdew** [comment]
so where is the bg label set to 0? show me your code pls

**Comment by mtjhl** [comment]
@FL77N  请问您指的哪里设置为 0 ？

**Comment by FL77N** [comment]
> @FL77N 请问您指的哪里设置为 0 ？

https://github.com/meituan/YOLOv6/blob/618a59749c0312e54ec2b9f85744c9cb73d7c226/yolov6/assigners/tal_assigner.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L145

您好，就是这里，我看paddle的tal就是设置的bg_idx，然后我看v6 atss 里面也是设置的 80

**Comment by leedewdew** [comment]
Yep, Here leaves some misunderstanding. This line of code handles label padding when batch enabled. In fact, you can set any value for this label, since it will be filtered by 'fg_mask' later.

**Comment by FL77N** [comment]
> Yep, Here leaves some misunderstanding. This line of code handles label padding when batch enabled. In fact, you can set any value for this label, since it will be filtered by 'fg_mask' later.

3qu
