### ISSUE TITLE
AttributeError: 'Detect' object has no attribute 'grid_cell_size'

### ISSUE THREAD

**Issue by JanviAg** [meituan/YOLOv6#530]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）  

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

I have clone this repo and I ran the commands in the Google Colab.
The error is showing that detect object has no grid_size_cell attribute.
The following command contains the error.
#Inferencing
!python tools/infer.py --weights yolov6n.pt --source /content/YOLOv6/data/images/image1.jpg

Also, the original command has different file, but that file is not visible in the repo now. So, I changed the image for detection.

**Comment by Chilicyy** [comment]
Did you downloaded the new weights from [release 2.0](https://github.com/meituan/YOLOv6/releases/tag/0.2.0)?

**Comment by thaibao2001** [comment]
> 

I have the same problem too. After downloading the new weights from [release 2.0](https://github.com/meituan/YOLOv6/releases/tag/0.2.0), everything became normal.

**Comment by shravankumar147** [comment]
I have faced the same issue, it's resolved after using the weights from [YOLOv6/releases/tag/0.2.0](https://github.com/meituan/YOLOv6/releases/tag/0.2.0)

# Download Small Weight
!wget https://github.com/meituan/YOLOv6/releases/download/0.2.0/yolov6s.pt
