### ISSUE TITLE
请问自蒸馏是怎么起作用的？

### ISSUE THREAD

**Issue by Yamabukiss** [meituan/YOLOv6#537]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）  

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

我看到在没有设置teacher_weight 时 教师模型和学生模型是以一样的方式进行生成的 但是教师模型是每个epoch中不计算梯度的 那么他是怎么起作用呢？

**Comment by Chilicyy** [comment]
你好，自蒸馏主要是通过KL散度最小化教师模型和学生模型的预测，包括分类预测和回归预测。具体代码可参考[loss_distill.py](https://github.com/meituan/YOLOv6/blob/main/yolov6/models/loss_distill.py)，原理可参考[tech report](https://arxiv.org/abs/2209.02976)。

**Comment by Yamabukiss** [comment]
We limit the teacher to be the student itself but
pretrained, hence we call it self-distillation. 

技术报告中这句话我不是很明白 我没有设置预训练模型和teacher_model_path的前提下  
teacher_model是怎么让student_model 学习到知识的？

**Comment by Yamabukiss** [comment]
> 你好，自蒸馏主要是通过KL散度最小化教师模型和学生模型的预测，包括分类预测和回归预测。具体代码可参考[loss_distill.py](https://github.com/meituan/YOLOv6/blob/main/yolov6/models/loss_distill.py)，原理可参考[tech report](https://arxiv.org/abs/2209.02976)。

We limit the teacher to be the student itself but
pretrained, hence we call it self-distillation.

技术报告中这句话我不是很明白 我没有设置预训练模型和teacher_model_path的前提下
teacher_model是怎么让student_model 学习到知识的？

**Comment by Chilicyy** [comment]
这句话主要是强调教师模型跟学生模型的网络尺寸是一样的，因此称为自蒸馏。如果要采用自蒸馏技术，需要设置teacher_model_path。

**Comment by Yamabukiss** [comment]
> 这句话主要是强调教师模型跟学生模型的网络尺寸是一样的，因此称为自蒸馏。如果要采用自蒸馏技术，需要设置teacher_model_path。

好的 谢谢
