### ISSUE TITLE
about the 300 epoch

### ISSUE THREAD

**Issue by FL77N** [meituan/YOLOv6#538]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [ ] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）  

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

你好，我看 v6 small 的默认配置是 400 epoch 的，请问 300 epoch 的配置应该选择哪一个呢？

**Comment by mtjhl** [comment]
您好，我们并没有为 300 epoch 单独制定配置文件，跟 400 epoch 的配置文件是一致的。

**Comment by FL77N** [comment]
> 您好，我们并没有为 300 epoch 单独制定配置文件，跟 400 epoch 的配置文件是一致的。

好的，谢谢你

**Comment by FL77N** [comment]
> 您好，我们并没有为 300 epoch 单独制定配置文件，跟 400 epoch 的配置文件是一致的。

你好，我还有一个问题，我看论文里面讲是提前 1 epoch 关掉马赛克有助于解决 border 问题，但是配置里面是 15，是以哪个为主呢
