### ISSUE TITLE
Low mAP score on small objects

### ISSUE THREAD

**Issue by haritsahm** [meituan/YOLOv6#539]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）  

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

I trained different models with my custom dataset and compare the results. Overall, YOLOv6 surpass the previous models on my custom dataset especially for medium and large objects, but the result for small objects is very low YOLOv7 > YOLOv5 > YOLOv6. Do you know why this happens? I checked your paper but I can't find the metrics for small/medium/large objects, do you mind to share the result here?

| Model | mAP@0.5:0.95 | mAP@.50 | mAP@.75 | mAP@Small | mAP@Medium | mAP@Large |
| -------- | ------| ------| -----| -----| ------| -----|
YOLOv5m | 57.91% | 73.97% | 64.14% | 20.24% | 46.39% | 65.50% |
YOLOv7* | 60.35% | 75.14% | 67.06% | **22.05%** | 51.32% | 66.70% |
YOLOv6m* | **70.68%** | **89.44%** | **77.98%** | 17.30% | **52.89%** | **81.36%** |
YOLOv6m-PTQ-INT8* | 70.68% | 89.44% | 77.98% | 17.30% | 52.89% | 81.36% |
YOLOv6s-hs-RepOpt | 66.66% | 87.31% | 74.05% | 15.08% | 48.51% | 77.73% |
YOLOv6s-hs-RepOpt-QAT | **66.13%** | **87.20%** | **73.70%** | 15.08% | **48.16%** | **76.92%** |

**Comment by leedewdew** [comment]
Thank you for your feedback. 
If you don't mind inference speed, may adding a P2 from neck is good choice.
Of course, This will be the direction of our next efforts. If you are interested, help us pls, make YOLOv6 better together.

**Comment by gogocoded** [comment]
> 

Excuse me, what is P2?

**Comment by haritsahm** [comment]
I think by adding the Rep_p2 on RepPanNeck. So the backbone will return ERBlock [2,3,4,5] and the neck will fuse from layer [2, 3, 4, 5]

**Comment by gogocoded** [comment]
> I think by adding the Rep_p2 on RepPanNeck. So the backbone will return ERBlock [2,3,4,5] and the neck will fuse from layer [2, 3, 4, 5]

Ok，thanks
