### ISSUE TITLE
how to use tensorboard to monitor the training process？

### ISSUE THREAD

**Issue by LiJiahang617** [meituan/YOLOv6#54]
i ran the training process successfully,but i met two issues, first is that my mAP and losses are all 0:
![Screenshot from 2022-06-25 21-28-34](https://user-images.githubusercontent.com/103312600/175776037-ebf11932-83c1-45f5-893d-a1929b6ea41e.png)
second is that i don't know how to monitor my training process in tensorboard, what command should i type in terminal ? i tried typing: tensorboard --logdir=runs but it didn't work, and i don't have document in my runs file:
![Screenshot from 2022-06-25 21-42-18](https://user-images.githubusercontent.com/103312600/175776176-c72c80ff-f2ee-4e34-9994-b17b103f18f5.png)
just args, is that normal?

**Comment by czla** [comment]
1. You can pull the latest code and check your dataset, you can visualize your dataset by script `yolov6/data/vis_dataset.py`;
2. Check your `logdir`, normally it look likes `runs/train/exp_{num}`.
