### ISSUE TITLE
请给个简体中文说明书

### ISSUE THREAD

**Issue by futureflsl** [meituan/YOLOv6#540]
### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar feature requests.

### Description

请给个简体中文说明书

### Additional

请给个简体中文说明书

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by mtjhl** [comment]
好的，我们本周加上中文的 readme 文档。
