### ISSUE TITLE
Results do not correspond to current coco set

### ISSUE THREAD

**Issue by dream-floating** [meituan/YOLOv6#545]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [ ] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

根据readme的指引，我使用了coco数据集，并使用了如下训练命令：

> python -m torch.distributed.launch --nproc_per_node 4 tools/train.py  --batch 256  --conf configs/yolov6n.py --data data/coco.yaml --epoch 400 --device 0,1,2,3 --name yolov6n_coco

报了如下的错误：
`Evaluating mAP by pycocotools.
#
Saving runs/train/yolov6n_coco1/predictions.json...
loading annotations into memory...
Done (t=0.32s)
creating index...
index created!
Loading and preparing results...
ERROR in evaluate and save model.
ERROR in training loop or eval/save model.
Traceback (most recent call last):
  File "tools/train.py", line 126, in <module>
    main(args)
  File "tools/train.py", line 116, in main
    trainer.train()
  File "/home/YOLOv6-main/yolov6/core/engine.py", line 99, in train
    self.train_in_loop(self.epoch)
  File "/home/YOLOv6-main/yolov6/core/engine.py", line 119, in train_in_loop
    self.eval_and_save()
  File "/home/YOLOv6-main/yolov6/core/engine.py", line 157, in eval_and_save
    self.eval_model()
  File "/home/YOLOv6-main/yolov6/core/engine.py", line 199, in eval_model
    task='train')
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/YOLOv6-main/tools/eval.py", line 154, in run
    eval_result = val.eval_model(pred_result, model, dataloader, task)
  File "/home/YOLOv6-main/yolov6/core/evaler.py", line 261, in eval_model
    pred = anno.loadRes(pred_json)
  File "/opt/conda/lib/python3.7/site-packages/pycocotools/coco.py", line 328, in loadRes
    'Results do not correspond to current coco set'
AssertionError: Results do not correspond to current coco set
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 24023 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 24024 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 24025 closing signal SIGTERM`

**Comment by Chilicyy** [comment]
hi, did you download the file `instances_val2017.json` from COCODATASET [Website](https://cocodataset.org/#download), and organize your dataset directory correctly as shown in readme?

**Comment by dream-floating** [comment]
Yes,I have downloaded the file instances_val2017.json and placed it in the specified location as required by readme,but I found that there are three annotations files in the link of COCO dataset, namely 2017 Train/Val annotations [241MB], 2017 Stuff Train/Val annotations [1.1GB] and 2017 Panoptic Train/Val annotations [821MB].The file I downloaded is 2017 Train/Val annotations [241MB],Did I download the correct file?If so, what is the solution of the problem I put forward on github?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "meituan/YOLOv6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月12日(星期三) 下午2:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [meituan/YOLOv6] Results do not correspond to current coco set (Issue #545)





 
hi, did you download the file instances_val2017.json from COCODATASET Website, and organize your dataset directory correctly as shown in readme?

**Comment by Chilicyy** [comment]
We just check and verify the latest code from main branch, and it run normally. Are you using the latest code? If the problem still happens, pls provide us with further imformation, including the entire log, the dataset directory structure,ect so that we can help to locate the problem.

**Comment by dream-floating** [comment]
Yes, I'm sure I'm using the latest code.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "meituan/YOLOv6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月12日(星期三) 晚上7:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [meituan/YOLOv6] Results do not correspond to current coco set (Issue #545)





 
We just check and verify the latest code from main branch, and it run normally. Are you using the latest code? If the problem still happens, pls provide us with further imformation, including the entire log, the dataset directory structure,ect so that we can help to locate the problem.

**Comment by Chilicyy** [comment]
You can try to add the args `--check-images --check-labels` in your training command. If the problem still happens, pls provide us with further imformation, including the entire log, the dataset directory structure,ect so that we can help to locate the issue.
