### ISSUE TITLE
利用coco评估错误

### ISSUE THREAD

**Issue by Wisdom2wisdom** [meituan/YOLOv6#546]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

Calculate metric failed, might check dataset.

### Additional

Calculate metric failed, might check dataset.

**Comment by Chilicyy** [comment]
你好，麻烦提供更详细的信息。

**Comment by Wisdom2wisdom** [comment]
![image](https://user-images.githubusercontent.com/91510018/195342881-73c072a4-b5ef-4d8e-825b-ae361669d98c.png)

**Comment by shensheng272** [comment]
你好，错误提示显示计算指标过程中出现问题。大概率是验证集的数据格式有问题，可以检测下验证集的数据格式是否符合yolo的格式。
另外想问下验证集的图片数量大概是多少，图片中看起来应该是100张左右？

**Comment by Wisdom2wisdom** [comment]
验证集数量107，验证集格式没有问题，在windows正常运行，但是在ubuntu出现以上错误

**Comment by shensheng272** [comment]
是否可能是数据文件在不同平台上的换行等字符问题？看看能否在ubuntu上生成标注文件。另外也可以注意下数据缓存，可以加上  --check-images    --check-labels
