### ISSUE TITLE
eval的时候，有两个ap指标

### ISSUE THREAD

**Issue by riskeverything** [meituan/YOLOv6#554]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

使用tools/eval.py进行验证，会有两个ap的结果产生，这两个ap的结果差异有点明显，尤其是人脸的ap，要比pycocotools高接近2个点，这个正常嘛？需要以哪个为准？
![1](https://user-images.githubusercontent.com/17629812/196084224-b25e1776-4eb0-42d3-b90d-66e1a4a61dce.JPG)

**Comment by shensheng272** [comment]
你好，两种不同的ap计算方式主要涵盖了yolov5和pycocotools两种比较常见的评估方法。
建议在自己的数据集上多采用yolov5的评估方式，因为yolov5的计算ap曲线采样的点更多一些（100vs1000），相对更精确，而且评价代码运行速度上也更快一些。
