### ISSUE TITLE
Training with custom data, mAP =-1?

### ISSUE THREAD

**Issue by anhTuan0712** [meituan/YOLOv6#555]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

1. I trained my own data (follow instructions here: https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md)
2. Train configuration
**cmd train:** 
python tools/train.py --batch 8 --conf configs/yolov6l_finetune.py --data data/dataset.yaml --device 0 --check-images --check-labels
**yaml file:**
is_coco: False
nc: 3 # number of classes
names: ["crack", "pothole", "crack_mix"] # class names
**cfg**:
  I used the file yolov6l_finetune.py and did not edit anything.
4. Issue:
   All mAP are equal to -1
Log image during training:
![image](https://user-images.githubusercontent.com/75367671/196102893-617118dd-d474-4d9b-9b4d-859fe3eae779.png)
Image when running cmd: python tools/eval.py --data data/dataset.yaml  --weights last_ckpt.pt --device 0 --batch 8 (I tried batch = 1,2,4,8,16,32 = 1,2,4,8,16,32)
![image](https://user-images.githubusercontent.com/75367671/196102644-6ee2977c-1c3c-434c-9ff1-25d6a6468122.png)
how can I solve this issue?

### Additional

I have consulted the following links:
https://github.com/meituan/YOLOv6/issues/523
https://github.com/meituan/YOLOv6/issues/527
**when inference with last_ckpt.pt still gives good results.**

**Comment by shensheng272** [comment]
AP = -1 happened when val dataset is wrong (format, file structure).
`when inference with last_ckpt.pt still gives good results.` Did you mean trained model is okay to infer image on val images?
If infer result to very close to label info, model did learn something.
Could you provide same example of the names of val images and labels, code might  failed to parse file name?

**Comment by anhTuan0712** [comment]
> Could you provide same example of the names of val images and labels, code might failed to parse file name?

Hi @shensheng272, thank you.
Here is a comparison image between the dataset (Val ) and the inference result.
![010](https://user-images.githubusercontent.com/75367671/196148322-e62e7adf-b56c-4329-a71c-645495800f41.PNG)
![122](https://user-images.githubusercontent.com/75367671/196148358-f0bd9403-4420-45a7-9264-73189ff053c6.PNG)
![143](https://user-images.githubusercontent.com/75367671/196148382-479cb677-6b16-46be-8f34-3d32a397b2a8.PNG)

**Comment by anhTuan0712** [comment]
> Did you mean trained model is okay to infer image on val images?
> If infer result to very close to label info, model did learn something.

Yes that's right, but when calculating mAP, the result is -1.

**Comment by anhTuan0712** [comment]
Sorry, the problem is caused by the dataset (the annotation in Val is faulty).
I would like to end this issue.
