### ISSUE TITLE
TypeError: _output_padding() missing 1 required positional argument: 'num_spatial_dims'

### ISSUE THREAD

**Issue by yitian8377** [meituan/YOLOv6#557]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [ ] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

拉取最新的代碼，執行：
CUDA_VISIBLE_DEVICES=0 python tools/train.py \
       --data ./data/coco.yaml \
       --output-dir ./runs/opt_train_v6s_ptq \
       --conf configs/repopt/yolov6s_opt_qat.py \
       --quant \
       --calib \
       --batch 32 \
       --workers 0

報錯如下：
/usr/local/anaconda3/envs/mmcv/bin/python /data/_KJT_Workspace_HDD/_Codes/yitian/Python/YOLOv6/tools/train.py --data ./data/coco.yaml --output-dir ./runs/opt_train_v6s_ptq --conf configs/repopt/yolov6s_opt_qat.py --quant --calib --batch 32 --workers 0
/usr/local/anaconda3/envs/mmcv/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Using 1 GPU for training... 
training args are: Namespace(batch_size=32, calib=True, check_images=False, check_labels=False, conf_file='configs/repopt/yolov6s_opt_qat.py', data_path='./data/coco.yaml', device='0', dist_url='env://', distill=False, distill_feat=False, epochs=400, eval_final_only=False, eval_interval=20, gpu_count=0, heavy_eval_range=50, img_size=640, local_rank=-1, name='exp', output_dir='./runs/opt_train_v6s_ptq', quant=True, rank=-1, resume=False, save_ckpt_on_last_n_epoch=-1, save_dir='runs/opt_train_v6s_ptq/exp3', stop_aug_last_n_epoch=15, teacher_model_path=None, temperature=20, workers=0, world_size=1, write_trainbatch_tb=False)

Train: Final numbers of valid images: 118287/ labels: 118287. 
7.9s for dataset initialization.
Val: Final numbers of valid images: 5000/ labels: 5000. 
0.3s for dataset initialization.
Model: Model(
  (backbone): EfficientRep(
    (stem): RealVGGBlock(
      (relu): ReLU(inplace=True)
      (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn): BatchNorm2d(32, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (se): Identity()
    )
    (ERBlock_2): Sequential(
      (0): RealVGGBlock(
        (relu): ReLU(inplace=True)
        (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (se): Identity()
      )
      (1): RepBlock(
        (conv1): RealVGGBlock(
          (relu): ReLU(inplace=True)
          (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (se): Identity()
        )
        (block): Sequential(
          (0): RealVGGBlock(
            (relu): ReLU(inplace=True)
            (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (se): Identity()
          )
        )
      )
    )
    (ERBlock_3): Sequential(
      (0): RealVGGBlock(
        (relu): ReLU(inplace=True)
        (conv): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (se): Identity()
      )
      (1): RepBlock(
        (conv1): RealVGGBlock(
          (relu): ReLU(inplace=True)
          (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (se): Identity()
        )
        (block): Sequential(
          (0): RealVGGBlock(
            (relu): ReLU(inplace=True)
            (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (se): Identity()
          )
          (1): RealVGGBlock(
            (relu): ReLU(inplace=True)
            (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (se): Identity()
          )
          (2): RealVGGBlock(
            (relu): ReLU(inplace=True)
            (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (se): Identity()
          )
        )
      )
    )
    (ERBlock_4): Sequential(
      (0): RealVGGBlock(
        (relu): ReLU(inplace=True)
        (conv): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (se): Identity()
      )
      (1): RepBlock(
        (conv1): RealVGGBlock(
          (relu): ReLU(inplace=True)
          (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (se): Identity()
        )
        (block): Sequential(
          (0): RealVGGBlock(
            (relu): ReLU(inplace=True)
            (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (se): Identity()
          )
          (1): RealVGGBlock(
            (relu): ReLU(inplace=True)
            (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (se): Identity()
          )
          (2): RealVGGBlock(
            (relu): ReLU(inplace=True)
            (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (se): Identity()
          )
          (3): RealVGGBlock(
            (relu): ReLU(inplace=True)
            (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (se): Identity()
          )
          (4): RealVGGBlock(
            (relu): ReLU(inplace=True)
            (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (se): Identity()
          )
        )
      )
    )
    (ERBlock_5): Sequential(
      (0): RealVGGBlock(
        (relu): ReLU(inplace=True)
        (conv): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (se): Identity()
      )
      (1): RepBlock(
        (conv1): RealVGGBlock(
          (relu): ReLU(inplace=True)
          (conv): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (se): Identity()
        )
        (block): Sequential(
          (0): RealVGGBlock(
            (relu): ReLU(inplace=True)
            (conv): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (se): Identity()
          )
        )
      )
      (2): SimSPPF(
        (cv1): SimConv(
          (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): ReLU(inplace=True)
        )
        (cv2): SimConv(
          (conv): Conv2d(1024, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn): BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): ReLU(inplace=True)
        )
        (m): MaxPool2d(kernel_size=5, stride=1, padding=2, dilation=1, ceil_mode=False)
      )
    )
  )
  (neck): RepPANNeck(
    (Rep_p4): RepBlock(
      (conv1): RealVGGBlock(
        (relu): ReLU(inplace=True)
        (conv): Conv2d(384, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (se): Identity()
      )
      (block): Sequential(
        (0): RealVGGBlock(
          (relu): ReLU(inplace=True)
          (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (se): Identity()
        )
        (1): RealVGGBlock(
          (relu): ReLU(inplace=True)
          (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (se): Identity()
        )
        (2): RealVGGBlock(
          (relu): ReLU(inplace=True)
          (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (se): Identity()
        )
      )
    )
    (Rep_p3): RepBlock(
      (conv1): RealVGGBlock(
        (relu): ReLU(inplace=True)
        (conv): Conv2d(192, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (se): Identity()
      )
      (block): Sequential(
        (0): RealVGGBlock(
          (relu): ReLU(inplace=True)
          (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (se): Identity()
        )
        (1): RealVGGBlock(
          (relu): ReLU(inplace=True)
          (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (se): Identity()
        )
        (2): RealVGGBlock(
          (relu): ReLU(inplace=True)
          (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (se): Identity()
        )
      )
    )
    (Rep_n3): RepBlock(
      (conv1): RealVGGBlock(
        (relu): ReLU(inplace=True)
        (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (se): Identity()
      )
      (block): Sequential(
        (0): RealVGGBlock(
          (relu): ReLU(inplace=True)
          (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (se): Identity()
        )
        (1): RealVGGBlock(
          (relu): ReLU(inplace=True)
          (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (se): Identity()
        )
        (2): RealVGGBlock(
          (relu): ReLU(inplace=True)
          (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (se): Identity()
        )
      )
    )
    (Rep_n4): RepBlock(
      (conv1): RealVGGBlock(
        (relu): ReLU(inplace=True)
        (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (se): Identity()
      )
      (block): Sequential(
        (0): RealVGGBlock(
          (relu): ReLU(inplace=True)
          (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (se): Identity()
        )
        (1): RealVGGBlock(
          (relu): ReLU(inplace=True)
          (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (se): Identity()
        )
        (2): RealVGGBlock(
          (relu): ReLU(inplace=True)
          (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (se): Identity()
        )
      )
    )
    (reduce_layer0): SimConv(
      (conv): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): ReLU(inplace=True)
    )
    (upsample0): Transpose(
      (upsample_transpose): ConvTranspose2d(128, 128, kernel_size=(2, 2), stride=(2, 2))
    )
    (reduce_layer1): SimConv(
      (conv): Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): ReLU(inplace=True)
    )
    (upsample1): Transpose(
      (upsample_transpose): ConvTranspose2d(64, 64, kernel_size=(2, 2), stride=(2, 2))
    )
    (downsample2): SimConv(
      (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): ReLU(inplace=True)
    )
    (downsample1): SimConv(
      (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): ReLU(inplace=True)
    )
  )
  (detect): Detect(
    (proj_conv): Conv2d(17, 1, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (stems): ModuleList(
      (0): Conv(
        (conv): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (2): Conv(
        (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
    )
    (cls_convs): ModuleList(
      (0): Conv(
        (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (2): Conv(
        (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
    )
    (reg_convs): ModuleList(
      (0): Conv(
        (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (1): Conv(
        (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
      (2): Conv(
        (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU(inplace=True)
      )
    )
    (cls_preds): ModuleList(
      (0): Conv2d(64, 80, kernel_size=(1, 1), stride=(1, 1))
      (1): Conv2d(128, 80, kernel_size=(1, 1), stride=(1, 1))
      (2): Conv2d(256, 80, kernel_size=(1, 1), stride=(1, 1))
    )
    (reg_preds): ModuleList(
      (0): Conv2d(64, 4, kernel_size=(1, 1), stride=(1, 1))
      (1): Conv2d(128, 4, kernel_size=(1, 1), stride=(1, 1))
      (2): Conv2d(256, 4, kernel_size=(1, 1), stride=(1, 1))
    )
  )
)
Skip Layer detect.proj_conv
Insert fakequant after upsample
extract scales:  tensor(0.98975, device='cuda:0', dtype=torch.float16) tensor(0.99219, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.98975, device='cuda:0', dtype=torch.float16) tensor(0.99219, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99072, device='cuda:0', dtype=torch.float16) tensor(0.99170, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99121, device='cuda:0', dtype=torch.float16) tensor(0.99170, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99023, device='cuda:0', dtype=torch.float16) tensor(0.99121, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99072, device='cuda:0', dtype=torch.float16) tensor(0.99170, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99072, device='cuda:0', dtype=torch.float16) tensor(0.99170, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99121, device='cuda:0', dtype=torch.float16) tensor(0.99121, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99121, device='cuda:0', dtype=torch.float16) tensor(0.99170, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99072, device='cuda:0', dtype=torch.float16) tensor(0.99121, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99072, device='cuda:0', dtype=torch.float16) tensor(0.99121, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99121, device='cuda:0', dtype=torch.float16) tensor(0.99121, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99121, device='cuda:0', dtype=torch.float16) tensor(0.99121, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99072, device='cuda:0', dtype=torch.float16) tensor(0.99121, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99072, device='cuda:0', dtype=torch.float16) tensor(0.99121, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99072, device='cuda:0', dtype=torch.float16) tensor(0.99121, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99072, device='cuda:0', dtype=torch.float16) tensor(0.99121, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99072, device='cuda:0', dtype=torch.float16) tensor(0.99121, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99072, device='cuda:0', dtype=torch.float16) tensor(0.99121, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99072, device='cuda:0', dtype=torch.float16) tensor(0.99121, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99072, device='cuda:0', dtype=torch.float16) tensor(0.99121, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99072, device='cuda:0', dtype=torch.float16) tensor(0.99121, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99072, device='cuda:0', dtype=torch.float16) tensor(0.99121, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.98926, device='cuda:0', dtype=torch.float16) tensor(0.99268, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99072, device='cuda:0', dtype=torch.float16) tensor(0.99219, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99072, device='cuda:0', dtype=torch.float16) tensor(0.99170, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99072, device='cuda:0', dtype=torch.float16) tensor(0.99219, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99072, device='cuda:0', dtype=torch.float16) tensor(0.99170, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99121, device='cuda:0', dtype=torch.float16) tensor(0.99121, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99121, device='cuda:0', dtype=torch.float16) tensor(0.99121, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99121, device='cuda:0', dtype=torch.float16) tensor(0.99170, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99072, device='cuda:0', dtype=torch.float16) tensor(0.99121, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99072, device='cuda:0', dtype=torch.float16) tensor(0.99121, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99072, device='cuda:0', dtype=torch.float16) tensor(0.99121, device='cuda:0', dtype=torch.float16)
extract scales:  tensor(0.99072, device='cuda:0', dtype=torch.float16) tensor(0.99121, device='cuda:0', dtype=torch.float16)
  0%|          | 0/4 [00:15<?, ?it/s]
Traceback (most recent call last):
  File "/data/_KJT_Workspace_HDD/_Codes/yitian/Python/YOLOv6/tools/train.py", line 126, in <module>
    main(args)
  File "/data/_KJT_Workspace_HDD/_Codes/yitian/Python/YOLOv6/tools/train.py", line 114, in main
    trainer.calibrate(cfg)
  File "/data/_KJT_Workspace_HDD/_Codes/yitian/Python/YOLOv6/yolov6/core/engine.py", line 500, in calibrate
    ptq_calibrate(self.model, self.train_loader, cfg)
  File "/data/_KJT_Workspace_HDD/_Codes/yitian/Python/YOLOv6/tools/qat/qat_utils.py", line 58, in ptq_calibrate
    collect_stats(model, train_loader, cfg.ptq.calib_batches)
  File "/data/_KJT_Workspace_HDD/_Codes/yitian/Python/YOLOv6/tools/qat/qat_utils.py", line 26, in collect_stats
    model(image.cuda())
  File "/usr/local/anaconda3/envs/mmcv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/_KJT_Workspace_HDD/_Codes/yitian/Python/YOLOv6/yolov6/models/yolo.py", line 40, in forward
    x = self.neck(x)
  File "/usr/local/anaconda3/envs/mmcv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/_KJT_Workspace_HDD/_Codes/yitian/Python/YOLOv6/yolov6/models/reppan.py", line 105, in forward
    upsample_feat0 = self.upsample0(fpn_out0)
  File "/usr/local/anaconda3/envs/mmcv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/_KJT_Workspace_HDD/_Codes/yitian/Python/YOLOv6/yolov6/layers/common.py", line 137, in forward
    return self.upsample_transpose(x)
  File "/usr/local/anaconda3/envs/mmcv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/anaconda3/envs/mmcv/lib/python3.8/site-packages/pytorch_quantization/nn/modules/quant_conv.py", line 341, in forward
    output_padding = self._output_padding(input, output_size, self.stride, self.padding, self.kernel_size)
TypeError: _output_padding() missing 1 required positional argument: 'num_spatial_dims'

Process finished with exit code 1

envs:
torch                              1.12.1
onnx                               1.12.0
pytorch-quantization               2.1.2

**Comment by yitian8377** [comment]
> @yitian8377 I think this is related to PyTorch version, similar to what I found in my experiments #485. Try to use `pytorch<=1.12.0` or nvidia pytorch docker `nvcr.io/nvidia/pytorch:22.04-py3` until the author can patch the codes for latest pytorch version

Thanks for your reply , but I still report the same error after modifying  ‘pytorch==1.12.0‘’

**Comment by semihhdemirel** [comment]
@yitian8377 I had a similar error. I fixed my error using "pytorch==1.11.0".

**Comment by lueker** [comment]
@EchoEsprit 谢谢大佬，是这里的问题，改完就可以了
