### ISSUE TITLE
训练yolov6t时会出现nan值

### ISSUE THREAD

**Issue by wssywh** [meituan/YOLOv6#567]
在使用coco数据集复现时，config文件使用yolov6t，训练的时候模型输出值会变为nan，使用yolov6s就不会出现

**Comment by mtjhl** [comment]
您好，请问出现 nan 后的报错信息是什么？方便发一下吗？

**Comment by Chilicyy** [comment]
@wssywh 您好，如果需要复现coco数据集上的指标，请参考README ->Reproduce our results on COCO->For s/tiny model里面的启动命令进行训练。

**Comment by wssywh** [comment]
> 您好，请问出现 nan 后的报错信息是什么？方便发一下吗？

![Image_20221025092945](https://user-images.githubusercontent.com/19625405/197660897-6b923df2-8fa9-4384-a237-f39a16bae0ed.png)

**Comment by wssywh** [comment]
> @wssywh 您好，如果需要复现coco数据集上的指标，请参考README ->Reproduce our results on COCO->For s/tiny model里面的启动命令进行训练。

是按照readme上面的命令来复现的，readme上面是使用了8张卡，我复现的时候使用的是4张卡，batch_size数减半，其他的参数是一样的

**Comment by Chilicyy** [comment]
@wssywh 看起来这边的代码不是最新的，麻烦拉取最新的代码试试。

**Comment by wssywh** [comment]
@Chilicyy 这个我测试过，我拉取最新的代码训练yolov6t，还是会出现一样的错误，我排查了一下出问题的原因，主要是和混合精度训练有关，把混合精度训练关掉，就不会出现这个问题

**Comment by wangq95** [comment]
@Chilicyy 请问要怎么关掉混合精度训练？
