### ISSUE TITLE
部署时报错

### ISSUE THREAD

**Issue by Shrinco** [meituan/YOLOv6#580]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

在用相关的脚本把 yolov6l.pt 转换为 yolov6l.trt 文件后，使用部署代码部署时出现了下列错误，请问这是什么原因？该如何解决？
![image](https://user-images.githubusercontent.com/50402380/198210831-48f0bf69-da6b-4b0f-ad13-15682e281bd4.png)

**Comment by mtjhl** [comment]
您看一下导出的 onnx 模型的输入节点名字是否是 `image_arrays`。

**Comment by Shrinco** [comment]
您好，是这个吗？
![image](https://user-images.githubusercontent.com/50402380/198237122-8a7faaad-1cd2-48c1-a4af-a5f77158bccf.png)

**Comment by Shrinco** [comment]
> 您看一下导出的 onnx 模型的输入节点名字是否是 `image_arrays`。

您好，我修改了代码中的输入节点名称，已经解决啦，谢谢。
