### ISSUE TITLE
How to combine two weights: one from without using pretrained and another using pretrained?

### ISSUE THREAD

**Issue by ahmetfurkaann** [meituan/YOLOv6#583]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [x] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

I trained 2 different models, using and not using the pre-trained model. These two weights perform differently on the same images (one makes more accurate decisions, the other performs better detection). My question is, is it possible to create a co-decision mechanism using both weight files?

**Comment by mtjhl** [comment]
Suppose output of model A is a tensor [5400, 84], 5400 is the number of bboxes, 84 is compose by 80 (classes) and 4( bboxes), output of model B is also [5400, 84], you can combine the classes output A ( [5400, 80] with the bboxes output of B ([5400,4]). Maybe this can work.
You can also use ensemble methods, put output of model A and model B togather to do NMS, maybe this can improve the mAP.

**Comment by ahmetfurkaann** [comment]
So, do you have any suggestions to implement the ensemble method for YOLOv6? I did some research but couldn't find much.

**Comment by mtjhl** [comment]
> Suppose output of model A is a tensor [5400, 84], 5400 is the number of bboxes, 84 is compose by 80 (classes) and 4( bboxes), output of model B is also [5400, 84], you can combine the classes output A ( [5400, 80] with the bboxes output of B ([5400,4]). Maybe this can work. You can also use ensemble methods, put output of model A and model B together , then applay NMS, maybe this method can improve the mAP.

You can try those two methods I mentioned above, and find whether it is effective.
