### ISSUE TITLE
关于M尺寸模型的head结构的疑问

### ISSUE THREAD

**Issue by Wang-Kaige** [meituan/YOLOv6#584]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

您好！首先感谢贵团队对于代码的开源以及对问题的解答！
在我复现YOLO v6-M模型时，通过打印网络结构我发现在训练时effidehead文件中Detect类的forward函数中cls_output的尺寸为[32, 80, 80, 80];[32, 80, 40, 40];[32, 80, 20, 20]，这我可以理解为在batchsize为32情况下对于三种不同尺寸的特征图均产生80类的信息输出；但打印reg_output的尺寸时，reg_output却为[32, 68, 80, 80];[32, 68, 40, 40];[32, 68, 20, 20]，请问这里的68代表什么呢？如果是锚框的位置信息，为什么不是推理时reg_output输出的4个位置信息呢？
我在查看网络结构时也发现，训练时head部分结构为
(reg_preds): ModuleList(
      (0): Conv2d(96, 68, kernel_size=(1, 1), stride=(1, 1))
      (1): Conv2d(192, 68, kernel_size=(1, 1), stride=(1, 1))
      (2): Conv2d(384, 68, kernel_size=(1, 1), stride=(1, 1))
    )
这也证明了reg_output输出的通道是68，还请您解答下68的含义是什么。

**Comment by Chilicyy** [comment]
您好，这里的68由4*17计算得到的，由于M/L网络我们默认额外采用Distribution Focal Loss (DFL)进行坐标回归学习，因此会比一般的bbox回归输出维度更多。

**Comment by Wang-Kaige** [comment]
> 您好，这里的68由4*17计算得到的，由于M/L网络我们默认额外采用Distribution Focal Loss (DFL)进行坐标回归学习，因此会比一般的bbox回归输出维度更多。

谢谢！我查看了论文中关于DFL的描述后，确实发现了多了17倍的参数值的描述。还有一个问题，当我使用M尺寸网络时，head部分的结构是不是将只把分类和回归分支进行了解耦，并没有将回归分支中的bbox尺寸支路和前后景判断支路解耦，请问我理解的正确吗？我提出上述问题的依据是查看了head部分的网络结构，发现回归支路只是由一组reg_convs和reg_preds的卷积级联构成，并没有进行bbox旁路和前后景判断旁路的细分。请您不吝赐教！

**Comment by Chilicyy** [comment]
> > 您好，这里的68由4*17计算得到的，由于M/L网络我们默认额外采用Distribution Focal Loss (DFL)进行坐标回归学习，因此会比一般的bbox回归输出维度更多。
> 
> 谢谢！我查看了论文中关于DFL的描述后，确实发现了多了17倍的参数值的描述。还有一个问题，当我使用M尺寸网络时，head部分的结构是不是将只把分类和回归分支进行了解耦，并没有将回归分支中的bbox尺寸支路和前后景判断支路解耦，请问我理解的正确吗？我提出上述问题的依据是查看了head部分的网络结构，发现回归支路只是由一组reg_convs和reg_preds的卷积级联构成，并没有进行bbox旁路和前后景判断旁路的细分。请您不吝赐教！

v2版本的代码去掉了前景背景判断分支，关于背景的判断会在分类分支中与目标类别一起学习。

**Comment by Wang-Kaige** [comment]
> > > 您好，这里的68由4*17计算得到的，由于M/L网络我们默认额外采用Distribution Focal Loss (DFL)进行坐标回归学习，因此会比一般的bbox回归输出维度更多。
> > 
> > 
> > 谢谢！我查看了论文中关于DFL的描述后，确实发现了多了17倍的参数值的描述。还有一个问题，当我使用M尺寸网络时，head部分的结构是不是将只把分类和回归分支进行了解耦，并没有将回归分支中的bbox尺寸支路和前后景判断支路解耦，请问我理解的正确吗？我提出上述问题的依据是查看了head部分的网络结构，发现回归支路只是由一组reg_convs和reg_preds的卷积级联构成，并没有进行bbox旁路和前后景判断旁路的细分。请您不吝赐教！
> 
> v2版本的代码去掉了前景背景判断分支，关于背景的判断会在分类分支中与目标类别一起学习。

十分感谢！因为v6论文中没有更具体的结构图，包括网络上其他人画的结构图也有一些错误，故上述问题是在我深入学习v6时遇到的。目前我的问题已经结束了，祝好！
