### ISSUE TITLE
测试精度比YOLOv5低8个百分点

### ISSUE THREAD

**Issue by LvShuaiChao** [meituan/YOLOv6#59]
对于单类目标的训练测试，YOLOv6最高只能上86%，但是YOLOv5却可以轻松上90%。数据集使用的同样的数据集，但精度却差这么多，这是怎么一回事呢？

**Comment by SCIKings** [comment]
是不是一因为没有使用预训练权重

**Comment by LvShuaiChao** [comment]
> 是不是一因为没有使用预训练权重

两者都使用了预训练权重

**Comment by ChHanXiao** [comment]
我的数据集也并没有提升，很尴尬

**Comment by acai66** [comment]
请问测试的数据集是密集小目标数据集吗？

**Comment by cumtb-zyh** [comment]
插个眼，我的也是，没有yolov5的精度高

**Comment by LvShuaiChao** [comment]
![Uploading image.png…]()
YOLOv6的几个版本都用过了，发现效果都不好

**Comment by fire717** [comment]
这就尴尬了，这不是打官方脸嘛

**Comment by 1411030449** [comment]
是的，在我自己的数据集上比yolov5也低了8-10个点
