### ISSUE TITLE
Yolov6 with Flask

### ISSUE THREAD

**Issue by ahmed024** [meituan/YOLOv6#592]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

I have a website that accesses the user's camera and sends the frames to flask surver(in realtime). This is how I get the frame on the Flask server.

```
---Some other code-------
@app.route('/yolo', methods = ['POST'])
def GetImage():
     image_file = request.files['image']
```
When I get the frame with the above code, I tried to do yolov6 object detection on it and return the result to the website.

```
from yolov6.core.inferer import Inferer
import json

---Some other code-------
@app.route('/yolo', methods = ['POST'])
def GetImage():
     image_file = request.files['image']
     inferer = Inferer(image_file, weights, device, yaml, img_size, half)
     output = inferer.infer(conf_thres, iou_thres, classes)
     Result=jsonify(output),200,{"Content-Type":"application/json"}
     return (Result)
```

However, the issue I'm having is that I can't get Yolov6 to process my frame. This error is produced by the code above.

`TypeError: expected str, bytes or os.PathLike object, not FileStorage`

I tried PIL Image and np.array, but neither worked for me so far.

The Inferer function can be found [here](https://github.com/meituan/YOLOv6/blob/main/yolov6/core/inferer.py)

**Comment by mtjhl** [comment]
Where does this error `TypeError: expected str, bytes or os.PathLike object, not FileStorage` occurs?
Maybe the `jsonify` need dict as parameter. You need to check whether the `output`’s type is dict.

**Comment by ahmed024** [comment]
I believe the error occurs because the image type required by the Inferer function differs from the type of image I am passing. For example, Inferer requires str, bytes, or os.PathLike object, but I'm passing FileStorage. I attempted to convert the image to bytes, but it did not work.

**Comment by dsbyprateekg** [comment]
@ahmed024 instead of loading the input image as `image_file = request.files['image']` , try to load it with Image.open() then-
1. convert it to RGB format
2. then convert it to numpy array format
And then pass it to your Inferer()
