### ISSUE TITLE
--save-img flag is not logically correct

### ISSUE THREAD

**Issue by iampreviero** [meituan/YOLOv6#593]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [ ] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

In tools/infer.py, line 29:  `parser.add_argument('--save-img', action='store_false', help='save visuallized inference results.')`

`store_false` implies that when calling from terminal `--save-img` will **not** save the images/videos etc. This is counter intuitive / semantically incorrect. Replace the name with something like `--no-save`, so that when specified images are not saved. 

By default, images should be saved anyway.

**Comment by mtjhl** [comment]
Thank you very much, we have fix this logical problem.
