### ISSUE TITLE
what does the numbers of data_aug stands for?

### ISSUE THREAD

**Issue by asafberreby** [meituan/YOLOv6#598]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [x] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

Hello, i wanted to ask about:

`data_aug = dict(
    hsv_h=0.0138,
    hsv_s=0.664,
    hsv_v=0.464,
    degrees=0.373,
    translate=0.245,
    scale=0.898,
    shear=0.602,
    flipud=0.00856,
    fliplr=0.5,
    mosaic=1.0,
    mixup=0.243,
)`

what does the numbers stands for? it is probability?

**Comment by mtjhl** [comment]
Some of them are probability, such as flipup, fliplr, mosaic; some of them are not, such as scales, you can know what are they doing here, for example, the scale is the parameter to control the zoom ratio.
https://github.com/meituan/YOLOv6/blob/1563345ef72b26ab011627d97bfb74fcbea17914/yolov6/data/data_augment.py#L124
