### ISSUE TITLE
YOLOv6n RuntimeError: CUDA error: device-side assert triggered   

### ISSUE THREAD

**Issue by LvShuaiChao** [meituan/YOLOv6#60]
![image](https://user-images.githubusercontent.com/35528109/175797198-a890e00a-46e5-4f48-afa2-d0ca0210678f.png)

**Comment by khwengXU** [comment]
Hi, what's your training shell? When the errors happened?

**Comment by LvShuaiChao** [comment]
> 

python tools/train.py --batch 4 --conf configs/yolov6n.py --data ./data/coco.yaml --device 0 --workers 0

**Comment by yydc-0** [comment]
have you solved the problem?

**Comment by eorroot** [comment]
I have the same problem

**Comment by cvirxsc** [comment]
I have the same problem, and the program always stops at the same iteration and then reports an error. What should I do?

**Comment by sohaiblaraba** [comment]
Same here...

**Comment by smile366** [comment]
你的问题解决了吗
