### ISSUE TITLE
Question from paper

### ISSUE THREAD

**Issue by d5423197** [meituan/YOLOv6#601]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

hello there,

I have a question about the sentence "In YOLOv6, we adopt the anchor pointbased paradigm, whose box regression branch actually predicts the distance from the anchor point to the four sides of
the bounding boxes." from the paper. 

I have read the code for the part computing the loss. I could not find where the code corresponds to this sentence. Could you point it out?

Thanks,

ZD

**Comment by Chilicyy** [comment]
Hi, you can refer to this line https://github.com/meituan/YOLOv6/blob/main/yolov6/models/effidehead.py#L126

**Comment by mtjhl** [comment]
@d5423197 
You can refer to this line:
https://github.com/meituan/YOLOv6/blob/1563345ef72b26ab011627d97bfb74fcbea17914/yolov6/models/effidehead.py#L126

**Comment by Chilicyy** [comment]
> Hello there,
> 
> Thanks for your reply. What about in training?

In training, you can refer to this line : https://github.com/meituan/YOLOv6/blob/main/yolov6/models/loss.py#L206.
