### ISSUE TITLE
Background images cause CLS loss to go to inf

### ISSUE THREAD

**Issue by ehiggins0** [meituan/YOLOv6#602]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

Hello, I am training on a custom dataset with two objects that are very similar to each other, so am using background images to remove false positives. There are ~34k positive images and ~58k negative images in the dataset. When training, excess background images cause the cls loss to go to inf, which causes the process to crash on multi-gpu instances. Are there any ways to fix this?

cls_loss
![train_cls_loss](https://user-images.githubusercontent.com/88253228/200686408-2176aebe-5a11-4662-83dc-a3119512ebcf.svg)

**Comment by mtjhl** [comment]
We are fixing this problem now, we will inform you when it is fixed. Sorry for the inconvince.

**Comment by Chilicyy** [comment]
@ehiggins0 hi, are you using the latest code?

**Comment by mtjhl** [comment]
We have fix this bug now, please pull the latest code. Sorry for the inconvince. @ehiggins0

**Comment by ehiggins0** [comment]
Seems like that fixed it, thank you!
