### ISSUE TITLE
cahce images in ram

### ISSUE THREAD

**Issue by eorroot** [meituan/YOLOv6#604]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

是否考虑增加 cache  images in ram 方法，v6 对单卡训练不太友好，对有大内存用户，可以用内存换速度

**Comment by mtjhl** [comment]
我们可以记下这个需求，但是对于 4 卡或者 8 卡， 都加载到内存，需要大概 500G - 1T 内存，有点大。

**Comment by eorroot** [comment]
非常感谢您的回复！
