### ISSUE TITLE
Does YOLOv6 support NVIDIA Jetson deployment? How is the inference at the edge? 

### ISSUE THREAD

**Issue by notelainemade** [meituan/YOLOv6#61]

**Comment by khwengXU** [comment]
Thanks for your attentions！
We have received your suggestion, we will consider the integration.

**Comment by Samsara-1999** [comment]
I also have this question, and I'm ready to run this model on NANO, but it makes me puzzle after generating .engine file, i wanna know how to do.
pls,thanks.
