### ISSUE TITLE
Incorrect --save-txt directory 

### ISSUE THREAD

**Issue by iampreviero** [meituan/YOLOv6#612]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [ ] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

In `tools/infer.py`, using the `--save-txt` flags allows to store the predictions as txt files. From `infer.py`, these should be saved in a `labels` subdirectory of `save-dir`, which is created in the `infer.py` script. However, in the `yolov6/core/inferer.py` line 85, it is just saved in the same directory as `save-img`, i.e. `labels` subdirectory is ignored. 

Additionally, even when `save-img` and `save-txt` are false, these directories are created.
Please, I suggest changing line 82-86 with 
```
if save_img:
    img_folder = os.path.join(save_dir, rel_path)
    os.makedirs(img_folder, exist_ok=True)
    save_path = os.path.join(save_dir, rel_path, os.path.basename(img_path))

if save_txt:
    txt_folder = os.path.join(save_dir, 'labels', rel_path)
    os.makedirs(txt_folder, exist_ok=True)
    txt_path = os.path.join(txt_folder, os.path.splitext(os.path.basename(img_path))[0])
```

In theory, you could even avoid creating the `save-dir` in `tools\infer.py` since the above `os.makedirs` is used, which is recursive. 

I apologize this is a question rather than a pull request, but I've changed the original code a bit.

**Comment by mtjhl** [comment]
We will check the code to see how to optimize it. Thank you.
