### ISSUE TITLE
为什么下载yolov6l.onnx模型的时候需要登录站点？

### ISSUE THREAD

**Issue by xingjunhong** [meituan/YOLOv6#616]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [ ] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

为什么下载yolov6l.onnx模型的时候需要登录站点？
然而他给的站点打不开，我无法拿到用户名和密码。

**Comment by Chilicyy** [comment]
You can download it from https://github.com/meituan/YOLOv6/releases/download/0.2.0/yolov6l.onnx

**Comment by xingjunhong** [comment]
我就是在这个链接下载的，就是要登录什么站点，需要用户名和密码

**Comment by Chilicyy** [comment]
指的是登录github账号吗？
