### ISSUE TITLE
Problem with multigpu training on Win 10

### ISSUE THREAD

**Issue by susanin1970** [meituan/YOLOv6#620]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

Hi, thanks for this repo :)

I have a problem with multigpu training on Win 10 machine with 2 x RTX 2080 Ti  
When I try to multigpu train YOLOv6-M on custom dataset with command  
```
 python -m torch.distributed.launch --nproc_per_node 2 .\tools\train.py --batch 4 --img-size 1280 --conf .\configs\yolov6m_finetune.py --data .\data\ships_dataset.yaml --device 0,1 --epochs 50
```
 I got follow error: 
 ```
 AttributeError: module 'signal' has no attribute 'SIGKILL'. Did you mean: 'SIGILL'? 
 ```  
 
 I thought the change `SIGIKLL` to `SIGTERM` in `Lib\site-packages\torch\distributed\elastic\timer\file_based_local_timer.py` would solve this problem, but after launch command above after changing I got follow error:  
 
 ```
 RuntimeError: Function argument device_ids not supported for the selected backend gloo  
 ```  
 
 What I am doing wrong? Is training on multiple GPUs supported in VOLOv6 now in Win 10?  
 
 I tried to train in Conda environment with Python 3.10.0,  PyTorch 1.13.0 and CUDA 11.6 
 
 Thanks in advance for the answer :)

**Comment by susanin1970** [comment]
Maybe running multigpu training must be in Docker like YOLOv5?

**Comment by Chilicyy** [comment]
Currently, you can try to run in  the Docker of YOLOv5. We will consider releasing a Docker for your convinience.

**Comment by susanin1970** [comment]
@Chilicyy, thank you for the answer :)  

Do I understand correctly that YOLOv6 training on multigpu is currently only supported on Linux?

**Comment by Chilicyy** [comment]
The problem might be caused by DDP training , not multigpu training. You can try to train YOLOv6 on WINDOWS  by using DP mode, but a bit slower than DDP mode , with the command as following:
`python .\tools\train.py --batch 4 --img-size 1280 --conf .\configs\yolov6m_finetune.py --data .\data\ships_dataset.yaml --device 0,1 --epochs 50`

**Comment by susanin1970** [comment]
Awesome! That's helped, thank you :)  
Indeed, the problem was in the DDP, I can run training on multigpu in normal mode

**Comment by susanin1970** [comment]
I have another problem with multigpu YOLOv6 training  
When I try to train YOLOv6 in 2 x RTX 2080 Ti with batch = 4, I got follow error: 

```
RuntimeError: DataLoader worker (pid(s) 9400) exited unexpectedly  
```  

When I try to train with batch = 2, I sometimes got wollow error:  

```
RuntimeError: CUDA error: device-side assert triggered
```  

Do I understand correctly that I need check my dataset for invalid labels/images?

**Comment by susanin1970** [comment]
Well, I set `--batch 8` and `--workers 0` and I got `CUDA error: device-side assert triggered` again :(

**Comment by susanin1970** [comment]
Issue is not actual, thanks for help :)
