### ISSUE TITLE
Need help with benchmark YOLOv5,v6,v7 on TT100K

### ISSUE THREAD

**Issue by thaihoangminhtam** [meituan/YOLOv6#622]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

Greeting team!
I'm creating a benchmark by trying to reproduce your benchmark for the TT100K dataset. At first glance, your model has much better fps and almost the accuracy as YOLOv5m, as shown in the table1 below. I tried reproducing by converting YOLOv7 to ONNX and engine like the procedure with YOLOv6 but received the error as img1 below. I have speed test successfully all of them based on [https://github.com/Linaom1214/TensorRT-For-YOLO-Series/tree/main/utils](url). Is there any way I can evaluate YOLOv5,v6,v7 using your `deploy/ONNX/eval_trt.py` as show in img2 for convenient (like the way you do to benchmark all of them in your paper)
img1
![Screenshot from 2022-11-21 04-31-02](https://user-images.githubusercontent.com/66732238/202927218-486357bf-5c31-4cc1-8c03-07db7b68e558.png)
img2
![Screenshot from 2022-11-21 04-35-22](https://user-images.githubusercontent.com/66732238/202927371-d774b9f5-036a-47a5-a59d-838a238ae896.png)
table1
![Screenshot from 2022-11-21 04-41-38](https://user-images.githubusercontent.com/66732238/202927655-e4e6235c-fe27-4da0-88fb-079a0fb20bf8.png)

edit1: I use the yolov5's `val.py` to evaluate yolov5 model not using `eval_trt.py`

**Comment by Chilicyy** [comment]
Hi, @thaihoangminhtam , I'm afraid that `eval_trt.py` is not suitable for yolov5/yolov7,  because we use different code architecture and format with yolov5/yolov7.

**Comment by thaihoangminhtam** [comment]
Hi @Chilicyy ,
Can you share the procedure, code architecture, and format to benchmark? Or I must use their build-in evaluate code in yolov5/v7 repositories.

**Comment by Chilicyy** [comment]
In our benchmark with other detectors, we just quote the metics from their official released results. So maybe you can use their build-in evaluation code.

**Comment by thaihoangminhtam** [comment]
Hi,
YOLOv7 can work with your `eval_trt.py` because its `export.py` supports end2end ONNX. Have you benchmarked the YOLOv7w6 before so I can take a reference? My result of YOLOv7w6 is quite weird ...  Anyway, I'm very pleased with YOLOv6s -> I can verify your work SOTA of the YOLO family now ^^ Thank you
![Screenshot from 2022-11-21 21-25-10](https://user-images.githubusercontent.com/66732238/203080568-ad459f1f-e1ad-478f-8709-1c3d8542e553.png)
