### ISSUE TITLE
Confidence Score / Object loss

### ISSUE THREAD

**Issue by d5423197** [meituan/YOLOv6#623]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

Hello there,

After reading the paper and the recent code. I realize that YOLOv6 has removed object loss. In inferencing mode, the confidence score is hard coded as 1. So confidence threshold is useless in YOLOv6.

Thanks,

ZD

**Comment by Chilicyy** [comment]
In v1.0 released code, we apply object loss ,  conf score = obj_conf * cls_conf. Then in v2.0 released code, we remove object loss, so conf score equals to  cls_conf.

**Comment by d5423197** [comment]
https://github.com/meituan/YOLOv6/blob/0b44d792e60febf848335f44a08eb776092f5985/yolov6/models/effidehead.py#L131

Isn't this hard coded as 1?

**Comment by Chilicyy** [comment]
> https://github.com/meituan/YOLOv6/blob/0b44d792e60febf848335f44a08eb776092f5985/yolov6/models/effidehead.py#L131
> 
> Isn't this hard coded as 1?

It means obj_conf is hard-coded as 1, not cls_conf.
