### ISSUE TITLE
prediction result only retains a maximum of 300

### ISSUE THREAD

**Issue by yang-0201** [meituan/YOLOv6#624]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

I found that each time eval.py of a picture of the prediction result only retains a maximum of 300, if the confidence level is adjusted down, the result is also 300, this is the official set value？

**Comment by Chilicyy** [comment]
Yes, max_det is set to 300 defaultly. If your want to adjust this setting, you can reload the value of max_det when applying `non_max_suppression` or change the value of max_det  in this line https://github.com/meituan/YOLOv6/blob/main/yolov6/utils/nms.py#L31.
