### ISSUE TITLE
A question about get_optimizer

### ISSUE THREAD

**Issue by johnnysclai** [meituan/YOLOv6#625]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

```py
cfg.solver.weight_decay *= args.batch_size * accumulate / 64
cfg.solver.lr0 *= args.batch_size / (self.world_size * 32) # rescale lr0 related to batchsize
```

Why the constants are 64 and 32? Should I change to other values if I don't have 8 GPUs?

**Comment by Chilicyy** [comment]
These two constants is set according to the results of our experiments on COCO dataset.  We use 8 GPUs for training models on COCO, if you don't have 8 GPUs, the relevant hyparmeters like lr0 can be adjusted automatically by this line.

**Comment by johnnysclai** [comment]
Thank you.
