### ISSUE TITLE
How to calculate the number of parameters and Gflops of the model before training starts？

### ISSUE THREAD

**Issue by yang-0201** [meituan/YOLOv6#626]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

How to calculate the number of parameters and Gflops of the model before training starts？
I saw the code in eval.py to calculate the number of model parameters, I added it to the build_model function in yolo.py and the final form is as follows：
def build_model(cfg, num_classes, device,img_size):
    model = Model(cfg, channels=3, num_classes=num_classes, anchors=cfg.model.head.anchors).to(device)
    from yolov6.utils.events import LOGGER
    from yolov6.utils.torch_utils import get_model_info
    LOGGER.info("Model Summary: {}".format(get_model_info(model, img_size = img_size)))
    return model

I then I get the data for each model as：
yolov6l Params: 58.52M, Gflops: 144.38
yolov6m Params: 37.12M, Gflops: 90.10
yolov6s Params: 18.83M, Gflops: 48.93
yolov6t Params: 10.60M, Gflops: 27.64
yolov6n Params: 4.72M, Gflops: 12.39
However, these data are not consistent with the model parametric quantities in the table, how to correctly output the model parametric quantities and GFLOPS before training

**Comment by Chilicyy** [comment]
We use the technique of structural reparameterization in the training process, so it is inaccurate to calculate the parameter amount and FLOPs amount before training. Because after the training is completed, the multi-branch structure will be converted equivalently during model inference and deployment, and the data in the table we release represents the converted model parameters and FLOPs amount.

**Comment by yang-0201** [comment]
Thank you. So the number of parameters and Gflops counted when inferring with the weights obtained after training is the correct information？
