### ISSUE TITLE
Freezing layers

### ISSUE THREAD

**Issue by AMG222** [meituan/YOLOv6#627]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

Hi,
I'm traning YOLOv6 in my own dataset and I was wondering to freeze some layer because it seems to train all the model even with the finetune config file.
How can I freeze some layer of the model, to perform Transfer learning?

I read carefully the config file and the arguments of tools/train.py and I don't see any argument or value to make it.

Thanks so much

**Comment by Chilicyy** [comment]
Currently, we don't support freezing layers for training. If you want to freeze layers in backbone, you can refer to this code block before training.
```
for k, v in self.model.named_parameters():
    v.requires_grad = True  # train all layers
    if k.startswith('backbone'):
        v.requires_grad = False # freeze backbone
```

**Comment by Chilicyy** [comment]
Currently, we don't support freezing layers for training. If you want to freeze layers in backbone, you can refer to this code block before training.
```
for k, v in self.model.named_parameters():
    v.requires_grad = True  # train all layers
    if k.startswith('backbone'):
        v.requires_grad = False # freeze backbone
```

**Comment by AMG222** [comment]
Ok, seems to work well
Thanks so much

**Comment by Xiaofei-Kevin-Yang** [comment]
> Currently, we don't support freezing layers for training. If you want to freeze layers in backbone, you can refer to this code block before training.
> 
> ```
> for k, v in self.model.named_parameters():
>     v.requires_grad = True  # train all layers
>     if k.startswith('backbone'):
>         v.requires_grad = False # freeze backbone
> ```

Hi there, thanks for your excellent work. I am a beginner at YOLOv6. Could you please provide more details if I want to freeze the backbone. Look forward to your reply.

**Comment by Xiaofei-Kevin-Yang** [comment]
> Ok, seems to work well Thanks so much

Hi there, I was wondering did you solve this problem.

**Comment by AMG222** [comment]
> > Currently, we don't support freezing layers for training. If you want to freeze layers in backbone, you can refer to this code block before training.
> > ```
> > for k, v in self.model.named_parameters():
> >     v.requires_grad = True  # train all layers
> >     if k.startswith('backbone'):
> >         v.requires_grad = False # freeze backbone
> > ```
> 
> Hi there, thanks for your excellent work. I am a beginner at YOLOv6. Could you please provide more details if I want to freeze the backbone. Look forward to your reply.

Using that code you freeze the backbone, if you want to freeze other parts use other keywords or look for the specific index in the architecture and use a counter.
