### ISSUE TITLE
训练时， out of memeory

### ISSUE THREAD

**Issue by deepxiaobai** [meituan/YOLOv6#628]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

Inferencing model in train datasets.:  34%|██████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                                                                                          | 310/923 [00:43<01:29,  6.87it/s]
Inferencing model in train datasets.:  34%|██████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                                                                                         | 311/923 [00:43<01:25,  7.15it/s]
Inferencing model in train datasets.:  34%|██████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                                                                                         | 312/923 [00:43<01:29,  6.85it/s]
Inferencing model in train datasets.:  34%|██████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                                                                                         | 313/923 [00:43<01:25,  7.10it/s]
Inferencing model in train datasets.:  34%|███████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                                                                                        | 314/923 [00:43<01:33,  6.49it/s]
Inferencing model in train datasets.:  34%|███████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                                                                                        | 315/923 [00:43<01:29,  6.78it/s]
Inferencing model in train datasets.:  34%|███████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                                                                                        | 316/923 [00:44<01:29,  6.82it/s]
Inferencing model in train datasets.:  34%|████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                                                                                       | 317/923 [00:44<01:28,  6.87it/s]
Inferencing model in train datasets.:  34%|████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                                                                                       | 317/923 [00:44<01:24,  7.18it/s]

ERROR in evaluate and save model.
ERROR in training loop or eval/save model.
Traceback (most recent call last):
  File "tools/train.py", line 126, in <module>
    main(args)
  File "tools/train.py", line 116, in main
    trainer.train()
  File "D:\work\YOLOv6-main\yolov6\core\engine.py", line 99, in train
    self.train_in_loop(self.epoch)
  File "D:\work\YOLOv6-main\yolov6\core\engine.py", line 119, in train_in_loop
    self.eval_and_save()
  File "D:\work\YOLOv6-main\yolov6\core\engine.py", line 157, in eval_and_save
    self.eval_model()
  File "D:\work\YOLOv6-main\yolov6\core\engine.py", line 192, in eval_model
    results, vis_outputs, vis_paths = eval.run(self.data_dict,
  File "D:\soft\anaconda3\envs\yolov6\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\work\YOLOv6-main\tools\eval.py", line 153, in run
    pred_result, vis_outputs, vis_paths = val.predict_model(model, dataloader, task)
  File "D:\work\YOLOv6-main\yolov6\core\evaler.py", line 120, in predict_model
    for i, (imgs, targets, paths, shapes) in enumerate(pbar):
  File "D:\soft\anaconda3\envs\yolov6\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "D:\work\YOLOv6-main\yolov6\data\data_load.py", line 98, in __iter__
    yield next(self.iterator)
  File "D:\soft\anaconda3\envs\yolov6\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "D:\soft\anaconda3\envs\yolov6\lib\site-packages\torch\utils\data\dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "D:\soft\anaconda3\envs\yolov6\lib\site-packages\torch\utils\data\dataloader.py", line 1250, in _process_data
    data.reraise()
  File "D:\soft\anaconda3\envs\yolov6\lib\site-packages\torch\_utils.py", line 457, in reraise
    raise exception
MemoryError: Caught MemoryError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\work\YOLOv6-main\yolov6\data\datasets.py", line 189, in load_image
    im = cv2.imread(path)
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 6220800 bytes in function 'cv::OutOfMemoryError'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\soft\anaconda3\envs\yolov6\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\soft\anaconda3\envs\yolov6\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\soft\anaconda3\envs\yolov6\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\work\YOLOv6-main\yolov6\data\datasets.py", line 108, in __getitem__
    img, (h0, w0), (h, w) = self.load_image(index)
  File "D:\work\YOLOv6-main\yolov6\data\datasets.py", line 192, in load_image
    im = cv2.cvtColor(np.asarray(Image.open(path)), cv2.COLOR_RGB2BGR)
  File "D:\soft\anaconda3\envs\yolov6\lib\site-packages\PIL\Image.py", line 687, in __array_interface__
    new["data"] = self.tobytes()
  File "D:\soft\anaconda3\envs\yolov6\lib\site-packages\PIL\Image.py", line 749, in tobytes
    return b"".join(data)
MemoryError

训练时显存逐渐增加

**Comment by Chilicyy** [comment]
你好，看起来是数据加载时cpu内存不足导致的问题。可以试试在训练启动命令中添加`--workers 0`，或者调小batchsize.

**Comment by deepxiaobai** [comment]
> 

我把batchsize调为4  workers为0，在训练时发现，训练完一个epoch后执行评估时会出现，显存占满的情况
<img width="514" alt="微信图片_20221122092527" src="https://user-images.githubusercontent.com/67140303/203192594-ca7a7ae5-d11c-4ff9-8618-49ea86b257a6.png">

**Comment by deepxiaobai** [comment]
> 你好，看起来是数据加载时cpu内存不足导致的问题。可以试试在训练启动命令中添加`--workers 0`，或者调小batchsize.

多次运行，都是在训练完一个epoch后，在执行评估过程中出现显存占用100%的情况

**Comment by Chilicyy** [comment]
从报错日志看，是图片加载导致的内存不足报错，可以检查下验证集中是不是有特别大的图片或者异常图片

**Comment by deepxiaobai** [comment]
> 



> 从报错日志看，是图片加载导致的内存不足报错，可以检查下验证集中是不是有特别大的图片或者异常图片

应该不会，我没有设置单独的验证集，验证集和训练集是同一个目录
而且这个数据集我使用yolov5训练过，并没有出现问题

**Comment by Chilicyy** [comment]
> > 
> 
> > 从报错日志看，是图片加载导致的内存不足报错，可以检查下验证集中是不是有特别大的图片或者异常图片
> 
> 应该不会，我没有设置单独的验证集，验证集和训练集是同一个目录 而且这个数据集我使用yolov5训练过，并没有出现问题

请问每次报错程序中断的位置是一样的吗？麻烦提供下详细的报错信息截图和训练配置。如果方便的话，可以把数据集发一下，不然这边没法复现您这个错误。

**Comment by Chilicyy** [comment]
模型训练过程显存利用率100%是正常的，看起来程序能够正常运行了。
