### ISSUE TITLE
strange loss

### ISSUE THREAD

**Issue by LiJiahang617** [meituan/YOLOv6#63]
when i was training, i found that my loss is like this:
![Screenshot from 2022-06-26 16-13-16](https://user-images.githubusercontent.com/103312600/175805718-59eb56ea-c23a-4f0b-983a-1d4761f2b0db.png)
only obj_loss is that normal,or it is because my datasets is not organized rightly?
this is my coco datasets organization:
![Screenshot from 2022-06-26 16-16-59](https://user-images.githubusercontent.com/103312600/175805813-7391d400-f4fe-4d5f-a5fd-0a7b4c672d11.png)
![Screenshot from 2022-06-26 16-17-09](https://user-images.githubusercontent.com/103312600/175805816-e095f47e-d943-49e3-9401-da4349541208.png)
![Screenshot from 2022-06-26 16-17-19](https://user-images.githubusercontent.com/103312600/175805819-8bf85e31-a907-4415-b4f7-ebf7f5701265.png)

**Comment by LiJiahang617** [comment]
and my coco.yaml is like this:
![Screenshot from 2022-06-26 16-18-48](https://user-images.githubusercontent.com/103312600/175805872-6e03966d-6580-42d3-b658-1e92ef81c5ad.png)
when i want to train this model ,is the anno_path supposed to be tran2017.json? or val2017.json?

**Comment by Chilicyy** [comment]
@LiJiahang617 It depends on which dataset you want to evaluate model on. Generally, it should be val2017.json.
