### ISSUE TITLE
tflite export

### ISSUE THREAD

**Issue by BestITUserEUW** [meituan/YOLOv6#630]
### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar feature requests.

### Description

Hey,
i'm coming from yolov5, and would like to use yolov6 but i can only run inference with tensorflow lite. Would be cool if this could be added as an export if possible.

### Use case

Tensorflow Lite Model Conversion.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Chilicyy** [comment]
Thanks for your attention. We have received your suggestion, and we'll consider adding this feature in the next version.

**Comment by BestITUserEUW** [comment]
@Chilicyy Thanks,  looking forward for the release :+1:

**Comment by ibaiGorordo** [comment]
Sorry for reopening, I was able to convert the model to TFLite (haven't tested it yet) using the `[onnx2tf library](https://github.com/PINTO0309/onnx2tf)`.

Here is a Colab notebook to convert the model:
https://colab.research.google.com/drive/1XEBcXPaS27t9PG301jJzFnU_KouAfjKk?usp=sharing

**Comment by abhishekbj97** [comment]
> Sorry for reopening, I was able to convert the model to TFLite (haven't tested it yet) using the [onnx2tf library](https://github.com/PINTO0309/onnx2tf).
> 
> Here is a Colab notebook to convert the model: https://colab.research.google.com/drive/1XEBcXPaS27t9PG301jJzFnU_KouAfjKk?usp=sharing

i am facing the same problem 
can anyone sugession?
