### ISSUE TITLE
量化问题

### ISSUE THREAD

**Issue by wuminjie12** [meituan/YOLOv6#633]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

我使用6sbase模型在自己的数据集上进行训练，使用deploy中的export_onnx.py转成onnx模型，
命令是：python3 deploy/ONNX/export_onnx.py --weights saved_model.pt --batch-size 30 --simplify
再转int8的trt模型虽然能推理，但相比fp16的trt模型降了很多，想问下有可能是什么问题？

**Comment by khwengXU** [comment]
hi，感谢关注v6，请问“相比fp16的trt模型降了很多”，指的是哪方面降了很多？

**Comment by wuminjie12** [comment]
召回降了很多

**Comment by khwengXU** [comment]
请问转int8的trt方式是怎么样的？  可以关注一下int8后一致性的情况 😃

**Comment by Chilicyy** [comment]
@wuminjie12 你好，这边如果用的是v2.0发版的模型，想要掉点少需要参考我们提供的[量化教程](https://github.com/meituan/YOLOv6/blob/main/tools/qat/README.md) 先做ReOpt训练-》QAT蒸馏训练 -》PTQ量化推理。此外，我们还提供了PTQ量化友好的模型，可参考[这里](https://github.com/meituan/YOLOv6/blob/main/configs/base/README.md)，直接PTQ量化掉点较少。

**Comment by sunxirui310** [comment]
> @wuminjie12 你好，这边如果用的是v2.0发版的模型，想要掉点少需要参考我们提供的[量化教程](https://github.com/meituan/YOLOv6/blob/main/tools/qat/README.md) 先做ReOpt训练-》QAT蒸馏训练 -》PTQ量化推理。此外，我们还提供了PTQ量化友好的模型，可参考[这里](https://github.com/meituan/YOLOv6/blob/main/configs/base/README.md)，直接PTQ量化掉点较少。

请问v3.0的模型，也适用于量化教程吗？我在尝试 6n6 模型
