### ISSUE TITLE
训练结果可视化

### ISSUE THREAD

**Issue by Shaoli7** [meituan/YOLOv6#634]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

您好，想请问一下怎么让训练过程中loss和mAp显示出来呢，没有找到相关文件，训练输出文件夹也没有看到结果图片。等待您的解答。

**Comment by moonjay1013** [comment]
runs/train/exp 文件夹下不是有训练过程的tensorboard日志文件吗

**Comment by mtjhl** [comment]
训练过程中，loss 不是一直都在实时显示吗？至于将每次评估的 mAP 写入到文件，这个功能我们后面可以安排添加一下。

**Comment by Shaoli7** [comment]
> 训练过程中，loss 不是一直都在实时显示吗？至于将每次评估的 mAP 写入到文件，这个功能我们后面可以安排添加一下。
谢谢您的解答，对的，loss是实时显示的，但是我是想以图表的形式显示出来，像下面的图片似的，我该怎么做呢。
![results](https://user-images.githubusercontent.com/113178614/203992407-66f50743-f7fc-4085-bece-913a9aeda7f1.png)
而且并没有在runs/train/exp中找到tensorboard日志文件是什么原因呢。等待您的回复。
![训练结果](https://user-images.githubusercontent.com/113178614/203993052-7159fd06-77ea-48f7-b7b3-f42ba3afca4f.jpg)

**Comment by moonjay1013** [comment]
> > 训练过程中，loss 不是一直都在实时显示吗？至于将每次评估的 mAP 写入到文件，这个功能我们后面可以安排添加一下。
> > 谢谢您的解答，对的，loss是实时显示的，但是我是想以图表的形式显示出来，像下面的图片似的，我是用的pycharm进行训练的，我该怎么做呢。
> > ![results](https://user-images.githubusercontent.com/113178614/203992407-66f50743-f7fc-4085-bece-913a9aeda7f1.png)
> > 而且并没有在runs/train/exp中找到tensorboard日志文件是什么原因呢。等待您的回复。
> > ![训练结果](https://user-images.githubusercontent.com/113178614/203993052-7159fd06-77ea-48f7-b7b3-f42ba3afca4f.jpg)

tensorboard日志文件就是以_events.out.tfevents_ 开头的，在cmd窗口进入目录下使用`tensorboard --logdir .`可以在浏览器查看训练过程mAP曲线和loss曲线，但是没有P、R值和PR曲线。
