### ISSUE TITLE
请问可以用npu训练嘛？

### ISSUE THREAD

**Issue by xingjunhong** [meituan/YOLOv6#635]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

请问可以在npu上训练嘛？有做npu 的适配嘛？

**Comment by mtjhl** [comment]
目前还没有，请问您指的是哪家公司的 NPU 设备？

**Comment by xingjunhong** [comment]
华为atlas的设备

**Comment by mtjhl** [comment]
我们这边没有 Atlas 设备。如果 Atlas 支持 PyTorch，应该还比较好迁移，如果是要用 MindSpore，可能得迁移框架。
