### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by gnftau** [meituan/YOLOv6#64]
I am a beginner, I would like to ask the code running on the Linux server, training will always report module error. ModuleNotFoundError: No module named 'tools.eval'

**Comment by khwengXU** [comment]
Thanks for your attentions.
Do you add modules path in PYTHONPATH?

**Comment by acai66** [comment]
![image](https://user-images.githubusercontent.com/37766207/175844996-92efccd7-1109-4295-affb-1c5ea7b6abdc.png)
create `__init__.py` in `YOLOv6/tools/`, then change `sys.path.append(str(ROOT))` to `sys.path.insert(0, str(ROOT))` in `YOLOv6/tools/train.py`

**Comment by PuristWu** [comment]
Thank you bro

**Comment by RooKichenn** [comment]
①Put the infer.py and train.py files in the main folder of yolov6.
![image](https://user-images.githubusercontent.com/78341437/176612231-ca8cc548-9823-45de-b4f2-416e9ce6d57a.png)
②修改inferer.py
![image](https://user-images.githubusercontent.com/78341437/176612595-6293d9c1-43b9-4726-9767-87d825af804f.png)
problem solved

**Comment by remembersu** [comment]
Thank！ I run the infer.py because I modified absolute path

**Comment by mtjhl** [comment]
Did you install YOLOX in this python envs, if you installed, you can run `pip uninstall yolox`.

**Comment by remembersu** [comment]
Thanks. I run the code successfully!



发自我的iPhone


------------------ Original ------------------
From: RooKichenn ***@***.***&gt;
Date: Thu,Jun 30,2022 2:57 PM
To: meituan/YOLOv6 ***@***.***&gt;
Cc: remembersu ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [meituan/YOLOv6] ModuleNotFoundError (Issue #64)





 
①Put the infer.py and train.py files in the main folder of yolov6.
 
 ②修改inferer.py
 
 problem solved
