### ISSUE TITLE
Missing citation of Localization Distillation

### ISSUE THREAD

**Issue by Zzh-tju** [meituan/YOLOv6#642]
We need to inform you that your paper missed an important citation of [Localization Distillation for Object Detection](https://arxiv.org/abs/2204.05957), which is a journal extension of [LD CVPR 2022](https://openaccess.thecvf.com/content/CVPR2022/html/Zheng_Localization_Distillation_for_Dense_Object_Detection_CVPR_2022_paper.html).

```
@Article{zheng2022rotatedLD,
  title={Localization Distillation for Object Detection},
  author= {Zheng, Zhaohui and Ye, Rongguang and Hou, Qibin and Ren, Dongwei and Wang, Ping and Zuo, Wangmeng and Cheng, Ming-Ming},
  journal={arXiv preprint arXiv:2204.05957},
  year={2022}
}
```

In Sec. 2.4.2 of your paper, you propose **self-distillation**, which is identical to **Sec. 3.2.2 Self-LD** in [LD paper](https://arxiv.org/abs/2102.12252v1) in Feb 2021. 

LD was also incorporated into [MMDetection](https://github.com/open-mmlab/mmdetection/tree/master/configs/ld) framework in March 2021.

**In order not to cause some unnecessary troubles in the future, and for the sake of academic rigor, we believe that this is a mistake that cannot be overlooked.**

### Additional

We hope to see these corrections as soon as possible.

**Comment by Chilicyy** [comment]
Sorry for our oversight. We'll add the citation as soon as possible.
