### ISSUE TITLE
What is the difference between --img-size and --test-load-size in eval.py

### ISSUE THREAD

**Issue by yang-0201** [meituan/YOLOv6#647]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

What is the difference between --img-size and --test-load-size in eval.py
If I change the training image size to 1280, do I need to set both parameters to 1280 in eval.py when I validate?
And if I want to validate with a larger size, do both parameters need to be modified?
I get different results when I try different modifications.

**Comment by mtjhl** [comment]
`test_load_size` is used here
https://github.com/meituan/YOLOv6/blob/4b174ca5056841cac66d898c49fd19297c4dcba8/yolov6/data/datasets.py#L196

this paramater is a little smaller than img-size, for example, 634, while img size is 640, then we pad 3 pixels to the both sides of the image to get better result.
If your pixel size is 1280, then the `test_load_size` can be set to 1274 or 1272.

**Comment by shensheng272** [comment]
--img-size mean img size used for model infer (when no extra pad).
--test-load-size mean img load size before eval preprocess.

> If I change the training image size to 1280, do I need to set both parameters to 1280 in eval.py when I validate?
And if I want to validate with a larger size, do both parameters need to be modified?

Both answer is yes.

**Comment by yang-0201** [comment]
Thank you very much！
