### ISSUE TITLE
mAP Exception

### ISSUE THREAD

**Issue by Lizhijian-123** [meituan/YOLOv6#65]
为什么我的AP都是0,已经训练了240个epoch了,在我自己的数据集上,且用了预训练权重
45/5000 
Why is it that my AP is all 0 and I have trained 240 epochs on my own dataset and used pre-training weights.!!!
![image](https://user-images.githubusercontent.com/85280708/175806308-b299c83a-4267-4698-85b0-dd776956bb39.png)

**Comment by liu-ai-z** [comment]
请问预训练权重去哪里下载？

**Comment by Lizhijian-123** [comment]
> 

![image](https://user-images.githubusercontent.com/85280708/175814438-905a359f-e6aa-4405-9bcc-436ee483d836.png)
这里

**Comment by hhsummerwind** [comment]
同样的问题,  val有问题, 但是单独跑infer是好的, 有定位到问题吗?
