### ISSUE TITLE
loss获取

### ISSUE THREAD

**Issue by Shaoli7** [meituan/YOLOv6#658]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

您好，我想请教下，YOLOv6有没有将训练过程中的loss值进行保存呢，就像YOLOv5那样保存成了文本文件，或者我该怎么在训练完获取每个epoch的loss值呢，等待您的解答。

**Comment by Chilicyy** [comment]
你好，loss值可以从这里获取  https://github.com/meituan/YOLOv6/blob/main/yolov6/core/engine.py#L142

**Comment by sauravgarg540** [comment]
A log file can also be created that logs the args, model, loss, accuracy, and information about the environment. If the team is interested I can add this feature.
