### ISSUE TITLE
about yolov6t  Params and Gflops

### ISSUE THREAD

**Issue by yang-0201** [meituan/YOLOv6#659]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

我发现官方对于yolov6t 模型的参数量和Gflops为15.0 | 36.7
但是我训练一个yolov6t网络，并用权重在验证的时候得到的数据为Model Summary: Params: 9.67M, Gflops: 24.83
差距比较大，这是为什么，并且n，s，m，l模型同样的操作差距比较小，基本符合官方的数据

**Comment by yang-0201** [comment]
如果我对yolov6的网络模块改进后，如何才能正确计算新模型的整个参数量和Gflops数据，便于写在论文里

**Comment by Chilicyy** [comment]
README中关于yolov6t的参数量和计算量数值 有误，已更正了。
如果需要计算新模型的参数量和计算量，可以跑评估代码：
`python tools/eval.py --task speed --weights weights/yolov6t.pt`

**Comment by yang-0201** [comment]
好的，论文里也可以更正下
