### ISSUE TITLE
get confusion matrix and some graph metrics as Yolov5 gives

### ISSUE THREAD

**Issue by danik7** [meituan/YOLOv6#661]
### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar feature requests.

### Description

how can we get that?
Thanks!

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by mtjhl** [comment]
We will add those functions as soon as possible.
