### ISSUE TITLE
用mmdetection方法统计 Gflops 时 数值为官方的一半

### ISSUE THREAD

**Issue by yang-0201** [meituan/YOLOv6#664]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

我在看mmdetection出版的yolo系列改进RTMDet算法的论文时候，https://arxiv.org/abs/2212.07784
看到论文上面列出的yolov5，yolov6 的Gflops问题，统计到的Gflops都是你们官方数据的一半，我在yolov6代码中调用了下mmcv的get_flops.py算法（https://github.com/open-mmlab/mmdetection/blob/master/tools/analysis_tools/get_flops.py）
的时候，统计了下yolov6 l的参数和Gflops，发现数值都是官方数值的一半，是什么原因导致的，是他们的统计方法有问题嘛

**Comment by yang-0201** [comment]
![0GLLPWH2VR08 YJAYA1IY_H](https://user-images.githubusercontent.com/89863442/209074842-3f40bae2-a8f1-4378-bb93-9585ce0e5ace.png)
![KU8NUKV (`PCVF1SSDFG_@B](https://user-images.githubusercontent.com/89863442/209074926-1c7f35af-24d2-4444-8189-e9f00c14b454.png)

**Comment by yang-0201** [comment]
使用python ptflops包中的
get_model_complexity_info方法也会遇到该问题
`from ptflops import get_model_complexity_info`
    `flops, params = get_model_complexity_info(model, (3, 640, 640), as_strings=True, print_per_layer_stat=True)`
    `print('flops: ', flops, 'params: ', params)`

**Comment by mtjhl** [comment]
应该是单位不一样导致的，MMDET 算的应该是 MACs，一个 MACs 包含两个 FLOP，所以数量是其他工具统计的一半。具体您可以参考一下这个看看
https://zhuanlan.zhihu.com/p/364543528

**Comment by yang-0201** [comment]
谢谢，了解了！
