### ISSUE TITLE
t模型单类别训练转onnx之后精度下降明显，多类别下降的少？

### ISSUE THREAD

**Issue by pyl62112991** [meituan/YOLOv6#665]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

单精度pth模型测试精度八十几，onnx只有十几

### Additional

单精度pth模型测试精度八十几，onnx只有十几

**Comment by mtjhl** [comment]
按理说 PyTorch 和 ONNX 推理，精度应该是一致的，您可以排查一下前处理和后处理是否有问题。

**Comment by pyl62112991** [comment]
letterbox改成了keep ratio的方式，多类的也是这样改的，但是结果有差异

**Comment by mtjhl** [comment]
前后处理对齐，理论上结果是一样的。建议您检查一下是否有潜在的bug。

**Comment by pyl62112991** [comment]
好的，谢谢，我再检查一下
