### ISSUE TITLE
How to count detected and classified object in yolov6?

### ISSUE THREAD

**Issue by amzpun** [meituan/YOLOv6#668]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

How can we count detected and classified object in yolov6? I have computed json output file but it doesn't have accurate count verified using infer.py. In yolov5 following code works well. I am just wondering if there is similar feature that I have not yet explored.

import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Images
dir = 'https://github.com/ultralytics/yolov5/raw/master/data/images/'
imgs = [dir + f for f in ('zidane.jpg', 'bus.jpg')]  # batch of images

# Inference
results = model(imgs)
results.print()  # or .show(), .save()
print(results.pandas().xyxy[0])

**Comment by mtjhl** [comment]
You can add one line `num = len(det)` to get the number of detections here: https://github.com/meituan/YOLOv6/blob/db033474e961331bed5bec05ae11c8b350c12053/yolov6/core/inferer.py#L79)

**Comment by amzpun** [comment]
Thank you @mtjhl for navigating me to solution. However, I am still wondering about testing bulk images at once rather than  single image using infer.py.

**Comment by mtjhl** [comment]
`tools/infer.py` can run bulk images at once. Or you can add this code to `core/evaler.py`.

**Comment by amzpun** [comment]
Thanks @mtjhl. I appreciate your help so much.
