### ISSUE TITLE
预训练权重去哪里下载？

### ISSUE THREAD

**Issue by liu-ai-z** [meituan/YOLOv6#67]

**Comment by khwengXU** [comment]
Thanks for your attentions!
The pretrain weight is in the release log.

**Comment by liu-ai-z** [comment]
Thanks

**Comment by jia0511** [comment]
链接: https://pan.baidu.com/s/1qbeXL6ONYT-G7zgp01YV7g 提取码: 25ac

**Comment by liny23** [comment]
README->Benchmark->the first column has link

**Comment by rocklee2022** [comment]
> README->Benchmark->the first column has link

but this link always need Failed - Needs authorization
