### ISSUE TITLE
add pretrained model info in custom data training and update onnx export

### ISSUE THREAD

**Issue by hasibzunair** [meituan/YOLOv6#672]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

Creating this issue for a possible PR to update the following: 

1. Add instruction to download pre-trained model(s) when training on custom data [here](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md#2-create-a-config-file).
2. Update command to export as ONNX format, this was discussed but not updated in #613 

I think these two would help make training and deploying on custom data much easier!

**Comment by mtjhl** [comment]
Thank you for your good advice, do you mean you want to make a PR to implement those two funcitons. If so, welcome to make a PR.

**Comment by hasibzunair** [comment]
Yes, will get started then.
