### ISSUE TITLE
Multiple directory allocation  in data.yaml 

### ISSUE THREAD

**Issue by HetNaik997** [meituan/YOLOv6#675]
### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar feature requests.

### Description

Can we allocate multiple directories in data.yaml file during the model training? 

### Use case

For example, In YOLOV5 and YOLOv7, we can allocate multiple data input directories as shown in the example here: 
train: 
- /home/Labels/Batch2/images
- /home/Labels/Batch3/images
- /home/Labels/Batch4/images
- /home/Labels/Batch5/images
- /home/Labels/Batch6/images
- /home/Labels/Batch7/images
- /home/Labels/Batch8/images

A similar structure will return an error with YOLOv6 as :
"TypeError: stat: path should be string, bytes, os.PathLike or integer, not list"

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by mtjhl** [comment]
I will add this funciton within 3 days. If you already  add this funciton, welcome to make a PR.

**Comment by Chilicyy** [comment]
@HetNaik997 hi, multiple directories of dataset is supported actually. You can organize your dataset as the following format:
- /Home/images/train/batch1/
- /Home/images/train/batch2/
- /Home/images/val/batch1/
- /Home/images/val/batch2/
- /Home/labels/train/batch1/
- /Home/labels/train/batch2/
- /Home/labels/val/batch1/
- /Home/labels/val/batch2/

and then set the path in data.yaml as like:
train:/Home/images/train
val:/Home/images/val
