### ISSUE TITLE
How to check Total Number of Parameters in YOLO6 Model for Custom Dataset?

### ISSUE THREAD

**Issue by abhishekbj97** [meituan/YOLOv6#681]
### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar feature requests.

### Description

How to check parameters for Custom Dataset?

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by mtjhl** [comment]
You can use `python tools/eval.py --weights path/to/weights --data path/to/data/config/file`， it will show flops and parameters of your custom model.

**Comment by abhishekbj97** [comment]
Thank You,
I floops and parameter.

But another question how to get each class mAP accuracy?

**Comment by Chilicyy** [comment]
@abhishekbj97  Add `--verbose` to print mAP of each classes.

**Comment by KOBE-LZY** [comment]
May I ask where the specific location of this "-- weights path/to/weights -- data path/to/data/config/file" is
