### ISSUE TITLE
启动单卡训练，请问为什么会出现这么多进程？分别都是做什么？

### ISSUE THREAD

**Issue by HueCheng1021** [meituan/YOLOv6#693]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

单卡训练，发现开了很多进程，请教下为什么？

### Additional

44696 pts/2    Rl+    0:34 python tools/train.py --batch 32 --epochs 1 --conf configs/base/yolov6s_base_finetune.py --data data/zhengzhi.yaml --device 0 --quant --name debug_single
44903 pts/2    R+     0:01 python tools/train.py --batch 32 --epochs 1 --conf configs/base/yolov6s_base_finetune.py --data data/zhengzhi.yaml --device 0 --quant --name debug_single
44987 pts/2    R+     0:01 python tools/train.py --batch 32 --epochs 1 --conf configs/base/yolov6s_base_finetune.py --data data/zhengzhi.yaml --device 0 --quant --name debug_single
45095 pts/2    R+     0:01 python tools/train.py --batch 32 --epochs 1 --conf configs/base/yolov6s_base_finetune.py --data data/zhengzhi.yaml --device 0 --quant --name debug_single
45191 pts/2    R+     0:01 python tools/train.py --batch 32 --epochs 1 --conf configs/base/yolov6s_base_finetune.py --data data/zhengzhi.yaml --device 0 --quant --name debug_single
45287 pts/2    R+     0:01 python tools/train.py --batch 32 --epochs 1 --conf configs/base/yolov6s_base_finetune.py --data data/zhengzhi.yaml --device 0 --quant --name debug_single
45383 pts/2    R+     0:01 python tools/train.py --batch 32 --epochs 1 --conf configs/base/yolov6s_base_finetune.py --data data/zhengzhi.yaml --device 0 --quant --name debug_single
45479 pts/2    R+     0:01 python tools/train.py --batch 32 --epochs 1 --conf configs/base/yolov6s_base_finetune.py --data data/zhengzhi.yaml --device 0 --quant --name debug_single
45575 pts/2    R+     0:01 python tools/train.py --batch 32 --epochs 1 --conf configs/base/yolov6s_base_finetune.py --data data/zhengzhi.yaml --device 0 --quant --name debug_single
45776 pts/2    S+     0:00 python tools/train.py --batch 32 --epochs 1 --conf configs/base/yolov6s_base_finetune.py --data data/zhengzhi.yaml --device 0 --quant --name debug_single

**Comment by mtjhl** [comment]
这些同名的，是数据加载的线程， 默认是八个。多余的一个应该是量化的线程。加上主进程，一共是10个。

**Comment by HueCheng1021** [comment]
跑了demo，发现一共出现17个进程，完整信息如下：
PID TTY      STAT   TIME COMMAND
54860 pts/2    Rl+    0:31 python tools/train.py --batch 32 --conf configs/yolov6s_finetune.py --data data/zhengzhi.yaml --device 0
55127 pts/2    Rl+    0:03 python tools/train.py --batch 32 --conf configs/yolov6s_finetune.py --data data/zhengzhi.yaml --device 0
55232 pts/2    Rl+    0:03 python tools/train.py --batch 32 --conf configs/yolov6s_finetune.py --data data/zhengzhi.yaml --device 0
55328 pts/2    Rl+    0:03 python tools/train.py --batch 32 --conf configs/yolov6s_finetune.py --data data/zhengzhi.yaml --device 0
55424 pts/2    Rl+    0:03 python tools/train.py --batch 32 --conf configs/yolov6s_finetune.py --data data/zhengzhi.yaml --device 0
55523 pts/2    Rl+    0:03 python tools/train.py --batch 32 --conf configs/yolov6s_finetune.py --data data/zhengzhi.yaml --device 0
55619 pts/2    Rl+    0:03 python tools/train.py --batch 32 --conf configs/yolov6s_finetune.py --data data/zhengzhi.yaml --device 0
55715 pts/2    Rl+    0:03 python tools/train.py --batch 32 --conf configs/yolov6s_finetune.py --data data/zhengzhi.yaml --device 0
55811 pts/2    Rl+    0:03 python tools/train.py --batch 32 --conf configs/yolov6s_finetune.py --data data/zhengzhi.yaml --device 0
56014 pts/2    Rl+    0:02 python tools/train.py --batch 32 --conf configs/yolov6s_finetune.py --data data/zhengzhi.yaml --device 0
56015 pts/2    Rl+    0:02 python tools/train.py --batch 32 --conf configs/yolov6s_finetune.py --data data/zhengzhi.yaml --device 0
56016 pts/2    Rl+    0:02 python tools/train.py --batch 32 --conf configs/yolov6s_finetune.py --data data/zhengzhi.yaml --device 0
56017 pts/2    Rl+    0:02 python tools/train.py --batch 32 --conf configs/yolov6s_finetune.py --data data/zhengzhi.yaml --device 0
56018 pts/2    R+     0:02 python tools/train.py --batch 32 --conf configs/yolov6s_finetune.py --data data/zhengzhi.yaml --device 0
56019 pts/2    Rl+    0:02 python tools/train.py --batch 32 --conf configs/yolov6s_finetune.py --data data/zhengzhi.yaml --device 0
56020 pts/2    Rl+    0:02 python tools/train.py --batch 32 --conf configs/yolov6s_finetune.py --data data/zhengzhi.yaml --device 0
56021 pts/2    Rl+    0:02 python tools/train.py --batch 32 --conf configs/yolov6s_finetune.py --data data/zhengzhi.yaml --device 0

**Comment by mtjhl** [comment]
多数都是数据加载加载进程。
