### ISSUE TITLE
Downlaod the checkpoint automatically

### ISSUE THREAD

**Issue by sauravgarg540** [meituan/YOLOv6#695]
### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar feature requests.

### Description

When using inference remove a step of downloading the checkpoint manually

### Use case

Instead of manually downloading the checkpoint, a user needs to provide which model they need to use and the path to the checkpoint. If the checkpoint is missing then download from the GitHub link  automatically.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by sauravgarg540** [comment]
#696

**Comment by mtjhl** [comment]
Good advice, we will consider to add it.

**Comment by mtjhl** [comment]
We already merge this function from PR.
