### ISSUE TITLE
Reproduce v3 results

### ISSUE THREAD

**Issue by haritsahm** [meituan/YOLOv6#699]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

Great work with the new release of YOLOv6! Especially with the mAP boost for all models.

I tried to reproduce the inference speed, but I wasn't able to get similar or close to your reports. It's hard to build your custom environment and I used an existing `nvcr.io/nvidia/pytorch` docker instead.

My questions:
1. Did you use the quantized models for the benchmark?
2. Related to my last issue #539, does the new version also boost the metrics for small objects?
3. Do you have plan to update the benchmark result using TRT 8 to make it comparable with legacy model benchmark? From my result, TRT8 boost the performance since it solve major problems in TRT7.

Test environment:
- pt -> onnx: exported using docker 21.06
- onnx -> trt: Using `21.06` (TRT7) and `22.04` (TRT8)

Commands:
### 1. Precision `FP32`
```
### Build engine
trtexec --explicitBatch --fp16 --inputIOFormats=fp32:chw --outputIOFormats=fp32:chw --buildOnly --workspace=1024 --onnx=weights/model-b1.onnx --saveEngine=weights/model-b1.engine

### Run engine
trtexec --fp16 --avgRuns=1000 --warmUp=1000 --workspace=1024 --inputIOFormats=fp32:chw --outputIOFormats=fp32:chw --loadEngine=model-b1.engine
```

### 2. Precision `FP16`
```
### Build engine
trtexec --explicitBatch --fp16 --inputIOFormats=fp16:chw --outputIOFormats=fp16:chw --buildOnly --workspace=1024 --onnx=weights/model-b1.onnx --saveEngine=weights/model-b1.engine

### Run engine
trtexec --fp16 --avgRuns=1000 --warmUp=1000 --workspace=1024 --inputIOFormats=fp16:chw --outputIOFormats=fp16:chw --loadEngine=model-b1.engine

```
### Result on 21.06 (TRT7)
| Model Name | Batch Size | Precision | Infer Time |
| ---------------- | --------------- | ------------- | ------------- |
| Yolov6s | 1 | FP32 | 252.7 |
| Yolov6m | 1 | FP32 | 150.2 |
|---|---|---|---|
| Yolov6s | 32 | FP32 | 416.0 |
| Yolov6m | 32 | FP32 | 210.3 |
|---|---|---|---|
| Yolov6s | 1 | FP16 | 288.0 |
| Yolov6m | 1 | FP16 | 151.7 |
|---|---|---|---|
| Yolov6s | 32 | FP16 | 466.7 |
| Yolov6m | 32 | FP16 | 194.8 |

### Result on 22.04 (TRT8)
| Model Name | Batch Size | Precision | Infer Time |
| ---------------- | --------------- | ------------- | ------------- |
| Yolov6s | 1 | FP32 | 317.7 |
| Yolov6m | 1 | FP32 | 162.4 |
|---|---|---|---|
| Yolov6s | 32 | FP32 | 427.2 |
| Yolov6m | 32 | FP32 | 200 |
|---|---|---|---|
| Yolov6s | 1 | FP16 | 319.2 |
| Yolov6m | 1 | FP16 | 164.0 |
|---|---|---|---|
| Yolov6s | 32 | FP16 | 427.2 |
| Yolov6m | 32 | FP16 | 205.0 |

**Comment by mtjhl** [comment]
1. Did you use the quantized models for the benchmark?
* The inference speeds we reported are FP16 model's speed, not INT8 quantized model.
2. Related to my last issue https://github.com/meituan/YOLOv6/issues/539, does the new version also boost the metrics for small objects?
* We didnot record the AP on small/midium/big objects. We will pay more attention on those metrics later. You can test the models of YOLOv6 0.2.1 and 0.3 to see the details of mAP.
3. Do you have plan to update the benchmark result using TRT 8 to make it comparable with legacy model benchmark? From my result, TRT8 boost the performance since it solve major problems in TRT7.
 * Yes, we already tested the related models' speed with TRT8.  However, many other detectors reported the speed on TRT7, so that we only show the results of TRT8. We are open to update the results with TRT8.

**Comment by shensheng272** [comment]
Test speed configs and commands are listed in [Test speed](https://github.com/meituan/YOLOv6/blob/main/docs/Test_speed.md)

Speed performance is highly related to hardware and software setting. Could you provide more hardware setting? 

By the way, fp32  trt engine build commands should be --fp32, this might be the reason why your fp32 results to close to fp16

**Comment by haritsahm** [comment]
> Test speed configs and commands are listed in [Test speed](https://github.com/meituan/YOLOv6/blob/main/docs/Test_speed.md)
> 
> Speed performance is highly related to hardware and software setting. Could you provide more hardware setting?
> 
> By the way, fp32 trt engine build commands should be --fp32, this might be the reason why your fp32 results to close to fp16

I think I misspelled the --fp16 since I just copy the command from FP16 section. I don't use the `--fp16` when trying the FP32 precision. I use T4 with 20cores cpu. I'll try to reproduce it again later
