### ISSUE TITLE
YOLOv6 on NVIDIA DeepStream

### ISSUE THREAD

**Issue by marcoslucianops** [meituan/YOLOv6#704]
Repository to use YOLOv6 model on NVIDIA DeepStream SDK.

Link: https://github.com/marcoslucianops/DeepStream-Yolo

**Support for YOLOv6 >= 2.0**

#### Config

```
board = NVIDIA Tesla V100 (AWS: p3.2xlarge)
batch-size = 1
eval = val2017 (COCO)
sample = 1920x1080 video
```

#### NMS config

- Eval

```
nms-iou-threshold=0.65
pre-cluster-threshold=0.001
topk=300
```

- Test

```
nms-iou-threshold=0.45
pre-cluster-threshold=0.25
topk=300
```

#### Results (comming soon)

| DeepStream          | Precision | Resolution | IoU=0.5:0.95 | IoU=0.5 | IoU=0.75 | FPS<br />(without display) |
|:-------------------:|:---------:|:----------:|:------------:|:-------:|:--------:|:--------------------------:|
| YOLOv6-L6 3.0       | FP16      | 1280       |         |    |     |                      |
| YOLOv6-M6 3.0       | FP16      | 1280       |         |    |     |                      |
| YOLOv6-S6 3.0       | FP16      | 1280       |         |    |     |                      |
| YOLOv6-N6 3.0       | FP16      | 1280       |         |    |     |                      |
| YOLOv6-L 3.0        | FP16      | 640        |         |    |     |                      |
| YOLOv6-M 3.0        | FP16      | 640        |         |    |     |                      |
| YOLOv6-S 3.0        | FP16      | 640        |         |    |     |                      |
| YOLOv6-N 3.0        | FP16      | 640        |         |    |     |                      |

**Comment by mtjhl** [comment]
Thank you very much for adding yolov6 in your great work. 👍👍👍
