### ISSUE TITLE
About Backbone Size

### ISSUE THREAD

**Issue by YinengXiong** [meituan/YOLOv6#705]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

请问RepVGG-b1的网络推理时间大致与v6的哪个版本的backbone相当？

**Comment by mtjhl** [comment]
我看 RepVGG-B1 的 参数是  51.82 M，但是它的输入应该是 224x224，YOLOv6L 整个模型是 59.6 M，backbone 应该在 40M 左右，YOLOv6M 整个模型是 34.9M，bacbkone 可能是 20 M 左右，YOLOv6 输入是 640x640 ，总的推理时间可能跟 M 模型差不多。但是这个得测测才知道。以上仅是人工来推算的。
