### ISSUE TITLE
输入尺寸问题

### ISSUE THREAD

**Issue by TGUCJX** [meituan/YOLOv6#709]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [x] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

输入尺寸只能是320的倍数吗，不能自定义尺寸吗，而且宽高比只能是1：1吗

**Comment by mtjhl** [comment]
1. 可以不是 320 的倍数，可以自定义尺寸，例如 512 这种，只要是 32 的倍数就行。
2. 宽高比当前训练的时候是 1:1 ，这个我们马上更新成支持长方形训练。

**Comment by a1134877579** [comment]
thank you
