### ISSUE TITLE
[bug] val转coco格式时width和height写反了

### ISSUE THREAD

**Issue by ChHanXiao** [meituan/YOLOv6#71]
val转coco格式时width和height写反了，导致评估mAP一直为0
https://github.com/meituan/YOLOv6/blob/d22979c1cba98304c84b19eb3569c23e3ed24961/yolov6/data/datasets.py#L368

**Comment by khwengXU** [comment]
Thanks for your attentions！
We have received your suggestions and will fix it soon.

**Comment by khwengXU** [comment]
The bug is fixed.
