### ISSUE TITLE
YOLOv6_030 使用release3.0的yolov6s.pt权重提示numpy(>=1.24.0 in requirements.txt)版本过高

### ISSUE THREAD

**Issue by ChenGongfu** [meituan/YOLOv6#710]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

# python tools/eval.py --weights yolov6s.pt --data data/coco.yaml --img 640

Namespace(data='data/coco.yaml', weights='yolov6s.pt', batch_size=32, img_size=640, conf_thres=0.03, iou_thres=0.65, task='val', device='0', half=False, save_dir='runs/val/', name='exp', test_load_size=640, letterbox_return_int=False, scale_exact=False, force_no_pad=False, not_infer_on_rect=False, reproduce_640_eval=False, eval_config_file='./configs/experiment/eval_640_repro.py', do_coco_metric=True, do_pr_metric=False, plot_curve=True, plot_confusion_matrix=False, verbose=False, config_file='')
Loading checkpoint from yolov6s.pt

Fusing model...
/home/cgf/miniconda3/envs/YOLOv6_021/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Switch model to deploy modality.
Model Summary: Params: 18.54M, Gflops: 45.28
Val: Checking formats of labels with 8 process(es): 
4952 label(s) found, 48 label(s) missing, 0 label(s) empty, 0 invalid label file
Val: Final numbers of valid images: 5000/ labels: 5000. 
Traceback (most recent call last):
  File "/home/cgf/Projects/YOLO/v6/YOLOv6-0.3.0/tools/eval.py", line 164, in <module>
    main(args)
  File "/home/cgf/Projects/YOLO/v6/YOLOv6-0.3.0/tools/eval.py", line 159, in main
    run(**vars(args))
  File "/home/cgf/miniconda3/envs/YOLOv6_021/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/cgf/Projects/YOLO/v6/YOLOv6-0.3.0/tools/eval.py", line 149, in run
    dataloader = val.init_data(dataloader, task)
  File "/home/cgf/Projects/YOLO/v6/YOLOv6-0.3.0/yolov6/core/evaler.py", line 97, in init_data
    dataloader = create_dataloader(self.data[task if task in ('train', 'val', 'test') else 'val'],
  File "/home/cgf/Projects/YOLO/v6/YOLOv6-0.3.0/yolov6/data/data_load.py", line 41, in create_dataloader
    dataset = TrainValDataset(
  File "/home/cgf/Projects/YOLO/v6/YOLOv6-0.3.0/yolov6/data/datasets.py", line 75, in __init__
    np.int
  File "/home/cgf/miniconda3/envs/YOLOv6_021/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?

**Comment by mtjhl** [comment]
您可以这么操作，来解决版本问题
用 np.int_ 替换 yolov6/data/datasets.py 中的 np.int .
