### ISSUE TITLE
训练过程中的验证和训练完验证，指标差距很大，是什么原因导致的？

### ISSUE THREAD

**Issue by TGUCJX** [meituan/YOLOv6#714]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

训练过程中验证和训练完用eval.py验证，指标差距很大，这是什么原因导致的？

**Comment by Chilicyy** [comment]
您好，一般来说指标不会有差异。麻烦发下您训练后用的评估命令，以及相关的指标差距截图。

**Comment by TGUCJX** [comment]
训练
![image](https://user-images.githubusercontent.com/58207653/218619963-3f702e87-fe6c-4c07-b4c6-8ceccfe8d27c.png)
验证
`python tools/eval.py --data data/dataset.yaml --weights runs/train/yolov6s_hlb_1024/weights/last_ckpt.pt --task val --img 1024`
![image](https://user-images.githubusercontent.com/58207653/218620172-e4531004-416a-49a8-8843-11b9c5ef7ec1.png)

**Comment by Chilicyy** [comment]
您训练时输入图像尺寸也是1024吗？

**Comment by TGUCJX** [comment]
是的

**Comment by Chilicyy** [comment]
能提供下启动eval.py后的日志吗？

**Comment by TGUCJX** [comment]
是这块吗？
![image](https://user-images.githubusercontent.com/58207653/218624347-76cb82b6-0071-4d98-9b40-75cf4e6abbc5.png)

**Comment by Chilicyy** [comment]
`--test_load_size` 这个参数也要设置为 1024，不然实际用的是640尺寸做评估。

**Comment by TGUCJX** [comment]
原来是这样，谢谢你，解决了，非常感谢！！！

**Comment by Claraeunice** [comment]
> 能提供下启动 eval.py 后的打印日志吗？

你好，请问一下为什么你验证出来有这么多指标呢？我跑的时候验证发现只有两个指标：0.5和0.5：0.95
