### ISSUE TITLE
export onnx error

### ISSUE THREAD

**Issue by Lorilin7** [meituan/YOLOv6#718]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

使用 python3 ./deploy/ONNX/export_onnx.py --weights yolov6s.pt --img 640 --batch-size 1  --simplify 报错如下：
ONNX export failure: Node (/detect/Unsqueeze) has input size 2 not in range [min=1, max=1].

==> Context: Bad node spec: input: "/detect/Expand_1_output_0" input: "/detect/Constant_3_output_0" output: "/detect/Unsqueeze_output_0" name: "/detect/Unsqueeze" op_type: "Unsqueeze"

使用yolov6m.pt依然存在同样问题

**Comment by mtjhl** [comment]
这个模型是从 YOLOv6 官方 github 下载的吗？ 您的 onnx 版本是？

**Comment by Lorilin7** [comment]
> 这个模型是从 YOLOv6 官方 github 下载的吗？ 您的 onnx 版本是？

hi ，已经检查过版本，onnx版本低于1.10.0, 更新后使用官方github可以export出onnx模型，感谢
