### ISSUE TITLE
onnx推理结果置信度为1

### ISSUE THREAD

**Issue by llopen** [meituan/YOLOv6#728]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

  onnx模型是用脚本python ./deploy/ONNX/export_onnx.py --weights ./weights/yolov6s_base.pt --img 640 --batch 1 --simplify 生成的，输出结果目标框是准确的，但是置信度结果都为1

**Comment by mtjhl** [comment]
是的，那个 iou conf 我们默认都设置为1 了，具体的每个类别的置信度，您需要从类别置信度来取。例如模型输出的是 【8400，7】，分别代表[ 4个 位置，1个 iou conf， 2 个每个类别对应的置信度】，您需要从后面 2 个类别置信度来获取置信度。
