### ISSUE TITLE
Inference on model trained on custom dataset

### ISSUE THREAD

**Issue by ferraridamiano** [meituan/YOLOv6#730]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

Hello, thank you for this cool project!
I followed the turtorial and trained on coco128. The training succeeded, now I would like to infer on the trained model, so I added the following command to the turtorial:

    !python tools/infer.py --weights /content/YOLOv6/runs/train/exp/weights/best_ckpt.pt --source ../coco128/images/train2017/000000000025.jpg

However the predicted image does not have any BBox, is it because of the small dataset or am I doing something wrong? I also tested other images and all of them have no BBox.

**Comment by mtjhl** [comment]
The dataset is too small, you can download the pretrained model from YOLOv6 release page.

**Comment by ferraridamiano** [comment]
Thank you for the fast reply!
How many images are needed to train the nano model for "good enough" results?

**Comment by mtjhl** [comment]
If you use pretrained model to finetune your model, and your objects is not to small, maybe 1000 images is fine. More data , better performace you will get.
