### ISSUE TITLE
A bug of "datasets.py"

### ISSUE THREAD

**Issue by Accustomer** [meituan/YOLOv6#735]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

在datasets.py的TrainValDataset类的get_imgs_labels函数中，这段代码可能会导致bug：
`
  label_paths = sorted(
      osp.join(label_dir, _new_rel_path_with_ext(img_dir, p, ".txt"))
      for p in img_paths
  )
`
因为sorted之后的label_paths和img_paths顺序可能错乱。比如，我在训练时这么命名样本：
`
img_paths = ['a.jpg', 'a.tag.jpg']
label_paths = ['a.txt', 'a.tag.txt']
`
排序之后就会变成：
`
img_paths = ['a.jpg', 'a.tag.jpg']
label_paths =['a.tag.txt', 'a.txt']
`
这样的顺序错乱会导致训练出现严重问题，所以不能使用sorted函数。

**Comment by mtjhl** [comment]
感谢您提出的潜在 bug，我们会尽快修复这个问题。
