### ISSUE TITLE
用预训练模型推理时RepVGGBlock如何设置成deploy模式

### ISSUE THREAD

**Issue by wsy-yjys** [meituan/YOLOv6#736]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

我在使用turtorial.ipynb文件进行debug推理时，发现算法运行至RepVGGBlock时并没有使用deploy模式，请问该如何设置成该模式？

**Comment by khwengXU** [comment]
Thanks for your attentions, could you show the detailed debug shell?

**Comment by wsy-yjys** [comment]
您好，如果直接使用官方提供的预训练模型，在进行预测时RepVGGBlock是自动使用deploy模式吗？

**Comment by mtjhl** [comment]
预测的时候是转成部署模式的。具体可以见这里：
https://github.com/meituan/YOLOv6/blob/c418f67a15c4dca69480e08a5809dc42cd187a30/yolov6/core/evaler.py#L79

**Comment by wsy-yjys** [comment]
好的，谢谢！
