### ISSUE TITLE
为什么eval的时候实在训练集上

### ISSUE THREAD

**Issue by ianpundar** [meituan/YOLOv6#739]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

<img width="842" alt="image" src="https://user-images.githubusercontent.com/57125678/221570372-ef6cfd05-b6aa-48e1-acee-a53fe4dd9a03.png">
为什么实在训练集上测试，我是用的yaml文件如下
`
....
anno_path: datasets/widerface/annotations/widerface2019_val_cocostyle.json

is_coco: False

nc: 1
names: [ 'face' ]
`

**Comment by mtjhl** [comment]
可能是现实的字段误导了您。其实它就是在验证集评估的。

**Comment by ianpundar** [comment]
> 可能是现实的字段误导了您。其实它就是在验证集评估的。

明白了，谢谢
