### ISSUE TITLE
How can I train my data without .json?

### ISSUE THREAD

**Issue by tonyostum2022** [meituan/YOLOv6#74]
My data is in YOLO format, but I can't use yolov6 without a .json file, can you help me?

**Comment by jia0511** [comment]
https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md

**Comment by aknsel** [comment]
> https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md

Although I created a label in txt format as described in the link above, I am getting the following error
![Screen Shot 2022-06-28 at 11 27 46](https://user-images.githubusercontent.com/108330135/176152386-a3f4f46d-f076-427f-8c19-402abb6116cb.png)
