### ISSUE TITLE
[inference.ipynb] RGB order is wrong

### ISSUE THREAD

**Issue by TamyGit** [meituan/YOLOv6#741]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [ ] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

Hi, I found a small mistake in inference.ipynb.
You are using PIL to read an image.
The color order of PIL is RGB.
You don't need to transpose the color order later.
Or, you should use cv2, which is BGR.

```
  try:
    from PIL import Image
    img_src = np.asarray(Image.open(requests.get(url, stream=True).raw))
    assert img_src is not None, f'Invalid image: {path}'
  except Exception as e:
    LOGGER.Warning(e)
  image = letterbox(img_src, img_size, stride=stride)[0]

  # Convert
  image = image.transpose((2, 0, 1))[::-1]  # HWC to CHW, BGR to RGB
```

**Comment by mtjhl** [comment]
Thanks, I will fix this error.

**Comment by mtjhl** [comment]
Actually, YOLOv6 model use BGR order, so this code is correct, however, the annotation is wrong, it should be `# HWC to CHW, RGB to BGR`.
Thank you again. I fixed this mistake.
