### ISSUE TITLE
CSPBepBackbone' object has no attribute 'fuse_P2

### ISSUE THREAD

**Issue by abhishekbj97** [meituan/YOLOv6#747]
### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar feature requests.

### Description

CSPBepBackbone' object has no attribute 'fuse_P2

How to resolve this issue?

### Use case

Pre-trained model is giving error when i convert from .pt to .onnx

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by mtjhl** [comment]
Hi, What's your code version? Does your code is latest?

**Comment by abhishekbj97** [comment]
2.0

**Comment by Chilicyy** [comment]
@abhishekbj97 Hi, we have already updated to v3.0, please git pull the latest code on main branch.

**Comment by abhishekbj97** [comment]
Its working now
Thank You!
