### ISSUE TITLE
mAP

### ISSUE THREAD

**Issue by Sunway-s** [meituan/YOLOv6#75]
<img width="1074" alt="截屏2022-06-26 下午9 57 37" src="https://user-images.githubusercontent.com/108172018/175817819-c675cb72-af77-4c68-9656-58020b45e1f2.png">
<img width="212" alt="截屏2022-06-26 下午10 06 23" src="https://user-images.githubusercontent.com/108172018/175818166-a63c06bd-a1f4-43d8-87de-a0a2b3296ec3.png">
MAP 都是零

**Comment by zheng325** [comment]
> <img alt="截屏2022-06-26 下午9 57 37" width="1074" src="https://user-images.githubusercontent.com/108172018/175817819-c675cb72-af77-4c68-9656-58020b45e1f2.png">
> 
> <img alt="截屏2022-06-26 下午10 06 23" width="212" src="https://user-images.githubusercontent.com/108172018/175818166-a63c06bd-a1f4-43d8-87de-a0a2b3296ec3.png">
> 
> MAP 都是零

coco.yaml路径用绝对路径，但是又会出现新的报错，结果与coco集不对应

**Comment by cumtb-zyh** [comment]
我的也是，mAP全是0

**Comment by ChHanXiao** [comment]
#71 这个问题

**Comment by kwuliang** [comment]
运行命令加上  ‘ --check-images --check-labels ’
