### ISSUE TITLE
Dynamic input shape with tensorrt

### ISSUE THREAD

**Issue by dferrarigrowtech** [meituan/YOLOv6#751]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [ ] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

Hello and thanks for this project. I'm trying to use the `.engine` file (created with `onnx_to_tensorrt.py`) with pyhton. When I created it, I saw this in the log:
```
2023-03-16 09:43:45 - __main__ - DEBUG - === Network Description ===
2023-03-16 09:43:45 - __main__ - DEBUG - Input  0 | Name: images  | Shape: (1, 3, 640, 640)
2023-03-16 09:43:45 - __main__ - DEBUG - Output 0 | Name: outputs | Shape: (1, 8400, 6)
2023-03-16 09:43:45 - __main__ - DEBUG - === Optimization Profiles ===
2023-03-16 09:43:45 - __main__ - DEBUG - images - OptProfile 0 - Min (1, 3, 640, 640) Opt (1, 3, 640, 640) Max (1, 3, 640, 640)
```
Which means that the input size is fixed to 640x640 image. What if I would like to use it with images with a different aspect ratio? I'm able to use the model with 640x640 image, but not with other sizes.

Thank you!

**Comment by Chilicyy** [comment]
Hi @dferrarigrowtech , you can try to export onnx model with the input size what you want, and then convert to trt engine file again.
