### ISSUE TITLE
源码

### ISSUE THREAD

**Issue by sdreamforchen** [meituan/YOLOv6#752]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

1 蒸馏代码中，N/S有loss_iou_lrtb，而M/L没有，且head中没有loss_iou_lrtb这个loss。想请教下这是如何考虑的呢？
2 自蒸馏的流程，是先无预训练权重训练一个模型，然后用这个模型再次训练相同的、无预训练权重的模型吗？相当于走了2遍。

**Comment by sdreamforchen** [comment]
您好。再请教一个问题：Due to the removal of quantization-sensitive layers in v2.0 release, we directly use full QAT on YOLOv6-S
trained with RepOptimizer。
这句话的意思是先用yolov6-V1.0训练一个网络（采用哪种方式训练，RepOpt？），然后做量化敏感度分析，把敏感度高的直接删除了，再训练成yolov6-V2.0吗？

**Comment by Chilicyy** [comment]
@sdreamforchen 感谢您的关注！
1. 蒸馏代码中，N/S有loss_iou_lrtb 是为了推理加速，由于采用DFL之后对N/S模型的推理速度影响较大，因此增加了一个回归分支在训练过程中一起学习，推理时用该分支替代DFL分支去预测目标位置坐标；M/L模型默认开启DFL，因此不需要额外增加回归分支；
2. 是的，第一次先训练一个教师网络，第二次用教师网络蒸馏学生网络，两个模型网络结构一致，均没采用预训练权重；
3. QAT的相关训练流程可以参考[教程](https://yolov6-docs.readthedocs.io/zh_CN/latest/%E9%87%8F%E5%8C%96/%E9%87%8F%E5%8C%96.html#)的指引。

**Comment by sdreamforchen** [comment]
谢谢您！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月20日(周一) 晚上7:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [meituan/YOLOv6] 源码 (Issue #752)




 
@sdreamforchen 感谢您的关注！
  
蒸馏代码中，N/S有loss_iou_lrtb 是为了推理加速，由于采用DFL之后对N/S模型的推理速度影响较大，因此增加了一个回归分支在训练过程中一起学习，推理时用该分支替代DFL分支去预测目标位置坐标；M/L模型默认开启DFL，因此不需要额外增加回归分支；
 
是的，第一次先训练一个教师网络，第二次用教师网络蒸馏学生网络，两个模型网络结构一致，均没采用预训练权重；
 
QAT的相关训练流程可以参考教程的指引。

**Comment by sdreamforchen** [comment]
> 

您好。量化参考教程并没有提到Due to the removal of quantization-sensitive layers in v2.0 release, we directly use full QAT on YOLOv6-S trained with RepOptimizer的相关信息

**Comment by xingyueye** [comment]
@sdreamforchen 在v2版本中，结构相比于v1有所改动。在v1中我们发现量化敏感的层，其中最有影响的就是proj_head分支，这块在v2中被移除了。所以说就可以对整个网络进行QAT，不需要再去进行partial 量化了。

**Comment by sdreamforchen** [comment]
谢谢。你们的流程的确让人学习到很多，谢谢大佬！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月21日(周二) 上午10:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [meituan/YOLOv6] 源码 (Issue #752)




 
@sdreamforchen 在v2版本中，结构相比于v1有所改动。在v1中我们发现量化敏感的层，其中最有影响的就是proj_head分支，这块在v2中被移除了。所以说就可以对整个网络进行QAT，不需要再去进行partial 量化了。

**Comment by sdreamforchen** [comment]
> @sdreamforchen 在v2版本中，结构相比于v1有所改动。在v1中我们发现量化敏感的层，其中最有影响的就是proj_head分支，这块在v2中被移除了。所以说就可以对整个网络进行QAT，不需要再去进行partial 量化了。

您好，对比了v1的onnx，是把obj_preds3个分支的那个conv删除了吧
