### ISSUE TITLE
yolov6n with fuse_ab QAT训练问题

### ISSUE THREAD

**Issue by OMG59E** [meituan/YOLOv6#758]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

teacher_model with fuse_ab 不支持 QAT训练?

**Comment by OMG59E** [comment]
YOLOV6/configs/repopt/yolov6n_opt_qat.py   增加  anchors_init=[[10, 13, 19, 19, 33, 23]], 
仍然报错：
Traceback (most recent call last):
  File "tools/train.py", line 128, in <module>
    main(args)
  File "tools/train.py", line 113, in main
    trainer = Trainer(args, cfg, device)
  File "/media/xingwg/workspaces/YOLOv6/yolov6/core/engine.py", line 64, in __init__
    self.quant_setup(model, cfg, device)
  File "/media/xingwg/workspaces/YOLOv6/yolov6/core/engine.py", line 557, in quant_setup
    model.load_state_dict(torch.load(cfg.qat.calib_pt)['model'].float().state_dict())
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Model:
        Missing key(s) in state_dict: "detect.reg_preds_lrtb.0.weight", "detect.reg_preds_lrtb.0.bias", "detect.reg_preds_lrtb.1.weight", "detect.reg_preds_lrtb.1.bias", "detect.reg_preds_lrtb.2.weight", "detect.reg_preds_lrtb.2.bias".

**Comment by OMG59E** [comment]
虽然上述可以进行QAT训练了，但是产生的模型是异常的，不能检测到任何目标，qat_MAP也是0

**Comment by mtjhl** [comment]
如果是要使用量化模型的话，推荐使用 [QARep 版本]( https://github.com/meituan/YOLOv6/tree/main/configs/qarepvgg)
这个量化掉点比较少。或者使用普通卷积版本。
QAT 训练的，当时是支持 v0.2 版本的，我们后面会评估是否更新这个 QAT 脚本。

**Comment by OMG59E** [comment]
> 如果是要使用量化模型的话，推荐使用 [QARep 版本](https://github.com/meituan/YOLOv6/tree/main/configs/qarepvgg) 这个量化掉点比较少。或者使用普通卷积版本。 QAT 训练的，当时是支持 v0.2 版本的，我们后面会评估是否更新这个 QAT 脚本。

自定义数据集，QAT训练流程是不是: finetune -> hs_search -> reopt -> ptq_gen_calib -> QAT训练  ？

**Comment by mtjhl** [comment]
的确是这个流程。但是 RepOpt 训练流程有点繁琐。建议用当前的  QARepVGG 版本训练。

**Comment by junjun1023** [comment]
> 的确是这个流程。但是 RepOpt 训练流程有点繁琐。建议用当前的 QARepVGG 版本训练。

請問利用 QARepVGG 版本訓練完後，要怎麼樣才能把模型轉成 quantized 的
