### ISSUE TITLE
YOLOv6 3.0's YOLOv6-S model performances worse than YOLOv6-S-base?

### ISSUE THREAD

**Issue by tino926** [meituan/YOLOv6#759]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

in the YOLOv6 3.0 release page: https://github.com/meituan/YOLOv6/releases/tag/0.3.0

YOLOv6-S model's accuracy is 45.0, lower than than YOLOv6-S-base's 45.3
YOLOv6-S model's fps is 339, slower than YOLOv6-S-base's 346

Do you have some discussion why the new model performance worse than the old model?
On the other hand, how can I train the YOLOv6-S-base? With an older YOLOv6 release?

**Comment by mtjhl** [comment]
1. Do you have some discussion why the new model performance worse than the old model?
   YOLOv6s base model is newer, those base model use basic conv, not repvgg, their mAP is lower than the corresponding repvgg model, except for the yolov6s.
2. On the other hand, how can I train the YOLOv6-S-base? With an older YOLOv6 release?
 Both base model and YOLOv6n/s/m/l can be trained in the v0.3 or v0.3.1.
