### ISSUE TITLE
训练自己的数据集问题

### ISSUE THREAD

**Issue by ruoyuchen0903** [meituan/YOLOv6#76]
AssertionError: Results do not correspond to current coco set

**Comment by mingwz** [comment]
老哥你解决了吗？我也是遇到了相同的问题

**Comment by ExWang** [comment]
when generate_coco_format_labels， this repo make `img_id` by `osp.basename(img_path).split('.')[0]` in `datasets.py`. You will get 'str' label.
BUT, when evaluating results, this repo make `img_id ` by 'int(path.stem) if path.stem.isnumeric() else path.stem'. You may get 'int' label.
After, coco tools will check these `img_id`, so lead this `AssertionError `

**Comment by mingwz** [comment]
Thanks for your reply! I solve the problem by this way. @ExWang

**Comment by ruoyuchen0903** [comment]
so how can I solve it?

2022-06-27 15:05:30"Nebula Wang" ***@***.***>写道：

when generate_coco_format_labels， this repo make img_id by osp.basename(img_path).split('.')[0] in datasets.py. You will get 'str' label.
BUT, when evaluating results, this repo make img_id by 'int(path.stem) if path.stem.isnumeric() else path.stem'. You may get 'int' label.
After, coco tools will check these img_id, so lead this AssertionError

**Comment by ExWang** [comment]
> 
<img width="827" alt="image" src="https://user-images.githubusercontent.com/30236357/176069812-c7f7f018-bfc1-4986-b2e3-12df927592b9.png">

**Comment by ExWang** [comment]
> so how can I solve it? 2022-06-27 15:05:30"Nebula Wang" ***@***.***>写道： when generate_coco_format_labels， this repo make img_id by osp.basename(img_path).split('.')[0] in datasets.py. You will get 'str' label. BUT, when evaluating results, this repo make img_id by 'int(path.stem) if path.stem.isnumeric() else path.stem'. You may get 'int' label. After, coco tools will check these img_id, so lead this AssertionError — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

<img width="827" alt="image" src="https://user-images.githubusercontent.com/30236357/176069895-dedd5ab9-911c-4e4b-8e50-d7a4009f76cd.png">

**Comment by moxigk** [comment]
之前的错误是：
TypeError: '<' not supported between instances of 'str' and 'int'

我根据你的方法改了，出现了这个问题
AssertionError: Results do not correspond to current coco set

是不是数据集的名字必须是数字吗？不能包含英文吗或者其他字符吗？

**Comment by xiaoluxiaoluxiaolu** [comment]
>

> Hello, I would like to know which file needs to be modified

**Comment by ExWang** [comment]
> > 
> 
> > Hello, I would like to know which file needs to be modified

YOLOv6/yolov6/data/datasets.py , line 493
[            img_id = int(path.stem) if path.stem.isnumeric() else path.stem](https://github.com/meituan/YOLOv6/blob/1d1335c62a939f2e5d639bdf2afec65c18beb59f/yolov6/data/datasets.py#L493)

**Comment by ExWang** [comment]
> 之前的错误是： TypeError: '<' not supported between instances of 'str' and 'int'
> 
> 我根据你的方法改了，出现了这个问题 AssertionError: Results do not correspond to current coco set
> 
> 是不是数据集的名字必须是数字吗？不能包含英文吗或者其他字符吗？

我看不是必须数字的，最早这个repo生成image_id用的img_id = osp.basename(img_path).split('.')[0]是str的id，但是在后面predict的时候，用的 `img_id = int(path.stem) if path.stem.isnumeric() else path.stem` ,也就是说，假设你的图片名字是数字的，就会转成int的id。

不过这个不统一的问题好像在最近的一个commit中修复了，pull一下最新的就行

**Comment by Mobu59** [comment]
@nidetaoge have you fixed the problem?

**Comment by yutao007** [comment]
将这里的images_id修改后，仍然还是报错。感觉这一块有问题没有完全解决。其中我的环境是：
torch                   1.10.0+cu111
torchaudio              0.10.0+rocm4.1
torchvision             0.11.0+cu111


修改处
def save_one_json(predn, jdict, path, class_map):
    # Save one JSON result {"image_id": 42, "category_id": 18, "bbox": [258.15, 41.29, 348.26, 243.78], "score": 0.236}
    #image_id = int(path.stem) if path.stem.isnumeric() else path.stem
    image_id = path.stem

报错处
   assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())), \
AssertionError: Results do not correspond to current coco set
terminate called without an active exception
Aborted (core dumped)

**Comment by qybing** [comment]
1.把datasets.py文件的img_id = int(path.stem) if path.stem.isnumeric() else path.stem改成img_id = path.stem
2.把evaler.py文件的image_id = int(path.stem) if path.stem.isnumeric() else path.stem改成img_id = path.stem
就可以运行起来了

**Comment by Mobu59** [comment]
> 1.把datasets.py文件的img_id = int(path.stem) if path.stem.isnumeric() else path.stem改成img_id = path.stem 2.把evaler.py文件的image_id = int(path.stem) if path.stem.isnumeric() else path.stem改成img_id = path.stem 就可以运行起来了

Thanks, I made it

**Comment by yutao007** [comment]
谢谢博主解答，我已经按照提示将datasets.py    evaler.py   val.py   三个文件中关于image_id的赋值都改成了path.stem
但还是报错，如果别人没错的话，那应该就是我这边数据集或者别的问题了
   assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())), \
AssertionError: Results do not correspond to current coco set

**Comment by yutao007** [comment]
问题解决了，要记得删掉先前跑数据生成的json文件。

**Comment by luckyeap2020** [comment]
> 之前的错误是： TypeError: '<' not supported between instances of 'str' and 'int'
> 
> 我根据你的方法改了，出现了这个问题 AssertionError: Results do not correspond to current coco set
> 
> 是不是数据集的名字必须是数字吗？不能包含英文吗或者其他字符吗？

不用改源代码，只用一个粗暴的方式解决了：
1. 数据集中文件的名称只用数字
2. 删除之前训练产生的所有过程文件，即只保留原始数据集的图片和标注

**Comment by ruabliuqiu** [comment]
训练前，自己数据集分布和制作方法跟yolov5一样好像，不需要json格式标签。我参考这个博主的方法训练成功了，https://blog.csdn.net/DeepLearning_/article/details/125511165?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22125511165%22%2C%22source%22%3A%22DeepLearning_%22%7D&ctrtid=c4P6Y

**Comment by ruabliuqiu** [comment]
> 训练前，自己数据集分布和制作方法跟yolov5一样好像，不需要json格式标签。我参考这个博主的方法训练成功了，https://blog.csdn.net/DeepLearning_/article/details/125511165?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22125511165%22%2C%22source%22%3A%22DeepLearning_%22%7D&ctrtid=c4P6Y

训练自己数据集很简单的，只要环境配置好了就行。

**Comment by ruabliuqiu** [comment]
训练自己数据集很简单的，跟v5一样。

**Comment by ruabliuqiu** [comment]
训练前，自己数据集分布和制作方法跟yolov5一样，不需要json格式标签。我参考这个博主的方法训练成功了，[https://blog.csdn.net/DeepLearning_/article/details/125511165?spm=1001.2014.3001.5502](url)

**Comment by shenshi19** [comment]
> 训练前，自己数据集分布和制作方法跟yolov5一样，不需要json格式标签。我参考这个博主的方法训练成功了，[https://blog.csdn.net/DeepLearning_/article/details/125511165?spm=1001.2014.3001.5502](url)
兄弟，你的yaml文件是什么样子的，我参考了你发的链接还是有问题的

**Comment by Yaomingyang** [comment]
官方已经解决这个问题了，重新下载工程，按照docs/Train_custom_data.md运行即可

**Comment by yaos666** [comment]
> 1.把datasets.py文件的img_id = int(path.stem) if path.stem.isnumeric() else path.stem改成img_id = path.stem 2.把evaler.py文件的image_id = int(path.stem) if path.stem.isnumeric() else path.stem改成img_id = path.stem 就可以运行起来了

成功啦，必须把datasets.py、evaler.py都改了才能运行起来，只改evaler.py文件还是会报错的哟

**Comment by shenshi19** [comment]
> > 1.把datasets.py文件的img_id = int(path.stem) if path.stem.isnumeric() else path.stem改成img_id = path.stem 2.把evaler.py文件的image_id = int(path.stem) if path.stem.isnumeric() else path.stem改成img_id = path.stem 就可以运行起来了
> 
> 成功啦，必须把datasets.py、evaler.py都改了才能运行起来，只改evaler.py文件还是会报错的哟

新版的好像datasets.py好像img_id-int()那里改了

**Comment by suzauddola** [comment]
Evaluating mAP by pycocotools.
Saving runs/train/ttop_6s_3004/predictions.json...
ERROR in evaluate and save model.
ERROR in training loop or eval/save model.

Training completed in 0.039 hours.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
Traceback (most recent call last):
  File "tools/train.py", line 94, in <module>
    main(args)
  File "tools/train.py", line 84, in main
    trainer.train()
  File "/YOLOv6/yolov6/core/engine.py", line 70, in train
    self.train_in_loop()
  File "/YOLOv6/yolov6/core/engine.py", line 89, in train_in_loop
    self.eval_and_save()
  File "/YOLOv6/yolov6/core/engine.py", line 115, in eval_and_save
    self.eval_model()
  File "/YOLOv6/yolov6/core/engine.py", line 134, in eval_model
    results = eval.run(self.data_dict,
  File "/yolov6/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/YOLOv6/tools/eval.py", line 83, in run
    eval_result = val.eval_model(pred_result, model, dataloader, task)
  File "/YOLOv6/yolov6/core/evaler.py", line 127, in eval_model
    pred = anno.loadRes(pred_json)
  File "/home/suza/.conda/envs/yolov6/lib/python3.8/site-packages/pycocotools/coco.py", line 327, in loadRes
    assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())), \
AssertionError: Results do not correspond to current coco set



> When generate_coco_format_labels, this repo make `img_id` by `osp.basename(img_path).split('.')[0]` in `datasets.py`. You **will** get `str` label.
> 
> BUT, when evaluating results, this repo make `img_id` by `int(path.stem) if path.stem.isnumeric() else path.stem` in `convert_to_coco_format` in `evaler.py`. You **may** get `int` label.
> 
> Then, coco tools will check these `img_id`, so lead this `AssertionError`.
> 
> So I suggest to modify `image_id = int(path.stem) if path.stem.isnumeric() else path.stem` to `image_id = path.stem` to solve this error.

After changing to "image_id = path.stem" now this error appears !!

**Comment by jcrdeep** [comment]
https://github.com/meituan/YOLOv6/issues/207#issuecomment-1173439101
