### ISSUE TITLE
Bug-eval

### ISSUE THREAD

**Issue by sdreamforchen** [meituan/YOLOv6#764]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

配置没20epoch验证时，260时不进行验证，264epoch进行验证，其他都是20的整数。最后一个epoch也未eval！

**Comment by Chilicyy** [comment]
请问您训练的总epoch数是多少？最后15个epoch 每3个epoch做一次eval，您可以自己调整eval的间隔。

**Comment by sdreamforchen** [comment]
300epoch



---Original---
From: ***@***.***&gt;
Date: Fri, Apr 7, 2023 10:25 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [meituan/YOLOv6] Bug-eval (Issue #764)




 
请问您训练的总epoch数是多少？最后15个epoch 每3个epoch做一次eval，您可以自己调整eval的间隔。

**Comment by Chilicyy** [comment]
如果您需要最后50个epoch 每个epoch都进行评估，可以将[这行](https://github.com/meituan/YOLOv6/blob/c1e71bc05d9bb6ebf33a8c629bd58acd4cb56d94/yolov6/core/engine.py#L168)的3改为1。

**Comment by sdreamforchen** [comment]
谢谢



---Original---
From: ***@***.***&gt;
Date: Fri, Apr 7, 2023 11:25 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [meituan/YOLOv6] Bug-eval (Issue #764)




 
如果您需要最后50个epoch 每个epoch都进行评估，可以将这行的3改为1。

**Comment by mtjhl** [comment]
@sdreamforchen  我们修复了最后一个 epoch 不评估的问题。https://github.com/meituan/YOLOv6/pull/771/files

**Comment by sdreamforchen** [comment]
谢谢。可否加微信群呢？现在不让加



---Original---
From: ***@***.***&gt;
Date: Fri, Apr 7, 2023 13:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [meituan/YOLOv6] Bug-eval (Issue #764)




 
@sdreamforchen  我们修复了最后一个 epoch 不评估的问题。https://github.com/meituan/YOLOv6/pull/771/files

**Comment by mtjhl** [comment]
您再试一下，应该可以了。
