### ISSUE TITLE
The neck of YOLOv6 (N and S)

### ISSUE THREAD

**Issue by pumpbumb** [meituan/YOLOv6#769]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

In YOLOv6 3.0, I studied the source code and found that it seems the implementation of **RepBiFPANNeck** is just a **RepPANNeck**, not a **BiPAN**. Am I missing something? I look forward to your answer. Thanks very much.😊

**Comment by Chilicyy** [comment]
Hi, you can search `BiFusion` in **RepBiFPANNeck**  for further study.

**Comment by pumpbumb** [comment]
![image](https://user-images.githubusercontent.com/76927477/230768915-568edb79-3cde-4331-a1f6-d8ef74d8960c.png)

Thanks for your reply. As shown in the above figure, `Bi` is reflected in `BiC Module`.  However, in the beginning, I think it is the meaning of `Bi` expressed in the figure below (taken from `EfficientDet`). It seems that I don't understand the meaning of `Bi` clearly. I'm not sure if I'm thinking correctly. Could you please give me some advice? Much appreciated. ^o^

![image](https://user-images.githubusercontent.com/76927477/230768920-5a14398e-19da-4b2f-8fe6-2028926c1e98.png)

**Comment by mtjhl** [comment]
BiC means Bi-directional Concatenation.

**Comment by pumpbumb** [comment]
> BiC means Bi-directional Concatenation.

Got it. Thanks.
