### ISSUE TITLE
Results do not correspond to current coco set

### ISSUE THREAD

**Issue by Timeless-tys** [meituan/YOLOv6#77]
I use the following code for training
python tools/train.py --batch 16 --conf configs/yolov6s.py --data ./data/coco.yaml --device 0
But this mistake happened
AssertionError: Results do not correspond to current coco set
![image](https://user-images.githubusercontent.com/68460579/175844162-07fc58fc-32db-4944-889b-e0d2993e372d.png)

**Comment by mingwz** [comment]
I have the same problem, did you solve it?

**Comment by UygarUsta99** [comment]
I am having the same issue.I could not solve it either.

**Comment by ExWang** [comment]
Try  my comment at #76 , this may be the cause.
