### ISSUE TITLE
Yolov6n/s训练日志

### ISSUE THREAD

**Issue by XA-hyy** [meituan/YOLOv6#778]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

您好，能否提供一下yolov6n/s的fuse_ab模式下的训练日志，复现指标时遇到了问题，想参照训练日志核对一下，谢谢！

**Comment by mtjhl** [comment]
请留下您的邮箱。谢谢

**Comment by XA-hyy** [comment]
872034471@qq.com   感谢~

**Comment by mtjhl** [comment]
已发送，请查收。

**Comment by XA-hyy** [comment]
收到~

**Comment by XA-hyy** [comment]
感谢提供的训练日志，但是我还是有些疑惑。在最新的yolov6v3.0版本中，我从readme看到：“第一次训练模型时（不使用蒸馏）需要开启fuse_ab，并指定use_dfl=True“，但是您提供的日志，无论是v6s或者v6n的dfl loss都是0。而且日志中的网络结构显示reg_preds_af的输出维度是4而不是68，我理解就是use_dfl=False？  所以第一次训练时use_dfl应该怎么设置呢？

**Comment by mtjhl** [comment]
我确认了一下，第一次训练的时候，是需要开启 dfl的，但是训练 teacher 模型的日志，我找不到了。那是另外一个团队训练的。真是抱歉。当时给您发的日志，是不开 dfl 的。


________________________________
发件人: Heyuyang ***@***.***>
发送时间: 2023年4月21日 14:23
收件人: meituan/YOLOv6
抄送: 蒋红亮; Comment
主题: <外部邮件>[美团安全提示：疑似垃圾邮件，请谨慎操作][美团安全提示：疑似垃圾邮件，请谨慎操作]Re: [meituan/YOLOv6] Yolov6n/s训练日志 (Issue #778)


感谢提供的训练日志，但是我还是有些疑惑。在最新的yolov6v3.0版本中，我从readme看到：“第一次训练模型时（不使用蒸馏）需要开启fuse_ab，并指定use_dfl=True“，但是您提供的日志，无论是v6s或者v6n的dfl loss都是0。而且日志中的网络结构显示reg_preds_af的输出维度是4而不是68，我理解就是use_dfl=False？ 所以第一次训练时use_dfl应该怎么设置呢？

―

**Comment by XA-hyy** [comment]
好的 没事，我也不开dfl也能作为对齐指标的参考，谢谢。
