### ISSUE TITLE
Add more images while resuming for training a custom model 

### ISSUE THREAD

**Issue by VivekSinghDS** [meituan/YOLOv6#783]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

I would like to resume my training, however, I have more data than the one present in the training set. How can I resume my training again along with the added data ? Should I directly place it in the training folder and the rest will be taken care of ?

**Comment by mtjhl** [comment]
You can do as you said above. Or you may finetune from the model you trained, you can add the model path here.
https://github.com/meituan/YOLOv6/blob/6b9f5f4ea3185496b5f62a934c3c8f2d095c0318/configs/yolov6n_finetune.py#L4

**Comment by VivekSinghDS** [comment]
Thanks, got it
