### ISSUE TITLE
PTQ 报错：letterbox() got an unexpected keyword argument 'return_int'

### ISSUE THREAD

**Issue by tigerzjh** [meituan/YOLOv6#787]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

我看上周更新后，letterbox 参数无法对应
https://github.com/meituan/YOLOv6/blob/6b9f5f4ea3185496b5f62a934c3c8f2d095c0318/deploy/TensorRT/tensorrt_processor.py#L47
https://github.com/meituan/YOLOv6/blob/main/deploy/TensorRT/calibrator.py#L65

### Additional

我看上周更新后，letterbox 参数无法对应
https://github.com/meituan/YOLOv6/blob/6b9f5f4ea3185496b5f62a934c3c8f2d095c0318/deploy/TensorRT/tensorrt_processor.py#L47
https://github.com/meituan/YOLOv6/blob/main/deploy/TensorRT/calibrator.py#L65

**Comment by mtjhl** [comment]
更新后的代码去掉了这个参数。您用新代码运行，是否遇到了问题呢？

**Comment by tigerzjh** [comment]
可以用
