### ISSUE TITLE
TensorRT for YOLOV6 support Python/C++

### ISSUE THREAD

**Issue by Linaom1214** [meituan/YOLOv6#79]
https://github.com/Linaom1214/tensorrt-python

**Comment by zhiqwang** [comment]
We've added a quick C++ inference example https://github.com/zhiqwang/yolov5-rt-stack/pull/432 .

**Comment by Linaom1214** [comment]
> We also add a quick C++ inference example 😄 [zhiqwang/yolov5-rt-stack#432](https://github.com/zhiqwang/yolov5-rt-stack/pull/432) for Windows system.
我只是个代码小白，求大佬放过

**Comment by xinsuinizhuan** [comment]
> We also add a quick C++ inference example 😄 [zhiqwang/yolov5-rt-stack#432](https://github.com/zhiqwang/yolov5-rt-stack/pull/432) for Windows system.

yolov6的模型转tensorrt，可以搞成c++的吗？

**Comment by Linaom1214** [comment]
> > We also add a quick C++ inference example 😄 [zhiqwang/yolov5-rt-stack#432](https://github.com/zhiqwang/yolov5-rt-stack/pull/432) for Windows system.
> 
> yolov6的模型转tensorrt，可以搞成c++的吗？

可以可以  以上是我和走佬的方案 欢迎push
