### ISSUE TITLE
Usage of YOLOv6 self-distillation training. 

### ISSUE THREAD

**Issue by tbensap18** [meituan/YOLOv6#790]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

#

Can anyone please help me better understand how self-distillation works. I tried to train my model using the given tutorial here and tried implementing it in my code but I am using only a single GPU as I am using Colab in training. So I had adjust the parameters given to work on my run. Below is the original code and my adjusted code.

### Self-distillation code
`# Be sure to open use_dfl mode in config file (use_dfl=True, reg_max=16).`

`!python -m torch.distributed.launch --nproc_per_node 8 tools/train.py --batch 256 --conf configs/yolov6s_finetune.py --data data/dataset.yaml --distill --teacher_model_path your_model_path --device 0,1,2,3,4,5,6,7`

### My code
`# Be sure to open use_dfl mode in config file (use_dfl=True, reg_max=16).`

`!python -m tools/train.py --batch 16 --conf configs/yolov6s_finetune.py --data data/dataset.yaml --distill --teacher_model_path your_model_path --device 0`

Only problem is I cannot set it to run. What should I set teacher_model_path your_model_path? I don't quite understand this so if anyone can explain more on this and how can I implement it to work using Colab's free GPU. 

Thanks in advance

**Comment by mtjhl** [comment]
You need to train a model first, then use this model as your teacher model.
You can refer to this https://github.com/meituan/YOLOv6/blob/main/docs/Train_coco_data.md, it shows how to train the teacher model, and how to distill.

If you only use single gpu, you do not need to add `-m`, however, you add `-m ` after python.
