### ISSUE TITLE
why yolov6-3.0 detect  obj_conf by torch.ones?

### ISSUE THREAD

**Issue by Waterman0524** [meituan/YOLOv6#793]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

why yolov6-3.0 detect  obj_conf by torch.ones?

**Comment by Waterman0524** [comment]
> In YOLOv6 v3.0, we remove the object branch on the detection head, therefore we use a constant tensor with a value of 1 as a placeholder.

thank you very much

**Comment by gaigaimm** [comment]
> 在 YOLOv6 v3.0 中，我们删除了检测头上的对象分支，因此我们使用值为 1 的常量张量作为占位符。

请问下怎样训练带有objectness的模型呢，置信度为一在端侧做nms太费时了

**Comment by DrChungAlbert** [comment]
对于NMS而言，其主要任务是消除重叠的边界框，只保留最佳的预测。这通常是基于类别置信度分数进行的，而不直接依赖于对象性分数。因此，即使YOLOv6没有对象性分支，NMS仍然可以有效地根据置信度分数和IoU阈值操作。

**Comment by gaigaimm** [comment]
发送失败，请稍后再发
