### ISSUE TITLE
AssertionError: Results do not correspond to current coco set

### ISSUE THREAD

**Issue by gzh205** [meituan/YOLOv6#796]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

我将COCO格式的数据集转换成YOLO格式后，使用coco.yaml训练。anno.loadRes(pred_json)出现 Results do not correspond to current coco set错误，请问可能是什么原因造成的？数据集里的图片都是001.jpg;002.jpg...

assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())), \
AssertionError: Results do not correspond to current coco set

**Comment by mtjhl** [comment]
请问您的 数据配置文件中是否有 `anno_path` 字段，如果您的数据不是 coco 数据集，这个字段可以删除。我们也会优化一下代码逻辑，避免出现这种的问题。

**Comment by gzh205** [comment]
是的，删除anno_path之后就再也没有问题了。
