### ISSUE TITLE
an option to omit confidence values from the generated .txt file during inference

### ISSUE THREAD

**Issue by tino926** [meituan/YOLOv6#813]
### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar feature requests.

### Description

Add an option to infer.py to omit confidence values from the generated .txt.

### Use case

Thus the output .txt files conform to the standard YOLO annotation format. And can be directly utilized for training other models.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by mtjhl** [comment]
Thank you for your advice. In my opinion, this is customized requirements. If you need to ommit it, you can change the codes by yourself.
