### ISSUE TITLE
加载权重出错

### ISSUE THREAD

**Issue by tgf123** [meituan/YOLOv6#814]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

最新版的/home/nihao/tgf/code/YOLOv6/yolov6/layers/common.py修改之后，预训练权重没有更新吗
AttributeError: Can't get attribute 'SimConv' on <module 'yolov6.layers.common' from '/home/nihao/tgf/code/YOLOv6/yolov6/layers/common.py'>

**Comment by shensheng272** [comment]
你好，你使用的预训练模型是 yolov6s 3.0 还是？ 
使用最新的代码，需要配套最新的pt。

**Comment by tgf123** [comment]
好的，我知道了，十分感谢您的回复，我应该是使用的是3.0的权重，main的代码，我会更新我的代码，但我的权重是yolov6中yolov6/utils/general.py自动下载的

**Comment by Chilicyy** [comment]
你好，最新的代码已修复自动下载的链接，这边可以把原来的模型删除重新运行代码，或者在4.0 release页面下载权重。
