### ISSUE TITLE
请问网络中RepConv实现代码在哪部分？

### ISSUE THREAD

**Issue by chengzihencai** [meituan/YOLOv6#82]

**Comment by khwengXU** [comment]
Thanks for your attentions!
What is RepConv? Is is the basic Repvgg conv?

**Comment by chengzihencai** [comment]
感谢解答，我阅读美团技术团队的文章：[https://tech.meituan.com/2022/06/23/yolov6-a-fast-and-accurate-target-detection-framework-is-opening-source.html](url)，其中在2.1提到了“我们将 Backbone 中 stride=2 的普通 Conv 层替换成了 stride=2 的 RepConv层”，我想请问在项目文件中哪里可以找到RepConv层的实现代码？

**Comment by khwengXU** [comment]
[YOLOv6](https://github.com/meituan/YOLOv6)/[yolov6](https://github.com/meituan/YOLOv6/tree/main/yolov6)/[layers](https://github.com/meituan/YOLOv6/tree/main/yolov6/layers)/common.py
RepConv means the basic single RepVgg, you can find it on the above link.

**Comment by chengzihencai** [comment]
非常感谢
