### ISSUE TITLE
如何进行多Batch部署Tensorrt

### ISSUE THREAD

**Issue by mnwnmn** [meituan/YOLOv6#836]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

我需要使用多Batch的tensorrt功能，但按照教程的方式在转onnx与trt时设置成了batch=4，全程没有报错，但推理结果不正确，请教多Batch时我应该怎么操作。

**Comment by Chilicyy** [comment]
您好，可以提供下转换onnx和trt的命令吗？

**Comment by mnwnmn** [comment]
转onnx使用python eval_yolo_trt.py --weights best_ckpt.pt --img-size 128 1024 --batch-size 4
转trt使用python -m best_ckpt.onnx --dtpye fp16 --img-size 128 1024 --batch-size 4
我也测试了将上边两条命令中的batch-size分别改为1进行了不同的组合，也使用的trtexec这个工具使用了不同组合的测试，但是都没有成功，我使用的是c++的部署代码
