### ISSUE TITLE
V3版本代码何时发布呢？

### ISSUE THREAD

**Issue by sdreamforchen** [meituan/YOLOv6#842]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

您好。请问你们V3版本的代码大概啥时候发布呢？

**Comment by mtjhl** [comment]
您好，现在已经发布到 0.4 版本了。

**Comment by sdreamforchen** [comment]
感谢感谢。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月31日(周三) 下午2:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [meituan/YOLOv6] V3版本代码何时发布呢？ (Issue #842)




 
您好，现在已经发布到 0.4 版本了。
