### ISSUE TITLE
Rectangular training and export

### ISSUE THREAD

**Issue by JasonHMaxwell** [meituan/YOLOv6#843]
### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar feature requests.

### Description

Yolov8 offers optimised training and export for rectangular datasets, such as wide aspect ratio 16:9 datasets. This is very useful for  industrial and edge applications where images will always be in the same orientation and the same or similar wide aspect ratios. In the case of yolov8, rect=true minimises the padding per batch. You can also specify a rectangular image size during export, e.g. 640*384, and the layers of the resulting model are adjusted accordingly (see the attached netron screenshot).
![Screenshot from 2023-05-26 00-28-04](https://github.com/meituan/YOLOv6/assets/91002185/83a94f29-d9b8-4683-bf93-5060fb2282b2)

### Use case

This feature is useful for all applications where the orientation is fixed (as most cameras have a wide aspect ratio).

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mtjhl** [comment]
we already support rectangle and specific shape training, please see https://github.com/meituan/YOLOv6/blob/main/docs/About_training_size.md

**Comment by JasonHMaxwell** [comment]
Thanks @mtjhl the instructions in the link you shared worked :)

**Comment by KaranBhuva22** [comment]
@mtjhl Why is the rectangular training parameter `--rect` missing in version 3? I need it to fine-tune v3 on custom data.
