### ISSUE TITLE
QAT量化流程问题

### ISSUE THREAD

**Issue by BearCooike** [meituan/YOLOv6#848]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

各位前辈你们好，最近再利用Yolov6项目学习模型量化的工程，对QAT的流程有一点疑惑。
使用qat_export.py将QAT训练完的pt权重导出为onnx时，一共会生成三个文件：
一个是带QDQ的onnx文件
一个是去除了QDQ的onnx文件
一个calibrate的cache文件
我看`tools\qat\README.md`里说是使用trtexec 加上去除qdq和onnx和cache文件转换为engine，但`deploy\TensorRT\onnx_to_trt.py`中却说qat不需要传入calibrate相关的内容。
请问一下，到底是`onnx_to_trt.py`这个文件的onnx输入带不带QDQ？去除QDQ的onnx文件可以不带cache直接用trtexec转int8吗？

**Comment by xingyueye** [comment]
@BearCooike onnx_to_trt.py可以理解为trtexec的PythonAPI，本质上是一致的，都可以使用带QDQ的onnx文件，或 不带QDQ的onnx+ cache文件来生成量化模型。这是TensorRT的两种量化模型构建方式，具体可以参考 https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#working-with-int8

**Comment by BearCooike** [comment]
好的，谢谢了
