### ISSUE TITLE
not found: YOLO format widerface labels

### ISSUE THREAD

**Issue by sijun-zhou** [meituan/YOLOv6#849]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

when click the link in the branc of 'yolo6 face', the result is 'not found'.
could you plz help to provide the 'YOLO format widerface labels'.

Thx in anvance!

**Comment by mtjhl** [comment]
Here it is. https://github.com/meituan/YOLOv6/releases/download/0.3.1/widerface_label_yoloformat.tar.gz
I update the download link. Sorry for the inconvenience.

**Comment by sijun-zhou** [comment]
got it. thx!
