### ISSUE TITLE
MAP comparsion of yolov4-scaled model,yolov5,yolov6 models ? & official paper of yolov6?

### ISSUE THREAD

**Issue by akashAD98** [meituan/YOLOv6#85]
1.can you please share whats your map performance on coco 2017? on the image size of 416*416
2.is there any official papaer of yolov6? any blog about the detailed explanation about architecture?
<img width="561" alt="image" src="https://user-images.githubusercontent.com/62583018/175889941-ce15f26e-ce04-4b70-aa23-dc2909717442.png">

**Comment by khwengXU** [comment]
Thanks for your attention!
We plan to publish technical report，including explanation about architecture.

**Comment by Dimfred** [comment]
would be great if you could tag me here once you do :)

**Comment by zidanexu** [comment]
@Dimfred   Thank you for your attention.  Technical report has been published.  You can find the link on our home page.
