### ISSUE TITLE
Dfl loss 0 when finetune YOLOv6n and YOLOv6s

### ISSUE THREAD

**Issue by Leo-Thomas** [meituan/YOLOv6#864]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

I am finetuning YOLOv6n, YOLOv6s, YOLOv6m, and YOLOv6l on a custom dataset. I have followed all relevant tutorials. When I train YOLOv6m and YOLOv6l there is no problem, but when training YOLOv6n and YOLOv6s, on the same dataset, the dfl loss is always 0.

![issueYOLOv6](https://github.com/meituan/YOLOv6/assets/91854676/50b8d756-7102-4f00-aafb-94fdf983ae57)

I tried changing things like batch size and optimizer as suggested in other issues, but it doesn't work.

Thanks in advance for any help.

**Comment by mtjhl** [comment]
It is because N/S model does not use DFL, you can set it to True to use DFL here.
https://github.com/meituan/YOLOv6/blob/4364f29bf3244f2e73d0c42a103cd7a9cbb16ca9/configs/yolov6s.py#L32

**Comment by zl021369** [comment]
> It is because N/S model does not use DFL, you can set it to True to use DFL here.
> 
> https://github.com/meituan/YOLOv6/blob/4364f29bf3244f2e73d0c42a103cd7a9cbb16ca9/configs/yolov6s.py#L32

我将其设为True之后  报错RuntimeError: CUDA error: device-side assert triggered

**Comment by 1348545336** [comment]
> > It is because N/S model does not use DFL, you can set it to True to use DFL here.
> > https://github.com/meituan/YOLOv6/blob/4364f29bf3244f2e73d0c42a103cd7a9cbb16ca9/configs/yolov6s.py#L32
> 
> 我将其设为True之后 报错RuntimeError: CUDA error: device-side assert triggered

把33行的代码改成reg_max=16就好了
