### ISSUE TITLE
bugs in tools/train.py

### ISSUE THREAD

**Issue by a136522541** [meituan/YOLOv6#87]
in tools/train.py line 65
`args.rank, args.local_rank, args.world_size = get_envs()`
the get_envs function in yolov6/utils/envs.py
```
def get_envs():
    """Get PyTorch needed environments from system envirionments."""
    local_rank = int(os.getenv('LOCAL_RANK', -1))
    rank = int(os.getenv('RANK', -1))
    world_size = int(os.getenv('WORLD_SIZE', 1)) 
    return local_rank, rank, world_size
```

the get_envs() function returns local_rank, rank, world_size
this bug will cause error when training with multi machine

**Comment by Mobu59** [comment]
@a136522541 have you fixed the problem?

**Comment by a136522541** [comment]
@Mobu59 
just change the order of the code is OK

`args.local_rank, args.rank, args.world_size = get_envs()`

**Comment by Mobu59** [comment]
> @Mobu59 just change the order of the code is OK
> 
> `args.local_rank, args.rank, args.world_size = get_envs()`

I have modified as you said, but when I run "python -m torch.distributed.launch --nproc_per_node 4 tools/train.py --batch-size 4 --conf configs/yolov6_tiny_head_det.py --data data /head_det.yaml --device 4,5,6,7
", I was caught in "Using 4 GPU for training...
Initializing process group..."

**Comment by a136522541** [comment]
> > @Mobu59 just change the order of the code is OK
> > `args.local_rank, args.rank, args.world_size = get_envs()`
> 
> I have modified as you said, but when I run "python -m torch.distributed.launch --nproc_per_node 4 tools/train.py --batch-size 4 --conf configs/yolov6_tiny_head_det.py --data data /head_det.yaml --device 4,5,6,7 ", I was caught in "Using 4 GPU for training... Initializing process group..."

@Mobu59 can you show the entire error message? I remember I have encounter the same problem, but I'm not sure how to fix until I can read the whole meassage

**Comment by Mobu59** [comment]
When I run python -m torch.distributed.launch --nproc_per_node 4 tools/train.py --batch-size 4 --conf configs/yolov6_tiny_head_det.py --data data/head_det.yaml --device 4,5,6,7
It shows:
/world/data-gpu-94/liyang/anaconda3/envs/yolov6/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
training args are: Namespace(batch_size=4, check_images=False, check_labels=False, conf_file='configs/yolov6_tiny_head_det.py', data_path='data/head_det.yaml', device='4,5,6,7', dist_url='tcp://127.0.0.1:8888', epochs=400, gpu_count=0, img_size=640, local_rank=0, name='exp', noval=False, output_dir='./runs/train', rank=0, workers=8, world_size=4)

Using 4 GPU for training...
Initializing process group...

finally stuck here

**Comment by a136522541** [comment]
> When I run python -m torch.distributed.launch --nproc_per_node 4 tools/train.py --batch-size 4 --conf configs/yolov6_tiny_head_det.py --data data/head_det.yaml --device 4,5,6,7 It shows: /world/data-gpu-94/liyang/anaconda3/envs/yolov6/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated and will be removed in future. Use torchrun. Note that --use_env is set by default in torchrun. If your script expects `--local_rank` argument to be set, please change it to read from `os.environ['LOCAL_RANK']` instead. See https://pytorch.org/docs/stable/distributed.html#launch-utility for further instructions
> 
> warnings.warn( WARNING:torch.distributed.run:
> 
> Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
> 
> training args are: Namespace(batch_size=4, check_images=False, check_labels=False, conf_file='configs/yolov6_tiny_head_det.py', data_path='data/head_det.yaml', device='4,5,6,7', dist_url='tcp://127.0.0.1:8888', epochs=400, gpu_count=0, img_size=640, local_rank=0, name='exp', noval=False, output_dir='./runs/train', rank=0, workers=8, world_size=4)
> 
> Using 4 GPU for training... Initializing process group...
> 
> finally stuck here

@Mobu59 what is your pytorch version? the version should be >1.8.1

**Comment by Mobu59** [comment]
@a136522541 torch1.11.0+cu10.2

**Comment by a136522541** [comment]
> @a136522541 torch1.11.0+cu10.2

@Mobu59 Mine is '1.8.1+cu102', maybe you can try this version and see if it works
