### ISSUE TITLE
EIOU和SIOU

### ISSUE THREAD

**Issue by sdreamforchen** [meituan/YOLOv6#89]
您好，根据你们的测试试验，你们是不是测试过EIOU和SIOU呢？  这俩谁效果好些呢？

**Comment by Chilicyy** [comment]
Thanks for your attention!
We did some experiments with different IOU loss like CIOU, EIOU and SIOU on YOLOv6s model, and the results showed that SIOU loss(43.1% mAP) > EIOU loss (42.9% mAP) > CIOU loss (42.8% mAP).

**Comment by sdreamforchen** [comment]
Thanks very much



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月27日(周一) 晚上7:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [meituan/YOLOv6] EIOU和SIOU (Issue #89)




 
Thanks for your attention!
 We did some experiments with different IOU loss like CIOU, EIOU and SIOU on YOLOv6s model, and the results showed that SIOU loss(43.1% mAP) &gt; EIOU loss (42.9% mAP) &gt; CIOU loss (42.8% mAP).
