### ISSUE TITLE
Tensorboard only showing the first 22 epochs

### ISSUE THREAD

**Issue by jethrolow** [meituan/YOLOv6#893]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

I recently trained a yolov6lite-m model. When viewing the tensorboard visualisation of the training run, I realised that only the first 22 epochs are showing. This is despite training for 400 epochs. Please see the image below. I also received the message in the terminal "TensorFlow installation not found - running with reduced feature set.".

I can't figure out why this is happening. Any help would be appreciated!!

![Screenshot from 2023-08-21 02-17-55](https://github.com/meituan/YOLOv6/assets/85182365/c59b6faa-3f42-4311-ad67-8a57de789717)

**Comment by Hamburgerrrr** [comment]
我也是，训练了100轮，但是只有9轮的结果
![image](https://github.com/meituan/YOLOv6/assets/77449129/0b5696e9-1b0a-418e-8a33-24acf441b542)
