### ISSUE TITLE
about the training loss

### ISSUE THREAD

**Issue by quynhanh12345** [meituan/YOLOv6#91]
I'm wondering why the training loss is equal to 0 all the time and mAP also has the same result. Please help!

![Screenshot from 2022-06-27 18-06-42](https://user-images.githubusercontent.com/64362302/175927805-ae735b89-7624-4ee4-a58d-c90792e42c3a.png)

**Comment by Chilicyy** [comment]
Hi, please git pull the latest scripts and check if your dataset 's format is converted correctly, otherwise you'll get abnormal loss and mAP results.

**Comment by Prabhakaran-Gokul** [comment]
Hi, I have the latest scripts but iou_loss, l1_loss and cls_loss is still 0, except obj_loss.

I checked the instances_val.json file that was created under the annotations folder and found that the "annotations" key is an empty list.
