### ISSUE TITLE
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution

### ISSUE THREAD

**Issue by Egorundel** [meituan/YOLOv6#918]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

Hello!

When I run the this command:
`python3 tools/train.py --workers 8 --epochs 400 --batch 64 --conf-file configs/yolov6l_finetune.py --data-path data/dataset.yaml --name yolov6-custom --output-dir /mnt/data/VideoAi/Vinogradov/best_runs_yolov6/train --fuse_ab`

I have the following problem:
`RuntimeError: Unable to find a valid cuDNN algorithm to run convolution`

Screenshot with error:
![Screenshot from 2023-10-03 16-45-24](https://github.com/meituan/YOLOv6/assets/65890558/847e3ca4-745c-4a1a-9f7e-2b15abb13583)

My **dataset.yaml**:
![Screenshot from 2023-10-03 16-53-06](https://github.com/meituan/YOLOv6/assets/65890558/1ef7da63-fdab-4d8e-94be-5c9763403bca)

What could be the problem?

**Env:**

torch: 1.9.0+cu111
torchvision: 0.10.0+cu111
CUDA: 11.1
Ubuntu: 20.04

**Comment by mtjhl** [comment]
Reduce the batch size can solve this problem.
