### ISSUE TITLE
Module Not Found

### ISSUE THREAD

**Issue by vodub** [meituan/YOLOv6#919]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

i got some ModuleNotFoundError: No module named 'yolov6'. 
when i check my pip & conda installation there is yolov6 0.0.1 on conda list, but there's nothing in pip list
can anyone help me?

### Additional

conda list
![image](https://github.com/meituan/YOLOv6/assets/145485549/4af77507-1f6b-4963-bcb9-e6f6d1ac9060)

pip list
![image](https://github.com/meituan/YOLOv6/assets/145485549/067f8a15-c362-485f-a062-9c7bad616bb5)

**Comment by mtjhl** [comment]
You can run this project  in the yolov6 directory.

**Comment by vodub** [comment]
> You can run this project in the yolov6 directory.

still ModuleNotFoundError: No module named 'yolov6'

**Comment by vodub** [comment]
> You can run this project in the yolov6 directory.

did you mean YOLOv6 directory ?
cause in YOLOv6 directory there's yolov6 directory

**Comment by Chilicyy** [comment]
Hi @vodub , the latest YOLOv6 project is not currently available in  pip tools, and git clone the latest project if you want to test on it.

**Comment by mtjhl** [comment]
You need to run this project in the root directory of YOLOv6 project.

**Comment by vodub** [comment]
> You need to run this project in the root directory of YOLOv6 project.
> Hi @vodub , the latest YOLOv6 project is not currently available in pip tools, and git clone the latest project if you want to test on it.

okay thank you
