### ISSUE TITLE
Information about the loss formula

### ISSUE THREAD

**Issue by ckyrkou** [meituan/YOLOv6#92]
Where can we find more information about the loss formula and the different weight coefficients?

Can you provide a detailed equation?

**Comment by Anupam-USP** [comment]
I think  [SIoU](https://arxiv.org/ftp/arxiv/papers/2205/2205.12740.pdf) loss is used as said [here](https://chowdera.com/2022/175/202206241256266607.html#:~:text=improved%201.3%25%20AP.-,SIoU%20Bounding%20box%20regression%20loss,-In%20order%20to)
