### ISSUE TITLE
Automatic Stop When Evaluating on Google Colab

### ISSUE THREAD

**Issue by vodub** [meituan/YOLOv6#923]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

In my case, i'll try train with 5 epoch and eval-interval 1. But When already train first epoch, eval automatic stopped with google colab. In this case, I use Colab Pro with GPU T4 high-ram, and also try with A100 & V100.

![image](https://github.com/meituan/YOLOv6/assets/145485549/b7f73f08-e85e-4f80-a509-53b0b45759d6)

**Comment by Chilicyy** [comment]
Hi @vodub , do you mean your training tasks were all corrupted  on  Colab Pro with T4, A100 or V100?

**Comment by vodub** [comment]
> Hi @vodub , do you mean your training tasks were all corrupted on Colab Pro with T4, A100 or V100? Could you show more details about the training command?

Hi sir, my code 

%cd /content/YOLOv6
!python tools/train.py --batch 32 --conf /content/YOLOv6/configs/yolov6n_finetune.py --data /content/datasets-vod/data.yaml --device 0 --epochs 5 --eval-interval 1

and the result from training

Training start...

     Epoch        lr  iou_loss  dfl_loss  cls_loss
       0/4     0.0032    0.4161         0     2.251: 100% 7379/7379 [1:16:48<00:00,  1.60it/s]
Inferencing model in train datasets.: 100% 732/732 [41:09<00:00,  3.37s/it]

Evaluating speed.

Evaluating mAP by pycocotools.
Saving runs/train/exp1/predictions.json...
loading annotations into memory...
Done (t=0.34s)
creating index...
index created!
Loading and preparing results...
DONE (t=88.51s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
^C

training is work normally, but when evaluating i dont know why the cell is interrupted automaticly. Is it bug from google colab?

**Comment by vodub** [comment]
> Hi @vodub , do you mean your training tasks were all corrupted on Colab Pro with T4, A100 or V100? Could you show more details about the training command?

Hi sir, my code 

%cd /content/YOLOv6
!python tools/train.py --batch 32 --conf /content/YOLOv6/configs/yolov6n_finetune.py --data /content/datasets-vod/data.yaml --device 0 --epochs 5 --eval-interval 1

and the result from training

Training start...

     Epoch        lr  iou_loss  dfl_loss  cls_loss
       0/4     0.0032    0.4161         0     2.251: 100% 7379/7379 [1:16:48<00:00,  1.60it/s]
Inferencing model in train datasets.: 100% 732/732 [41:09<00:00,  3.37s/it]

Evaluating speed.

Evaluating mAP by pycocotools.
Saving runs/train/exp1/predictions.json...
loading annotations into memory...
Done (t=0.34s)
creating index...
index created!
Loading and preparing results...
DONE (t=88.51s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
^C

training is work normally, but when evaluating i dont know why the cell is interrupted automaticly. Is it bug from google colab?

**Comment by Chilicyy** [comment]
Hi @vodub , you can set `--eval-final-only` , which means only evaluate at the final epoch, to accomplish the training process.  Besides, you can separately do evaluation to check if there's someting wrong with your validationset.

**Comment by vodub** [comment]
> Hi @vodub , you can set `--eval-final-only` , which means only evaluate at the final epoch, to accomplish the training process. Besides, you can separately do evaluation to check if there's someting wrong with your validationset.

okay, thanky you
