### ISSUE TITLE
AttributeError: 'Model' object has no attribute 'nc'

### ISSUE THREAD

**Issue by k-apos** [meituan/YOLOv6#939]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [ ] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

When I use -- verbose in eval.py to take mAP I got the following error:

Traceback (most recent call last):
  File "/content/YOLOv6/tools/eval.py", line 169, in <module>
    main(args)
  File "/content/YOLOv6/tools/eval.py", line 164, in main
    run(**vars(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/YOLOv6/tools/eval.py", line 159, in run
    eval_result = val.eval_model(pred_result, model, dataloader, task)
  File "/content/YOLOv6/yolov6/core/evaler.py", line 276, in eval_model
    label_count_dicts = [copy.deepcopy(label_count_dict) for _ in range(model.nc)]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Model' object has no attribute 'nc'

**Comment by abdull6771** [comment]
check your yaml file

**Comment by k-apos** [comment]
The yaml file is correct because when I remove '--verbose' the code runs properly

**Comment by michelle123-creator** [comment]
Did you successfully fix the error?

**Comment by michelle123-creator** [comment]
Change the model.nc to 80 in evaler.py. This help for me

**Comment by KnitVikas** [comment]
remove nc and provide number of classes you are using manually .  this works for me.
