### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'python_exit_status'

### ISSUE THREAD

**Issue by ZKH66** [meituan/YOLOv6#94]

**Comment by mingwz** [comment]
may be #76

**Comment by tanbin5070** [comment]
Hello, I have the same problem as you. Have you solved it
![image](https://user-images.githubusercontent.com/34202292/176104613-99c166d3-80d4-4d6f-b7f7-eba08fe4e53d.png)

**Comment by ZKH66** [comment]
应该是数据集格式问题

**Comment by stitchshaw** [comment]
same problem here......

**Comment by mtjhl** [comment]
Is this bug occured when the tranining process is finishing? @ZKH66

**Comment by stitchshaw** [comment]
> 

yes, just ignore it.
