### ISSUE TITLE
训练过程map一直为0

### ISSUE THREAD

**Issue by nobody-cheng** [meituan/YOLOv6#941]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

刚拉的分支, 验证的精度一直都为0，步骤如下，是我哪里设置错了吗
训练的参数都是默认，跑的 yolov6n.py
```
# 使用下面的脚本验证了数据标签的准确性
python yolov6/data/vis_dataset.py --img_dir dataset/CrowdHumanVisible_NoMask/images/val2017/ --label_dir dataset/CrowdHumanVisible_NoMask/labels/val2017/
python yolov6/data/vis_dataset.py --img_dir dataset/CrowdHumanVisible_NoMask/images/train2017/ --label_dir dataset/CrowdHumanVisible_NoMask/labels/train2017/
```
训练命令
```
python -m torch.distributed.launch --nproc_per_node 4 tools/train.py --batch 128 --conf configs/yolov6n.py --data data/head_person.yaml --epoch 300  --device 0,1,2,3 --name head_person/yolov6n  --fuse_ab --write_trainbatch_tb --cache-ram
```
tensorboard情况
![image](https://github.com/meituan/YOLOv6/assets/34908468/4cfbe2aa-5fe2-4088-9d1e-7c9df8c8d630)
下图的map一直为0
![image](https://github.com/meituan/YOLOv6/assets/34908468/49b1ec5f-f774-43c8-bb74-f8bb911e31be)
![image](https://github.com/meituan/YOLOv6/assets/34908468/90879a04-8bd0-45c0-a2b9-722bf6afdf81)

**Comment by nobody-cheng** [comment]
```
--check-images --check-labels
```

**Comment by SangbumChoi** [comment]
@nobody-cheng I think that is not appropriate answer

**Comment by nobody-cheng** [comment]
> @nobody-cheng I think that is not appropriate answer
```
# --cache-ram False
python -m torch.distributed.launch --nproc_per_node 4 tools/train.py --batch 128 --conf configs/yolov6n.py --data data/head_person.yaml --epoch 400  --device 0,1,2,3 --name head_person/yolov6n  --fuse_ab --write_trainbatch_tb --check-images --check-labels
```
![bug1](https://github.com/meituan/YOLOv6/assets/34908468/5ff3b962-682d-4bcd-9578-6616c8cc4f94)
```
# --cache-ram True
python -m torch.distributed.launch --nproc_per_node 4 tools/train.py --batch 128 --conf configs/yolov6n.py --data data/head_person.yaml --epoch 400  --device 0,1,2,3 --name head_person/yolov6n_cache  --fuse_ab --write_trainbatch_tb --check-images --check-labels --cache-ram
```
![bug2](https://github.com/meituan/YOLOv6/assets/34908468/d9bb29db-a829-4f02-80cf-e7bbd7846a93)

![image](https://github.com/meituan/YOLOv6/assets/34908468/fa8c8111-fbf3-461e-91b2-7c80586b07de)

@SangbumChoi

**Comment by SangbumChoi** [comment]
@nobody-cheng Yeah, I think you will get reasonable result without having check-label argument. I think main problem is whether you turn on --cache-ram.
```
# --cache-ram False
python -m torch.distributed.launch --nproc_per_node 4 tools/train.py --batch 128 --conf configs/yolov6n.py --data data/head_person.yaml --epoch 400  --device 0,1,2,3 --name head_person/yolov6n  --fuse_ab --write_trainbatch_tb
```
