### ISSUE TITLE
cache-ram

### ISSUE THREAD

**Issue by SangbumChoi** [meituan/YOLOv6#942]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

It seems that current commit https://github.com/meituan/YOLOv6/commit/d512ce7c4f103e8887960198505518bed404abdc
have some huge difference of performance (using --cache-ram returns almost 0 AP while not using --cache-ram returns safely such as 20AP) while enabling --cache-ram. Did your team confirmed about this issue?

**Comment by SangbumChoi** [comment]
fyi (this is the log for no -- cache-ram)
```
Evaluating mAP by pycocotools.
Saving ./output/predictions.json...
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.45s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=3.41s).
Accumulating evaluation results...
DONE (t=1.14s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.158
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.214
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.179
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.057
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.252
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.274
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.216
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.355
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.371
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.132
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.479
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.499
Results saved to ./output/
Epoch: 29 | mAP@0.5: 0.21412485355460034 | mAP@0.50:0.95: 0.15842523373182324
```

**Comment by SangbumChoi** [comment]
https://github.com/meituan/YOLOv6/issues/941

**Comment by SangbumChoi** [comment]
it seems like something related to validation dataset should not be cached?

**Comment by mtjhl** [comment]
We will check the bug as soon as possible.

**Comment by SangbumChoi** [comment]
@mtjhl https://github.com/meituan/YOLOv6/pull/948 you can start debugging from here
