### ISSUE TITLE
导出torchscript的问题，使用NCNN下的export_torchscript.py

### ISSUE THREAD

**Issue by TD-wzw** [meituan/YOLOv6#944]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

请问一下，按照官当的文档指引，使用yolov6lite_s.pt导出后的torchscript模型是各个下采样倍数分开输出的，为什么使用yolov6n.pt导出后就会把各个倍数的concat在一起输出？？？这里怎么控制一下

**Comment by TD-wzw** [comment]
再补充一下，使用yolov6lite_s.pt的时候可以走到effidehead_lite.py里边的DETECT类，但使用yolov6n.pt的时候就走不进去，这到底是由啥控制的？

**Comment by TD-wzw** [comment]
已解决

**Comment by huarouwu** [comment]
请问 具体是什么问题呢  我将yolov6lite_s.pt转为onnx失败了，报错AttributeError: 'ConvModule' object has no attribute 'act'，请问您是怎麽解决的呢
