### ISSUE TITLE
Mutli GPU; RANK vs LOCAL_RANK

### ISSUE THREAD

**Issue by josht000** [meituan/YOLOv6#945]
First of all, thanks for making this great library online and open source. Much appreciated. 

Using an Ubuntu 22.04 LTS system with PyTorch 2.0.1 and Python 3.9.4. I'm trying to run your example command for multi-gpu training but with a custom dataset in yolo format and getting a strange error. 

I have 16 GPUs in a single node system. Single GPU training works fine but is so slow with large images, plus so much hardware left under utilized.

Command:
`python -m torch.distributed.launch --nproc_per_node 8 tools/train.py --batch 128 --conf configs/yolov6s6_finetune.py --data data/dataset.yaml --img 1280 --device 0,1,2,3,4,5,6,7`

dataset file:

```yaml
train: /blah/images/train
val: /blah/images/val

is_coco: False

nc: 3
names: ['a', 'b', 'c']
```

Questions:
1. Is the command that you provided and I showed above actually attemptiing to use DDP?
2. What is the relationship of rank and local_rank env variables?  
3. Can you give an example of how to use the above env vars correctly for my system? 

Thanks!

### Additional

**the error message:**

❯ python -m torch.distributed.launch --nproc_per_node 8 tools/train.py --batch 128 --conf configs/yolov6s6_finetune.py --data data/dataset.yaml --img 1280 --device 0,1,2,3,4,5,6,7
 FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

warnings.warn(
WARNING:torch.distributed.run:
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
usage: train.py [-h] [--data-path DATA_PATH] [--conf-file CONF_FILE] [--img-size IMG_SIZE] [--rect] [--batch-size BATCH_SIZE] [--epochs EPOCHS] [--workers WORKERS] [--device DEVICE] [--eval-interval EVAL_INTERVAL]
                [--eval-final-only] [--heavy-eval-range HEAVY_EVAL_RANGE] [--check-images] [--check-labels] [--output-dir OUTPUT_DIR] [--name NAME] [--dist_url DIST_URL] [--gpu_count GPU_COUNT]
                [--local_rank LOCAL_RANK] [--resume [RESUME]] [--write_trainbatch_tb] [--stop_aug_last_n_epoch STOP_AUG_LAST_N_EPOCH] [--save_ckpt_on_last_n_epoch SAVE_CKPT_ON_LAST_N_EPOCH] [--distill]
                [--distill_feat] [--quant] [--calib] [--teacher_model_path TEACHER_MODEL_PATH] [--temperature TEMPERATURE] [--fuse_ab] [--bs_per_gpu BS_PER_GPU] [--specific-shape] [--height HEIGHT] [--width WIDTH]
                [--cache-ram]
train.py: error: unrecognized arguments: --local-rank=4
usage: train.py [-h] [--data-path DATA_PATH] [--conf-file CONF_FILE] [--img-size IMG_SIZE] [--rect] [--batch-size BATCH_SIZE] [--epochs EPOCHS] [--workers WORKERS] [--device DEVICE] [--eval-interval EVAL_INTERVAL]
                [--eval-final-only] [--heavy-eval-range HEAVY_EVAL_RANGE] [--check-images] [--check-labels] [--output-dir OUTPUT_DIR] [--name NAME] [--dist_url DIST_URL] [--gpu_count GPU_COUNT]
                [--local_rank LOCAL_RANK] [--resume [RESUME]] [--write_trainbatch_tb] [--stop_aug_last_n_epoch STOP_AUG_LAST_N_EPOCH] [--save_ckpt_on_last_n_epoch SAVE_CKPT_ON_LAST_N_EPOCH] [--distill]
                [--distill_feat] [--quant] [--calib] [--teacher_model_path TEACHER_MODEL_PATH] [--temperature TEMPERATURE] [--fuse_ab] [--bs_per_gpu BS_PER_GPU] [--specific-shape] [--height HEIGHT] [--width WIDTH]
                [--cache-ram]
train.py: error: unrecognized arguments: --local-rank=0
usage: train.py [-h] [--data-path DATA_PATH] [--conf-file CONF_FILE] [--img-size IMG_SIZE] [--rect] [--batch-size BATCH_SIZE] [--epochs EPOCHS] [--workers WORKERS] [--device DEVICE] [--eval-interval EVAL_INTERVAL]
                [--eval-final-only] [--heavy-eval-range HEAVY_EVAL_RANGE] [--check-images] [--check-labels] [--output-dir OUTPUT_DIR] [--name NAME] [--dist_url DIST_URL] [--gpu_count GPU_COUNT]
                [--local_rank LOCAL_RANK] [--resume [RESUME]] [--write_trainbatch_tb] [--stop_aug_last_n_epoch STOP_AUG_LAST_N_EPOCH] [--save_ckpt_on_last_n_epoch SAVE_CKPT_ON_LAST_N_EPOCH] [--distill]
                [--distill_feat] [--quant] [--calib] [--teacher_model_path TEACHER_MODEL_PATH] [--temperature TEMPERATURE] [--fuse_ab] [--bs_per_gpu BS_PER_GPU] [--specific-shape] [--height HEIGHT] [--width WIDTH]
                [--cache-ram]
train.py: error: unrecognized arguments: --local-rank=3
usage: train.py [-h] [--data-path DATA_PATH] [--conf-file CONF_FILE] [--img-size IMG_SIZE] [--rect] [--batch-size BATCH_SIZE] [--epochs EPOCHS] [--workers WORKERS] [--device DEVICE] [--eval-interval EVAL_INTERVAL]
                [--eval-final-only] [--heavy-eval-range HEAVY_EVAL_RANGE] [--check-images] [--check-labels] [--output-dir OUTPUT_DIR] [--name NAME] [--dist_url DIST_URL] [--gpu_count GPU_COUNT]
                [--local_rank LOCAL_RANK] [--resume [RESUME]] [--write_trainbatch_tb] [--stop_aug_last_n_epoch STOP_AUG_LAST_N_EPOCH] [--save_ckpt_on_last_n_epoch SAVE_CKPT_ON_LAST_N_EPOCH] [--distill]
                [--distill_feat] [--quant] [--calib] [--teacher_model_path TEACHER_MODEL_PATH] [--temperature TEMPERATURE] [--fuse_ab] [--bs_per_gpu BS_PER_GPU] [--specific-shape] [--height HEIGHT] [--width WIDTH]
                [--cache-ram]
usage: train.py [-h] [--data-path DATA_PATH] [--conf-file CONF_FILE] [--img-size IMG_SIZE] [--rect] [--batch-size BATCH_SIZE] [--epochs EPOCHS] [--workers WORKERS] [--device DEVICE] [--eval-interval EVAL_INTERVAL]
                [--eval-final-only] [--heavy-eval-range HEAVY_EVAL_RANGE] [--check-images] [--check-labels] [--output-dir OUTPUT_DIR] [--name NAME] [--dist_url DIST_URL] [--gpu_count GPU_COUNT]
                [--local_rank LOCAL_RANK] [--resume [RESUME]] [--write_trainbatch_tb] [--stop_aug_last_n_epoch STOP_AUG_LAST_N_EPOCH] [--save_ckpt_on_last_n_epoch SAVE_CKPT_ON_LAST_N_EPOCH] [--distill]
                [--distill_feat] [--quant] [--calib] [--teacher_model_path TEACHER_MODEL_PATH] [--temperature TEMPERATURE] [--fuse_ab] [--bs_per_gpu BS_PER_GPU] [--specific-shape] [--height HEIGHT] [--width WIDTH]
                [--cache-ram]
train.py: error: unrecognized arguments: --local-rank=1
train.py: error: unrecognized arguments: --local-rank=2
usage: train.py [-h] [--data-path DATA_PATH] [--conf-file CONF_FILE] [--img-size IMG_SIZE] [--rect] [--batch-size BATCH_SIZE] [--epochs EPOCHS] [--workers WORKERS] [--device DEVICE] [--eval-interval EVAL_INTERVAL]
                [--eval-final-only] [--heavy-eval-range HEAVY_EVAL_RANGE] [--check-images] [--check-labels] [--output-dir OUTPUT_DIR] [--name NAME] [--dist_url DIST_URL] [--gpu_count GPU_COUNT]
                [--local_rank LOCAL_RANK] [--resume [RESUME]] [--write_trainbatch_tb] [--stop_aug_last_n_epoch STOP_AUG_LAST_N_EPOCH] [--save_ckpt_on_last_n_epoch SAVE_CKPT_ON_LAST_N_EPOCH] [--distill]
                [--distill_feat] [--quant] [--calib] [--teacher_model_path TEACHER_MODEL_PATH] [--temperature TEMPERATURE] [--fuse_ab] [--bs_per_gpu BS_PER_GPU] [--specific-shape] [--height HEIGHT] [--width WIDTH]
                [--cache-ram]
usage: train.py [-h] [--data-path DATA_PATH] [--conf-file CONF_FILE] [--img-size IMG_SIZE] [--rect] [--batch-size BATCH_SIZE] [--epochs EPOCHS] [--workers WORKERS] [--device DEVICE] [--eval-interval EVAL_INTERVAL]
                [--eval-final-only] [--heavy-eval-range HEAVY_EVAL_RANGE] [--check-images] [--check-labels] [--output-dir OUTPUT_DIR] [--name NAME] [--dist_url DIST_URL] [--gpu_count GPU_COUNT]
                [--local_rank LOCAL_RANK] [--resume [RESUME]] [--write_trainbatch_tb] [--stop_aug_last_n_epoch STOP_AUG_LAST_N_EPOCH] [--save_ckpt_on_last_n_epoch SAVE_CKPT_ON_LAST_N_EPOCH] [--distill]
                [--distill_feat] [--quant] [--calib] [--teacher_model_path TEACHER_MODEL_PATH] [--temperature TEMPERATURE] [--fuse_ab] [--bs_per_gpu BS_PER_GPU] [--specific-shape] [--height HEIGHT] [--width WIDTH]
                [--cache-ram]
usage: train.py [-h] [--data-path DATA_PATH] [--conf-file CONF_FILE] [--img-size IMG_SIZE] [--rect] [--batch-size BATCH_SIZE] [--epochs EPOCHS] [--workers WORKERS] [--device DEVICE] [--eval-interval EVAL_INTERVAL]
                [--eval-final-only] [--heavy-eval-range HEAVY_EVAL_RANGE] [--check-images] [--check-labels] [--output-dir OUTPUT_DIR] [--name NAME] [--dist_url DIST_URL] [--gpu_count GPU_COUNT]
                [--local_rank LOCAL_RANK] [--resume [RESUME]] [--write_trainbatch_tb] [--stop_aug_last_n_epoch STOP_AUG_LAST_N_EPOCH] [--save_ckpt_on_last_n_epoch SAVE_CKPT_ON_LAST_N_EPOCH] [--distill]
                [--distill_feat] [--quant] [--calib] [--teacher_model_path TEACHER_MODEL_PATH] [--temperature TEMPERATURE] [--fuse_ab] [--bs_per_gpu BS_PER_GPU] [--specific-shape] [--height HEIGHT] [--width WIDTH]
                [--cache-ram]
train.py: error: unrecognized arguments: --local-rank=7
train.py: error: unrecognized arguments: --local-rank=5
train.py: error: unrecognized arguments: --local-rank=6
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 837219) of binary: /home/name/anaconda3/envs/training/bin/python
Traceback (most recent call last):
  File "/home/name/anaconda3/envs/training/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/name/anaconda3/envs/training/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/name/anaconda3/envs/training/lib/python3.9/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/name/anaconda3/envs/training/lib/python3.9/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/name/anaconda3/envs/training/lib/python3.9/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/name/anaconda3/envs/training/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/name/anaconda3/envs/training/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/name/anaconda3/envs/training/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

tools/train.py FAILED

Failures:
[1]:
  time      : 2023-11-06_16:46:17
  host      : orl3dgxlab.us.lmco.com
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 837221)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-11-06_16:46:17
  host      : orl3dgxlab.us.lmco.com
  rank      : 2 (local_rank: 2)
  exitcode  : 2 (pid: 837222)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-11-06_16:46:17
  host      : orl3dgxlab.us.lmco.com
  rank      : 3 (local_rank: 3)
  exitcode  : 2 (pid: 837223)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2023-11-06_16:46:17
  host      : orl3dgxlab.us.lmco.com
  rank      : 4 (local_rank: 4)
  exitcode  : 2 (pid: 837224)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2023-11-06_16:46:17
  host      : orl3dgxlab.us.lmco.com
  rank      : 5 (local_rank: 5)
  exitcode  : 2 (pid: 837225)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2023-11-06_16:46:17
  host      : orl3dgxlab.us.lmco.com
  rank      : 6 (local_rank: 6)
  exitcode  : 2 (pid: 837226)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2023-11-06_16:46:17
  host      : orl3dgxlab.us.lmco.com
  rank      : 7 (local_rank: 7)
  exitcode  : 2 (pid: 837227)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

Root Cause (first observed failure):
[0]:
  time      : 2023-11-06_16:46:17
  host      : orl3dgxlab.us.lmco.com
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 837219)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by josht000** [comment]
I googled for the first bug and was eventually able to get it to work simply by adding --local-rank into the input args in train.py. Also, pytorch 1.8 was not working for me.

**Comment by senhorinfinito** [comment]
`pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117`


This will resolve the issue/

**Comment by hamedgorji** [comment]
> `pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117`
> 
> This will resolve the issue/

It resolved my issue too. 
Thanks
