### ISSUE TITLE
Where is the paper?

### ISSUE THREAD

**Issue by mjack3** [meituan/YOLOv6#95]
Thanks

**Comment by khwengXU** [comment]
Thanks for your attentions!
We plans to publish the technical report.

**Comment by innat** [comment]
Is it paper or technical report?
https://min.news/en/news/cddfdf9fe2d2b91815470aa47655b3a9.html

**Comment by mjack3** [comment]
Is not a paper

**Comment by innat** [comment]
technical report?

IMHO, there should be a paper first; and same tone goes to yolo-v5.
