### ISSUE TITLE
The model fine-tuning problem based on the 4090 GPU.

### ISSUE THREAD

**Issue by Zong-my** [meituan/YOLOv6#952]
**My training set consists of 700,000 images with a resolution of 640. I have two 4090 GPUs. What is the minimum GPU memory required for fine-tuning the YOLOv6l6 model, and can I use the two 4090 GPUs for this task?**

**The configuration file for VS Code is as follows:**
{
// Use IntelliSense to learn about possible attributes.
// Hover to view descriptions of existing attributes.
// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
"version": "0.2.0",
"configurations": [
{
// "name": "Python: train_aux",
"name": "Python: train",
"type": "python",
"request": "launch",
"program": "/opt/conda/envs/py39_torch1101_cuda111/lib/python3.9/site-packages/torch/distributed/launch.py",
"console": "integratedTerminal",
"justMyCode": true,
"args": [
"--nproc_per_node=2",
"--master_port", "1064",
"train.py",
"--conf", "configs/yolov6l_finetune.py",
"--data", "data/dataset.yaml",
"--epochs", "32",
"--batch", "2",
"--bs_per_gpu", "1",
"--img", "640",
"--device", "1,2",
"--workers", "0",
],
"env": {"CUDA_VISIBLE_DEVICES":"1,2"},
    }
]
}

**Problems are as follows:**
Exception has occurred: RuntimeError
CUDA error: device-side assert triggered
File "/home/user/Documents/YOLOv6-main/yolov6/models/losses/loss.py", line 103, in call
mask_gt)
File "/home/user/Documents/YOLOv6-main/yolov6/assigners/tal_assigner.py", line 67, in forward
pd_scores_, pd_bboxes_, gt_labels_, gt_bboxes_, anc_points, mask_gt_)
File "/home/user/Documents/YOLOv6-main/yolov6/assigners/tal_assigner.py", line 106, in get_pos_mask
align_metric, overlaps = self.get_box_metrics(pd_scores, pd_bboxes, gt_labels, gt_bboxes)
File "/home/user/Documents/YOLOv6-main/yolov6/assigners/tal_assigner.py", line 128, in get_box_metrics
bbox_scores = pd_scores[ind[0], ind[1]]

**The error log is as follows:**
& index < sizes[i] && "index out of bounds"failed. /pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:97: operator(): block: [209,0,0], thread: [95,0,0] Assertionindex >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
OOM RuntimeError is raised due to the huge memory cost during label assignment. CPU mode is applied in this batch. If you want to avoid this issue, try to reduce the batch size or image size.
------------CPU Mode for This Batch-------------
OOM RuntimeError is raised due to the huge memory cost during label assignment. CPU mode is applied in this batch. If you want to avoid this issue, try to reduce the batch size or image size.
------------CPU Mode for This Batch-------------
0%| | 0/382769 [00:04<?, ?it/s]
ERROR in training steps.
ERROR in training loop or eval/save model.
ERROR in training steps.
ERROR in training loop or eval/save model.

**I've set the batch size for a single GPU to 1 and the image resolution to 640, yet it's somewhat surprising that there's still an issue with insufficient memory.**

**Comment by Zong-my** [comment]
**The error log is as follows:**
& index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:97: operator(): block: [209,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
OOM RuntimeError is raised due to the huge memory cost during label assignment.                     CPU mode is applied in this batch. If you want to avoid this issue,                     try to reduce the batch size or image size.
------------CPU Mode for This Batch-------------
OOM RuntimeError is raised due to the huge memory cost during label assignment.                     CPU mode is applied in this batch. If you want to avoid this issue,                     try to reduce the batch size or image size.
------------CPU Mode for This Batch-------------
  0%|          | 0/382769 [00:04<?, ?it/s]                                                          
ERROR in training steps.
ERROR in training loop or eval/save model.
ERROR in training steps.
ERROR in training loop or eval/save model.

**Comment by Zong-my** [comment]
**I've set the batch size for a single GPU to 1 and the image resolution to 640, yet it's somewhat surprising that there's still an issue with insufficient memory.**

**Comment by Zong-my** [comment]
Done

**Comment by MiksVasiljevs** [comment]
For anyone experiencing this problem, you can get a similar error if the number of classes specified in dataset config file is less than the number of classes that actually appear in annotations.

Updating the config file solved the problem for me.
