### ISSUE TITLE
关于多模型蒸馏

### ISSUE THREAD

**Issue by tonyostum2022** [meituan/YOLOv6#955]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

你好，我正在尝试使用yolov6进行多模型蒸馏的研究，当我额外加载一个模型时，即使没有修改其他的代码，模型的训练结果也发生了改变，请问这是什么原因呢？

具体操作：在yolov6/core/engine.py第58行

model = self.get_model(args, cfg, self.num_classes, device)

之后加入一行

model_test = self.get_model(args, cfg, self.num_classes, device)

按理说只是额外创建了一个新的模型，为什么会影响到现存模型的训练结果呢？

**Comment by Chilicyy** [comment]
@tonyostum2022 您好，由于pytorch初始化的原因，每次训练一般都会有一些结果误差（<0.3% mAP 都是属于正常的），这边说的结果发生变化具体有多大变化呢？

**Comment by tonyostum2022** [comment]
> @tonyostum2022 您好，由于pytorch初始化的原因，每次训练一般都会有一些结果误差（<0.3% mAP 都是属于正常的），这边说的结果发生变化具体有多大变化呢？

根据实验结果来看，相同环境下相同的命令，每个epoch显示的loss和最后的测试结果都是不变的。
在添加额外模型后，每个epoch显示的loss和最后的测试结果都发生了变化，mAP变化<0.3%，但是mAP50下降了3~4%。
为了对比不同蒸馏策略的效果，希望尽可能消除这种随机的扰动，请问有没有办法可以消除这种影响呢？

PS：试着改变了workers的数量，也产生了类似的影响
