### ISSUE TITLE
YOLOV6 模型输入尺寸问题

### ISSUE THREAD

**Issue by ChaocunChen** [meituan/YOLOv6#956]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

训练自己数据集输入尺寸改为224或者192（只要 低于256的任何尺寸）都会自动更新到256，我想保持自己设定的尺寸该怎么办？
提示信息如下：
python tools/train.py --batch 64 --conf configs/yolov6n_finetune.py --data data/hand_test.yaml  --img-size 128
2023-11-20 20:03:14.730613: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-20 20:03:14.795511: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-20 20:03:15.795162: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
--img-size 128 must be multiple of max stride 32, updating to 256
Using 1 GPU for training...
麻烦大神指导一下，感谢！

**Comment by ChaocunChen** [comment]
@mtjhl 大佬帮看下 感谢

**Comment by Chilicyy** [comment]
@ChaocunChen 您好，可以尝试将[这行](https://github.com/meituan/YOLOv6/blob/035d8de724ec2227eadf8f1cf5821a75c2b4331e/tools/train.py#L96)的floor变量设为0.

**Comment by ChaocunChen** [comment]
> @ChaocunChen 您好，可以尝试将[这行](https://github.com/meituan/YOLOv6/blob/035d8de724ec2227eadf8f1cf5821a75c2b4331e/tools/train.py#L96)的floor变量设为0. `args.img_size = check_img_size(args.img_size, 32, floor=0)`

@Chilicyy 感谢 可以了 原来是这里做了限制

**Comment by ChaocunChen** [comment]
> > @ChaocunChen 您好，可以尝试将[这行](https://github.com/meituan/YOLOv6/blob/035d8de724ec2227eadf8f1cf5821a75c2b4331e/tools/train.py#L96)的floor变量设为0. `args.img_size = check_img_size(args.img_size, 32, floor=0)`
> 
> @Chilicyy 感谢 可以了 原来是这里做了限制

@Chilicyy 按照您说的修改成128 但是模型最终大小还是和256输入的一样 这是为何？这么看128还是不生效嘛

**Comment by ChaocunChen** [comment]
> > > @ChaocunChen 您好，可以尝试将[这行](https://github.com/meituan/YOLOv6/blob/035d8de724ec2227eadf8f1cf5821a75c2b4331e/tools/train.py#L96)的floor变量设为0. `args.img_size = check_img_size(args.img_size, 32, floor=0)`
> > 
> > 
> > @Chilicyy 感谢 可以了 原来是这里做了限制
> 
> @Chilicyy 按照您说的修改成128 但是模型最终大小还是和256输入的一样 这是为何？这么看128还是不生效嘛

看onnx的输入确实是128了 运行速度也提高了 感谢
