### ISSUE TITLE
onnx模型输出头

### ISSUE THREAD

**Issue by lzh-666666** [meituan/YOLOv6#959]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

运行export_onnx.py导出的onnx模型只有一个输出头，想改成三个应该怎么改呢

**Comment by Chilicyy** [comment]
您好，这边可以尝试注释这两行 https://github.com/meituan/YOLOv6/blob/035d8de724ec2227eadf8f1cf5821a75c2b4331e/yolov6/models/effidehead.py#L121C12-L122C106

**Comment by lzh-666666** [comment]
> 您好，这篇文章可以尝试注释这两行https://github.com/meituan/YOLOv6/blob/035d8de724ec2227eadf8f1cf5821a75c2b4331e/yolov6/models/effidehead.py#L121C12-L122C106

您好，感谢您的回复，我刚刚进行尝试，导出还是一个输出头

**Comment by Chilicyy** [comment]
![image](https://github.com/meituan/YOLOv6/assets/107050484/50b670b7-cf48-4fb9-905f-aa9558c1b8cd)
您需要根据您自己的模型配置选择对应的effidehead头定义的文件，进行相应的修改。

**Comment by lzh-666666** [comment]
> ![image](https://user-images.githubusercontent.com/107050484/284783903-50b670b7-cf48-4fb9-905f-aa9558c1b8cd.png) 您需要根据您自己的模型配置选择对应的effidehead头定义的文件，进行相应的修改。

感谢，我在对应的文件11行左右看见一个参数，export=false
	我只把这个改为true，就可以实现导出的onnx模型是三个输出头的操作
	如果我把您标注的两行注释的话，会提示RuntimeError: Sizes of tensors must match except in dimension 3. Expected size 80 but got size 40 for tensor number 1 in the list.
	最终是根据您的提示找到了对应的文件

**Comment by TD-wzw** [comment]
for k, m in model.named_modules():
        if isinstance(m, Detect):
            m.export = True
这样就行了，那个参数外部可以动态控制

**Comment by lzh-666666** [comment]
> ```
> for k, m in model.named_modules():
>     if isinstance(m, Detect):
>         m.export = True
> ```
> 
> 这样就行了，那个参数外部可以动态控制

好的，感谢
