### ISSUE TITLE
Uncover the hidden parts for full reproducibly 

### ISSUE THREAD

**Issue by nirbarazida** [meituan/YOLOv6#96]
Hey

I'm Nir, and I'm a data scientist at DagsHub (A GitHub-based platform for ML).
**Big KODUS on this project**! I already used it locally for some hello world inference, and I can't wait to take it to a more challenging test drive!

I saw a few issues #95 #91 #80 that seek more information about the development phase. I'd love to see if we can help you on that front by connecting the repo to DagsHub and hosting the Git server, issues & PR next to your data, models, experiments, and labels. It will uncover the hiding parts of the project for the community and take it one step closer to full reproducibility.

If there are any other challenges you think we can help you with - we'd be more than happy to pitch in. Open Source Data Science is part of our DNA and we try to help promote it in any way possible.

Please feel free to reach out -> https://discord.gg/skXZZjJd2w (Nir#1036)

**Comment by mtjhl** [comment]
Thanks for your attention, we will learn about DagsHub, if the repo suits, we are glad to put it your platform.
