### ISSUE TITLE
best_ckpt？last_ckpt！

### ISSUE THREAD

**Issue by Rosal-1998** [meituan/YOLOv6#964]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

您好，我在训练几次模型之后发现训练结束之后best_ckpt和last_ckpt是同一个，并不会保存在训练中最好的ck，（但是在训练过程中是一直更新最好的），在最后训练结束之后又会变成last_ckpt？请问这个是为什么呢？
谢谢您在目标检测领域做出的贡献！

**Comment by Chilicyy** [comment]
@Rosal-1998 您好，保存best_ckpt的代码逻辑是判断当前评估指标中的mAP是否比上一次评估的指标高，如果更高，则会保存下来，last_ckpt则会将每次评估的当前checkpoint保存下来，直到模型训练结束。
