### ISSUE TITLE
Error while training the YOLOv6-seg with adding "--fuse_ab"

### ISSUE THREAD

**Issue by DrChungAlbert** [meituan/YOLOv6#975]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

Not sure why I got this error while adding "--fuse_ab"
CUDA_VISIBLE_DEVCES=5,6,7 python -m torch.distributed.launch --nproc_per_node 3 tools/train.py --batch 128 --conf configs/yolov6n_seg.py --img-size 512 --fuse_ab --device 5,6,7

 gives me this error when it prompts in the beginning of training process:

Training start...

     Epoch        lr  iou_loss  dfl_loss  cls_loss  seg_loss
  0%|          | 0/605 [00:08<?, ?it/s]                                                             
ERROR in training steps.
ERROR in training loop or eval/save model.
Traceback (most recent call last):
  File "/data1/albert/YOLOv6-seg/tools/train.py", line 142, in <module>
    main(args)
  File "/data1/albert/YOLOv6-seg/tools/train.py", line 132, in main
    trainer.train()
  File "/data1/albert/YOLOv6-seg/yolov6/core/engine.py", line 124, in train
    self.train_one_epoch(self.epoch)
  File "/data1/albert/YOLOv6-seg/yolov6/core/engine.py", line 138, in train_one_epoch
    self.train_in_steps(epoch_num, self.step)
  File "/data1/albert/YOLOv6-seg/yolov6/core/engine.py", line 173, in train_in_steps
    total_loss_ab, loss_items_ab = self.compute_loss_ab((preds[0],preds[1],preds[2], preds[6]), targets, epoch_num, step_num,
TypeError: ComputeLoss.__call__() takes 7 positional arguments but 8 were given
ERROR in training steps.

(Repeat 3 times above)

WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 9391 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 9389) of binary: /root/miniconda3/bin/python
Segmentation fault (core dumped)

**Comment by Chilicyy** [comment]
Hi @DrChungAlbert , fuse_ab mode is not supported in yolov6-seg branch, for large gpu memory occupy with fuse_ab mode. To correctly train segmentation model, please refer to tutorial in [README.md](https://github.com/meituan/YOLOv6/blob/yolov6-seg/README.md)
