### ISSUE TITLE
why iou_loss,l1_loss,obj_loss,cls_loss is not 0,but map is 0?

### ISSUE THREAD

**Issue by hjl0202** [meituan/YOLOv6#98]
when i train wy dataset,iou_loss,l1_loss,obj_loss,cls_loss is not 0,but map is 0

**Comment by Zephyr69** [comment]
Same here with a custom dataset and the latest repo. The same dataset trains normally with yolov5.

**Comment by mtjhl** [comment]
> when i train wy dataset,iou_loss,l1_loss,obj_loss,cls_loss is not 0,but map is 0

Thanks for your attention. Please pull the newest code to see whether the mAP is still 0. If mAP is still 0, feel free to inform us.

**Comment by chriszxk** [comment]
I trained the model yesterday, but the mAP is still 0, so the code update today?

**Comment by mtjhl** [comment]
> 

I am reproduce this bug, I would try to fix this today.  Sorry for  inconvenience of use.
