### ISSUE TITLE
training time for one epoch largely increased as training continues

### ISSUE THREAD

**Issue by tino926** [meituan/YOLOv6#996]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

I'm training a yolov6lite-L model, and there's a significant change in the time required for one epoch. As follows, after the first evaluation, the time needed for one epoch went from less than an hour to over eight hours. Is this normal?

Epoch 17: 57:16
Epoch 18: 56.46
Epoch 19: 56.58

Evaluating mAP...

Epoch 20: 1:36:48
Epoch 21: 4:53:35
Epoch 22: 8:16:27
Epoch 23: 5:34:24
Epoch 24: 7:01:41

I'm using a single 4090 for training, with a batch size of 48 and the img_size is set to 480. The training data consists of approximately 1 million images (Objects 365).

**Comment by Chilicyy** [comment]
Hi @tino926 , it is abnormal. You can check if there's someone else using the same machine, or other processes occupying the CPU or GPU memory.
