### ISSUE TITLE
关于v3.0部分的代码

### ISSUE THREAD

**Issue by MissingJade** [meituan/YOLOv6#998]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

请问v3.0论文的代码是在v3分支还是已经合并到主分支了呢？主分支一直在更新而v3这个分子好久没更新了，因此有些疑惑

**Comment by Chilicyy** [comment]
您好，v3分支代码为v3.0 release时代码的备份，由于后续进行了一些代码重构和功能的添加和更新，因此主分支一直在更新。相关的release记录可查看https://github.com/meituan/YOLOv6/releases。
